'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),fixtures=require('../helpers/founder-pay-p2-fixtures.cjs'),{resolveBrowserRuntime}=require('../helpers/playwright-runtime');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'outputs/founder-pay-p2-correction');fs.mkdirSync(path.join(out,'screenshots'),{recursive:true});
(async()=>{const runtime=resolveBrowserRuntime('chrome'),browser=await runtime.browserType.launch({executablePath:runtime.executablePath,headless:true}),receipts=[];try{for(const width of [1440,390]){const context=await browser.newContext({viewport:{width,height:width===390?844:1000},acceptDownloads:true}),page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.goto(pathToFileURL(path.join(root,'public/unlisted/investor-forecast.html')).href);await page.waitForFunction(()=>window.currentNorthStarDriverResult?.rows.length===120);
for(const [name,input]of Object.entries(fixtures)){let assertions=0;const check=(value,label)=>{assert.ok(value,`${width} ${name}: ${label}`);assertions++;};await page.evaluate(x=>localStorage.setItem('northstar-investor-calculator-v3.3',JSON.stringify(x)),input);await page.locator('#load').click();const month=name==='default'?13:1;await page.locator('#selectedMonth').fill(String(month));await page.locator('#selectedMonth').dispatchEvent('change');
const owner=await page.locator('#ownerMoneySummary').innerText();await page.locator('#annualDetails').evaluate(e=>e.open=true);const annualDisclosure=page.locator('#annualRows tr').first().locator('details');await annualDisclosure.evaluate(e=>e.open=true);const annual=await annualDisclosure.innerText(),row=page.locator(`[data-month="${month}"]`),rowText=await row.innerText();
check(await page.locator('#monthlyHeader th').count()===7,'seven columns');check(await page.locator('.month-summary').count()===120,'120 months');check(await row.locator('[data-expand-month]').getAttribute('aria-expanded')==='false','row remains collapsed');check(rowText.includes('Additional withdrawals (company-wide)'),'withdrawals visible without expansion');
if(['default','taxUnavailable'].includes(name)){check(/FORECAST investor receipts: Unavailable \/ unconfigured/.test(owner.replace(/\s+/g,' ')),'monthly forecast unavailable, not0');check(/FORECAST investor receipts: Unavailable \/ unconfigured/.test(annual.replace(/\s+/g,' ')),'annual forecast unavailable, not0');check(rowText.includes('Unavailable / unconfigured'),'collapsed unknown status');check(owner.includes('cash scenario assumes no additional owner withdrawals'),'cash placeholder qualified');}
if(name==='configuredZero'){check(/FORECAST investor receipts: \$0/.test(owner.replace(/\s+/g,' ')),'genuine configured zero monthly');check(/FORECAST investor receipts: \$0/.test(annual.replace(/\s+/g,' ')),'genuine configured zero annual');check(await row.locator('.withdrawal-summary').innerText().then(t=>t.includes('$0')),'collapsed genuine zero');}
if(name==='payout'){check(rowText.includes('$10,000')&&rowText.includes('$3,500'),'withdrawals distinct from founder pay');check(owner.includes('$9,900')&&owner.includes('$13,400')&&owner.includes('assumed founder/other-owner'),'assumed owner share qualified');check(/FORECAST investor receipts: \$100/.test(owner.replace(/\s+/g,' ')),'investor100 retained');check(await page.evaluate(()=>{const r=window.currentNorthStarDriverResult.rows[0];return r.endingCash===1208972&&r.operatingProfit===233972&&r.founderPay===3500;}),'unchanged exact payout cash and operating result');}
if(name.startsWith('actual')){check(/Recorded ACTUAL investor receipts: \$100/.test(owner.replace(/\s+/g,' ')),'actual100 retained monthly');check(/Recorded ACTUAL investor receipts: \$100/.test(annual.replace(/\s+/g,' ')),'actual100 retained annual');check(rowText.includes('Unknown actual total')&&rowText.includes('Founder pay unknown'),'unknown actual founder/pool split');if(name==='actual')check(annual.includes('FORECAST investor receipts:')&&annual.includes('Unavailable / unconfigured')&&annual.includes('Combined investor total unavailable'),'mixed annual recorded and unavailable separated');else check(!annual.includes('FORECAST investor receipts:'),'actual-only year has no invented forecast');}
check(await page.evaluate(()=>document.body.scrollWidth<=innerWidth+1),'no page overflow');check(await page.evaluate(()=>document.querySelector('.monthly-table').scrollWidth<=document.querySelector('#monthlyProjectionScroll').clientWidth+2),'no primary table sideways overflow');check(await row.locator('.withdrawal-amount').evaluateAll(elements=>elements.every(e=>{const r=document.createRange();r.selectNodeContents(e);return r.getClientRects().length===1;})),'withdrawal currency unbroken');
check(await annualDisclosure.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'annual owner disclosure wraps without clipping its text');
await row.scrollIntoViewIfNeeded();if(width>700)await page.locator('#monthlyProjectionScroll').evaluate(e=>window.scrollTo(0,scrollY+e.getBoundingClientRect().top-30));await page.screenshot({path:path.join(out,'screenshots',`${name}-row-${width}.png`)});await page.locator('#ownerMoneySummary').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'screenshots',`${name}-owner-${width}.png`)});
if(name==='actual'){await annualDisclosure.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'screenshots',`mixed-annual-${width}.png`)});}
if(name==='payout'){await page.locator('#save').click();const before=await page.evaluate(()=>JSON.stringify(window.currentNorthStarDriverResult));await page.locator('#load').click();check(await page.evaluate(()=>JSON.stringify(window.currentNorthStarDriverResult))===before,'save/reload exact result');for(const kind of ['Monthly','Annual']){const pending=page.waitForEvent('download');await page.locator('#export'+kind).click();await (await pending).saveAs(path.join(out,`payout-${kind.toLowerCase()}-${width}.csv`));}check(fs.readFileSync(path.join(out,`payout-monthly-${width}.csv`),'utf8').includes('10000'),'download still includes configured pool');}
receipts.push({width,name,assertions,owner,annual,row:rowText});}
assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await context.close();}fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({cases:receipts,assertions:receipts.reduce((s,x)=>s+x.assertions,0),runtimeErrors:0,httpRequests:0},null,2)+'\n');console.log(receipts.map(({width,name,assertions})=>({width,name,assertions})));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
