'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const c=require('../src/estimating/travelCalculation');
const {fixture,id}=require('./helpers/m24-travel-input');
test('declared round trips and whole traveling group produce109, not extra vehicle labor',()=>{const i=fixture();assert.equal(c.calculate(i,'USD').total,'109.00');i.trips[0].vehicles=2;assert.equal(c.calculate(i,'USD').total,'133.00');});
test('explicit asymmetric return is a separate line',()=>{const i=fixture();i.logistics=[];const a=i.trips[0];a.returnIncluded=false;a.trips=1;const b=structuredClone(a);b.lineId=id(3);b.origin=a.destination;b.destination=a.origin;b.distance.value='15';b.time.value='30';i.trips.push(b);assert.equal(c.calculate(i,'USD').total,'65.00');});
test('fuel efficiency uses exact kilometre units',()=>{const i=fixture();i.logistics=[];const t=i.trips[0];t.distance={value:'100',unit:'km',basis:'reported'};t.returnIncluded=false;t.trips=1;t.people=0;t.labor={method:'not_applicable',reason:'Included in another reviewed plan'};t.vehicle={method:'consumption',unit:'l',price:'1.50',basis:'efficiency',quantity:null,efficiency:{value:'8',unit:'l_per_100km'},otherCosts:{status:'not_applicable',note:'Fuel-only declared example'}};assert.equal(c.calculate(i,'USD').total,'12.00');});
test('whole-fleet consumption is once, per vehicle leg is explicit',()=>{const i=fixture();i.logistics=[];const t=i.trips[0];t.vehicles=3;t.people=0;t.labor={method:'not_applicable',reason:'No labor cost in this example'};t.vehicle={method:'consumption',unit:'us_gal',price:'4.00',basis:'whole_job',quantity:'5',efficiency:null,otherCosts:{status:'not_applicable',note:'Fuel-only declared example'}};assert.equal(c.calculate(i,'USD').total,'20.00');t.vehicle.basis='per_vehicle_leg';assert.equal(c.calculate(i,'USD').total,'240.00');});
test('whole-job charge is once, per vehicle trip is not per return leg',()=>{const i=fixture();i.logistics=[];const t=i.trips[0];t.vehicles=3;t.labor={method:'not_applicable',reason:'No labor cost in this example'};t.vehicle={method:'job_charge',amount:'10.00',scope:'whole_job'};assert.equal(c.calculate(i,'USD').total,'10.00');t.vehicle.scope='per_vehicle_trip';assert.equal(c.calculate(i,'USD').total,'60.00');});
test('missing cost remains incomplete and explicit zero stays known',()=>{const i=fixture();i.trips[0].vehicle.rate=null;assert.equal(c.calculate(i,'USD').total,null);assert.equal(c.calculate(i,'USD').knownCostSubtotal,'85.00');i.trips[0].vehicle.rate='0.00';assert.equal(c.calculate(i,'USD').total,'85.00');});
test('straight-line geometry never supplies driving cost',()=>{const i=fixture();i.trips[0].distance.basis='straight_line';assert.equal(c.calculate(i,'USD').total,null);});
test('exact kilometre conversion yields same mileage charge',()=>{const i=fixture();const t=i.trips[0];t.distance={value:'1.609344',unit:'km',basis:'reported'};t.returnIncluded=false;t.trips=1;t.labor={method:'not_applicable',reason:'No labor cost in this example'};i.logistics=[];assert.equal(c.calculate(i,'USD').total,'0.60');});
test('all-in costs reject extra fields and itemized duplicate categories',()=>{const i=fixture();i.trips[0].vehicle.fuel='4.00';assert.throws(()=>c.calculate(i,'USD'));delete i.trips[0].vehicle.fuel;i.trips[0].vehicle={method:'itemized_distance',rates:Array.from({length:3},()=>({category:'fuel_energy',applicable:true,rate:'0.10',unit:'mi',reason:null}))};assert.throws(()=>c.calculate(i,'USD'));});
test('precision, invalid efficiency and amount overflow reject',()=>{const i=fixture();i.trips[0].vehicle.rate='0.335';assert.throws(()=>c.calculate(i,'USD'));i.trips[0].vehicle.rate='999999999999.99';assert.throws(()=>c.calculate(i,'USD'));});
test('trip and access duplicate identities reject',()=>{const i=fixture();i.logistics[0].lineId=i.trips[0].lineId;assert.throws(()=>c.calculate(i,'USD'));});


test('access dates reject normalized invalid dates and preserve valid leap days',()=>{const i=fixture();i.access=[{lineId:id(9),label:'Reported closure',status:'closed',start:'2026-02-31T08:00:00Z',end:'2026-03-04T09:00:00Z',appliesToJob:true,source:i.trips[0].source}];assert.throws(()=>c.calculate(i,'USD'),/date/);i.access[0].start='2028-02-29T08:00:00Z';i.access[0].end='2028-02-29T09:00:00.000Z';assert.equal(c.calculate(i,'USD').total,'109.00');});

test('unknown traveling headcount keeps known vehicle costs without inventing a crew',()=>{const i=fixture();i.trips[0].people=null;const r=c.calculate(i,'USD');assert.equal(r.total,null);assert.equal(r.knownCostSubtotal,'29.00');assert.equal(r.trips[0].totalTravelingPeople,null);i.trips[0].people=0;assert.equal(c.calculate(i,'USD').total,'29.00');});
