'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const c=require('../src/estimating/travelCostComposition');
const {fixture}=require('./helpers/m24-travel-input'),{line:workLine,inputs}=require('./helpers/m24-labor-input');
const item=()=>({calculationVersion:'m19-part3-canonical-v2',estimate:{currency:'USD'},snapshot:{service:{supported:true},materialsCharge:500,laborCharge:800,equipmentCharge:100,knownDirectMaterialCost:500,knownInternalLaborCost:800,knownEquipmentCost:100,travel:{distanceMiles:2,knownInternalCost:6}}});
const common=()=>({id:crypto.randomUUID(),revision:1,digest:'a'.repeat(64),sourcePins:{estimateId:'fixture'},action:'save',currency:'USD'});
const material=()=>({...common(),calculationVersion:'estimate-material-plan-v1',inputs:{material:'Boards',quantity:'10',unit:'ft',wastePercent:'0',unitPrice:'60.00',sourceType:'my_estimate',sourceNote:'Task estimate',priceDate:null}});
const labor=()=>({...common(),calculationVersion:'estimate-labor-plan-v1',inputs:inputs([workLine({hourlyCost:'50.00'})])});
const equipment=()=>({...common(),calculationVersion:'estimate-equipment-cost-plan-v1',inputs:{equipmentBasis:{planId:'same-equipment-review'},lines:[{lineId:crypto.randomUUID(),access:'owned',method:'economic_recovery',notApplicableReason:null,plannedHours:'8',rental:null,allocation:{period:'year',usableHours:'600',pool:{amount:'12000.00',scope:'equipment_only',split:null},includedCategories:['capital_recovery'],additionalCosts:[]},operating:{mode:'all_in',allIn:{status:'not_applicable',rate:null},fuelEnergy:null,consumables:null,maintenance:null},fees:[],source:{kind:'my_estimate',issuer:'',reference:'',note:'',effectiveOn:null,endsOn:null,geography:''}}]}});
const travel=()=>({...common(),calculationVersion:'estimate-travel-plan-v1',inputs:fixture()});
const coverage=p=>({componentManifest:c.manifest(p),overlaps:[],equipmentOutside:[],confirmed:true,reason:'Separate declared costs reviewed.'});
function permutations(a){return a.length?a.flatMap((x,i)=>permutations(a.filter((_,j)=>i!==j)).map(t=>[x,...t])):[[]];}
for(const order of permutations(c.KINDS))test('four component order '+order.join(' → '),()=>{const saved={material:material(),labor:labor(),equipment:equipment(),travel:travel()};let selection={selected:null};for(const component of order){const pair=c.compose(selection,component,saved[component]);const result=c.calculate(item(),pair,coverage(pair));assert.equal(result.grossProfit,null);selection={selected:{calculationVersion:c.VERSION,materialPlan:pair.material,laborPlan:pair.labor,equipmentCostPlan:pair.equipment,travelPlan:pair.travel,componentManifest:c.manifest(pair)}};}assert.equal(c.calculate(item(),c.plans(selection),coverage(saved)).knownDirectCosts,'1829.00');assert.equal(c.components(selection).travel.id,saved.travel.id);});
test('80 of travel already in labor contributes29 once',()=>{const pair={travel:travel()};const cov=coverage(pair);cov.overlaps=[{travelLineId:pair.travel.inputs.trips[0].lineId,category:'travel_labor',component:'labor',sourceLineId:'original',amount:'80.00',reason:'Travel labor included in original allowance.'}];const r=c.calculate(item(),pair,cov);assert.equal(r.knownTravelInternalCost,'29.00');assert.equal(r.knownDirectCosts,'1429.00');assert.equal(r.travelAlreadyIncluded,'80.00');});
test('overclaim and stale coverage cannot transfer to changed components',()=>{const pair={travel:travel()};const cov=coverage(pair);cov.overlaps=[{travelLineId:pair.travel.inputs.trips[0].lineId,category:'travel_labor',component:'labor',sourceLineId:'original',amount:'105.00',reason:'Too much.'}];assert.throws(()=>c.calculate(item(),pair,cov));cov.overlaps=[];pair.labor=labor();assert.throws(()=>c.calculate(item(),pair,cov),/review/i);});
test('unknown original cost keeps complete total unknown after travel adoption',()=>{const i=item();i.snapshot.knownInternalLaborCost=null;const p={travel:travel()};const r=c.calculate(i,p,coverage(p));assert.equal(r.knownDirectCosts,null);assert.equal(r.knownDirectCostSubtotal,'709.00');});
test('large replaced original travel does not cause false overflow',()=>{const i=item();i.snapshot.travel.knownInternalCost=999999999999.99;const p={travel:travel()};assert.equal(c.calculate(i,p,coverage(p)).knownDirectCosts,'1509.00');assert.equal(i.snapshot.travel.knownInternalCost,999999999999.99);});
test('equipment excluded travel share requires exact cost owner without mutating old receipt',()=>{const e=equipment(),t=travel(),l=e.inputs.lines[0];l.method='rental';l.allocation=null;l.rental={unit:'job',quantity:'1',minimumQuantity:'1',charge:{amount:'324.00',scope:'mixed',split:{equipment:'300.00',operator:'0.00',travel:'24.00',overhead:'0.00',operatorCoverage:{status:'unknown',basis:null,note:''},travelCoverage:{status:'covered',basis:{kind:'original'},note:'Historical original travel basis'}}}};const pair={equipment:e,travel:t},cov=coverage(pair),before=JSON.stringify(e);assert.throws(()=>c.calculate(item(),pair,cov),/accounted/);cov.equipmentOutside=[{equipmentLineId:l.lineId,kind:'travel',component:'travel',targetCategory:'vehicle',targetLineId:t.inputs.trips[0].lineId,amount:'24.00',reason:'Mileage covers the excluded delivery share.'}];assert.equal(c.calculate(item(),pair,cov).knownDirectCosts,'1709.00');assert.equal(JSON.stringify(e),before);});

test('coverage is bounded by exact contribution category as well as whole trip',()=>{const pair={travel:travel()},cov=coverage(pair);cov.overlaps=[{travelLineId:pair.travel.inputs.trips[0].lineId,category:'vehicle',component:'labor',sourceLineId:'original',amount:'25.00',reason:'Explicit owner allocation, not inferred task names.'}];assert.throws(()=>c.calculate(item(),pair,cov),/exceeds/);cov.overlaps[0].amount='24.00';assert.equal(c.calculate(item(),pair,cov).knownTravelInternalCost,'85.00');cov.overlaps.push({...cov.overlaps[0],amount:'1.00'});assert.throws(()=>c.calculate(item(),pair,cov),/exceeds/);});
