'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {loads,stages,bindLoads}=require('../src/estimating/travelOperations');
const {fixture,id}=require('./helpers/m24-travel-input');
const {haul,stageInput}=require('./helpers/m24-travel-operations-input');
const value=(r,kind)=>r[kind].quantity;
test('known volume and payload yield 10,10,5; existing load yields6,10,9',()=>{const h=haul();let r=loads(h);assert.equal(r.additionalLoads,3);assert.deepEqual(value(r.firstLoad,'volume'),{numerator:'10',denominator:'1'});assert.deepEqual(value(r.lastLoad,'volume'),{numerator:'5',denominator:'1'});assert.equal(r.lastLoadPartial,true);h.volume.existing='4';h.mass.existing='400';r=loads(h);assert.equal(r.additionalLoads,3);assert.deepEqual(value(r.firstLoad,'volume'),{numerator:'6',denominator:'1'});assert.deepEqual(value(r.lastLoad,'volume'),{numerator:'9',denominator:'1'});});
test('payload limits loads without inventing density',()=>{const h=haul();h.mass.capacity='500';let r=loads(h);assert.equal(r.additionalLoads,5);assert.equal(r.lastLoadPartial,false);h.mass.output=null;r=loads(h);assert.equal(r.additionalLoads,null);assert.equal(r.complete,false);});
test('retained material is excluded once and zero new output preserves existing disposal',()=>{const h=haul();h.volume.retained='5';h.mass.retained='500';assert.equal(loads(h).additionalLoads,2);h.volume.retained='25';h.mass.retained='2500';h.volume.existing='10';h.mass.existing='1000';const r=loads(h);assert.equal(r.additionalLoads,0);assert.equal(r.existingDisposalIncluded,false);assert.match(r.cautions.join(' '),/existing contents/);});
test('full initial container requires separate clearance before three new loads',()=>{const h=haul();h.volume.existing='10';h.mass.existing='1000';const r=loads(h);assert.equal(r.initialClearanceRequired,true);assert.equal(r.additionalLoads,3);assert.equal(r.existingDisposalIncluded,false);});
test('mixed and missing facts remain incomplete, contradictory recorded facts reject',()=>{const h=haul();h.homogeneous=false;assert.equal(loads(h).additionalLoads,null);h.homogeneous=true;h.mass.output='0';assert.throws(()=>loads(h),/conflict/);h.mass.output='2500';h.volume.retained='26';assert.throws(()=>loads(h),/retained/);});
test('parallel distinct resources yield60 elapsed and105 personminutes, never a labor price',()=>{const r=stages(stageInput());assert.deepEqual(r.feasibleElapsedMinutes,{numerator:'60',denominator:'1'});assert.deepEqual(r.personMinutes,{numerator:'105',denominator:'1'});assert.equal(r.cost,undefined);});
test('parallel same driver conflicts; explicit serial dependency resolves timing',()=>{const s=stageInput();s.stages[1].resourceIds=[id(1)];let r=stages(s);assert.equal(r.feasibleElapsedMinutes,null);assert.equal(r.cautions[0].kind,'parallel_resource_conflict');s.stages[1].dependencies=[id(3)];r=stages(s);assert.deepEqual(r.feasibleElapsedMinutes,{numerator:'105',denominator:'1'});});
test('unknown availability/duration and future dependency never establish feasibility',()=>{const s=stageInput();s.resources[0].available=null;assert.equal(stages(s).feasibleElapsedMinutes,null);s.resources[0].available=true;s.stages[0].duration=null;assert.equal(stages(s).declaredElapsedMinutes,null);s.stages[0].dependencies=[id(4)];assert.throws(()=>stages(s),/earlier/);});
test('three outbound loads, two returns and one final destination remain distinct',()=>{const h=haul(),a=fixture().trips[0];Object.assign(a,{lineId:id(5),trips:3,vehicles:1,returnIncluded:false});const b={...a,lineId:id(6),trips:2,origin:a.destination,destination:a.origin},c={...a,lineId:id(7),trips:1,origin:a.destination,destination:a.origin};const links=[{groupId:h.lineId,tripId:a.lineId,role:'outbound',countBasis:'all_loads'},{groupId:h.lineId,tripId:b.lineId,role:'return',countBasis:'except_last'},{groupId:h.lineId,tripId:c.lineId,role:'final',countBasis:'once'}];assert.equal(bindLoads([h],links,[a,b,c]).complete,true);a.vehicles=2;assert.throws(()=>bindLoads([h],links,[a,b,c]),/does not match/);a.vehicles=1;a.returnIncluded=true;assert.throws(()=>bindLoads([h],links,[a,b,c]),/one-way/);});

test('explicit sourced density derives only new output and retained mass',()=>{const h=haul();h.mass.output=null;h.mass.retained=null;h.mass.capacity='500';h.detail={equipmentBasis:null,density:{value:'100',massUnit:'lb',volumeUnit:'yd3',source:h.source},orderedLoads:[]};const r=loads(h);assert.equal(r.additionalLoads,5);assert.deepEqual(r.densityDerived,['output','retained']);assert.equal(h.mass.output,null);h.detail.density.value=null;assert.equal(loads(h).complete,false);});
test('mixed measured loads use each declared capacity and conserve retained output',()=>{const h=haul();h.homogeneous=false;h.volume.capacity=h.volume.existing=h.mass.capacity=h.mass.existing=null;const unit=(quantity,capacity)=>({quantity,capacity,existing:'0'});h.detail={equipmentBasis:null,density:null,orderedLoads:[{loadId:id(70),volume:unit('10','10'),mass:unit('1000','1200'),initialLoadOwner:'this_job',initialLoadNote:'Recorded empty container.'},{loadId:id(71),volume:unit('15','20'),mass:unit('1500','2000'),initialLoadOwner:'this_job',initialLoadNote:'Second empty container.'}]};const r=loads(h);assert.equal(r.additionalLoads,2);assert.equal(r.complete,true);h.detail.orderedLoads[1].mass.capacity='1400';assert.throws(()=>loads(h),/capacity/);h.detail.orderedLoads[1].mass.capacity='2000';h.detail.orderedLoads[1].volume.quantity='14';assert.throws(()=>loads(h),/match/);});
