'use strict';
const request=require('supertest');
const {createDatabaseFixture}=require('../helpers/m23-part9b-overview-fixture');
const time=require('../../public/js/scheduling-time-contract');
const suite=process.env.M19_PG_ADMIN_URL?describe:describe.skip;
suite('Mounted isolated demo dispatch',()=>{
 let f,agent,cookie,workspace;
 async function read(){const r=await agent.get('/api/demo/command-center').set('Cookie',cookie||'');expect(r.status).toBe(200);if(!cookie)cookie=r.headers['set-cookie'][0].split(';')[0];workspace=r.body.data;return workspace;}
 function send(id,path,key,revision,body){return agent.post('/api/demo/command-center/appointments/'+id+'/'+path).set('Host','northstar.test').set('Origin','http://northstar.test').set('Sec-Fetch-Site','same-origin').set('Cookie',cookie).set('Idempotency-Key',key).set('X-NorthStar-Demo-Intent','schedule-times').set('X-NorthStar-Demo-Revision',String(revision)).send(body);}
 function proposal(w){const r=w.schedulingOverview.records.find(r=>r.allowedActions.length),zone=w.configuration.businessProfile.timeZone;const start=new Date(Date.now()+86400000),end=new Date(start.getTime()+7200000);return{id:r.appointmentId,body:{expectedRevision:r.authority.revision,expectedDigest:r.authority.digest,expectedTimeZone:zone,action:r.allowedActions[0],target:{kind:'unassigned',id:null},scheduledStart:time.formatInstant(start.toISOString(),zone).rfc3339,scheduledEnd:time.formatInstant(end.toISOString(),zone).rfc3339,appointmentStatus:r.authority.appointmentStatus,reason:'Review these entered times; staffing remains unassigned.'}};}
 beforeAll(async()=>{f=await createDatabaseFixture();agent=request(f.app);await read();},60000);
 afterAll(async()=>{if(f)await f.cleanup();},30000);

 beforeEach(async()=>{cookie='';await read();});
 function row(w,id){return w.schedulingOverview.records.find(r=>id?r.appointmentId===id:r.allowedActions.length);}
 async function preview(action,id,target,interval,key){const w=await read(),r=row(w,id),a=r.authority,zone=w.configuration.businessProfile.timeZone;const body={expectedRevision:a.revision,expectedDigest:a.digest,expectedTimeZone:zone,action,target:target||{kind:a.workforceProfileId?'profile':a.workforceCrewId?'crew':'unassigned',id:a.workforceProfileId||a.workforceCrewId||null},scheduledStart:interval?interval[0]:a.scheduledStart?time.formatInstant(a.scheduledStart,zone).rfc3339:null,scheduledEnd:interval?interval[1]:a.scheduledEnd?time.formatInstant(a.scheduledEnd,zone).rfc3339:null,appointmentStatus:a.appointmentStatus,reason:'Review this isolated demo dispatch change.'};const response=await send(r.appointmentId,'mutation-previews',key+'-preview',w.integrity.revision,body);if(response.status!==201)throw new Error(action+' preview '+response.status+' '+JSON.stringify({body,current:a,response:response.body}));return{id:r.appointmentId,body,v:response.body.data,key};}
 async function approve(p){const body={previewId:p.v.id,previewDigest:p.v.previewDigest,acknowledgedWarningDigests:p.v.warningDigests,acknowledgedReviewReasonDigests:p.v.reviewReasonDigests,reason:p.body.reason};const response=await send(p.id,'mutation-approvals',p.key+'-approval',p.v.demoWorkspaceRevision,body);expect(response.status).toBe(201);return{response,body,p};}
 async function setup(key){const w=await read(),id=row(w).appointmentId,zone=w.configuration.businessProfile.timeZone,date=new Date(Date.now()+86400000).toISOString().slice(0,10),interval=['10:00','11:00'].map(h=>time.resolveWallTime(date,h,zone).candidates[0].rfc3339);await approve(await preview('schedule',id,null,interval,key+'-schedule'));const targets=(await read()).schedulingOperator.targets.filter(t=>t.kind==='crew');await approve(await preview('assign',id,{kind:'crew',id:targets[0].id},null,key+'-assign'));return{id,targets,interval};}
 test('dispatch and all actual edits revoke atomically; old dispatch replay preserves revoked current state and raw graphs',async()=>{const{id,targets,interval}=await setup('life'),before=await read(),stored=(await f.ownerPool.query('SELECT state FROM demo_command_center_sessions WHERE id=$1',[before.session.id])).rows[0].state;let n=0;for(const action of ['reassign','reschedule','unassign']){const dispatch=await approve(await preview('dispatch',id,null,null,'dispatch-'+n));expect(dispatch.response.body.data.scheduleAuthority.dispatchState).toBe('dispatched');const changed=await approve(await preview(action,id,action==='reassign'?{kind:'crew',id:targets[1].id}:action==='unassign'?{kind:'unassigned',id:null}:null,action==='reschedule'?interval.map(v=>time.formatInstant(Date.parse(v)+3600000,before.configuration.businessProfile.timeZone).rfc3339):null,'dispatch-edit-'+n));expect(changed.response.body.data.scheduleAuthority.dispatchState).toBe('revoked');const replay=await send(id,'mutation-approvals',dispatch.p.key+'-approval',dispatch.p.v.demoWorkspaceRevision,dispatch.body);expect(replay.status).toBe(200);expect(replay.body.data).toEqual(dispatch.response.body.data);expect(row(await read(),id).authority.dispatchState).toBe('revoked');n++;}const after=await read(),state=(await f.ownerPool.query('SELECT state FROM demo_command_center_sessions WHERE id=$1',[before.session.id])).rows[0].state;expect(state.graphs).toEqual(stored.graphs);expect(state.demoScheduling.history.slice(-stored.demoScheduling.history.length)).toEqual(stored.demoScheduling.history);expect(after.graphs.find(g=>g.ids.appointment===id).work.scheduleAuthority.dispatchState).toBe('revoked');const calendar=await agent.get('/api/demo/command-center/canonical/compat/calendar').set('Cookie',cookie);expect(calendar.body.data.schedulingOverview.records.find(r=>r.appointmentId===id).authority).toEqual(row(after,id).authority);});
 test('intervening target change invalidates dispatch consent; cancellation of a proposal has no authority effect',async()=>{const{id,targets}=await setup('stale'),p=await preview('dispatch',id,null,null,'stale-dispatch');const a=await approve(await preview('reassign',id,{kind:'crew',id:targets[1].id},null,'stale-reassign'));const body={previewId:p.v.id,previewDigest:p.v.previewDigest,acknowledgedWarningDigests:p.v.warningDigests,acknowledgedReviewReasonDigests:p.v.reviewReasonDigests,reason:p.body.reason};const rejected=await send(id,'mutation-approvals','stale-dispatch-confirm',p.v.demoWorkspaceRevision,body);expect(rejected.status).toBe(409);expect(row(await read(),id).authority).toEqual(a.response.body.data.scheduleAuthority);const pending=await preview('dispatch',id,null,null,'cancelled-proposal');expect(pending.v.proposal.dispatchState).toBe('dispatched');expect(row(await read(),id).authority.dispatchState).toBe('not_dispatched');});
 test('dispatch preview expiry rejects approval without adding history',async()=>{const{id}=await setup('expiry'),p=await preview('dispatch',id,null,null,'expiry-dispatch'),{DemoCommandCenterRepository,normalizeToken}=require('../../src/commandCenter/demoRepository'),{sha256}=require('../../src/services/businessProfileAdapter');const token=normalizeToken(decodeURIComponent(cookie.split('=').slice(1).join('=')),new Date()),repository=new DemoCommandCenterRepository(()=>f.runtimePool,{clock:()=>new Date(Date.parse(p.v.expiresAt)+1)}),w=await read(),before=(await f.ownerPool.query('SELECT state FROM demo_command_center_sessions WHERE id=$1',[w.session.id])).rows[0].state;await expect(repository.mutate(token,{operation:'schedule_approve',appointmentId:id,expectedRevision:p.v.demoWorkspaceRevision,idempotencyKey:'expiry-dispatch-approve',scheduleBody:{previewId:p.v.id,previewDigest:p.v.previewDigest,acknowledgedWarningDigests:p.v.warningDigests,acknowledgedReviewReasonDigests:p.v.reviewReasonDigests,reason:p.body.reason}},{sourceHash:sha256('local expiry fixture')})).rejects.toMatchObject({status:410});expect((await f.ownerPool.query('SELECT state FROM demo_command_center_sessions WHERE id=$1',[w.session.id])).rows[0].state).toEqual(before);});
});
