'use strict';
const crypto=require('node:crypto');
const request=require('supertest');
const {createEstimateReviewFixture}=require('../helpers/m24-estimate-review-fixture');
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');
const token=(source,value)=>`ref_${sha(`${source}:${value}`)}`;

describe('Mission 25 Part 13C complete per-job outcome summary API',()=>{
 let f;
 beforeAll(async()=>{f=await createEstimateReviewFixture();},180000);
 afterAll(async()=>{if(f)await f.cleanup();},60000);
 test('evaluates exact current coverage, fails closed on overlap and never revives retired evidence',async()=>{
  const owner=f.actors.owner,estimate=f.estimateGraphs[0].ids.estimate;
  const post=(url,body,key=crypto.randomUUID(),actor=owner)=>request(f.app).post(url).set(actor.session.headers).set('X-CSRF-Token',actor.csrfToken).set('Idempotency-Key',key).send(body);
  const before=(await f.ownerPool.query('SELECT snapshot_digest FROM canonical_estimates WHERE organization_id=$1 AND id=$2',[f.org,estimate])).rows[0].snapshot_digest;

  const projectSource='evaluation.projects',projectReference='project-evaluation-1',projectRoot=`/api/v1/learning/external-project-change-order-sources/${projectSource}`;
  let response=await post(`${projectRoot}/consent`,{action:'grant',expectedRevision:0,expectedDigest:'none',reason:'Use current project evidence for coverage review.',confirmed:true,confirmationVersion:'m25-external-project-change-order-import-consent-v1'});const projectSourceConsent=response.body.data.consent;
  response=await post(`${projectRoot}/batches`,{schemaVersion:'m25-external-project-change-order-v1',mode:'historical_backfill',expectedConsentRevision:projectSourceConsent.revision,expectedConsentDigest:projectSourceConsent.digest,cursorBefore:null,cursorAfter:null,complete:true,records:[{externalRecordId:'project-record-evaluation',externalVersion:1,state:'active',recordType:'project',customerReference:'customer-evaluation',jobReference:'job-evaluation',estimateReference:'estimate-evaluation',projectReference,changeOrderReference:null,recordState:'completed',originalContract:{status:'recorded',amount:'1000.00',currency:'USD'},currentContract:{status:'recorded',amount:'1100.00',currency:'USD'},changeOrderValue:null,occurredAt:'2026-09-15T12:00:00.000Z',endedAt:'2026-09-15T20:00:00.000Z',timeZone:'America/New_York',evidenceClass:'provider_recorded',providerEvidenceDigest:sha('project-evaluation-evidence'),sourceUpdatedAt:'2026-09-15T21:00:00.000Z'}],reason:'Import exact project evidence.',confirmed:true,confirmationVersion:'m25-external-project-change-order-import-batch-v1'});expect(response.status).toBe(201);
  const projectMatchRoot=`/api/v1/learning/external-business-sources/project_change_order/${projectSource}`;let match=(await request(f.app).get(`${projectMatchRoot}/matches`).set(owner.session.headers)).body.data;let target=match.estimateTargets.find(value=>value.targetId===estimate),source=match.references.find(value=>value.referenceKind==='project'&&value.externalReference===projectReference);
  response=await post(`${projectMatchRoot}/matches`,{action:'link',referenceKind:'project',externalReference:projectReference,targetKind:'estimate',targetId:estimate,expectedRevision:0,expectedDigest:'none',expectedSourceDigest:source.sourceDigest,expectedTargetDigest:target.digest,reason:'Link exact project evidence.',confirmed:true,confirmationVersion:'m25-external-business-reference-match-v1'});expect(response.status).toBe(201);
  const projectOutcomeRoot=`/api/v1/learning/external-project-outcome-sources/${projectSource}`;response=await post(`${projectOutcomeRoot}/consent`,{action:'grant',expectedRevision:0,expectedDigest:'none',reason:'Use reviewed project outcomes.',confirmed:true,confirmationVersion:'m25-external-project-outcome-consent-v1'});const projectPurpose=response.body.data.consent;response=await post(`${projectOutcomeRoot}/outcomes`,{estimateId:estimate,projectReference,expectedConsentRevision:projectPurpose.revision,expectedConsentDigest:projectPurpose.digest,reason:'Record reviewed project outcome.',confirmed:true,confirmationVersion:'m25-external-project-outcome-observation-v1'});const projectObservation=response.body.data.observation;expect(projectObservation.fresh).toBe(true);

  const financialSource='evaluation.financial',financialRoot=`/api/v1/learning/external-financial-sources/${financialSource}`;response=await post(`${financialRoot}/consent`,{action:'grant',expectedRevision:0,expectedDigest:'none',reason:'Use current financial evidence for coverage review.',confirmed:true,confirmationVersion:'m25-external-financial-import-consent-v1'});const financialSourceConsent=response.body.data.consent;
  const financialRecord=(id,basis,amount)=>({externalRecordId:token(financialSource,id),externalVersion:1,state:'active',recordType:'accounting_entry',customerReference:token(financialSource,'customer'),jobReference:token(financialSource,'job'),estimateReference:token(financialSource,'estimate'),executionReference:null,projectReference:null,changeOrderReference:null,invoiceReference:null,paymentReference:null,collectionReference:null,accountingReference:token(financialSource,id),recordState:'posted',amountClaim:{status:'recorded',amount,currency:'USD',basis},occurredAt:'2026-09-15T12:00:00.000Z',timeZone:'America/New_York',evidenceClass:'provider_recorded',providerEvidenceDigest:sha(`financial-${id}-evidence`),sourceUpdatedAt:'2026-09-15T17:00:00.000Z'});
  response=await post(`${financialRoot}/batches`,{schemaVersion:'m25-external-financial-evidence-v1',mode:'historical_backfill',expectedConsentRevision:financialSourceConsent.revision,expectedConsentDigest:financialSourceConsent.digest,cursorBefore:null,cursorAfter:null,complete:true,records:[financialRecord('revenue','revenue','1000.00'),financialRecord('cost','direct_cost','400.00')],reason:'Import exact financial evidence.',confirmed:true,confirmationVersion:'m25-external-financial-import-batch-v1'});expect(response.status).toBe(201);
  const financialMatchRoot=`/api/v1/learning/external-business-sources/financial/${financialSource}`;for(const reference of['revenue','cost']){match=(await request(f.app).get(`${financialMatchRoot}/matches`).set(owner.session.headers)).body.data;target=match.estimateTargets.find(value=>value.targetId===estimate);source=match.references.find(value=>value.referenceKind==='accounting_entry'&&value.externalReference===token(financialSource,reference));response=await post(`${financialMatchRoot}/matches`,{action:'link',referenceKind:'accounting_entry',externalReference:token(financialSource,reference),targetKind:'estimate',targetId:estimate,expectedRevision:0,expectedDigest:'none',expectedSourceDigest:source.sourceDigest,expectedTargetDigest:target.digest,reason:'Link exact financial evidence.',confirmed:true,confirmationVersion:'m25-external-business-reference-match-v1'});expect(response.status).toBe(201);}
  const financialOutcomeRoot=`/api/v1/learning/external-financial-outcome-sources/${financialSource}`;response=await post(`${financialOutcomeRoot}/consent`,{action:'grant',expectedRevision:0,expectedDigest:'none',reason:'Use reviewed financial outcomes.',confirmed:true,confirmationVersion:'m25-external-financial-outcome-consent-v1'});const financialPurpose=response.body.data.consent;response=await post(`${financialOutcomeRoot}/outcomes`,{estimateId:estimate,expectedConsentRevision:financialPurpose.revision,expectedConsentDigest:financialPurpose.digest,reason:'Record reviewed financial outcome.',confirmed:true,confirmationVersion:'m25-external-financial-outcome-observation-v1'});const financialObservation=response.body.data.observation;expect(financialObservation.fresh).toBe(true);

  response=await post('/api/v1/learning/job-outcome-graph/consent',{action:'grant',expectedRevision:0,expectedDigest:'none',reason:'Review connected job outcomes.',confirmed:true,confirmationVersion:'m25-job-outcome-graph-consent-v1'});const consent=response.body.data.consent;
  response=await post(`/api/v1/learning/estimates/${estimate}/job-outcome-graph`,{expectedConsentRevision:consent.revision,expectedConsentDigest:consent.digest,nodes:[{nodeKind:'external_project',observationId:projectObservation.id,locator:{sourceKey:projectSource,projectReference}},{nodeKind:'external_financial',observationId:financialObservation.id,locator:{sourceKey:financialSource}}],reason:'Connect exact current outcomes.',confirmed:true,confirmationVersion:'m25-job-outcome-graph-v1'});expect(response.status).toBe(201);const graph=response.body.data.graph;
  response=await post(`/api/v1/learning/estimates/${estimate}/job-outcome-graph/evaluation`,{expectedGraphRevision:graph.revision,expectedGraphDigest:graph.digest,requiredDomains:['financial','scope'],reason:'Review the currently recorded areas.',confirmed:true,confirmationVersion:'m25-job-outcome-graph-evaluation-v1'});expect(response.status).toBe(201);const partialEvaluation=response.body.data.evaluation;
  response=await post(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`,{expectedEvaluationRevision:partialEvaluation.revision,expectedEvaluationDigest:partialEvaluation.digest,reason:'Attempt a summary before all areas are reviewed.',confirmed:true,confirmationVersion:'m25-job-outcome-summary-v1'});expect(response.status).toBe(409);expect(response.body.error.message).toBe('A current complete job outcome review is required.');
  const body={expectedGraphRevision:graph.revision,expectedGraphDigest:graph.digest,requiredDomains:['equipment','financial','labor','materials','scope','travel'],reason:'Review every job outcome summary area.',confirmed:true,confirmationVersion:'m25-job-outcome-graph-evaluation-v1'},key=crypto.randomUUID();
  const concurrent=await Promise.all([post(`/api/v1/learning/estimates/${estimate}/job-outcome-graph/evaluation`,body,key),post(`/api/v1/learning/estimates/${estimate}/job-outcome-graph/evaluation`,body,key)]);expect(concurrent.map(x=>x.status).sort()).toEqual([200,201]);const evaluation=concurrent.find(x=>x.status===201).body.data.evaluation;expect(evaluation.evaluation.completeness).toMatchObject({status:'needs_attention',complete:false,requiredDomainCount:6,coveredRequiredDomainCount:2,missingRequiredDomainCount:4});expect(evaluation.evaluation.conflicts).toMatchObject({status:'clear',count:0});
  const summaryBody={expectedEvaluationRevision:evaluation.revision,expectedEvaluationDigest:evaluation.digest,reason:'Prepare one complete job outcome summary.',confirmed:true,confirmationVersion:'m25-job-outcome-summary-v1'},summaryKey=crypto.randomUUID();
  const summaryConcurrent=await Promise.all([post(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`,summaryBody,summaryKey),post(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`,summaryBody,summaryKey)]);expect(summaryConcurrent.map(x=>x.status).sort()).toEqual([200,201]);const summary=summaryConcurrent.find(x=>x.status===201).body.data.summary;expect(summary).toMatchObject({fresh:true,available:true,summary:{version:'m25-job-outcome-summary-v1',status:'needs_attention',sourceCount:2}});const domains=Object.fromEntries(summary.summary.domains.map(value=>[value.domain,value]));expect(Object.keys(domains)).toEqual(['labor','travel','equipment','materials','scope','financial']);for(const domain of['labor','travel','equipment','materials'])expect(domains[domain]).toMatchObject({status:'unavailable',sources:[]});expect(domains.scope).toMatchObject({status:'recorded',sources:[{nodeKind:'external_project',claimSlot:'scope_delivery'}]});expect(domains.financial).toMatchObject({status:'recorded',sources:[{nodeKind:'external_financial',claimSlot:'financial_actuals'}]});expect(domains.scope.sources[0].details).toHaveProperty('projectDelivery');expect(domains.financial.sources[0].details).toHaveProperty('revenue');
  const saved=(await f.ownerPool.query('SELECT graph_id,evaluation_id,consent_id,graph_revision,evaluation_revision,rtrim(graph_digest) graph_digest,rtrim(evaluation_digest) evaluation_digest,calculation_version FROM canonical_job_outcome_summaries WHERE organization_id=$1 AND estimate_id=$2 ORDER BY revision DESC LIMIT 1',[f.org,estimate])).rows[0];expect(saved).toMatchObject({graph_id:graph.id,evaluation_id:evaluation.id,consent_id:consent.id,graph_revision:String(graph.revision),evaluation_revision:String(evaluation.revision),graph_digest:graph.digest,evaluation_digest:evaluation.digest,calculation_version:'m25-job-outcome-summary-v1'});
  const manifest=(await f.ownerPool.query('SELECT node_manifest FROM canonical_job_outcome_graphs WHERE id=$1',[graph.id])).rows[0].node_manifest,extra={...manifest.find(x=>x.nodeKind==='external_financial'),observationId:crypto.randomUUID()};const overlap=(await f.ownerPool.query('SELECT canonical_job_outcome_graph_evaluate_manifest($1::jsonb,$2::jsonb) value',[JSON.stringify([...manifest,extra]),JSON.stringify(['financial','scope'])])).rows[0].value;expect(overlap.conflicts).toMatchObject({status:'needs_review',count:1});expect(overlap.completeness.complete).toBe(false);
  const domainValidation=(await f.ownerPool.query("SELECT canonical_job_outcome_graph_required_domains_valid('[\"financial\",\"scope\"]'::jsonb) valid,canonical_job_outcome_graph_required_domains_valid('[\"scope\",\"financial\"]'::jsonb) unsorted,canonical_job_outcome_graph_required_domains_valid('[\"scope\",\"scope\"]'::jsonb) duplicate")).rows[0];expect(domainValidation).toEqual({valid:true,unsorted:false,duplicate:false});
  await expect(f.ownerPool.query("INSERT INTO canonical_job_outcome_summaries(organization_id,estimate_id,revision,previous_id,graph_id,graph_revision,graph_digest,graph_source_digest,evaluation_id,evaluation_revision,evaluation_digest,evaluation_source_digest,consent_id,consent_revision,consent_digest,summary,source_digest,calculation_version,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,request_key_hash,request_digest,canonical_digest) SELECT organization_id,estimate_id,revision+1,id,graph_id,graph_revision,graph_digest,graph_source_digest,evaluation_id,evaluation_revision,evaluation_digest,evaluation_source_digest,consent_id,consent_revision,consent_digest,jsonb_set(summary,'{status}','\"complete\"'::jsonb),source_digest,calculation_version,actor_user_id,membership_id,auth_session_id,'Tampered direct summary',true,confirmation_version,$2,$3,canonical_digest FROM canonical_job_outcome_summaries WHERE organization_id=$1 ORDER BY revision DESC LIMIT 1",[f.org,sha('tampered-summary-key'),sha('tampered-summary-request')])).rejects.toMatchObject({code:'23514'});
  expect((await request(f.app).get(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`).set(f.actors.member.session.headers)).status).toBe(403);expect((await request(f.app).get(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`).set(f.actors.otherOwner.session.headers)).status).toBe(409);
  const customer=(await f.ownerPool.query('SELECT c.id,c.updated_at::text updated_at FROM canonical_estimates e JOIN canonical_opportunities o ON o.organization_id=e.organization_id AND o.id=e.opportunity_id JOIN canonical_customers c ON c.organization_id=o.organization_id AND c.id=o.customer_id WHERE e.organization_id=$1 AND e.id=$2',[f.org,estimate])).rows[0];await f.ownerPool.query("UPDATE canonical_customers SET updated_at=updated_at+interval '1 second' WHERE organization_id=$1 AND id=$2",[f.org,customer.id]);let read=(await request(f.app).get(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`).set(owner.session.headers)).body.data.current;expect(read).toMatchObject({fresh:false,available:false,summary:null});expect((await post(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`,summaryBody,summaryKey)).status).toBe(409);await f.ownerPool.query('UPDATE canonical_customers SET updated_at=$3 WHERE organization_id=$1 AND id=$2',[f.org,customer.id,customer.updated_at]);
  response=await post('/api/v1/learning/job-outcome-graph/consent',{action:'revoke',expectedRevision:consent.revision,expectedDigest:consent.digest,reason:'Stop reviewing connected job outcomes.',confirmed:true,confirmationVersion:'m25-job-outcome-graph-consent-v1'});const revoked=response.body.data.consent;read=(await request(f.app).get(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`).set(owner.session.headers)).body.data;expect(read).toMatchObject({activeConsent:false,current:null,total:0});expect((await post(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`,summaryBody,summaryKey)).status).toBe(409);
  response=await post('/api/v1/learning/job-outcome-graph/consent',{action:'grant',expectedRevision:revoked.revision,expectedDigest:revoked.digest,reason:'Start a new connected outcome review period.',confirmed:true,confirmationVersion:'m25-job-outcome-graph-consent-v1'});read=(await request(f.app).get(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`).set(owner.session.headers)).body.data;expect(read).toMatchObject({activeConsent:true,current:null,total:0});expect((await post(`/api/v1/learning/estimates/${estimate}/job-outcome-summary`,summaryBody,summaryKey)).status).toBe(409);
  const privilege=(await f.ownerPool.query("SELECT has_table_privilege($1,'canonical_job_outcome_summaries','SELECT,INSERT,UPDATE,DELETE') table_access,has_function_privilege($1,'canonical_job_outcome_summary_compose(uuid,uuid,text,uuid,canonical_job_outcome_graphs,canonical_job_outcome_graph_evaluations)','EXECUTE') helper,has_function_privilege($1,'canonical_job_outcome_summary_read(uuid,uuid,text,uuid,uuid)','EXECUTE') entry",[f.roles.runtime])).rows[0];expect(privilege).toEqual({table_access:false,helper:false,entry:true});await expect(f.runtimePool.query('SELECT * FROM canonical_job_outcome_summaries')).rejects.toMatchObject({code:'42501'});await expect(f.ownerPool.query('DELETE FROM canonical_job_outcome_summaries')).rejects.toBeTruthy();
 const after=(await f.ownerPool.query('SELECT snapshot_digest FROM canonical_estimates WHERE organization_id=$1 AND id=$2',[f.org,estimate])).rows[0].snapshot_digest;expect(after).toBe(before);
 },180000);
 test('startup fails closed on leaked summary authority and restores the intended entry-only role',async()=>{
  const startup=async()=>{const client=await f.ownerPool.connect();try{await client.query('BEGIN');try{const result=await f.db.grantAndVerifyRuntimeAuthorityForTests(client,{runtimeRole:f.roles.runtime});await client.query('COMMIT');return result;}catch(error){await client.query('ROLLBACK');throw error;}}finally{client.release();}};
  const privileges=async()=>(await f.ownerPool.query("SELECT has_table_privilege($1,'canonical_job_outcome_summaries','SELECT,INSERT,UPDATE,DELETE') table_access,has_function_privilege($1,'canonical_job_outcome_summary_compose(uuid,uuid,text,uuid,canonical_job_outcome_graphs,canonical_job_outcome_graph_evaluations)','EXECUTE') helper,has_function_privilege($1,'canonical_job_outcome_summary_read(uuid,uuid,text,uuid,uuid)','EXECUTE') entry",[f.roles.runtime])).rows[0];

  await f.ownerPool.query('GRANT SELECT ON TABLE canonical_job_outcome_summaries TO PUBLIC');
  try{await expect(startup()).rejects.toThrow('Runtime database role privilege verification failed');}
  finally{await f.ownerPool.query('REVOKE ALL ON TABLE canonical_job_outcome_summaries FROM PUBLIC');}

  await f.ownerPool.query('GRANT EXECUTE ON FUNCTION canonical_job_outcome_summary_compose(uuid,uuid,text,uuid,canonical_job_outcome_graphs,canonical_job_outcome_graph_evaluations) TO PUBLIC');
  try{await expect(startup()).rejects.toThrow('Runtime database role privilege verification failed');}
  finally{await f.ownerPool.query('REVOKE ALL ON FUNCTION canonical_job_outcome_summary_compose(uuid,uuid,text,uuid,canonical_job_outcome_graphs,canonical_job_outcome_graph_evaluations) FROM PUBLIC');}

  await f.ownerPool.query('REVOKE ALL ON FUNCTION canonical_job_outcome_summary_read(uuid,uuid,text,uuid,uuid) FROM '+`"${f.roles.runtime.replace(/"/g,'""')}"`);
  expect((await privileges()).entry).toBe(false);
  await expect(startup()).resolves.toBeUndefined();
  expect(await privileges()).toEqual({table_access:false,helper:false,entry:true});
  await expect(f.runtimePool.query('SELECT * FROM canonical_job_outcome_summaries')).rejects.toMatchObject({code:'42501'});
  await expect(f.runtimePool.query("SELECT canonical_job_outcome_summary_domains_valid('[]'::jsonb)")).rejects.toMatchObject({code:'42501'});
 },180000);
});
