'use strict';
const {stableValue,sha256}=require('../services/businessProfileAdapter');
const legacy=require('./materialAdoptionContract'), material=require('./materialPlanContract'), labor=require('./laborPlanContract');
const VERSION='estimate-cost-adoption-v1',MAX=99999999999999n;
const FIELDS=['sourcePins','expectedPlanId','expectedPlanRevision','expectedPlanDigest','expectedDecisionRevision','expectedDecisionDigest','reason','confirmed','confirmationVersion','changedComponent','expectedComponents','assessment'];
function fail(message,status=400){throw Object.assign(new Error(message),{status,code:'COST_ADOPTION_INVALID'});}
function normalize(body){if(!body||Object.keys(body).length!==FIELDS.length||!FIELDS.every(k=>Object.hasOwn(body,k))||body.confirmationVersion!==VERSION||!['material','labor'].includes(body.changedComponent)||body.confirmed!==true||typeof body.reason!=='string'||!body.reason.trim()||Array.from(body.reason.trim()).length>2000||/[\u0000-\u001f\u007f-\u009f]/.test(body.reason)||!body.sourcePins||!body.expectedComponents||!body.assessment||typeof body.expectedPlanId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(body.expectedPlanId)||!Number.isSafeInteger(body.expectedPlanRevision)||body.expectedPlanRevision<1||body.expectedPlanRevision>10000||!Number.isSafeInteger(body.expectedDecisionRevision)||body.expectedDecisionRevision<0||body.expectedDecisionRevision>10000||! /^[a-f0-9]{64}$/.test(body.expectedPlanDigest)||!(body.expectedDecisionRevision===0?body.expectedDecisionDigest==='none':/^[a-f0-9]{64}$/.test(body.expectedDecisionDigest)))fail('Review the selected plan, its sources and the estimate change.');return stableValue({...body,reason:body.reason.trim()});}
function reference(plan){return plan?{kind:'plan',id:plan.id,revision:plan.revision,digest:plan.digest,calculationVersion:plan.calculationVersion,sourcePins:plan.sourcePins}:{kind:'original'};}
function components(selection){const s=selection?.selected;return stableValue(s?.calculationVersion===VERSION?s.componentManifest:{material:reference(s?.materialPlan),labor:reference(null)});}
function plans(selection){return {material:selection?.selected?.materialPlan||null,labor:selection?.selected?.laborPlan||null};}
function compose(selection,component,plan){return {...plans(selection),[component]:plan};}
function manifest(pair){return stableValue({material:reference(pair.material),labor:reference(pair.labor)});}
function applicable(value){return typeof value==='number'&&Number.isFinite(value)&&value>=0?value>0:null;}
function calculate(item,pair){if(item?.calculationVersion!==legacy.BASE_VERSION||!item.snapshot||!['USD','CAD','EUR'].includes(item.estimate?.currency))fail('This estimate cannot support a new cost review.');const s=item.snapshot,currency=item.estimate.currency,m=pair.material,l=pair.labor;if(m&&(m.action!=='save'||m.currency!==currency||!material.VERSIONS.includes(m.calculationVersion)))fail('The saved material plan is unavailable.');if(l&&(l.action!=='save'||l.currency!==currency||l.calculationVersion!==labor.VERSION))fail('The saved labor plan is unavailable.');const mr=m?material.calculate(m.inputs,currency,m.calculationVersion):null,lr=l?labor.calculate(l.inputs,currency):null;if(l&&lr.total===null)fail('Complete the missing labor costs before applying this plan.');const distance=s.travel?.distanceMiles;const applicability={material:m?true:applicable(s.materialsCharge),labor:l?true:applicable(s.laborCharge),equipment:applicable(s.equipmentCharge),travel:distance===null?false:typeof distance==='number'&&Number.isFinite(distance)&&distance>=0?true:null};const values={material:m?legacy.cents(mr.total):legacy.recordedCents(s.knownDirectMaterialCost),labor:l?legacy.cents(lr.total):legacy.recordedCents(s.knownInternalLaborCost),equipment:legacy.recordedCents(s.knownEquipmentCost),travel:legacy.recordedCents(s.travel?.knownInternalCost)};const complete=s.service?.supported===true&&Object.values(applicability).every(v=>v!==null)&&Object.keys(values).every(k=>applicability[k]!==true||values[k]!==null);let total=complete?Object.keys(values).reduce((n,k)=>n+(applicability[k]===true?values[k]:0n),0n):null;if(total!==null&&total>MAX)fail('Combined costs are too large. Review the plans.');return stableValue({calculationVersion:VERSION,currency,material:mr,labor:lr,knownDirectMaterialCost:legacy.decimal(values.material),knownInternalLaborCost:legacy.decimal(values.labor),knownEquipmentCost:legacy.decimal(values.equipment),knownTravelInternalCost:legacy.decimal(values.travel),knownDirectCosts:legacy.decimal(total),applicability,overhead:null,grossProfit:null,netProfit:null});}
function assessment(pair,serviceKey,now){return stableValue({date:now.toISOString().slice(0,10),laborSource:pair.labor?labor.assess(pair.labor.inputs,now):null,materialSource:pair.material&&[material.V3,material.V4].includes(pair.material.calculationVersion)?require('./materialSourceContract').assess(pair.material.inputs,pair.material.currency,{serviceKey,now}):null,materialAvailability:pair.material?.calculationVersion===material.V4?require('./materialAvailabilityContract').assess(pair.material.inputs,material.calculate(pair.material.inputs,pair.material.currency,pair.material.calculationVersion),{now}):null});}
function checkBasis(body,review,selection,plan){const d=review.decisions.writeBasis;if(review.isCurrent===false||!plan||plan.action!=='save'||plan.currency!==review.currency||body.expectedPlanId!==plan.id||body.expectedPlanRevision!==plan.revision||body.expectedPlanDigest!==plan.digest||sha256(plan.sourcePins)!==sha256(review.pins)||sha256(body.sourcePins)!==sha256(review.pins)||body.expectedDecisionRevision!==d.revision||body.expectedDecisionDigest!==d.digest||sha256(body.expectedComponents)!==sha256(components(selection)))fail('The estimate, plan or price review changed. Refresh and review again.',409);if(components(selection)[body.changedComponent]?.id===plan.id)fail('This plan is already included in the estimate.',409);}
function preview(item,selection,review,plan,component,now){if(!plan)fail('Save a current plan before applying it.');const pair=compose(selection,component,plan);const result=calculate(item,pair);return stableValue({result,sourcePins:review.pins,planId:plan.id,planDigest:plan.digest,decisionBasis:review.decisions.writeBasis,expectedComponents:components(selection),componentManifest:manifest(pair),assessment:assessment(pair,review.materialSourceContext.serviceKey,now)});}
function checkEvidence(item,selection,review,body,plan,now){checkBasis(body,review,selection,plan);if(body.changedComponent==='material'&&[material.V3,material.V4].includes(plan.calculationVersion))material.checkEvidence(plan.inputs,plan.currency,plan.calculationVersion,{now,serviceKey:review.materialSourceContext.serviceKey},true);else if(body.changedComponent==='labor'){if(plan.inputs.serviceKey!==review.materialSourceContext.serviceKey)fail('The service changed. Review the tasks again.',409);labor.calculate(plan.inputs,plan.currency);}const p=preview(item,selection,review,plan,body.changedComponent,now);if(sha256(body.assessment)!==sha256(p.assessment))fail('Source information changed. Refresh the comparison and confirm again.',409);return p;}
module.exports={VERSION,normalize,reference,components,plans,compose,manifest,calculate,assessment,checkBasis,preview,checkEvidence};
