'use strict';
const contract=require('./customerEstimateDeliveryContract');
const actorArgs=i=>[i.organizationId,i.actorUserId,i.actorAccessRole,i.authSessionId,i.estimateId];
function failure(e){if(e&&e.status)return e;const status=e?.code==='42501'?403:e?.code==='P0002'?404:e?.code==='P0001'?410:['40001','40P01','23505'].includes(e?.code)?409:['22023','22P02','23514'].includes(e?.code)?400:e?.code==='54000'?429:503;const message=status===404?'This customer estimate link is unavailable.':status===410?'This customer estimate link expired or was revoked.':status===409?'This customer estimate response was already recorded or changed. Refresh before trying again.':status===400?'Check the customer estimate details and try again.':status===403?'Your current account cannot manage customer estimate links.':status===429?'This estimate reached its customer-response limit.':'Customer estimate delivery is temporarily unavailable.';return Object.assign(new Error(message),{status,code:'CUSTOMER_ESTIMATE_DELIVERY_UNAVAILABLE',cause:e});}
function urlPath(token){return'/estimate/'+encodeURIComponent(token);}
async function read(client,input){try{return(await client.query('SELECT public.canonical_customer_estimate_delivery_read($1,$2,$3,$4,$5) result',actorArgs(input))).rows[0].result;}catch(e){throw failure(e);}}
async function create(pool,input,raw,now=new Date()){
 const body=contract.create(raw,now),idempotencyKey=contract.key(input.idempotencyKey),publicToken=contract.token(input.organizationId+':'+input.actorUserId,idempotencyKey),hash=contract.tokenHash(publicToken),client=await pool.connect();let discard=false;
 try{await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE');await client.query("SET LOCAL statement_timeout='10s'");await client.query("SET LOCAL lock_timeout='2s'");const data=(await client.query('SELECT public.canonical_customer_estimate_delivery_create($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) result',[...actorArgs(input),input.csrfToken,idempotencyKey,body.versionId,hash,body.expiresAt])).rows[0].result;await client.query('COMMIT');return{...data,urlPath:urlPath(publicToken)};}catch(e){await client.query('ROLLBACK').catch(()=>{discard=true;});throw failure(e);}finally{client.release(discard);}
}
async function revoke(pool,input,linkId){const idempotencyKey=contract.key(input.idempotencyKey),client=await pool.connect();let discard=false;try{await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE');const data=(await client.query('SELECT public.canonical_customer_estimate_delivery_revoke($1,$2,$3,$4,$5,$6,$7,$8) result',[...actorArgs(input),input.csrfToken,idempotencyKey,linkId])).rows[0].result;await client.query('COMMIT');return data;}catch(e){await client.query('ROLLBACK').catch(()=>{discard=true;});throw failure(e);}finally{client.release(discard);}}
async function demoRead(client,input){try{return(await client.query('SELECT public.demo_customer_estimate_delivery_read($1,$2,$3) result',[input.sourceTokenHash,input.tenantId,input.estimateId])).rows[0].result;}catch(e){throw failure(e);}}
async function demoCreate(client,input,raw,document,now=new Date()){try{const body=contract.create(raw,now),idempotencyKey=contract.key(input.idempotencyKey),publicToken=contract.token('demo:'+input.sourceTokenHash,idempotencyKey),tokenHash=contract.tokenHash(publicToken),keyHash=contract.sha256(idempotencyKey),requestHash=contract.sha256({estimateId:input.estimateId,versionId:body.versionId,tokenHash,expiresAt:body.expiresAt});const data=(await client.query('SELECT public.demo_customer_estimate_delivery_create($1,$2,$3,$4,$5,$6,$7,$8,$9) result',[input.sourceTokenHash,input.tenantId,input.estimateId,body.versionId,document,keyHash,requestHash,tokenHash,body.expiresAt])).rows[0].result;return{...data,urlPath:urlPath(publicToken)};}catch(e){throw failure(e);}}
async function demoRevoke(client,input,linkId){try{const keyHash=contract.sha256(contract.key(input.idempotencyKey)),requestHash=contract.sha256({estimateId:input.estimateId,linkId,action:'revoke'});return(await client.query('SELECT public.demo_customer_estimate_delivery_revoke($1,$2,$3,$4,$5,$6) result',[input.sourceTokenHash,input.tenantId,input.estimateId,linkId,keyHash,requestHash])).rows[0].result;}catch(e){throw failure(e);}}
async function publicRead(client,rawToken){try{return(await client.query('SELECT public.customer_estimate_delivery_public_read($1) result',[contract.tokenHash(rawToken)])).rows[0].result;}catch(e){throw failure(e);}}
async function publicMutate(pool,input,raw,kind){const body=kind==='accepted'?contract.accept(raw):contract.question(raw),keyHash=contract.sha256(contract.key(input.idempotencyKey)),requestHash=contract.sha256({kind,body}),remoteHash=contract.sha256(input.remoteAddress||'unknown'),agentHash=contract.sha256(input.userAgent||'unknown'),client=await pool.connect();let discard=false;try{await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE');const data=(await client.query('SELECT public.customer_estimate_delivery_public_mutate($1,$2,$3,$4,$5,$6,$7) result',[contract.tokenHash(input.token),kind,keyHash,requestHash,body,remoteHash,agentHash])).rows[0].result;await client.query('COMMIT');return data;}catch(e){await client.query('ROLLBACK').catch(()=>{discard=true;});throw failure(e);}finally{client.release(discard);}}
module.exports={read,create,revoke,demoRead,demoCreate,demoRevoke,publicRead,publicMutate,failure};
