'use strict';
const crypto=require('node:crypto');
const {sha256,stableValue}=require('../services/businessProfileAdapter');
const TOKEN_SECRET=()=>process.env.CUSTOMER_ESTIMATE_LINK_SECRET||process.env.AUTH_ACCESS_SECRET;
function error(message='Check the customer estimate link details and try again.'){throw Object.assign(new Error(message),{status:400,code:'CUSTOMER_ESTIMATE_DELIVERY_INVALID'});}
function key(value){if(typeof value!=='string'||!/^[A-Za-z0-9._:-]{16,128}$/.test(value))error('A valid retry key is required.');return value;}
function token(context,idempotencyKey){const secret=TOKEN_SECRET();if(typeof secret!=='string'||secret.length<32)throw Object.assign(new Error('Customer estimate links are unavailable.'),{status:503,code:'CUSTOMER_ESTIMATE_DELIVERY_UNAVAILABLE'});return crypto.createHmac('sha256',secret).update('northstar-customer-estimate-link-v1\0'+context+'\0'+key(idempotencyKey),'utf8').digest('base64url');}
function tokenHash(value){if(typeof value!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(value))error('This customer estimate link is invalid.');return crypto.createHash('sha256').update(value,'utf8').digest('hex');}
function create(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(k=>!['versionId','expiresInDays','confirmed','confirmationVersion'].includes(k))||raw.confirmed!==true||raw.confirmationVersion!=='customer-estimate-delivery-v1'||typeof raw.versionId!=='string'||!/^[0-9a-f-]{36}$/i.test(raw.versionId))error();const days=Number(raw.expiresInDays);if(!Number.isSafeInteger(days)||days<1||days>30)error('Choose a link duration from 1 to 30 days.');return Object.freeze(stableValue({versionId:raw.versionId,expiresInDays:days,confirmed:true,confirmationVersion:'customer-estimate-delivery-v1'}));}
function accept(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(k=>!['customerName','confirmed','confirmationVersion'].includes(k))||raw.confirmed!==true||raw.confirmationVersion!=='customer-estimate-accept-v1'||typeof raw.customerName!=='string')error('Enter your name and confirm that you accept this estimate.');const customerName=raw.customerName.trim().replace(/\s+/g,' ');if(customerName.length<2||customerName.length>160)error('Enter your name and confirm that you accept this estimate.');return Object.freeze(stableValue({customerName,confirmed:true,confirmationVersion:'customer-estimate-accept-v1'}));}
function question(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(k=>!['customerName','replyTo','message','confirmed','confirmationVersion'].includes(k))||raw.confirmed!==true||raw.confirmationVersion!=='customer-estimate-question-v1')error('Enter your question and contact information.');const customerName=String(raw.customerName||'').trim().replace(/\s+/g,' '),replyTo=String(raw.replyTo||'').trim(),message=String(raw.message||'').trim().replace(/\r\n/g,'\n');if(customerName.length<2||customerName.length>160||replyTo.length<3||replyTo.length>254||message.length<3||message.length>4000)error('Enter your question and contact information.');return Object.freeze(stableValue({customerName,replyTo,message,confirmed:true,confirmationVersion:'customer-estimate-question-v1'}));}
module.exports={create,accept,question,key,token,tokenHash,sha256,error};
