'use strict';
const {stableValue,sha256}=require('../services/businessProfileAdapter');
const math=require('./pricingCalculation');
const FIELDS=['action','expectedRevision','expectedDigest','sourcePins','expectedDecisionRevision','expectedDecisionDigest','inputs','currency','reason','confirmed','confirmationVersion','evidenceDigest'];
function conflict(message='The estimate, pricing plan or sources changed. Refresh and calculate again.'){throw Object.assign(new Error(message),{status:409,code:'PRICING_REVIEW_CHANGED'});}
function normalize(b){if(!math.exact(b,FIELDS)||!['save','withdraw'].includes(b.action)||![b.expectedRevision,b.expectedDecisionRevision].every(n=>Number.isSafeInteger(n)&&n>=0&&n<=10000)||typeof b.expectedDigest!=='string'||typeof b.expectedDecisionDigest!=='string'||!b.sourcePins||typeof b.sourcePins!=='object'||Array.isArray(b.sourcePins)||b.confirmed!==true||b.confirmationVersion!==math.VERSION||!math.text(b.reason,2000)||!['USD','CAD','EUR'].includes(b.currency)||typeof b.evidenceDigest!=='string'||!/^[a-f0-9]{64}$/.test(b.evidenceDigest))math.fail('Review the pricing entries and confirmation.');if(b.action==='withdraw'&&b.inputs!==null)math.fail('A withdrawal cannot contain a new pricing plan.');return stableValue({...b,reason:b.reason.trim()});}
function checkBasis(b,review,current){const d=review.decisions.writeBasis;if(review.isCurrent===false||b.expectedRevision!==(current?.revision||0)||b.expectedDigest!==(current?.digest||'none')||b.expectedDecisionRevision!==d.revision||b.expectedDecisionDigest!==d.digest||sha256(b.sourcePins)!==sha256(review.pins)||b.currency!==review.currency)conflict();}
function sourceList(inputs){return inputs?[...inputs.lines.map(l=>l.source),inputs.overhead.source]:[];}
function currentSource(s,sources){if(s.kind==='owner_estimate')return true;return(sources.references||[]).some(r=>r.kind===s.kind&&r.referenceId===s.referenceId&&r.digest===s.digest);}
function dateAssessment(inputs,date){const cautions=[];sourceList(inputs).forEach((s,index)=>{const reasons=[];if(!s.effectiveOn)reasons.push('date_unknown');else if(s.effectiveOn>date)reasons.push('not_yet_effective');if(!s.endsOn)reasons.push('freshness_unknown');else if(s.endsOn<date)reasons.push('expired');if(reasons.length)cautions.push({index,reasons});});return{date,cautions};}
function assess(inputs,sources){if(inputs.serviceKey!==sources.serviceKey)conflict('The job service changed. Refresh and review the pricing plan.');for(const s of sourceList(inputs))if(!currentSource(s,sources))conflict('A pricing source changed or is unavailable. Choose an available source and calculate again.');return dateAssessment(inputs,sources.asOfDate);}
function preview(inputs,currency,sources,now){if(sources.asOfDate!==new Date(now).toISOString().slice(0,10))conflict('The review date changed. Refresh and calculate again.');return stableValue({result:math.calculate(inputs,currency,sources.basis),assessment:assess(inputs,sources),evidenceDigest:sources.digest});}

function demoPlan(history,review,raw,key,now,sources){const body=normalize(raw),requestDigest=sha256(body),prior=history.find(e=>e.requestKey===key);if(prior){if(prior.requestDigest!==requestDigest)conflict('This save attempt was already used for different entries.');return{receipt:prior,replayed:true};}checkBasis(body,review,history[0]);let calculated=null;if(body.action==='save'){if(body.evidenceDigest!==sources.digest)conflict();calculated=preview(body.inputs,body.currency,sources,now);}else if(history[0]?.action!=='save')math.fail('There is no saved pricing plan to withdraw.');if(history.length>=20)throw Object.assign(new Error('This demo has reached its pricing history limit. Saved history remains available. Resetting clears its practice work.'),{status:429,code:'PRICING_HISTORY_LIMIT'});const receipt={id:require('node:crypto').randomUUID(),revision:(history[0]?.revision||0)+1,previousId:history[0]?.id||null,...body,calculationVersion:math.VERSION,result:calculated?.result||null,assessment:calculated?.assessment||null,evidence:body.action==='save'?sources:null,actorName:'Demo Reviewer',createdAt:now.toISOString(),requestKey:key,requestDigest,digest:sha256({body,sources:body.action==='save'?sources:null,previous:history[0]?.digest||null})};return{receipt,replayed:false};}
function project(data,review,sources,enabled,simulated,paused,now=new Date()){function expose(e){if(!e)return null;const {requestKey,requestDigest,evidence,...safe}=e;const hidden=sourceList(e.inputs).some(s=>!currentSource(s,sources));return{...safe,assessment:hidden?null:(safe.assessment||(safe.inputs&&evidence?.asOfDate?dateAssessment(safe.inputs,evidence.asOfDate):null)),result:hidden?null:safe.result,inputs:hidden?null:safe.inputs,reason:hidden?'Saved pricing source is no longer available.':safe.reason,sourceUnavailable:hidden,sourceBasisCurrent:sha256(e.sourcePins)===sha256(review.pins),currentAssessment:!hidden&&e.inputs?assess(e.inputs,{...sources,serviceKey:e.inputs.serviceKey},now):null};}return stableValue({contract:math.VERSION,sourcePins:review.pins,serviceKey:review.materialSourceContext?.serviceKey,decisionBasis:review.decisions.writeBasis,sources,canMutate:enabled&&review.isCurrent,mutationsPaused:paused,simulated,current:expose(data.current),history:(data.history||[]).map(expose),total:data.total||0,truncated:data.truncated===true});}
module.exports={...math,FIELDS,normalize,checkBasis,currentSource,sourceList,dateAssessment,assess,preview,demoPlan,project};
