'use strict';
const {stableValue,sha256}=require('../services/businessProfileAdapter');
const math=require('./pricingPolicyCalculation'),prior=require('./pricingPlanContract');
const FIELDS=[...prior.FIELDS,'pricingPin'];
function conflict(message='The estimate, pricing or reviewed price changed. Refresh and calculate the policy again.'){throw Object.assign(new Error(message),{status:409,code:'PRICING_POLICY_CHANGED'});}
function pin(p){return p?{id:p.id,revision:p.revision,digest:p.digest}:null;}
function normalize(b){if(!math.exact(b,FIELDS)||!['save','withdraw'].includes(b.action)||![b.expectedRevision,b.expectedDecisionRevision].every(n=>Number.isSafeInteger(n)&&n>=0&&n<=10000)||typeof b.expectedDigest!=='string'||typeof b.expectedDecisionDigest!=='string'||!b.sourcePins||typeof b.sourcePins!=='object'||Array.isArray(b.sourcePins)||b.confirmed!==true||b.confirmationVersion!==math.VERSION||!math.text(b.reason,2000)||!['USD','CAD','EUR'].includes(b.currency)||typeof b.evidenceDigest!=='string'||!/^[a-f0-9]{64}$/.test(b.evidenceDigest))math.fail('Review the policy entries and confirmation.');if(b.action==='withdraw'&&b.inputs!==null||b.action==='save'&&(!math.exact(b.pricingPin,['id','revision','digest'])||!math.text(b.pricingPin.id,80)||!Number.isSafeInteger(b.pricingPin.revision)||typeof b.pricingPin.digest!=='string'||!/^[a-f0-9]{64}$/.test(b.pricingPin.digest)))math.fail('Choose a saved pricing plan for this policy.');return stableValue({...b,reason:b.reason.trim()});}
function checkBasis(b,review,current){prior.checkBasis(b,review,current);}
function sourceList(inputs){return inputs?[inputs.source]:[];}
function dateAssessment(inputs,date){return prior.dateAssessment(inputs?{lines:[],overhead:{source:inputs.source}}:null,date);}
function assess(inputs,sources){if(inputs.serviceKey!==sources.serviceKey||!prior.currentSource(inputs.source,sources))conflict('A policy source changed or is unavailable. Choose an available source and calculate again.');return dateAssessment(inputs,sources.asOfDate);}
function preview(inputs,currency,sources,now){if(!sources.pricingPin||!sources.basis)conflict('Save a current pricing plan before calculating this policy.');if(sources.asOfDate!==new Date(now).toISOString().slice(0,10))conflict('The review date changed. Refresh and calculate again.');return stableValue({result:math.calculate(inputs,currency,sources.basis),assessment:assess(inputs,sources),evidenceDigest:sources.digest,pricingPin:sources.pricingPin});}
function demoPlan(history,review,raw,key,now,sources){const b=normalize(raw),requestDigest=sha256(b),old=history.find(e=>e.requestKey===key);if(old){if(old.requestDigest!==requestDigest)conflict('This save attempt was already used for different entries.');return{receipt:old,replayed:true};}checkBasis(b,review,history[0]);let value=null;if(b.action==='save'){if(b.evidenceDigest!==sources.digest||sha256(b.pricingPin)!==sha256(sources.pricingPin))conflict();value=preview(b.inputs,b.currency,sources,now);}else if(history[0]?.action!=='save')math.fail('There is no saved policy to withdraw.');if(history.length>=20)throw Object.assign(new Error('This demo has reached its pricing policy history limit. Saved history remains available. Resetting clears its practice work.'),{status:429,code:'PRICING_POLICY_HISTORY_LIMIT'});return{replayed:false,receipt:{id:require('node:crypto').randomUUID(),revision:(history[0]?.revision||0)+1,previousId:history[0]?.id||null,...b,pricingPin:b.action==='save'?sources.pricingPin:history[0].pricingPin,calculationVersion:math.VERSION,result:value?.result||null,assessment:value?.assessment||null,evidence:b.action==='save'?sources:null,actorName:'Demo Reviewer',createdAt:now.toISOString(),requestKey:key,requestDigest,digest:sha256({body:b,sources:b.action==='save'?sources:null,previous:history[0]?.digest||null})}};}
function project(data,review,sources,enabled,simulated,paused){
 function expose(e){if(!e)return null;const {requestKey,requestDigest,evidence,...safe}=e;const hidden=sourceList(e.inputs).some(s=>!prior.currentSource(s,sources))||(evidence?.pricingSources||prior.sourceList(evidence?.pricing?.inputs)).some(s=>!prior.currentSource(s,sources));const sourceBasisCurrent=sha256(e.sourcePins)===sha256(review.pins)&&sha256(e.pricingPin)===sha256(sources.pricingPin)&&!!sources.basis;const decisionBasisCurrent=e.expectedDecisionRevision===review.decisions.writeBasis.revision&&e.expectedDecisionDigest===review.decisions.writeBasis.digest;return{...safe,result:hidden?null:safe.result,inputs:hidden?null:safe.inputs,reason:hidden?'A saved pricing source is no longer available.':safe.reason,sourceUnavailable:hidden,sourceBasisCurrent,decisionBasisCurrent,current:sourceBasisCurrent&&decisionBasisCurrent&&!hidden,assessment:hidden?null:safe.assessment||dateAssessment(safe.inputs,evidence?.asOfDate||evidence?.baseSources?.asOfDate||sources.asOfDate),currentAssessment:!hidden&&e.inputs?dateAssessment(e.inputs,sources.asOfDate):null};}
 const current=expose(data.current);return stableValue({contract:math.VERSION,sourcePins:review.pins,serviceKey:sources.serviceKey,decisionBasis:review.decisions.writeBasis,sources,canMutate:enabled&&review.isCurrent,mutationsPaused:paused,simulated,current,history:(data.history||[]).map(expose),total:data.total||0,truncated:data.truncated===true});
}
function policyCheck(plans){const p=plans.current;if(!p||p.action!=='save')return{state:'unavailable',message:'Save a pricing policy to compare the proposal and reviewed price.'};if(p.sourceUnavailable)return{state:'unavailable',message:'A pricing source is unavailable. Review the available sources.'};if(!p.current)return{state:'changed',message:'Pricing or the reviewed price changed. Refresh and review the policy again.'};return{state:p.result?.threshold===null?'incomplete':'compared',result:p.result,message:'This is a policy comparison, not an approval of the price or policy.'+(p.currentAssessment?.cautions?.length?' Source dates need review; these are declared assumptions, not verified market pricing.':'')};}
module.exports={...math,FIELDS,pin,normalize,checkBasis,sourceList,dateAssessment,assess,preview,demoPlan,project,policyCheck};
