-- Package B v2 capability only. No validated rules ship here.
SELECT set_config('northstar.package_b_lock_timeout',current_setting('lock_timeout'),true),set_config('northstar.package_b_statement_timeout',current_setting('statement_timeout'),true);
SELECT set_config('lock_timeout',least(COALESCE(NULLIF((SELECT setting::integer FROM pg_settings WHERE name='lock_timeout'),0),2000),2000)::text||'ms',true),set_config('statement_timeout',least(COALESCE(NULLIF((SELECT setting::integer FROM pg_settings WHERE name='statement_timeout'),0),20000),20000)::text||'ms',true);
CREATE FUNCTION public.canonical_commercial_tax_rule_validate(v JSONB) RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE k TEXT;a JSONB;allowed TEXT[];
BEGIN
 IF public.canonical_field_evidence_object_keys_exact(v,ARRAY['version','validation','simulated','active','treatment','behavior','ratePercent','legalEffectiveOn','legalEndsOn','reviewedOn','reviewValidThrough','registration','collectionBasis','country','region','locality','jurisdiction','serviceKey','classification','applicability']) IS NOT TRUE OR v->>'version' IS DISTINCT FROM 'tax-preparation-v2' OR v->>'validation' IS DISTINCT FROM 'validated' OR jsonb_typeof(v->'simulated') IS DISTINCT FROM 'boolean' OR jsonb_typeof(v->'active') IS DISTINCT FROM 'boolean' OR v->>'treatment' IS NULL OR v->>'treatment' NOT IN('taxable','zero_rate','exempt') OR v->>'behavior' IS NULL OR v->>'behavior' NOT IN('exclusive','inclusive') OR v->>'registration' IS NULL OR v->>'registration' NOT IN('unknown','registered','not_registered','exempt') THEN RAISE EXCEPTION 'Tax rule invalid' USING ERRCODE='22023';END IF;
 IF public.canonical_commercial_percent(v->'ratePercent')>1000000 OR v->>'treatment' IN('zero_rate','exempt') AND public.canonical_commercial_percent(v->'ratePercent')<>0 THEN RAISE EXCEPTION 'Tax rule rate invalid' USING ERRCODE='22023';END IF;
 IF public.canonical_pricing_day(v->'legalEffectiveOn') IS NOT TRUE OR v->'legalEndsOn'<>'null'::jsonb AND public.canonical_pricing_day(v->'legalEndsOn') IS NOT TRUE OR v->>'legalEndsOn'<v->>'legalEffectiveOn' OR public.canonical_pricing_day(v->'reviewedOn') IS NOT TRUE OR public.canonical_pricing_day(v->'reviewValidThrough') IS NOT TRUE OR v->>'reviewValidThrough'<v->>'reviewedOn' THEN RAISE EXCEPTION 'Tax rule dates invalid' USING ERRCODE='22023';END IF;
 FOREACH k IN ARRAY ARRAY['country','region','locality','jurisdiction','serviceKey','classification','collectionBasis'] LOOP IF public.canonical_pricing_text(v->k,CASE WHEN k='collectionBasis' THEN 1000 ELSE 300 END,k='locality') IS NOT TRUE THEN RAISE EXCEPTION 'Tax rule context invalid' USING ERRCODE='22023';END IF;END LOOP;
 IF public.canonical_field_evidence_object_keys_exact(v->'applicability',ARRAY['serviceOperations','propertyUses','workContexts','customerExemptions']) IS NOT TRUE THEN RAISE EXCEPTION 'Tax applicability invalid' USING ERRCODE='22023';END IF;
 FOREACH k IN ARRAY ARRAY['serviceOperations','propertyUses','workContexts','customerExemptions'] LOOP
  a:=v->'applicability'->k;IF jsonb_typeof(a) IS DISTINCT FROM 'array' OR jsonb_array_length(a) NOT BETWEEN 1 AND 12 THEN RAISE EXCEPTION 'Tax applicability list invalid' USING ERRCODE='22023';END IF;
  IF (SELECT count(DISTINCT value) FROM jsonb_array_elements(a))<>jsonb_array_length(a) THEN RAISE EXCEPTION 'Duplicate applicability' USING ERRCODE='22023';END IF;
  allowed:=CASE k WHEN 'propertyUses' THEN ARRAY['residential','commercial','mixed','other'] WHEN 'workContexts' THEN ARRAY['maintenance','repair','new_construction','capital_improvement','other'] WHEN 'customerExemptions' THEN ARRAY['none','claimed'] ELSE NULL END;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(a) e WHERE jsonb_typeof(e) IS DISTINCT FROM 'string' OR CASE WHEN k='serviceOperations' THEN (e#>>'{}')!~'^[a-z][a-z0-9_]{0,99}$' ELSE NOT((e#>>'{}')=ANY(allowed)) END) THEN RAISE EXCEPTION 'Unsupported applicability value' USING ERRCODE='22023';END IF;
 END LOOP;RETURN TRUE;
END $$;
CREATE FUNCTION public.canonical_commercial_tax_applicability(f JSONB,a JSONB) RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE k TEXT;
BEGIN
 IF public.canonical_field_evidence_object_keys_exact(f,ARRAY['serviceOperation','propertyUse','workContext','customerExemption','evidenceRef']) IS NOT TRUE OR public.canonical_field_evidence_object_keys_exact(f->'evidenceRef',ARRAY['serviceOperation','propertyUse','workContext','customerExemption']) IS NOT TRUE OR f->'serviceOperation'<>'null'::jsonb AND (jsonb_typeof(f->'serviceOperation') IS DISTINCT FROM 'string' OR f->>'serviceOperation'!~'^[a-z][a-z0-9_]{0,99}$') OR f->>'propertyUse' IS NULL OR f->>'propertyUse' NOT IN('unknown','residential','commercial','mixed','other') OR f->>'workContext' IS NULL OR f->>'workContext' NOT IN('unknown','maintenance','repair','new_construction','capital_improvement','other') OR f->>'customerExemption' IS NULL OR f->>'customerExemption' NOT IN('unknown','none','claimed') THEN RAISE EXCEPTION 'Job applicability invalid' USING ERRCODE='22023';END IF;
 FOREACH k IN ARRAY ARRAY['serviceOperation','propertyUse','workContext','customerExemption'] LOOP IF public.canonical_pricing_text(f->'evidenceRef'->k,1000,TRUE) IS NOT TRUE OR f->k<>'null'::jsonb AND f->>k<>'unknown' AND btrim(f->'evidenceRef'->>k)='' THEN RAISE EXCEPTION 'Job fact reference required' USING ERRCODE='22023';END IF;END LOOP;
 IF a IS NULL THEN RETURN FALSE;END IF;
 RETURN COALESCE(a->'serviceOperations' @> jsonb_build_array(f->'serviceOperation') AND a->'propertyUses' @> jsonb_build_array(f->'propertyUse') AND a->'workContexts' @> jsonb_build_array(f->'workContext') AND a->'customerExemptions' @> jsonb_build_array(f->'customerExemption'),FALSE);
END $$;
CREATE FUNCTION public.canonical_commercial_tax_rule_insert_guard() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=pg_catalog,public,pg_temp AS $$ BEGIN
 IF NEW.version IS DISTINCT FROM 'tax-preparation-v2' OR NEW.content->>'version' IS DISTINCT FROM NEW.version OR public.canonical_commercial_tax_rule_validate(NEW.content) IS NOT TRUE THEN RAISE EXCEPTION 'New tax rules require v2 reviewed coverage' USING ERRCODE='23514';END IF;RETURN NEW;
END $$;
ALTER TABLE public.canonical_tax_rule_versions DROP CONSTRAINT canonical_tax_rule_versions_version_check;
ALTER TABLE public.canonical_tax_rule_versions ADD CONSTRAINT canonical_tax_rule_versions_version_check CHECK(version IN('tax-preparation-v1','tax-preparation-v2'));
ALTER TABLE public.canonical_tax_rule_versions ADD CONSTRAINT canonical_tax_rule_versions_content_version_check CHECK((version='tax-preparation-v1' OR content->>'version'=version AND public.canonical_commercial_tax_rule_validate(content)) IS TRUE);
CREATE TRIGGER canonical_tax_rule_versions_v2_insert BEFORE INSERT ON public.canonical_tax_rule_versions FOR EACH ROW EXECUTE FUNCTION public.canonical_commercial_tax_rule_insert_guard();
ALTER TABLE public.canonical_tax_preparation_jobs DROP CONSTRAINT canonical_tax_preparation_jobs_version_check;
ALTER TABLE public.canonical_tax_preparation_jobs ADD CONSTRAINT canonical_tax_preparation_jobs_version_check CHECK(version IN('tax-preparation-v1','tax-preparation-v2'));
ALTER TABLE public.canonical_tax_preparation_jobs ADD CONSTRAINT canonical_tax_preparation_jobs_inputs_version_check CHECK((version='tax-preparation-v1' OR inputs->>'version'=version) IS TRUE);
ALTER TABLE public.canonical_tax_profiles ADD CONSTRAINT canonical_tax_profiles_version_check CHECK((body->>'confirmationVersion'='tax-preparation-v1' OR body->>'confirmationVersion'='tax-preparation-v2' AND inputs->>'version'='tax-preparation-v2') IS TRUE);
ALTER TABLE public.canonical_commercial_terms DROP CONSTRAINT canonical_commercial_terms_body_check;
ALTER TABLE public.canonical_commercial_terms ADD CONSTRAINT canonical_commercial_terms_body_check CHECK((body->>'confirmationVersion' IN('estimate-commercial-terms-v1','estimate-commercial-terms-v2')) IS TRUE);
ALTER TABLE public.canonical_commercial_terms ADD CONSTRAINT canonical_commercial_terms_result_version_check CHECK((body->>'confirmationVersion'='estimate-commercial-terms-v1' OR action='withdraw' OR body#>>'{inputs,version}'='estimate-commercial-terms-v2' AND result->>'calculationVersion'='estimate-commercial-terms-v2') IS TRUE);
CREATE OR REPLACE FUNCTION public.canonical_commercial_tax_profile_validate(v JSONB) RETURNS VOID LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE c JSONB;k TEXT;ids TEXT[]:='{}';
BEGIN
 IF v->>'version'='tax-preparation-v2' THEN IF public.canonical_field_evidence_object_keys_exact(v,ARRAY['version','contexts']) IS NOT TRUE THEN RAISE EXCEPTION 'Tax profile invalid' USING ERRCODE='22023';END IF;PERFORM public.canonical_commercial_tax_profile_validate(v-'version');RETURN;END IF;
 IF public.canonical_field_evidence_object_keys_exact(v,ARRAY['contexts']) IS NOT TRUE OR jsonb_typeof(v->'contexts') IS DISTINCT FROM 'array' OR jsonb_array_length(v->'contexts')>12 THEN RAISE EXCEPTION 'Tax profile invalid' USING ERRCODE='22023';END IF;
 FOR c IN SELECT * FROM jsonb_array_elements(v->'contexts') LOOP
  IF public.canonical_field_evidence_object_keys_exact(c,ARRAY['id','country','region','locality','jurisdiction','serviceKey','classification','registration','registrationReference','collectionBasis','exemptionReference','effectiveOn','endsOn','sourceNote','sourceReference','acknowledged']) IS NOT TRUE OR public.canonical_pricing_text(c->'id',80) IS NOT TRUE OR c->>'id'=ANY(ids) OR c->>'registration' IS NULL OR c->>'registration' NOT IN('unknown','registered','not_registered','exempt') OR jsonb_typeof(c->'acknowledged') IS DISTINCT FROM 'boolean' OR c->'effectiveOn'<>'null'::jsonb AND public.canonical_pricing_day(c->'effectiveOn') IS NOT TRUE OR c->'endsOn'<>'null'::jsonb AND public.canonical_pricing_day(c->'endsOn') IS NOT TRUE OR c->>'endsOn'<c->>'effectiveOn' THEN RAISE EXCEPTION 'Tax context invalid' USING ERRCODE='22023';END IF;
  ids:=array_append(ids,c->>'id');FOREACH k IN ARRAY ARRAY['country','region','locality','jurisdiction','serviceKey','classification','registrationReference','collectionBasis','exemptionReference','sourceNote','sourceReference'] LOOP IF public.canonical_pricing_text(c->k,CASE WHEN k='sourceNote' THEN 1000 ELSE 300 END,TRUE) IS NOT TRUE THEN RAISE EXCEPTION 'Tax context text invalid' USING ERRCODE='22023';END IF;END LOOP;
  IF c->>'registration'='unknown' AND (c->>'registrationReference'<>'' OR c->>'exemptionReference'<>'') OR c->>'registration'<>'exempt' AND c->>'exemptionReference'<>'' THEN RAISE EXCEPTION 'Tax registration declaration contradicts reference' USING ERRCODE='22023';END IF;
 END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_tax_inputs(org UUID) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE raw_value JSONB;declared JSONB;offices JSONB;services JSONB;
BEGIN
 SELECT raw_profile INTO raw_value FROM public.canonical_business_profiles WHERE organization_id=org AND is_active=TRUE;
 SELECT inputs INTO declared FROM public.canonical_tax_profiles WHERE organization_id=org ORDER BY revision DESC LIMIT 1;
 SELECT COALESCE(jsonb_agg(jsonb_build_object('id',v->>'id')||public.canonical_commercial_tax_location(v) ORDER BY v->>'id'),'[]'::jsonb) INTO offices FROM jsonb_array_elements(COALESCE(raw_value#>'{headquarters,additionalOffices}','[]'::jsonb)) v;
 SELECT COALESCE(jsonb_agg(jsonb_build_object('id',v->>'id','name',COALESCE(v->>'name',''),'description',COALESCE(v->>'description','')) ORDER BY v->>'id'),'[]'::jsonb) INTO services FROM jsonb_array_elements(COALESCE(raw_value->'services','[]'::jsonb)) v;
 RETURN jsonb_build_object('version',CASE WHEN declared IS NULL OR declared->>'version'='tax-preparation-v2' THEN 'tax-preparation-v2' ELSE 'tax-preparation-v1' END,'headquarters',public.canonical_commercial_tax_location(raw_value->'headquarters'),'offices',offices,'serviceArea',raw_value->'serviceArea','services',services,'declared',COALESCE(declared,'{"version":"tax-preparation-v2","contexts":[]}'::jsonb));
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_tax_rules() RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT COALESCE(jsonb_agg(content||jsonb_build_object('id',id,'digest',digest) ORDER BY rule_key),'[]'::jsonb) FROM (SELECT DISTINCT ON(rule_key) * FROM public.canonical_tax_rule_versions WHERE CASE WHEN version='tax-preparation-v1' THEN content->>'version'=version ELSE content->>'version'=version AND public.canonical_commercial_tax_rule_validate(content) END ORDER BY rule_key,revision DESC LIMIT 1000) r
$$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_tax_enqueue(org UUID) RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE inputs_value JSONB;input_hash TEXT;rule_hash TEXT;job UUID;date_value DATE;
BEGIN
 -- Caller and every worker acquire organization before job locks.
 PERFORM 1 FROM public.organizations WHERE id=org FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Organization unavailable' USING ERRCODE='P0002';END IF;
 inputs_value:=public.canonical_commercial_tax_inputs(org);input_hash:=public.canonical_completion_digest(inputs_value);rule_hash:=public.canonical_completion_digest(public.canonical_commercial_tax_rules());date_value:=(clock_timestamp() AT TIME ZONE 'UTC')::date;
 INSERT INTO public.canonical_tax_preparation_jobs(organization_id,input_digest,rules_digest,version,inputs,as_of_date) VALUES(org,input_hash,rule_hash,inputs_value->>'version',inputs_value,date_value) ON CONFLICT(organization_id,input_digest,rules_digest,version,as_of_date) DO NOTHING RETURNING id INTO job;
 IF job IS NULL THEN SELECT id INTO job FROM public.canonical_tax_preparation_jobs WHERE organization_id=org AND input_digest=input_hash AND rules_digest=rule_hash AND version=inputs_value->>'version' AND as_of_date=date_value;END IF;
 RETURN job;
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_tax_backfill(limit_value INTEGER DEFAULT 5) RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE org UUID;n INTEGER:=0;
BEGIN
 IF limit_value NOT BETWEEN 1 AND 10 THEN RAISE EXCEPTION 'Preparation batch outside range' USING ERRCODE='22023';END IF;
 FOR org IN SELECT o.id FROM public.organizations o WHERE EXISTS(SELECT 1 FROM public.canonical_business_profiles p WHERE p.organization_id=o.id AND p.is_active) AND NOT EXISTS(SELECT 1 FROM public.canonical_tax_preparation_jobs j WHERE j.organization_id=o.id AND j.version=public.canonical_commercial_tax_inputs(o.id)->>'version' AND j.as_of_date=(clock_timestamp() AT TIME ZONE 'UTC')::date AND j.input_digest=public.canonical_completion_digest(public.canonical_commercial_tax_inputs(o.id)) AND j.rules_digest=public.canonical_completion_digest(public.canonical_commercial_tax_rules())) ORDER BY o.id LIMIT limit_value FOR UPDATE OF o SKIP LOCKED LOOP PERFORM public.canonical_commercial_tax_enqueue(org);n:=n+1;END LOOP;
 RETURN n;
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_tax_evaluate(inputs_value JSONB,rules_value JSONB,as_of TEXT,simulated BOOLEAN DEFAULT FALSE) RETURNS JSONB LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE missing JSONB:='[]';coverage JSONB:='[]';gaps JSONB;c JSONB;r JSONB;matches JSONB;k TEXT;state_value TEXT;
BEGIN
 IF inputs_value->>'version'='tax-preparation-v2' THEN
  IF public.canonical_pricing_day(to_jsonb(as_of)) IS NOT TRUE OR jsonb_typeof(rules_value) IS DISTINCT FROM 'array' OR jsonb_array_length(rules_value)>1000 OR inputs_value#>>'{declared,version}' IS DISTINCT FROM 'tax-preparation-v2' THEN RAISE EXCEPTION 'Tax preparation invalid' USING ERRCODE='22023';END IF;
  PERFORM public.canonical_commercial_tax_profile_validate(inputs_value->'declared');
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(rules_value) v WHERE v->>'version' IS NULL OR v->>'version' NOT IN('tax-preparation-v1','tax-preparation-v2')) THEN RAISE EXCEPTION 'Tax rule version invalid' USING ERRCODE='22023';END IF;
  FOR r IN SELECT * FROM jsonb_array_elements(rules_value) WHERE value->>'version'='tax-preparation-v2' LOOP
   PERFORM public.canonical_commercial_tax_rule_validate(r-'id'-'digest');IF r->'simulated' IS DISTINCT FROM to_jsonb(simulated) THEN RAISE EXCEPTION 'Tax rule isolation invalid' USING ERRCODE='22023';END IF;
  END LOOP;
  SELECT COALESCE(jsonb_agg(v||jsonb_build_object('version','tax-preparation-v1','effectiveOn',v->'legalEffectiveOn','endsOn',COALESCE(v->>'legalEndsOn','9999-12-31'))),'[]'::jsonb) INTO rules_value FROM jsonb_array_elements(rules_value) v WHERE v->>'version'='tax-preparation-v2' AND as_of>=v->>'legalEffectiveOn' AND (v->'legalEndsOn'='null'::jsonb OR as_of<=v->>'legalEndsOn') AND as_of>=v->>'reviewedOn' AND as_of<=v->>'reviewValidThrough';
  RETURN public.canonical_commercial_tax_evaluate(inputs_value||jsonb_build_object('version','tax-preparation-v1','declared',(inputs_value->'declared')-'version'),rules_value,as_of,simulated)||jsonb_build_object('version','tax-preparation-v2','inputDigest',public.canonical_completion_digest(inputs_value));
 END IF;
 IF inputs_value->>'version' IS DISTINCT FROM 'tax-preparation-v1' OR public.canonical_pricing_day(to_jsonb(as_of)) IS NOT TRUE OR jsonb_typeof(rules_value) IS DISTINCT FROM 'array' OR jsonb_array_length(rules_value)>1000 THEN RAISE EXCEPTION 'Preparation input invalid' USING ERRCODE='22023';END IF;
 PERFORM public.canonical_commercial_tax_profile_validate(inputs_value->'declared');
 IF COALESCE(inputs_value#>>'{headquarters,country}','')='' OR COALESCE(inputs_value#>>'{headquarters,state}','')='' OR COALESCE(inputs_value#>>'{headquarters,city}','')='' THEN missing:=missing||'"operating_location"'::jsonb;END IF;
 IF jsonb_array_length(inputs_value->'services')=0 THEN missing:=missing||'"services"'::jsonb;END IF;
 IF jsonb_array_length(inputs_value#>'{declared,contexts}')=0 THEN missing:=missing||'"collection_context"'::jsonb;END IF;
 FOR c IN SELECT * FROM jsonb_array_elements(inputs_value#>'{declared,contexts}') LOOP
  gaps:='[]';FOREACH k IN ARRAY ARRAY['country','region','jurisdiction','serviceKey','classification','collectionBasis','sourceNote','sourceReference'] LOOP IF btrim(c->>k)='' THEN gaps:=gaps||to_jsonb(k);END IF;END LOOP;
  IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(inputs_value->'services') s WHERE s->>'id'=c->>'serviceKey') THEN gaps:=gaps||'"supported_service"'::jsonb;END IF;
  IF c->>'registration'='unknown' THEN gaps:=gaps||'"registration"'::jsonb;END IF;
  IF c->>'registration'='registered' AND btrim(c->>'registrationReference')='' THEN gaps:=gaps||'"registration_reference"'::jsonb;END IF;
  IF c->>'registration'='exempt' AND btrim(c->>'exemptionReference')='' THEN gaps:=gaps||'"exemption_reference"'::jsonb;END IF;
  IF c->'acknowledged'<>'true'::jsonb THEN gaps:=gaps||'"acknowledgment"'::jsonb;END IF;
  IF c->>'effectiveOn' IS NULL THEN gaps:=gaps||'"effective_date"'::jsonb;END IF;
  IF as_of<c->>'effectiveOn' OR as_of>c->>'endsOn' THEN gaps:=gaps||'"applicability_date"'::jsonb;END IF;
  matches:='[]';IF jsonb_array_length(gaps)=0 THEN FOR r IN SELECT * FROM jsonb_array_elements(rules_value) LOOP
   IF r->>'validation'='validated' AND r->'simulated'=to_jsonb(simulated) AND r->>'version'='tax-preparation-v1' AND r->>'country'=c->>'country' AND r->>'region'=c->>'region' AND r->>'locality'=c->>'locality' AND r->>'jurisdiction'=c->>'jurisdiction' AND r->>'serviceKey'=c->>'serviceKey' AND r->>'classification'=c->>'classification' AND r->>'registration'=c->>'registration' AND r->>'collectionBasis'=c->>'collectionBasis' AND public.canonical_pricing_day(r->'effectiveOn') IS TRUE AND public.canonical_pricing_day(r->'endsOn') IS TRUE AND as_of>=r->>'effectiveOn' AND as_of<=r->>'endsOn' AND jsonb_typeof(r->'id')='string' AND r->>'digest'~'^[a-f0-9]{64}$' AND r->'active'='true'::jsonb THEN matches:=matches||jsonb_build_array(r);END IF;
  END LOOP;END IF;
  coverage:=coverage||jsonb_build_array(jsonb_build_object('contextId',c->>'id','state',CASE WHEN jsonb_array_length(gaps)>0 THEN 'missing_inputs' WHEN jsonb_array_length(matches)=1 THEN 'matched' WHEN jsonb_array_length(matches)>1 THEN 'conflicting_coverage' ELSE 'unsupported' END,'missing',gaps,'rule',CASE WHEN jsonb_array_length(matches)=1 THEN jsonb_build_object('id',matches#>>'{0,id}','digest',matches#>>'{0,digest}') END));
 END LOOP;
 state_value:=CASE WHEN jsonb_array_length(missing)>0 OR EXISTS(SELECT 1 FROM jsonb_array_elements(coverage) element WHERE element->>'state'='missing_inputs') THEN 'missing_inputs' WHEN jsonb_array_length(coverage)>0 AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements(coverage) element WHERE element->>'state'<>'matched') THEN 'matched' ELSE 'unsupported' END;
 RETURN jsonb_build_object('version','tax-preparation-v1','asOfDate',as_of,'inputDigest',public.canonical_completion_digest(inputs_value),'simulated',simulated,'state',state_value,'missing',missing,'coverage',coverage);
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_tax_source(g JSONB,context_value JSONB,transaction_day TEXT) RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE s JSONB:=g->'source';r JSONB;field TEXT;
BEGIN
 IF context_value->>'commercialVersion'='estimate-commercial-terms-v2' THEN
  IF public.canonical_field_evidence_object_keys_exact(s,ARRAY['kind','note','reference','legalEffectiveOn','legalEndsOn','reviewedOn','reviewValidThrough','jurisdiction','location','serviceKey','collectionBasis','acknowledged','ruleId','ruleDigest']) IS NOT TRUE THEN RAISE EXCEPTION 'Review tax source dates separately' USING ERRCODE='22023';END IF;
  FOREACH field IN ARRAY ARRAY['legalEffectiveOn','legalEndsOn','reviewedOn','reviewValidThrough'] LOOP IF s->field<>'null'::jsonb AND public.canonical_pricing_day(s->field) IS NOT TRUE THEN RAISE EXCEPTION 'Tax source dates invalid' USING ERRCODE='22023';END IF;END LOOP;
  IF s->>'legalEndsOn'<s->>'legalEffectiveOn' OR s->>'reviewValidThrough'<s->>'reviewedOn' THEN RAISE EXCEPTION 'Tax source dates conflict' USING ERRCODE='22023';END IF;
  IF s->>'kind'='validated' THEN
   SELECT v INTO r FROM jsonb_array_elements(COALESCE(context_value->'validatedRules','[]'::jsonb)) v WHERE v->>'id'=s->>'ruleId' AND v->>'digest'=s->>'ruleDigest' LIMIT 1;
   IF r IS NULL OR r->>'version' IS DISTINCT FROM 'tax-preparation-v2' THEN RAISE EXCEPTION 'Validated tax source changed' USING ERRCODE='40001';END IF;
   PERFORM public.canonical_commercial_tax_rule_validate(r-'id'-'digest');
   FOREACH field IN ARRAY ARRAY['legalEffectiveOn','legalEndsOn','reviewedOn','reviewValidThrough'] LOOP IF s->field IS DISTINCT FROM r->field THEN RAISE EXCEPTION 'Tax source dates changed' USING ERRCODE='40001';END IF;END LOOP;
   IF transaction_day IS NULL OR transaction_day<r->>'legalEffectiveOn' OR transaction_day>r->>'legalEndsOn' OR context_value->>'asOfDate' IS NULL OR context_value->>'asOfDate'<r->>'reviewedOn' OR context_value->>'asOfDate'>r->>'reviewValidThrough' THEN RAISE EXCEPTION 'Tax source review changed' USING ERRCODE='40001';END IF;
   IF public.canonical_commercial_tax_applicability(context_value->'jobApplicability',r->'applicability') IS NOT TRUE THEN
    IF context_value#>'{jobApplicability,serviceOperation}'='null'::jsonb OR context_value#>>'{jobApplicability,propertyUse}'='unknown' OR context_value#>>'{jobApplicability,workContext}'='unknown' OR context_value#>>'{jobApplicability,customerExemption}'='unknown' THEN RETURN FALSE;END IF;
    RAISE EXCEPTION 'Recorded job does not match tax source' USING ERRCODE='22023';
   END IF;
  END IF;
  SELECT COALESCE(jsonb_agg(v||jsonb_build_object('effectiveOn',v->'legalEffectiveOn','endsOn',v->'legalEndsOn')),'[]'::jsonb) INTO r FROM jsonb_array_elements(COALESCE(context_value->'validatedRules','[]'::jsonb)) v;
  RETURN public.canonical_commercial_tax_source(g||jsonb_build_object('source',(s-'legalEffectiveOn'-'legalEndsOn'-'reviewedOn'-'reviewValidThrough')||jsonb_build_object('effectiveOn',s->'legalEffectiveOn','endsOn',s->'legalEndsOn')),(context_value-'commercialVersion')||jsonb_build_object('validatedRules',r),transaction_day);
 END IF;
 IF public.canonical_field_evidence_object_keys_exact(s,ARRAY['kind','note','reference','effectiveOn','endsOn','jurisdiction','location','serviceKey','collectionBasis','acknowledged','ruleId','ruleDigest']) IS NOT TRUE OR s->>'kind' IS NULL OR s->>'kind' NOT IN ('unknown','owner_recorded','validated') OR jsonb_typeof(s->'acknowledged') IS DISTINCT FROM 'boolean' OR s->'effectiveOn'<>'null'::jsonb AND public.canonical_pricing_day(s->'effectiveOn') IS NOT TRUE OR s->'endsOn'<>'null'::jsonb AND public.canonical_pricing_day(s->'endsOn') IS NOT TRUE OR s->>'endsOn'<s->>'effectiveOn' THEN RAISE EXCEPTION 'Tax source invalid' USING ERRCODE='22023';END IF;
 FOREACH field IN ARRAY ARRAY['note','reference','jurisdiction','location','serviceKey','collectionBasis'] LOOP IF public.canonical_pricing_text(s->field,CASE field WHEN 'note' THEN 1000 WHEN 'collectionBasis' THEN 1000 WHEN 'serviceKey' THEN 100 WHEN 'jurisdiction' THEN 200 ELSE 300 END,TRUE) IS NOT TRUE THEN RAISE EXCEPTION 'Tax source text invalid' USING ERRCODE='22023';END IF;END LOOP;
 IF s->>'kind'<>'validated' AND (s->'ruleId'<>'null'::jsonb OR s->'ruleDigest'<>'null'::jsonb) THEN RAISE EXCEPTION 'Owner declaration cannot claim validated rule' USING ERRCODE='22023';END IF;
 IF s->>'kind'='unknown' THEN IF g->>'treatment'<>'unknown' OR g->'ratePercent'<>'null'::jsonb THEN RAISE EXCEPTION 'Unknown treatment has rate' USING ERRCODE='22023';END IF;RETURN FALSE;END IF;
 IF g->>'treatment'='unknown' OR s->'acknowledged'<>'true'::jsonb OR btrim(s->>'note')='' OR btrim(s->>'reference')='' OR btrim(s->>'jurisdiction')='' OR btrim(s->>'location')='' OR btrim(s->>'collectionBasis')='' OR s->>'serviceKey' IS DISTINCT FROM (CASE WHEN s->>'kind'='validated' AND context_value->'simulated'='true'::jsonb AND context_value?'taxServiceKey' THEN context_value->>'taxServiceKey' ELSE context_value->>'serviceKey' END) OR s->>'effectiveOn' IS NULL OR transaction_day IS NULL OR transaction_day<s->>'effectiveOn' OR transaction_day>s->>'endsOn' THEN RETURN FALSE;END IF;
 IF s->>'kind'='validated' THEN
  SELECT v INTO r FROM jsonb_array_elements(COALESCE(context_value->'validatedRules','[]'::jsonb)) v WHERE v->>'id'=s->>'ruleId' AND v->>'digest'=s->>'ruleDigest' LIMIT 1;
  IF r IS NULL OR r->'simulated' IS DISTINCT FROM context_value->'simulated' OR r->>'jurisdiction' IS DISTINCT FROM s->>'jurisdiction' OR r->>'serviceKey' IS DISTINCT FROM s->>'serviceKey' OR r->>'treatment' IS DISTINCT FROM g->>'treatment' OR r->>'ratePercent' IS DISTINCT FROM g->>'ratePercent' OR r->>'behavior' IS DISTINCT FROM g->>'behavior' OR transaction_day<r->>'effectiveOn' OR transaction_day>r->>'endsOn' THEN RAISE EXCEPTION 'Validated tax source changed' USING ERRCODE='40001';END IF;
 END IF;RETURN TRUE;
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_calculate(v JSONB,currency_value TEXT,context_value JSONB) RETURNS JSONB LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE rows_value JSONB:='[]';groups_value JSONB:='[]';adjustments_value JSONB:='[]';tax_map JSONB:='{}';unknowns JSONB:='[]';ids TEXT[]:='{}';group_ids TEXT[]:='{}';adjustment_ids TEXT[]:='{}';discounted TEXT[]:='{}';l JSONB;g JSONB;a JSONB;f JSONB;r JSONB;part JSONB;eligible JSONB;parts JSONB;allocations JSONB;n NUMERIC;basis NUMERIC;tax_value NUMERIC;net_value NUMERIC;payable NUMERIC;net_sum NUMERIC:=0;tax_sum NUMERIC:=0;total_sum NUMERIC:=0;idx INT;phase INT:=0;next_phase INT;has_order BOOLEAN:=FALSE;incomplete BOOLEAN:=FALSE;complete BOOLEAN;decrease BOOLEAN;behavior_count INT;line_id TEXT;tax_authority TEXT;
BEGIN
 IF v ? 'version' THEN
  IF v->>'version' IS DISTINCT FROM 'estimate-commercial-terms-v2' OR public.canonical_field_evidence_object_keys_exact(v,ARRAY['version','jobApplicability','transactionDate','adjustments','fees','taxGroups','payments']) IS NOT TRUE OR public.canonical_pricing_day(context_value->'asOfDate') IS NOT TRUE THEN RAISE EXCEPTION 'Commercial version invalid' USING ERRCODE='22023';END IF;
  PERFORM public.canonical_commercial_tax_applicability(v->'jobApplicability',NULL);
  RETURN public.canonical_commercial_calculate(v-'version'-'jobApplicability',currency_value,context_value||jsonb_build_object('commercialVersion','estimate-commercial-terms-v2','jobApplicability',v->'jobApplicability'))||jsonb_build_object('calculationVersion','estimate-commercial-terms-v2');
 END IF;
 IF currency_value IS NULL OR currency_value NOT IN ('USD','CAD','EUR') OR public.canonical_field_evidence_object_keys_exact(v,ARRAY['transactionDate','adjustments','fees','taxGroups','payments']) IS NOT TRUE OR v->'transactionDate'<>'null'::jsonb AND public.canonical_pricing_day(v->'transactionDate') IS NOT TRUE OR jsonb_typeof(v->'adjustments') IS DISTINCT FROM 'array' OR jsonb_array_length(v->'adjustments')>12 OR jsonb_typeof(v->'fees') IS DISTINCT FROM 'array' OR jsonb_typeof(v->'taxGroups') IS DISTINCT FROM 'array' OR jsonb_array_length(v->'taxGroups')>12 OR jsonb_typeof(context_value#>'{pricing,lines}') IS DISTINCT FROM 'array' OR jsonb_array_length(context_value#>'{pricing,lines}')=0 THEN RAISE EXCEPTION 'Commercial inputs invalid' USING ERRCODE='22023';END IF;
 FOR l IN SELECT * FROM jsonb_array_elements(context_value#>'{pricing,lines}') LOOP
  IF l->>'includedIn' IS NOT NULL THEN CONTINUE;END IF;IF l->>'lineId'=ANY(ids) THEN RAISE EXCEPTION 'Duplicate charge identity' USING ERRCODE='22023';END IF;ids:=array_append(ids,l->>'lineId');n:=public.canonical_pricing_money(l->'amount');incomplete:=incomplete OR n IS NULL;rows_value:=rows_value||jsonb_build_array(jsonb_build_object('lineId',l->>'lineId','label',l->>'label','kind','charge','original',n,'value',n));
 END LOOP;
 IF jsonb_array_length(rows_value)+jsonb_array_length(v->'fees')>12 THEN RAISE EXCEPTION 'Commercial line limit' USING ERRCODE='22023';END IF;
 FOR g IN SELECT * FROM jsonb_array_elements(v->'taxGroups') LOOP
  IF public.canonical_field_evidence_object_keys_exact(g,ARRAY['groupId','label','lineIds','behavior','treatment','ratePercent','source']) IS NOT TRUE OR public.canonical_pricing_text(g->'groupId',80) IS NOT TRUE OR g->>'groupId'=ANY(group_ids) OR public.canonical_pricing_text(g->'label',160) IS NOT TRUE OR jsonb_typeof(g->'lineIds') IS DISTINCT FROM 'array' OR jsonb_array_length(g->'lineIds') NOT BETWEEN 1 AND 12 OR g->>'behavior' IS NULL OR g->>'behavior' NOT IN ('exclusive','inclusive') OR g->>'treatment' IS NULL OR g->>'treatment' NOT IN ('unknown','taxable','zero_rate','exempt') THEN RAISE EXCEPTION 'Tax group invalid' USING ERRCODE='22023';END IF;
  group_ids:=array_append(group_ids,g->>'groupId');FOR l IN SELECT * FROM jsonb_array_elements(g->'lineIds') LOOP IF public.canonical_pricing_text(l,80) IS NOT TRUE OR tax_map ? (l#>>'{}') THEN RAISE EXCEPTION 'Tax groups overlap' USING ERRCODE='22023';END IF;tax_map:=tax_map||jsonb_build_object(l#>>'{}',g);END LOOP;
  IF g->>'treatment'='unknown' THEN IF g->'ratePercent'<>'null'::jsonb THEN RAISE EXCEPTION 'Unknown rate invalid' USING ERRCODE='22023';END IF;ELSE n:=public.canonical_commercial_percent(g->'ratePercent');IF g->>'treatment' IN ('zero_rate','exempt') AND n<>0 THEN RAISE EXCEPTION 'Zero treatment invalid' USING ERRCODE='22023';END IF;END IF;
 END LOOP;
 FOR a IN SELECT * FROM jsonb_array_elements(v->'adjustments') LOOP
  IF public.canonical_field_evidence_object_keys_exact(a,ARRAY['adjustmentId','label','kind','method','amount','percent','lineIds','reason']) IS NOT TRUE OR public.canonical_pricing_text(a->'adjustmentId',80) IS NOT TRUE OR a->>'adjustmentId'=ANY(adjustment_ids) OR public.canonical_pricing_text(a->'label',160) IS NOT TRUE OR public.canonical_pricing_text(a->'reason',1000) IS NOT TRUE OR a->>'kind' IS NULL OR a->>'kind' NOT IN ('line_discount','order_discount','adjustment') OR a->>'method' IS NULL OR a->>'method' NOT IN ('fixed','percent') OR jsonb_typeof(a->'lineIds') IS DISTINCT FROM 'array' OR jsonb_array_length(a->'lineIds')=0 OR (SELECT count(DISTINCT z) FROM jsonb_array_elements(a->'lineIds') z)<>jsonb_array_length(a->'lineIds') THEN RAISE EXCEPTION 'Adjustment invalid' USING ERRCODE='22023';END IF;
  adjustment_ids:=array_append(adjustment_ids,a->>'adjustmentId');next_phase:=CASE a->>'kind' WHEN 'line_discount' THEN 0 WHEN 'order_discount' THEN 1 ELSE 2 END;IF next_phase<phase THEN RAISE EXCEPTION 'Adjustment order invalid' USING ERRCODE='22023';END IF;phase:=next_phase;
  IF a->>'kind'='order_discount' THEN IF has_order THEN RAISE EXCEPTION 'One order discount supported' USING ERRCODE='22023';END IF;has_order:=TRUE;END IF;
  IF a->>'kind'='line_discount' THEN IF jsonb_array_length(a->'lineIds')<>1 OR a#>>'{lineIds,0}'=ANY(discounted) THEN RAISE EXCEPTION 'One line discount per charge' USING ERRCODE='22023';END IF;discounted:=array_append(discounted,a#>>'{lineIds,0}');END IF;
  eligible:='[]';FOR line_id IN SELECT jsonb_array_elements_text(a->'lineIds') LOOP SELECT x INTO r FROM jsonb_array_elements(rows_value) x WHERE x->>'lineId'=line_id;IF r IS NULL THEN RAISE EXCEPTION 'Adjustment charge unavailable' USING ERRCODE='22023';END IF;eligible:=eligible||jsonb_build_array(r);END LOOP;
  SELECT count(DISTINCT COALESCE(tax_map->(x->>'lineId')->>'behavior','unknown')) INTO behavior_count FROM jsonb_array_elements(eligible) x;IF behavior_count>1 THEN RAISE EXCEPTION 'Mixed inclusive adjustment unsupported' USING ERRCODE='22023';END IF;
  SELECT CASE WHEN bool_or(x->'value'='null'::jsonb) THEN NULL ELSE sum((x->>'value')::numeric) END INTO basis FROM jsonb_array_elements(eligible) x;
  IF a->>'method'='fixed' THEN IF a->'percent'<>'null'::jsonb THEN RAISE EXCEPTION 'Adjustment method invalid' USING ERRCODE='22023';END IF;n:=CASE WHEN a->>'kind'='adjustment' THEN public.canonical_commercial_signed(a->'amount') ELSE public.canonical_pricing_money(a->'amount') END;
  ELSE IF a->'amount'<>'null'::jsonb OR a->>'kind'='adjustment' THEN RAISE EXCEPTION 'Signed adjustment requires fixed amount' USING ERRCODE='22023';END IF;n:=round(basis*public.canonical_commercial_percent(a->'percent')/1000000);END IF;
  IF n IS NULL OR basis IS NULL THEN incomplete:=TRUE;adjustments_value:=adjustments_value||jsonb_build_array(jsonb_build_object('adjustmentId',a->>'adjustmentId','label',a->>'label','reason',a->>'reason','amount',NULL,'allocations','[]'::jsonb));CONTINUE;END IF;
  decrease:=a->>'kind'<>'adjustment' OR n<0;n:=abs(n);IF decrease AND n>basis THEN RAISE EXCEPTION 'Adjustment exceeds eligible base' USING ERRCODE='22023';END IF;
  parts:=public.canonical_commercial_allocate(n,eligible);allocations:='[]';FOR part IN SELECT * FROM jsonb_array_elements(parts) LOOP
   SELECT (o-1)::int INTO idx FROM jsonb_array_elements(rows_value) WITH ORDINALITY z(x,o) WHERE x->>'lineId'=part->>'lineId';basis:=(rows_value->idx->>'value')::numeric+CASE WHEN decrease THEN -(part->>'amount')::numeric ELSE (part->>'amount')::numeric END;PERFORM public.canonical_pricing_decimal(basis);rows_value:=jsonb_set(rows_value,ARRAY[idx::text,'value'],to_jsonb(basis));
   allocations:=allocations||jsonb_build_array(jsonb_build_object('lineId',part->>'lineId','amount',CASE WHEN decrease AND (part->>'amount')::numeric<>0 THEN '-' ELSE '' END||public.canonical_pricing_decimal((part->>'amount')::numeric)));
  END LOOP;
  adjustments_value:=adjustments_value||jsonb_build_array(jsonb_build_object('adjustmentId',a->>'adjustmentId','label',a->>'label','reason',a->>'reason','amount',CASE WHEN decrease AND n<>0 THEN '-' ELSE '' END||public.canonical_pricing_decimal(n),'allocations',allocations));
 END LOOP;
 FOR f IN SELECT * FROM jsonb_array_elements(v->'fees') LOOP
  IF public.canonical_field_evidence_object_keys_exact(f,ARRAY['lineId','label','amount','reason']) IS NOT TRUE OR public.canonical_pricing_text(f->'lineId',80) IS NOT TRUE OR f->>'lineId'=ANY(ids) OR public.canonical_pricing_text(f->'label',160) IS NOT TRUE OR public.canonical_pricing_text(f->'reason',1000) IS NOT TRUE THEN RAISE EXCEPTION 'Fee invalid' USING ERRCODE='22023';END IF;
  ids:=array_append(ids,f->>'lineId');n:=public.canonical_pricing_money(f->'amount');incomplete:=incomplete OR n IS NULL;rows_value:=rows_value||jsonb_build_array(jsonb_build_object('lineId',f->>'lineId','label',f->>'label','kind','fee','original',n,'value',n));
 END LOOP;
 FOR line_id IN SELECT jsonb_object_keys(tax_map) LOOP IF NOT line_id=ANY(ids) THEN RAISE EXCEPTION 'Taxed charge unavailable' USING ERRCODE='22023';END IF;END LOOP;
 FOREACH line_id IN ARRAY ids LOOP IF NOT tax_map ? line_id THEN unknowns:=unknowns||to_jsonb(line_id);END IF;END LOOP;
 FOR g IN SELECT * FROM jsonb_array_elements(v->'taxGroups') LOOP
  IF public.canonical_commercial_tax_source(g,context_value,v->>'transactionDate') IS NOT TRUE THEN unknowns:=unknowns||to_jsonb(g->>'groupId');END IF;
  SELECT jsonb_agg(x ORDER BY o),CASE WHEN bool_or(x->'value'='null'::jsonb) THEN NULL ELSE sum((x->>'value')::numeric) END INTO eligible,basis FROM jsonb_array_elements_text(g->'lineIds') WITH ORDINALITY z(id,o) JOIN LATERAL (SELECT x FROM jsonb_array_elements(rows_value) x WHERE x->>'lineId'=z.id) q ON TRUE;
  IF basis IS NULL OR unknowns ? (g->>'groupId') THEN groups_value:=groups_value||jsonb_build_array(jsonb_build_object('groupId',g->>'groupId','label',g->>'label','behavior',g->>'behavior','treatment',g->>'treatment','base',public.canonical_pricing_decimal(basis),'net',NULL,'tax',NULL,'total',NULL,'allocations','[]'::jsonb));CONTINUE;END IF;
  n:=public.canonical_commercial_percent(g->'ratePercent');net_value:=CASE WHEN g->>'behavior'='inclusive' THEN round(basis*1000000/(1000000+n)) ELSE basis END;tax_value:=CASE WHEN g->>'behavior'='inclusive' THEN basis-net_value ELSE round(basis*n/1000000) END;payable:=net_value+tax_value;PERFORM public.canonical_pricing_decimal(payable);
  parts:=public.canonical_commercial_allocate(tax_value,eligible);SELECT jsonb_agg(jsonb_build_object('lineId',x->>'lineId','tax',public.canonical_pricing_decimal((x->>'amount')::numeric)) ORDER BY o) INTO allocations FROM jsonb_array_elements(parts) WITH ORDINALITY z(x,o);
  groups_value:=groups_value||jsonb_build_array(jsonb_build_object('groupId',g->>'groupId','label',g->>'label','behavior',g->>'behavior','treatment',g->>'treatment','base',public.canonical_pricing_decimal(basis),'net',public.canonical_pricing_decimal(net_value),'tax',public.canonical_pricing_decimal(tax_value),'total',public.canonical_pricing_decimal(payable),'allocations',allocations));net_sum:=net_sum+net_value;tax_sum:=tax_sum+tax_value;total_sum:=total_sum+payable;
 END LOOP;
 complete:=NOT incomplete AND jsonb_array_length(unknowns)=0 AND jsonb_array_length(groups_value)>0;PERFORM public.canonical_pricing_decimal(net_sum);PERFORM public.canonical_pricing_decimal(tax_sum);PERFORM public.canonical_pricing_decimal(total_sum);
 SELECT COALESCE(jsonb_agg(jsonb_build_object('lineId',x->>'lineId','label',x->>'label','kind',x->>'kind','originalAmount',public.canonical_pricing_decimal((x->>'original')::numeric),'adjustedAmount',public.canonical_pricing_decimal((x->>'value')::numeric)) ORDER BY o),'[]'::jsonb) INTO rows_value FROM jsonb_array_elements(rows_value) WITH ORDINALITY z(x,o);
 tax_authority:=CASE WHEN NOT complete THEN 'unknown' WHEN NOT EXISTS(SELECT 1 FROM jsonb_array_elements(v->'taxGroups') x WHERE x#>>'{source,kind}'<>'validated') THEN 'validated' WHEN EXISTS(SELECT 1 FROM jsonb_array_elements(v->'taxGroups') x WHERE x#>>'{source,kind}'='owner_recorded') THEN 'owner_recorded' ELSE 'unknown' END;
 RETURN jsonb_build_object('calculationVersion','estimate-commercial-terms-v1','currency',currency_value,'lines',rows_value,'adjustments',adjustments_value,'taxGroups',groups_value,'netBeforeTax',CASE WHEN complete THEN public.canonical_pricing_decimal(net_sum) END,'tax',CASE WHEN complete THEN public.canonical_pricing_decimal(tax_sum) END,'total',CASE WHEN complete THEN public.canonical_pricing_decimal(total_sum) END,'complete',complete,'unresolvedTax',unknowns,'payments',public.canonical_commercial_payments(v->'payments',CASE WHEN complete THEN total_sum END),'taxAuthority',tax_authority);
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_sources(org UUID,actor UUID,role_value TEXT,session_value UUID,estimate UUID,selected BIGINT DEFAULT NULL) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE prior JSONB;base JSONB;policy_row public.canonical_pricing_policy_plans%ROWTYPE;tax_row public.canonical_tax_profiles%ROWTYPE;policy_valid BOOLEAN:=FALSE;rules_value JSONB;rule_pins JSONB;payload JSONB;rules_eligible JSONB;decision_value JSONB;tax_setup JSONB;
BEGIN
 prior:=public.canonical_pricing_policy_sources(org,actor,role_value,session_value,estimate,selected);base:=prior->'baseSources';decision_value:=prior->'decision';
 SELECT * INTO policy_row FROM public.canonical_pricing_policy_plans WHERE organization_id=org AND estimate_id=estimate ORDER BY revision DESC LIMIT 1;
 IF policy_row.action='save' AND policy_row.source_pins=prior->'sourcePins' AND policy_row.pricing_id::text=prior#>>'{pricingPin,id}' AND policy_row.currency=prior->>'currency' THEN BEGIN PERFORM public.canonical_pricing_policy_require(policy_row.inputs,prior);policy_valid:=TRUE;EXCEPTION WHEN serialization_failure THEN policy_valid:=FALSE;END;END IF;
 SELECT * INTO tax_row FROM public.canonical_tax_profiles WHERE organization_id=org ORDER BY revision DESC LIMIT 1;
 rules_value:=public.canonical_commercial_tax_rules();
 SELECT COALESCE(jsonb_agg(jsonb_build_object('id',v->>'id','digest',v->>'digest') ORDER BY v->>'id'),'[]'::jsonb) INTO rule_pins FROM jsonb_array_elements(rules_value) v;
 -- Real rules are not shipped. Only active source-controlled artifacts can match.
 tax_setup:=public.canonical_commercial_tax_read(org,actor,role_value,session_value);
 SELECT COALESCE(jsonb_agg(v ORDER BY v->>'id'),'[]'::jsonb) INTO rules_eligible FROM jsonb_array_elements(rules_value) v WHERE v->>'version'='tax-preparation-v2' AND v->'active'='true'::jsonb AND v->'simulated'='false'::jsonb AND tax_setup->'resultCurrent'='true'::jsonb AND EXISTS(SELECT 1 FROM jsonb_array_elements(COALESCE(tax_setup#>'{result,coverage}','[]'::jsonb)) c WHERE c->>'state'='matched' AND c#>>'{rule,id}'=v->>'id' AND c#>>'{rule,digest}'=v->>'digest');
 payload:=jsonb_build_object('baseSources',base,'sourcePins',prior->'sourcePins','currency',prior->>'currency','asOfDate',base->>'asOfDate','serviceKey',base->>'serviceKey','simulated',FALSE,
  'pricing',prior->'pricing','pricingPin',prior->'pricingPin','pricingCurrent',prior->'pricingPin' IS NOT NULL AND prior->'pricingPin'<>'null'::jsonb,
  'policy',CASE WHEN policy_row.id IS NOT NULL THEN public.canonical_pricing_policy_projection(policy_row) END,'policyPin',CASE WHEN policy_row.id IS NOT NULL THEN jsonb_build_object('id',policy_row.id,'revision',policy_row.revision,'digest',policy_row.digest) END,'policyBasisCurrent',policy_valid,
  'profilePin',base->'profilePin','taxProfilePin',CASE WHEN tax_row.id IS NOT NULL THEN jsonb_build_object('id',tax_row.id,'revision',tax_row.revision,'digest',tax_row.digest) END,
  'rulePins',rule_pins,'validatedRules',rules_eligible,'sourceDigest',public.canonical_completion_digest(base-'asOfDate'-'digest'),
  'decision',decision_value,'decisionBasis',jsonb_build_object('revision',COALESCE((decision_value->>'revision')::bigint,0),'digest',COALESCE(decision_value->>'digest','none')));
 RETURN payload||jsonb_build_object('digest',public.canonical_completion_digest(payload));
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_tax_read(org UUID,actor UUID,role_value TEXT,session_value UUID) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE p public.canonical_tax_profiles%ROWTYPE;r public.canonical_tax_preparation_results%ROWTYPE;profile_version TEXT;input_hash TEXT;rules_hash TEXT;history JSONB;current_value BOOLEAN;
BEGIN
 IF current_setting('transaction_isolation') NOT IN('repeatable read','serializable') OR role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Protected tax setup read required' USING ERRCODE='42501';END IF;
 PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);
 SELECT version_label INTO profile_version FROM public.canonical_business_profiles WHERE organization_id=org AND is_active;
 SELECT * INTO p FROM public.canonical_tax_profiles WHERE organization_id=org ORDER BY revision DESC LIMIT 1;
 SELECT saved.* INTO r FROM public.canonical_tax_preparation_current current_result JOIN public.canonical_tax_preparation_results saved ON saved.organization_id=current_result.organization_id AND saved.id=current_result.result_id WHERE current_result.organization_id=org;
 input_hash:=public.canonical_completion_digest(public.canonical_commercial_tax_inputs(org));rules_hash:=public.canonical_completion_digest(public.canonical_commercial_tax_rules());
 current_value:=r.id IS NOT NULL AND r.disposition='published' AND r.input_digest=input_hash AND r.rules_digest=rules_hash AND r.result->>'asOfDate'=(clock_timestamp() AT TIME ZONE 'UTC')::date::text;
 SELECT COALESCE(jsonb_agg(jsonb_build_object('id',x.id,'revision',x.revision,'digest',x.digest,'inputs',x.inputs,'createdAt',x.created_at) ORDER BY x.revision DESC),'[]'::jsonb) INTO history FROM(SELECT * FROM public.canonical_tax_profiles WHERE organization_id=org ORDER BY revision DESC LIMIT 50)x;
 RETURN jsonb_build_object('version',public.canonical_commercial_tax_inputs(org)->>'version','services',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',v->>'id','label',COALESCE(NULLIF(v->>'name',''),'Unnamed Business Service'))),'[]'::jsonb) FROM jsonb_array_elements(public.canonical_commercial_tax_inputs(org)->'services') v),'expectedProfileVersion',profile_version,'current',CASE WHEN p.id IS NOT NULL THEN jsonb_build_object('id',p.id,'revision',p.revision,'digest',p.digest,'inputs',p.inputs,'createdAt',p.created_at) END,'history',history,'inputDigest',input_hash,'rulesDigest',rules_hash,'resultCurrent',COALESCE(current_value,FALSE),'result',CASE WHEN current_value THEN r.result END,'preparationState',CASE WHEN current_value THEN r.result->>'state' WHEN r.id IS NULL THEN 'pending' ELSE 'changed' END);
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_tax_mutate(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,body_value JSONB) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE p public.canonical_tax_profiles%ROWTYPE;old public.canonical_tax_profiles%ROWTYPE;inserted public.canonical_tax_profiles%ROWTYPE;profile_version TEXT;key_hash TEXT;request_hash TEXT;next_revision BIGINT;
BEGIN
 PERFORM public.canonical_commercial_lock(org,actor,role_value,session_value,NULL,csrf);
 IF key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR octet_length(body_value::text)>32768 OR public.canonical_field_evidence_object_keys_exact(body_value,ARRAY['expectedRevision','expectedDigest','expectedProfileVersion','inputs','reason','confirmed','confirmationVersion']) IS NOT TRUE OR jsonb_typeof(body_value->'expectedRevision') IS DISTINCT FROM 'number' OR (body_value->>'expectedRevision')!~'^(0|[1-9][0-9]{0,4})$' OR (body_value->>'expectedRevision')::bigint>10000 OR public.canonical_pricing_text(body_value->'expectedDigest',64) IS NOT TRUE OR public.canonical_pricing_text(body_value->'expectedProfileVersion',100) IS NOT TRUE OR public.canonical_pricing_text(body_value->'reason',2000) IS NOT TRUE OR body_value->'confirmed' IS DISTINCT FROM 'true'::jsonb OR (body_value->>'confirmationVersion' IS NULL OR body_value->>'confirmationVersion' NOT IN('tax-preparation-v1','tax-preparation-v2')) THEN RAISE EXCEPTION 'Tax setup review invalid' USING ERRCODE='22023';END IF;
 PERFORM public.canonical_commercial_tax_profile_validate(body_value->'inputs');key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(body_value);
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':'||actor::text||':tax-profile:'||key_hash,0));SELECT * INTO old FROM public.canonical_tax_profiles WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;
 IF FOUND THEN IF old.request_digest<>request_hash THEN RAISE EXCEPTION 'Tax setup attempt changed' USING ERRCODE='23505';END IF;PERFORM public.canonical_travel_write_authority(org,actor,role_value,session_value,csrf);RETURN jsonb_build_object('receipt',jsonb_build_object('id',old.id,'revision',old.revision,'digest',old.digest),'replayed',TRUE);END IF;
 IF body_value->>'confirmationVersion' IS DISTINCT FROM 'tax-preparation-v2' THEN RAISE EXCEPTION 'Refresh to review the current version' USING ERRCODE='22023';END IF;
 SELECT * INTO p FROM public.canonical_tax_profiles WHERE organization_id=org ORDER BY revision DESC LIMIT 1;SELECT version_label INTO profile_version FROM public.canonical_business_profiles WHERE organization_id=org AND is_active;
 IF (body_value->>'expectedRevision')::bigint<>COALESCE(p.revision,0) OR body_value->>'expectedDigest' IS DISTINCT FROM COALESCE(p.digest,'none') OR body_value->>'expectedProfileVersion' IS DISTINCT FROM profile_version THEN RAISE EXCEPTION 'Tax setup or profile changed' USING ERRCODE='40001';END IF;
 IF body_value#>>'{inputs,version}' IS DISTINCT FROM 'tax-preparation-v2' THEN RAISE EXCEPTION 'Tax input version invalid' USING ERRCODE='22023';END IF;
 next_revision:=COALESCE(p.revision,0)+1;IF next_revision>10000 THEN RAISE EXCEPTION 'Tax setup history limit' USING ERRCODE='54000';END IF;
 PERFORM public.canonical_travel_write_authority(org,actor,role_value,session_value,csrf);
 INSERT INTO public.canonical_tax_profiles(organization_id,revision,previous_id,inputs,body,actor_user_id,request_key_hash,request_digest,digest) VALUES(org,next_revision,p.id,body_value->'inputs',body_value,actor,key_hash,request_hash,public.canonical_completion_digest(jsonb_build_object('body',body_value,'previous',p.id,'actor',actor))) RETURNING * INTO inserted;
 PERFORM public.canonical_commercial_tax_enqueue(org);PERFORM public.canonical_travel_write_authority(org,actor,role_value,session_value,csrf);
 RETURN jsonb_build_object('receipt',jsonb_build_object('id',inserted.id,'revision',inserted.revision,'digest',inserted.digest),'replayed',FALSE);
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_mutate(org UUID,actor UUID,role_value TEXT,session_value UUID,estimate UUID,csrf TEXT,key_value TEXT,body_value JSONB) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;sources JSONB;current_row public.canonical_commercial_terms%ROWTYPE;old public.canonical_commercial_terms%ROWTYPE;inserted public.canonical_commercial_terms%ROWTYPE;key_hash TEXT;request_hash TEXT;result_value JSONB;authority_value JSONB;actor_label TEXT;next_revision BIGINT;pricing_value UUID;policy_value UUID;
BEGIN
 authority:=public.canonical_commercial_lock(org,actor,role_value,session_value,estimate,csrf);
 IF key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR octet_length(body_value::text)>65536 OR public.canonical_field_evidence_object_keys_exact(body_value,ARRAY['action','expectedRevision','expectedDigest','sourcePins','expectedDecisionRevision','expectedDecisionDigest','inputs','currency','reason','confirmed','confirmationVersion','evidenceDigest']) IS NOT TRUE OR body_value->>'action' IS NULL OR body_value->>'action' NOT IN('save','withdraw') OR body_value->'confirmed' IS DISTINCT FROM 'true'::jsonb OR (body_value->>'confirmationVersion' IS NULL OR body_value->>'confirmationVersion' NOT IN('estimate-commercial-terms-v1','estimate-commercial-terms-v2')) OR public.canonical_pricing_text(body_value->'reason',2000) IS NOT TRUE OR jsonb_typeof(body_value->'expectedRevision') IS DISTINCT FROM 'number' OR (body_value->>'expectedRevision')!~'^(0|[1-9][0-9]{0,4})$' OR (body_value->>'expectedRevision')::bigint>10000 OR jsonb_typeof(body_value->'expectedDecisionRevision') IS DISTINCT FROM 'number' OR (body_value->>'expectedDecisionRevision')!~'^(0|[1-9][0-9]{0,4})$' OR (body_value->>'expectedDecisionRevision')::bigint>10000 OR public.canonical_pricing_text(body_value->'expectedDigest',64) IS NOT TRUE OR public.canonical_pricing_text(body_value->'expectedDecisionDigest',64) IS NOT TRUE OR (body_value->>'evidenceDigest')!~'^[a-f0-9]{64}$' THEN RAISE EXCEPTION 'Commercial confirmation invalid' USING ERRCODE='22023';END IF;
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('estimate',estimate,'body',body_value));
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':'||actor::text||':commercial:'||key_hash,0));SELECT * INTO old FROM public.canonical_commercial_terms WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;
 IF FOUND THEN IF old.request_digest<>request_hash THEN RAISE EXCEPTION 'Commercial attempt changed' USING ERRCODE='23505';END IF;PERFORM public.canonical_travel_write_authority(org,actor,role_value,session_value,csrf);RETURN jsonb_build_object('receipt',public.canonical_commercial_projection(old),'replayed',TRUE);END IF;
 IF body_value->>'confirmationVersion' IS DISTINCT FROM 'estimate-commercial-terms-v2' THEN RAISE EXCEPTION 'Refresh to review the current version' USING ERRCODE='22023';END IF;
 SELECT * INTO current_row FROM public.canonical_commercial_terms WHERE organization_id=org AND estimate_id=estimate ORDER BY revision DESC LIMIT 1;
 sources:=public.canonical_commercial_sources(org,actor,role_value,session_value,estimate,NULL);
 IF (body_value->>'expectedRevision')::bigint<>COALESCE(current_row.revision,0) OR body_value->>'expectedDigest' IS DISTINCT FROM COALESCE(current_row.digest,'none') OR body_value->'sourcePins' IS DISTINCT FROM sources->'sourcePins' OR body_value->>'currency' IS DISTINCT FROM sources->>'currency' OR jsonb_build_object('revision',body_value->'expectedDecisionRevision','digest',body_value->>'expectedDecisionDigest') IS DISTINCT FROM sources->'decisionBasis' THEN RAISE EXCEPTION 'Commercial basis changed' USING ERRCODE='40001';END IF;
 IF body_value->>'action'='save' THEN
  IF body_value#>>'{inputs,version}' IS DISTINCT FROM 'estimate-commercial-terms-v2' THEN RAISE EXCEPTION 'Commercial input version invalid' USING ERRCODE='22023';END IF;
  IF body_value->>'evidenceDigest' IS DISTINCT FROM sources->>'digest' OR sources->'pricingCurrent' IS DISTINCT FROM 'true'::jsonb THEN RAISE EXCEPTION 'Commercial source changed' USING ERRCODE='40001';END IF;
  result_value:=public.canonical_commercial_calculate(body_value->'inputs',body_value->>'currency',sources||jsonb_build_object('pricing',sources#>'{pricing,result}'));
  authority_value:=public.canonical_commercial_authority_pin(sources);pricing_value:=(sources#>>'{pricingPin,id}')::uuid;policy_value:=(sources#>>'{policyPin,id}')::uuid;
 ELSE
  IF current_row.id IS NULL OR current_row.action<>'save' OR body_value->'inputs' IS DISTINCT FROM 'null'::jsonb THEN RAISE EXCEPTION 'No commercial terms to withdraw' USING ERRCODE='22023';END IF;authority_value:=current_row.authority_pin;pricing_value:=current_row.pricing_id;policy_value:=current_row.policy_id;
 END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;IF next_revision>10000 THEN RAISE EXCEPTION 'Commercial history limit' USING ERRCODE='54000';END IF;
 PERFORM public.canonical_travel_write_authority(org,actor,role_value,session_value,csrf);SELECT name INTO actor_label FROM public.users WHERE organization_id=org AND id=actor;
 INSERT INTO public.canonical_commercial_terms(organization_id,estimate_id,revision,previous_id,pricing_id,policy_id,action,actor_user_id,membership_id,auth_session_id,actor_name,body,result,evidence,authority_pin,request_key_hash,request_digest,digest)
 VALUES(org,estimate,next_revision,current_row.id,pricing_value,policy_value,body_value->>'action',actor,(authority->>'membershipId')::uuid,session_value,COALESCE(actor_label,'Company Reviewer'),body_value,result_value,CASE WHEN body_value->>'action'='save' THEN sources END,authority_value,key_hash,request_hash,public.canonical_completion_digest(jsonb_build_object('estimate',estimate,'revision',next_revision,'previous',current_row.id,'actor',actor,'body',body_value,'sources',CASE WHEN body_value->>'action'='save' THEN sources END))) RETURNING * INTO inserted;
 RETURN jsonb_build_object('receipt',public.canonical_commercial_projection(inserted),'replayed',FALSE);
END $$;

CREATE OR REPLACE FUNCTION public.canonical_commercial_approve(org UUID,actor UUID,role_value TEXT,session_value UUID,estimate UUID,csrf TEXT,key_value TEXT,body_value JSONB) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;sources JSONB;after_sources JSONB;t public.canonical_commercial_terms%ROWTYPE;old public.canonical_commercial_approvals%ROWTYPE;inserted public.canonical_commercial_approvals%ROWTYPE;key_hash TEXT;request_hash TEXT;projection JSONB;calculated JSONB;comparison JSONB;decision_body JSONB;decision_result JSONB;exception_value JSONB;
BEGIN
 authority:=public.canonical_commercial_lock(org,actor,role_value,session_value,estimate,csrf);
 IF key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR octet_length(body_value::text)>32768 OR public.canonical_field_evidence_object_keys_exact(body_value,ARRAY['termsPin','evidenceDigest','expectedDecisionRevision','expectedDecisionDigest','scopeSummary','reason','confirmed','confirmationVersion','exceptions']) IS NOT TRUE OR public.canonical_field_evidence_object_keys_exact(body_value->'termsPin',ARRAY['id','revision','digest']) IS NOT TRUE OR public.canonical_pricing_text(body_value#>'{termsPin,id}',80) IS NOT TRUE OR jsonb_typeof(body_value#>'{termsPin,revision}') IS DISTINCT FROM 'number' OR (body_value#>>'{termsPin,revision}')!~'^[1-9][0-9]{0,4}$' OR (body_value#>>'{termsPin,digest}')!~'^[a-f0-9]{64}$' OR (body_value->>'evidenceDigest')!~'^[a-f0-9]{64}$' OR jsonb_typeof(body_value->'expectedDecisionRevision') IS DISTINCT FROM 'number' OR (body_value->>'expectedDecisionRevision')!~'^(0|[1-9][0-9]{0,4})$' OR public.canonical_pricing_text(body_value->'expectedDecisionDigest',64) IS NOT TRUE OR public.canonical_pricing_text(body_value->'scopeSummary',4000) IS NOT TRUE OR public.canonical_pricing_text(body_value->'reason',2000) IS NOT TRUE OR body_value->'confirmed' IS DISTINCT FROM 'true'::jsonb OR (body_value->>'confirmationVersion' IS NULL OR body_value->>'confirmationVersion' NOT IN('estimate-commercial-terms-v1','estimate-commercial-terms-v2')) THEN RAISE EXCEPTION 'Commercial approval invalid' USING ERRCODE='22023';END IF;
 exception_value:=body_value->'exceptions';IF public.canonical_field_evidence_object_keys_exact(exception_value,ARRAY['policyReason','policyUnknownAcknowledged','ownerRecordedTaxAcknowledged']) IS NOT TRUE OR public.canonical_pricing_text(exception_value->'policyReason',2000,TRUE) IS NOT TRUE OR jsonb_typeof(exception_value->'policyUnknownAcknowledged') IS DISTINCT FROM 'boolean' OR jsonb_typeof(exception_value->'ownerRecordedTaxAcknowledged') IS DISTINCT FROM 'boolean' THEN RAISE EXCEPTION 'Commercial exceptions invalid' USING ERRCODE='22023';END IF;
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('estimate',estimate,'body',body_value));
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':'||actor::text||':commercial-approve:'||key_hash,0));SELECT * INTO old FROM public.canonical_commercial_approvals WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;
 IF FOUND THEN IF old.request_digest<>request_hash THEN RAISE EXCEPTION 'Commercial approval attempt changed' USING ERRCODE='23505';END IF;PERFORM public.canonical_travel_write_authority(org,actor,role_value,session_value,csrf);RETURN jsonb_build_object('receipt',public.canonical_commercial_binding_projection(old),'replayed',TRUE);END IF;
 IF body_value->>'confirmationVersion' IS DISTINCT FROM 'estimate-commercial-terms-v2' THEN RAISE EXCEPTION 'Refresh to review the current version' USING ERRCODE='22023';END IF;
 SELECT * INTO t FROM public.canonical_commercial_terms WHERE organization_id=org AND estimate_id=estimate ORDER BY revision DESC LIMIT 1;
 IF t.body->>'confirmationVersion' IS DISTINCT FROM body_value->>'confirmationVersion' THEN RAISE EXCEPTION 'Save current terms before approval' USING ERRCODE='40001';END IF;
 IF t.id IS NULL OR t.action<>'save' THEN RAISE EXCEPTION 'Current commercial terms required' USING ERRCODE='40001';END IF;
 projection:=public.canonical_commercial_projection(t);sources:=public.canonical_commercial_sources(org,actor,role_value,session_value,estimate,NULL);
 IF body_value->'termsPin' IS DISTINCT FROM public.canonical_commercial_pin(projection) OR body_value->>'evidenceDigest' IS DISTINCT FROM sources->>'digest' OR jsonb_build_object('revision',body_value->'expectedDecisionRevision','digest',body_value->>'expectedDecisionDigest') IS DISTINCT FROM sources->'decisionBasis' OR public.canonical_commercial_current(projection,sources,NULL)->'current' IS DISTINCT FROM 'true'::jsonb THEN RAISE EXCEPTION 'Commercial approval source changed' USING ERRCODE='40001';END IF;
 calculated:=public.canonical_commercial_calculate(t.body->'inputs',t.body->>'currency',sources||jsonb_build_object('pricing',sources#>'{pricing,result}'));
 IF calculated IS DISTINCT FROM t.result THEN RAISE EXCEPTION 'Commercial totals changed' USING ERRCODE='40001';END IF;IF calculated->'complete' IS DISTINCT FROM 'true'::jsonb THEN RAISE EXCEPTION 'Commercial totals incomplete' USING ERRCODE='22023';END IF;
 comparison:=public.canonical_commercial_policy_comparison(projection,sources);
 IF comparison->>'state'='below' AND btrim(exception_value->>'policyReason')='' OR comparison->>'state'='unavailable' AND exception_value->'policyUnknownAcknowledged'<>'true'::jsonb OR calculated->>'taxAuthority'='owner_recorded' AND exception_value->'ownerRecordedTaxAcknowledged'<>'true'::jsonb THEN RAISE EXCEPTION 'Review commercial policy and tax acknowledgments' USING ERRCODE='22023';END IF;
 decision_body:=jsonb_build_object('action','approve','expectedRevision',body_value->'expectedDecisionRevision','expectedDigest',body_value->>'expectedDecisionDigest','sourcePins',t.body->'sourcePins','scopeSummary',btrim(body_value->>'scopeSummary'),'priceBeforeTax',calculated->>'netBeforeTax','currency',t.body->>'currency','reason',btrim(body_value->>'reason'),'confirmed',TRUE,'confirmationVersion','estimate-quote-preparation-v1');
 decision_result:=public.canonical_estimate_decision_mutate(org,actor,role_value,session_value,estimate,csrf,'commercial:'||key_hash,decision_body);
 IF decision_result->'replayed' IS DISTINCT FROM 'false'::jsonb THEN RAISE EXCEPTION 'Legacy receipt cannot establish new commercial approval' USING ERRCODE='23505';END IF;
 after_sources:=public.canonical_commercial_sources(org,actor,role_value,session_value,estimate,NULL);
 IF public.canonical_commercial_authority_pin(after_sources) IS DISTINCT FROM t.authority_pin OR after_sources#>>'{decision,id}' IS DISTINCT FROM decision_result#>>'{receipt,id}' THEN RAISE EXCEPTION 'Commercial approval basis changed during review' USING ERRCODE='40001';END IF;
 PERFORM public.canonical_travel_write_authority(org,actor,role_value,session_value,csrf);
 INSERT INTO public.canonical_commercial_approvals(organization_id,estimate_id,terms_id,decision_id,actor_user_id,membership_id,auth_session_id,body,policy_comparison,authority_pin,decision_pin,previous_decision_basis,request_key_hash,request_digest,digest)
 VALUES(org,estimate,t.id,(decision_result#>>'{receipt,id}')::uuid,actor,(authority->>'membershipId')::uuid,session_value,body_value,comparison,t.authority_pin,public.canonical_commercial_pin(decision_result->'receipt'),sources->'decisionBasis',key_hash,request_hash,public.canonical_completion_digest(jsonb_build_object('terms',t.id,'decision',decision_result#>>'{receipt,id}','body',body_value,'authority',t.authority_pin))) RETURNING * INTO inserted;
 RETURN jsonb_build_object('receipt',public.canonical_commercial_binding_projection(inserted),'replayed',FALSE);
END $$;
REVOKE ALL ON FUNCTION public.canonical_commercial_tax_rule_validate(jsonb),public.canonical_commercial_tax_applicability(jsonb,jsonb),public.canonical_commercial_tax_rule_insert_guard() FROM PUBLIC;
SELECT set_config('lock_timeout',current_setting('northstar.package_b_lock_timeout'),true),set_config('statement_timeout',current_setting('northstar.package_b_statement_timeout'),true);
