-- Mission 25 Part 10D: tenant-private imported vehicle and equipment utilization and operating-cost observations.
-- Each dimension is evaluated independently against the exact adopted Mission 24 equipment plans.

CREATE FUNCTION public.canonical_imported_asset_metric(planned NUMERIC,actual NUMERIC,unit_value TEXT,label_value TEXT,unavailable_reason TEXT DEFAULT NULL)
RETURNS JSONB LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE variance NUMERIC;pct NUMERIC;code TEXT;message TEXT;
BEGIN
 IF unavailable_reason IS NOT NULL OR planned IS NULL OR actual IS NULL OR planned<=0 THEN
  RETURN jsonb_build_object('status','unavailable','unit',NULL,'planned',NULL,'actual',NULL,'variance',NULL,'variancePercent',NULL,'advisoryCode',NULL,'advisoryMessage',NULL,'unavailableReason',COALESCE(unavailable_reason,label_value||' cannot be compared from the current evidence.'));
 END IF;
 variance:=round(actual-planned,6);pct:=round((variance/planned)*100,2);
 code:=CASE WHEN abs(pct)<=5 THEN 'within_expected_range' WHEN pct>0 THEN 'actual_above_plan' ELSE 'actual_below_plan' END;
 message:=CASE code WHEN 'within_expected_range' THEN label_value||' was within 5% of the adopted equipment plan.' WHEN 'actual_above_plan' THEN label_value||' was higher than the adopted equipment plan.' ELSE label_value||' was lower than the adopted equipment plan.' END;
 RETURN jsonb_build_object('status','compared','unit',unit_value,'planned',planned::text,'actual',actual::text,'variance',variance::text,'variancePercent',pct::text,'advisoryCode',code,'advisoryMessage',message,'unavailableReason',NULL);
END $$;

CREATE FUNCTION public.canonical_imported_asset_metric_valid(v JSONB) RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE planned NUMERIC;actual NUMERIC;variance NUMERIC;pct NUMERIC;
BEGIN
 IF jsonb_typeof(v)<>'object' OR COALESCE(v->>'status','') NOT IN ('compared','unavailable') THEN RETURN FALSE;END IF;
 IF v->>'status'='unavailable' THEN RETURN public.canonical_field_evidence_object_keys_exact(v,ARRAY['status','unit','planned','actual','variance','variancePercent','advisoryCode','advisoryMessage','unavailableReason']) AND v->'unit'='null'::jsonb AND v->'planned'='null'::jsonb AND v->'actual'='null'::jsonb AND v->'variance'='null'::jsonb AND v->'variancePercent'='null'::jsonb AND v->'advisoryCode'='null'::jsonb AND v->'advisoryMessage'='null'::jsonb AND public.canonical_learning_text_valid(v->>'unavailableReason',500);END IF;
 IF public.canonical_field_evidence_object_keys_exact(v,ARRAY['status','unit','planned','actual','variance','variancePercent','advisoryCode','advisoryMessage','unavailableReason']) IS NOT TRUE OR v->'unavailableReason'<>'null'::jsonb OR COALESCE(v->>'unit','') NOT IN ('machine_hour','USD','CAD','EUR') OR COALESCE(v->>'advisoryCode','') NOT IN ('within_expected_range','actual_above_plan','actual_below_plan') OR public.canonical_learning_text_valid(v->>'advisoryMessage',500) IS NOT TRUE THEN RETURN FALSE;END IF;
 BEGIN planned:=(v->>'planned')::numeric;actual:=(v->>'actual')::numeric;variance:=(v->>'variance')::numeric;pct:=(v->>'variancePercent')::numeric;EXCEPTION WHEN others THEN RETURN FALSE;END;
 RETURN planned>0 AND actual>=0 AND variance=round(actual-planned,6) AND pct=round((variance/planned)*100,2) AND v->>'advisoryCode'=CASE WHEN abs(pct)<=5 THEN 'within_expected_range' WHEN pct>0 THEN 'actual_above_plan' ELSE 'actual_below_plan' END;
END $$;
CREATE FUNCTION public.canonical_imported_asset_metrics_valid(v JSONB) RETURNS BOOLEAN LANGUAGE sql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT public.canonical_field_evidence_object_keys_exact(v,ARRAY['utilization','operatingCost']) AND public.canonical_imported_asset_metric_valid(v->'utilization') AND public.canonical_imported_asset_metric_valid(v->'operatingCost') $$;

CREATE TABLE public.canonical_external_asset_outcome_consents (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
 source_key TEXT NOT NULL CHECK(source_key~'^[a-z0-9][a-z0-9._-]{1,63}$'),purpose TEXT NOT NULL CHECK(purpose='imported_asset_utilization_cost_variance_v1'),
 revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000),previous_id UUID,action TEXT NOT NULL CHECK(action IN ('grant','revoke')),
 source_consent_id UUID NOT NULL,source_consent_revision BIGINT NOT NULL CHECK(source_consent_revision BETWEEN 1 AND 10000),source_consent_digest CHAR(64) NOT NULL CHECK(source_consent_digest~'^[0-9a-f]{64}$'),
 actor_user_id UUID NOT NULL,membership_id UUID NOT NULL,auth_session_id UUID NOT NULL,
 source_scope JSONB NOT NULL CHECK(source_scope='["canonical_estimates","canonical_estimate_revisions","canonical_equipment_plans","canonical_equipment_cost_plans","canonical_external_asset_import_records","canonical_external_asset_reference_matches","canonical_equipment_asset_versions","canonical_equipment_ledgers"]'::jsonb),
 consent_version TEXT NOT NULL CHECK(consent_version='m25-imported-asset-utilization-cost-consent-v1'),reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)),
 request_key_hash CHAR(64) NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'),request_digest CHAR(64) NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),canonical_digest CHAR(64) NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'),created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
 UNIQUE(organization_id,source_key,purpose,revision),UNIQUE(organization_id,actor_user_id,request_key_hash),UNIQUE(organization_id,source_key,id),
 FOREIGN KEY(organization_id,source_key,previous_id) REFERENCES public.canonical_external_asset_outcome_consents(organization_id,source_key,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,source_key,source_consent_id) REFERENCES public.canonical_external_asset_import_consents(organization_id,source_key,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id) ON DELETE RESTRICT,
 CHECK((revision=1 AND previous_id IS NULL) OR (revision>1 AND previous_id IS NOT NULL))
);
CREATE FUNCTION public.canonical_imported_asset_learning_consent_projection(value public.canonical_external_asset_outcome_consents) RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT jsonb_build_object('id',value.id,'sourceKey',value.source_key,'purpose',value.purpose,'revision',value.revision,'previousId',value.previous_id,'action',value.action,'sourceConsent',jsonb_build_object('id',value.source_consent_id,'revision',value.source_consent_revision,'digest',rtrim(value.source_consent_digest)),'sourceScope',value.source_scope,'consentVersion',value.consent_version,'reason',value.reason,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at) $$;

CREATE FUNCTION public.canonical_imported_asset_learning_consent_read(org UUID,actor UUID,role_value TEXT,session_value UUID,source_value TEXT) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_consent public.canonical_external_asset_import_consents%ROWTYPE;current_row public.canonical_external_asset_outcome_consents%ROWTYPE;history JSONB;total BIGINT;active_value BOOLEAN;
BEGIN
 IF role_value IS NULL OR role_value NOT IN ('owner','admin') THEN RAISE EXCEPTION 'Imported vehicle and equipment learning review is restricted' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'External vehicle and equipment source invalid' USING ERRCODE='22023';END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;
 SELECT * INTO current_row FROM public.canonical_external_asset_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_asset_utilization_cost_variance_v1' ORDER BY revision DESC LIMIT 1;
 active_value:=source_consent.id IS NOT NULL AND source_consent.action='grant' AND current_row.id IS NOT NULL AND current_row.action='grant' AND current_row.source_consent_id=source_consent.id AND rtrim(current_row.source_consent_digest)=rtrim(source_consent.canonical_digest);
 SELECT count(*) INTO total FROM public.canonical_external_asset_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_asset_utilization_cost_variance_v1';
 SELECT COALESCE(jsonb_agg(public.canonical_imported_asset_learning_consent_projection(item) ORDER BY revision DESC),'[]'::jsonb) INTO history FROM(SELECT * FROM public.canonical_external_asset_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_asset_utilization_cost_variance_v1' ORDER BY revision DESC LIMIT 20)item;
 RETURN jsonb_build_object('sourceKey',source_value,'active',active_value,'current',CASE WHEN current_row.id IS NULL THEN NULL ELSE public.canonical_imported_asset_learning_consent_projection(current_row) END,'history',history,'total',total,'truncated',total>20,'blockedReason',CASE WHEN active_value THEN NULL WHEN source_consent.id IS NULL OR source_consent.action<>'grant' THEN 'External vehicle and equipment source consent is not active.' WHEN current_row.id IS NOT NULL AND current_row.action='grant' THEN 'Vehicle and equipment learning consent must be renewed for the current source consent.' ELSE 'Vehicle and equipment learning consent is not active.' END);
END $$;

CREATE FUNCTION public.canonical_imported_asset_learning_consent_mutate(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,body JSONB) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;source_consent public.canonical_external_asset_import_consents%ROWTYPE;current_row public.canonical_external_asset_outcome_consents%ROWTYPE;replay public.canonical_external_asset_outcome_consents%ROWTYPE;inserted public.canonical_external_asset_outcome_consents%ROWTYPE;key_hash TEXT;request_hash TEXT;digest_value TEXT;next_revision BIGINT;currently_active BOOLEAN;scope_value JSONB:='["canonical_estimates","canonical_estimate_revisions","canonical_equipment_plans","canonical_equipment_cost_plans","canonical_external_asset_import_records","canonical_external_asset_reference_matches","canonical_equipment_asset_versions","canonical_equipment_ledgers"]'::jsonb;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;
 IF role_value IS NULL OR role_value NOT IN ('owner','admin') THEN RAISE EXCEPTION 'Imported vehicle and equipment learning review is restricted' USING ERRCODE='42501';END IF;
 PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Current subscription authority unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR octet_length(body::text)>8192 OR public.canonical_field_evidence_object_keys_exact(body,ARRAY['action','expectedRevision','expectedDigest','reason','confirmed','confirmationVersion']) IS NOT TRUE OR body->>'action' NOT IN ('grant','revoke') OR jsonb_typeof(body->'expectedRevision') IS DISTINCT FROM 'number' OR (body->>'expectedRevision')!~'^(0|[1-9][0-9]{0,3}|10000)$' OR jsonb_typeof(body->'expectedDigest') IS DISTINCT FROM 'string' OR body->>'expectedDigest'!~'^(none|[0-9a-f]{64})$' OR (((body->>'expectedRevision')::bigint=0)<>(body->>'expectedDigest'='none')) OR body->'confirmed' IS DISTINCT FROM 'true'::jsonb OR body->>'confirmationVersion' IS DISTINCT FROM 'm25-imported-asset-utilization-cost-consent-v1' OR jsonb_typeof(body->'reason') IS DISTINCT FROM 'string' OR public.canonical_learning_text_valid(body->>'reason',2000) IS NOT TRUE THEN RAISE EXCEPTION 'Imported vehicle and equipment learning consent invalid' USING ERRCODE='22023';END IF;
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'body',body));PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':imported-asset-learning-consent:'||source_value,0));
 SELECT * INTO replay FROM public.canonical_external_asset_outcome_consents WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Imported vehicle and equipment learning consent key conflict' USING ERRCODE='23505';END IF;RETURN jsonb_build_object('consent',public.canonical_imported_asset_learning_consent_projection(replay),'replayed',TRUE);END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1 FOR SHARE;IF source_consent.id IS NULL THEN RAISE EXCEPTION 'External vehicle and equipment source consent unavailable' USING ERRCODE='40001';END IF;
 SELECT * INTO current_row FROM public.canonical_external_asset_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_asset_utilization_cost_variance_v1' ORDER BY revision DESC LIMIT 1 FOR UPDATE;
 IF (body->>'expectedRevision')::bigint<>COALESCE(current_row.revision,0) OR body->>'expectedDigest' IS DISTINCT FROM COALESCE(rtrim(current_row.canonical_digest),'none') THEN RAISE EXCEPTION 'Imported vehicle and equipment learning consent changed' USING ERRCODE='40001';END IF;
 currently_active:=current_row.id IS NOT NULL AND current_row.action='grant' AND source_consent.action='grant' AND current_row.source_consent_id=source_consent.id AND rtrim(current_row.source_consent_digest)=rtrim(source_consent.canonical_digest);
 IF body->>'action'='grant' AND source_consent.action<>'grant' THEN RAISE EXCEPTION 'External vehicle and equipment source consent inactive' USING ERRCODE='40001';END IF;IF body->>'action'='grant' AND currently_active THEN RAISE EXCEPTION 'Vehicle and equipment learning consent is already active' USING ERRCODE='22023';END IF;IF body->>'action'='revoke' AND(current_row.id IS NULL OR current_row.action<>'grant') THEN RAISE EXCEPTION 'No vehicle and equipment learning consent' USING ERRCODE='22023';END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'purpose','imported_asset_utilization_cost_variance_v1','revision',next_revision,'previousId',current_row.id,'action',body->>'action','sourceConsentId',source_consent.id,'sourceConsentRevision',source_consent.revision,'sourceConsentDigest',rtrim(source_consent.canonical_digest),'actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'authSessionId',session_value,'sourceScope',scope_value,'consentVersion','m25-imported-asset-utilization-cost-consent-v1','reason',body->>'reason','requestDigest',request_hash));
 INSERT INTO public.canonical_external_asset_outcome_consents(organization_id,source_key,purpose,revision,previous_id,action,source_consent_id,source_consent_revision,source_consent_digest,actor_user_id,membership_id,auth_session_id,source_scope,consent_version,reason,request_key_hash,request_digest,canonical_digest) VALUES(org,source_value,'imported_asset_utilization_cost_variance_v1',next_revision,current_row.id,body->>'action',source_consent.id,source_consent.revision,rtrim(source_consent.canonical_digest),actor,(authority->>'membershipId')::uuid,session_value,scope_value,'m25-imported-asset-utilization-cost-consent-v1',body->>'reason',key_hash,request_hash,digest_value) RETURNING * INTO inserted;
 RETURN jsonb_build_object('consent',public.canonical_imported_asset_learning_consent_projection(inserted),'replayed',FALSE);
END $$;
CREATE FUNCTION public.canonical_imported_asset_planned_operating_cost(inputs_value JSONB) RETURNS JSONB LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE line_value JSONB;entry JSONB;key_value TEXT;hours NUMERIC;rate_cents NUMERIC;sum_fraction NUMERIC[];line_cents NUMERIC;total_cents NUMERIC:=0;complete_value BOOLEAN:=TRUE;
BEGIN
 FOR line_value IN SELECT value FROM jsonb_array_elements(inputs_value->'lines') LOOP
  IF line_value->>'method'='not_applicable' THEN CONTINUE;END IF;
  IF line_value->'plannedHours' IS NULL OR line_value->'plannedHours'='null'::jsonb THEN complete_value:=FALSE;CONTINUE;END IF;
  hours:=public.canonical_equipment_cost_quantity(line_value->'plannedHours')*1000000;sum_fraction:=ARRAY[0::numeric,1::numeric];
  FOREACH key_value IN ARRAY CASE WHEN line_value#>>'{operating,mode}'='all_in' THEN ARRAY['allIn'] ELSE ARRAY['fuelEnergy','consumables','maintenance'] END LOOP
   entry:=line_value->'operating'->key_value;
   IF entry->>'status'='unknown' THEN complete_value:=FALSE;
   ELSIF entry->>'status'='known' THEN rate_cents:=public.canonical_equipment_cost_equipment_cents(entry->'rate');IF rate_cents IS NULL THEN complete_value:=FALSE;ELSE sum_fraction:=public.canonical_equipment_cost_add(sum_fraction,rate_cents,hours,1000000);END IF;END IF;
  END LOOP;
  line_cents:=div(sum_fraction[1]*2+sum_fraction[2],sum_fraction[2]*2);total_cents:=total_cents+line_cents;
 END LOOP;
 RETURN jsonb_build_object('complete',complete_value,'cents',total_cents::text);
END $$;

CREATE TABLE public.canonical_external_asset_outcome_observations (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,source_key TEXT NOT NULL CHECK(source_key~'^[a-z0-9][a-z0-9._-]{1,63}$'),estimate_id UUID NOT NULL,
 external_job_reference TEXT NOT NULL CHECK(char_length(external_job_reference) BETWEEN 1 AND 128 AND external_job_reference~'^[!-~]+$'),revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000),previous_id UUID,
 consent_id UUID NOT NULL,consent_revision BIGINT NOT NULL CHECK(consent_revision BETWEEN 1 AND 10000),consent_digest CHAR(64) NOT NULL CHECK(consent_digest~'^[0-9a-f]{64}$'),
 source_manifest JSONB NOT NULL CHECK(jsonb_typeof(source_manifest)='object' AND octet_length(source_manifest::text)<=1048576),source_digest CHAR(64) NOT NULL CHECK(source_digest~'^[0-9a-f]{64}$'),metrics JSONB NOT NULL CHECK(jsonb_typeof(metrics)='object'),
 scope_note TEXT NOT NULL CHECK(public.canonical_learning_text_valid(scope_note,1000)),adoption_boundary TEXT NOT NULL CHECK(public.canonical_learning_text_valid(adoption_boundary,1000)),
 actor_user_id UUID NOT NULL,membership_id UUID NOT NULL,auth_session_id UUID NOT NULL,reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)),confirmed BOOLEAN NOT NULL CHECK(confirmed),
 confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-imported-asset-utilization-cost-observation-v1'),calculation_version TEXT NOT NULL CHECK(calculation_version='m25-imported-asset-utilization-cost-v1'),
 request_key_hash CHAR(64) NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'),request_digest CHAR(64) NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),canonical_digest CHAR(64) NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'),created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
 UNIQUE(organization_id,source_key,estimate_id,external_job_reference,revision),UNIQUE(organization_id,source_key,estimate_id,external_job_reference,source_digest,consent_id),UNIQUE(organization_id,actor_user_id,request_key_hash),UNIQUE(organization_id,source_key,id),
 FOREIGN KEY(organization_id,estimate_id) REFERENCES public.canonical_estimates(organization_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,source_key,previous_id) REFERENCES public.canonical_external_asset_outcome_observations(organization_id,source_key,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,source_key,consent_id) REFERENCES public.canonical_external_asset_outcome_consents(organization_id,source_key,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id) ON DELETE RESTRICT,
 CHECK((revision=1 AND previous_id IS NULL) OR (revision>1 AND previous_id IS NOT NULL)),
 CHECK(public.canonical_field_evidence_object_keys_exact(source_manifest,ARRAY['estimate','estimateRevision','equipmentPlan','equipmentCostPlan','sourceConsent','jobMatch','assetMatches','planAssets','importedRecords'])),
 CHECK(rtrim(source_digest)=public.canonical_completion_digest(source_manifest)),CHECK(public.canonical_imported_asset_metrics_valid(metrics))
);
CREATE TRIGGER canonical_external_asset_outcome_consents_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_external_asset_outcome_consents FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_learning_immutable();
CREATE TRIGGER canonical_external_asset_outcomes_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_external_asset_outcome_observations FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_learning_immutable();

CREATE FUNCTION public.canonical_imported_asset_learning_basis(org UUID,source_value TEXT,estimate UUID,job_reference_value TEXT) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE estimate_row public.canonical_estimates%ROWTYPE;revision_row public.canonical_estimate_revisions%ROWTYPE;cost_row public.canonical_equipment_cost_plans%ROWTYPE;plan_row public.canonical_equipment_plans%ROWTYPE;source_consent public.canonical_external_asset_import_consents%ROWTYPE;job_match public.canonical_external_asset_reference_matches%ROWTYPE;job_source JSONB;job_target JSONB;
 imported_records JSONB;asset_matches JSONB:='[]'::jsonb;plan_assets JSONB:='[]'::jsonb;source_manifest JSONB;metrics JSONB;planned_cost JSONB;match_row public.canonical_external_asset_reference_matches%ROWTYPE;source_basis JSONB;target_basis JSONB;record_value JSONB;line_value JSONB;evidence_value JSONB;
 record_total BIGINT;asset_total BIGINT:=0;planned_asset_total BIGINT:=0;utilization_asset_total BIGINT;cost_asset_total BIGINT;invalid_units BIGINT;currency_total BIGINT;invalid_cost_classes BIGINT;overlap_total BIGINT;
 planned_hours NUMERIC:=0;actual_hours NUMERIC;actual_cost NUMERIC;planned_cost_value NUMERIC;actual_currency TEXT;asset_reference_value TEXT;asset_category_value TEXT;asset_target UUID;
 utilization_reason TEXT;cost_reason TEXT;
BEGIN
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR job_reference_value IS NULL OR char_length(job_reference_value) NOT BETWEEN 1 AND 128 OR job_reference_value!~'^[!-~]+$' THEN RAISE EXCEPTION 'Imported vehicle and equipment source identity invalid' USING ERRCODE='22023';END IF;
 SELECT * INTO estimate_row FROM public.canonical_estimates WHERE organization_id=org AND id=estimate;IF NOT FOUND THEN RAISE EXCEPTION 'Estimate unavailable' USING ERRCODE='P0002',CONSTRAINT='imported_asset_estimate_unavailable';END IF;
 SELECT * INTO revision_row FROM public.canonical_estimate_revisions WHERE organization_id=org AND estimate_id=estimate AND equipment_cost_plan_id IS NOT NULL ORDER BY revision DESC LIMIT 1;IF NOT FOUND THEN RAISE EXCEPTION 'Adopted equipment plans required' USING ERRCODE='P0002',CONSTRAINT='imported_asset_plan_unavailable';END IF;
 SELECT * INTO cost_row FROM public.canonical_equipment_cost_plans WHERE organization_id=org AND estimate_id=estimate AND id=revision_row.equipment_cost_plan_id AND action='save';IF NOT FOUND THEN RAISE EXCEPTION 'Adopted equipment cost plan required' USING ERRCODE='P0002',CONSTRAINT='imported_asset_plan_unavailable';END IF;
 SELECT * INTO plan_row FROM public.canonical_equipment_plans WHERE organization_id=org AND estimate_id=estimate AND id=(cost_row.inputs#>>'{equipmentBasis,planId}')::uuid AND revision=(cost_row.inputs#>>'{equipmentBasis,revision}')::bigint AND digest=cost_row.inputs#>>'{equipmentBasis,digest}' AND action='save';IF NOT FOUND THEN RAISE EXCEPTION 'Adopted equipment plan required' USING ERRCODE='P0002',CONSTRAINT='imported_asset_plan_unavailable';END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;IF source_consent.id IS NULL OR source_consent.action<>'grant' THEN RAISE EXCEPTION 'Current source consent required' USING ERRCODE='P0002',CONSTRAINT='imported_asset_source_consent_unavailable';END IF;
 job_source:=public.canonical_external_asset_reference_source_basis(org,source_value,'job',job_reference_value);job_target:=public.canonical_external_asset_reference_target_basis(org,'job',estimate);
 SELECT * INTO job_match FROM public.canonical_external_asset_reference_matches WHERE organization_id=org AND source_key=source_value AND reference_kind='job' AND external_reference=job_reference_value ORDER BY revision DESC LIMIT 1;
 IF job_source IS NULL OR job_target IS NULL OR job_match.id IS NULL OR job_match.action<>'link' OR job_match.target_id<>estimate OR job_match.consent_id<>source_consent.id OR rtrim(job_match.consent_digest)<>rtrim(source_consent.canonical_digest) OR job_match.source_digest<>job_source->>'digest' OR job_match.target_digest<>job_target->>'digest' THEN RAISE EXCEPTION 'Current reviewed job match required' USING ERRCODE='P0002',CONSTRAINT='imported_asset_job_match_unavailable';END IF;

 WITH current_records AS(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_asset_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC),selected AS(SELECT * FROM current_records WHERE state='active' AND job_reference=job_reference_value AND record_type IN('utilization','operating_cost') ORDER BY external_record_id)
 SELECT count(*),COALESCE(jsonb_agg(public.canonical_external_asset_record_projection(r) ORDER BY external_record_id),'[]'::jsonb) INTO record_total,imported_records FROM selected r;
 IF record_total=0 THEN RAISE EXCEPTION 'Current utilization or operating-cost evidence required' USING ERRCODE='P0002',CONSTRAINT='imported_asset_evidence_unavailable';END IF;IF record_total>500 THEN RAISE EXCEPTION 'Vehicle and equipment evidence limit reached' USING ERRCODE='54000';END IF;

 FOR line_value IN SELECT value FROM jsonb_array_elements(plan_row.inputs->'lines') LOOP
  IF line_value->>'assetId' IS NULL THEN RAISE EXCEPTION 'Every adopted equipment line needs an exact reviewed asset' USING ERRCODE='P0002',CONSTRAINT='imported_asset_plan_asset_unavailable';END IF;
  SELECT value INTO evidence_value FROM jsonb_array_elements(plan_row.evidence->'assets') WHERE value->>'id'=line_value->>'assetId';IF evidence_value IS NULL THEN RAISE EXCEPTION 'Every adopted equipment line needs an exact reviewed asset' USING ERRCODE='P0002',CONSTRAINT='imported_asset_plan_asset_unavailable';END IF;
  target_basis:=public.canonical_external_asset_reference_target_basis(org,COALESCE((SELECT category FROM public.tenant_assets WHERE organization_id=org AND id=(line_value->>'assetId')::uuid),''),(line_value->>'assetId')::uuid);IF target_basis IS NULL THEN RAISE EXCEPTION 'A planned asset changed' USING ERRCODE='P0002',CONSTRAINT='imported_asset_plan_asset_unavailable';END IF;
  plan_assets:=plan_assets||jsonb_build_array(jsonb_build_object('lineId',line_value->>'lineId','task',line_value->>'task','assetId',line_value->>'assetId','assetVersion',evidence_value->'version','assetDigest',evidence_value->>'assetDigest','targetBasis',target_basis));planned_asset_total:=planned_asset_total+1;
  SELECT value INTO record_value FROM jsonb_array_elements(cost_row.inputs->'lines') WHERE value->>'lineId'=line_value->>'lineId';IF record_value->'plannedHours' IS NOT NULL AND record_value->'plannedHours'<>'null'::jsonb AND (record_value->>'plannedHours')::numeric>0 THEN planned_hours:=planned_hours+(record_value->>'plannedHours')::numeric;END IF;
 END LOOP;

 FOR asset_category_value,asset_reference_value IN WITH current_records AS(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_asset_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC) SELECT DISTINCT asset_category,asset_reference FROM current_records WHERE state='active' AND job_reference=job_reference_value AND record_type IN('utilization','operating_cost') ORDER BY asset_category,asset_reference LOOP
  source_basis:=public.canonical_external_asset_reference_source_basis(org,source_value,asset_category_value,asset_reference_value);
  SELECT * INTO match_row FROM public.canonical_external_asset_reference_matches WHERE organization_id=org AND source_key=source_value AND reference_kind=asset_category_value AND external_reference=asset_reference_value ORDER BY revision DESC LIMIT 1;
  target_basis:=public.canonical_external_asset_reference_target_basis(org,asset_category_value,match_row.target_id);
  IF source_basis IS NULL OR target_basis IS NULL OR match_row.id IS NULL OR match_row.action<>'link' OR match_row.consent_id<>source_consent.id OR rtrim(match_row.consent_digest)<>rtrim(source_consent.canonical_digest) OR match_row.source_digest<>source_basis->>'digest' OR match_row.target_digest<>target_basis->>'digest' THEN RAISE EXCEPTION 'Current reviewed asset matches required' USING ERRCODE='P0002',CONSTRAINT='imported_asset_asset_match_unavailable';END IF;
  asset_target:=match_row.target_id;IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(plan_assets)value WHERE value->>'assetId'=asset_target::text) THEN RAISE EXCEPTION 'Imported asset is outside the adopted equipment plan' USING ERRCODE='P0002',CONSTRAINT='imported_asset_plan_match_unavailable';END IF;
  asset_matches:=asset_matches||jsonb_build_array(jsonb_build_object('id',match_row.id,'revision',match_row.revision,'digest',rtrim(match_row.canonical_digest),'referenceKind',asset_category_value,'externalReference',asset_reference_value,'targetId',asset_target,'sourceDigest',match_row.source_digest,'targetDigest',match_row.target_digest,'targetBasis',target_basis));asset_total:=asset_total+1;
 END LOOP;

 WITH current_records AS(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_asset_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC),u AS(SELECT * FROM current_records WHERE state='active' AND job_reference=job_reference_value AND record_type='utilization')
 SELECT COALESCE(sum((normalized_evidence#>>'{utilization,value}')::numeric),0),count(*) FILTER(WHERE normalized_evidence#>>'{utilization,unit}'<>'machine_hour'),count(DISTINCT asset_category||':'||asset_reference) INTO actual_hours,invalid_units,utilization_asset_total FROM u;
 WITH current_records AS(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_asset_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC),u AS(SELECT * FROM current_records WHERE state='active' AND job_reference=job_reference_value AND record_type='utilization' AND normalized_evidence#>>'{utilization,unit}'='machine_hour') SELECT count(*) INTO overlap_total FROM u a JOIN u b ON a.id<b.id AND a.asset_category=b.asset_category AND a.asset_reference=b.asset_reference AND tstzrange(a.period_started_at,a.period_ended_at,'[)')&&tstzrange(b.period_started_at,b.period_ended_at,'[)');
 utilization_reason:=CASE WHEN planned_hours<=0 THEN 'The adopted equipment-cost plan has no positive planned equipment hours.' WHEN utilization_asset_total<>planned_asset_total THEN 'Every planned asset needs current utilization evidence for this job.' WHEN invalid_units>0 THEN 'Utilization is unavailable because planned equipment hours cannot be converted to engine hours, mileage, cycles, or job counts.' WHEN overlap_total>0 THEN 'Overlapping utilization periods need source review before comparison.' ELSE NULL END;

 planned_cost:=public.canonical_imported_asset_planned_operating_cost(cost_row.inputs);planned_cost_value:=(planned_cost->>'cents')::numeric/100;
 WITH current_records AS(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_asset_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC),c AS(SELECT * FROM current_records WHERE state='active' AND job_reference=job_reference_value AND record_type='operating_cost')
 SELECT COALESCE(sum((normalized_evidence#>>'{cost,amount}')::numeric),0),count(DISTINCT normalized_evidence#>>'{cost,currency}'),min(normalized_evidence#>>'{cost,currency}'),count(*) FILTER(WHERE normalized_evidence#>>'{cost,costClass}' NOT IN('fuel_energy','consumables','maintenance','repair')),count(DISTINCT asset_category||':'||asset_reference) INTO actual_cost,currency_total,actual_currency,invalid_cost_classes,cost_asset_total FROM c;
 cost_reason:=CASE WHEN planned_cost->'complete'<>'true'::jsonb THEN 'The adopted equipment-cost plan has unknown operating rates.' WHEN planned_cost_value<=0 THEN 'The adopted equipment-cost plan has no positive operating cost.' WHEN cost_asset_total<>planned_asset_total THEN 'Every planned asset needs current operating-cost evidence for this job.' WHEN currency_total<>1 OR actual_currency IS DISTINCT FROM cost_row.currency THEN 'Imported operating costs must use the adopted plan currency; no exchange rate was inferred.' WHEN invalid_cost_classes>0 THEN 'Financing, insurance, rental, and unspecified costs are not treated as job operating cost.' ELSE NULL END;
 metrics:=jsonb_build_object('utilization',public.canonical_imported_asset_metric(planned_hours,actual_hours,'machine_hour','Equipment utilization',utilization_reason),'operatingCost',public.canonical_imported_asset_metric(planned_cost_value,actual_cost,cost_row.currency,'Equipment operating cost',cost_reason));
 source_manifest:=jsonb_build_object('estimate',jsonb_build_object('id',estimate_row.id,'digest',rtrim(estimate_row.snapshot_digest)),'estimateRevision',jsonb_build_object('id',revision_row.id,'revision',revision_row.revision,'digest',revision_row.digest),'equipmentPlan',jsonb_build_object('id',plan_row.id,'revision',plan_row.revision,'digest',plan_row.digest),'equipmentCostPlan',jsonb_build_object('id',cost_row.id,'revision',cost_row.revision,'digest',cost_row.digest,'currency',cost_row.currency),'sourceConsent',jsonb_build_object('id',source_consent.id,'revision',source_consent.revision,'digest',rtrim(source_consent.canonical_digest)),'jobMatch',jsonb_build_object('id',job_match.id,'revision',job_match.revision,'digest',rtrim(job_match.canonical_digest),'sourceDigest',job_match.source_digest,'targetDigest',job_match.target_digest),'assetMatches',asset_matches,'planAssets',plan_assets,'importedRecords',imported_records);
 RETURN jsonb_build_object('sourceManifest',source_manifest,'sourceDigest',public.canonical_completion_digest(source_manifest),'metrics',metrics,'scopeNote','Utilization and operating cost are evaluated separately. Only machine hours and same-currency job operating costs are compared. Engine hours, distance, cycles and job counts remain unavailable. No engine-on time, productivity, exchange rate, maintenance event, downtime, condition or availability was inferred.','adoptionBoundary','Review these observations before changing future equipment assumptions. No estimate, price, schedule, job, vehicle, equipment, allocation, reimbursement, payroll or policy was changed.');
END $$;
CREATE FUNCTION public.canonical_imported_asset_unavailable_metrics(reason_value TEXT) RETURNS JSONB LANGUAGE sql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT jsonb_build_object('utilization',public.canonical_imported_asset_metric(NULL,NULL,NULL,'Equipment utilization',reason_value),'operatingCost',public.canonical_imported_asset_metric(NULL,NULL,NULL,'Equipment operating cost',reason_value)) $$;
CREATE FUNCTION public.canonical_imported_asset_outcome_projection(value public.canonical_external_asset_outcome_observations) RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT jsonb_build_object('id',value.id,'sourceKey',value.source_key,'estimateId',value.estimate_id,'externalJobReference',value.external_job_reference,'revision',value.revision,'previousId',value.previous_id,'consent',jsonb_build_object('id',value.consent_id,'revision',value.consent_revision,'digest',rtrim(value.consent_digest)),'sourceManifest',value.source_manifest,'sourceDigest',rtrim(value.source_digest),'metrics',value.metrics,'scopeNote',value.scope_note,'adoptionBoundary',value.adoption_boundary,'confirmed',value.confirmed,'confirmationVersion',value.confirmation_version,'calculationVersion',value.calculation_version,'reason',value.reason,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at) $$;

CREATE FUNCTION public.canonical_imported_asset_outcome_observe(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,estimate UUID,job_reference TEXT,expected_consent_revision BIGINT,expected_consent_digest TEXT,reason_value TEXT,confirmed_value BOOLEAN,confirmation_version_value TEXT) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;source_consent public.canonical_external_asset_import_consents%ROWTYPE;consent_row public.canonical_external_asset_outcome_consents%ROWTYPE;current_row public.canonical_external_asset_outcome_observations%ROWTYPE;replay public.canonical_external_asset_outcome_observations%ROWTYPE;inserted public.canonical_external_asset_outcome_observations%ROWTYPE;basis JSONB;next_revision BIGINT;key_hash TEXT;request_hash TEXT;digest_value TEXT;active_value BOOLEAN;fresh_value BOOLEAN:=FALSE;projection JSONB;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Imported vehicle and equipment learning review is restricted' USING ERRCODE='42501';END IF;
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR job_reference IS NULL OR char_length(job_reference) NOT BETWEEN 1 AND 128 OR job_reference!~'^[!-~]+$' OR key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR expected_consent_revision IS NULL OR expected_consent_revision NOT BETWEEN 1 AND 10000 OR expected_consent_digest IS NULL OR expected_consent_digest!~'^[0-9a-f]{64}$' OR public.canonical_learning_text_valid(reason_value,2000) IS NOT TRUE OR confirmed_value IS DISTINCT FROM TRUE OR confirmation_version_value IS DISTINCT FROM 'm25-imported-asset-utilization-cost-observation-v1' THEN RAISE EXCEPTION 'Imported vehicle and equipment observation input invalid' USING ERRCODE='22023';END IF;
 PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Current subscription authority unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':imported-asset-outcome:'||source_value||':'||estimate::text||':'||job_reference,0));
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');SELECT * INTO replay FROM public.canonical_external_asset_outcome_observations WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;
 IF FOUND THEN
  request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'estimateId',estimate,'externalJobReference',job_reference,'consentRevision',expected_consent_revision,'consentDigest',expected_consent_digest,'reason',reason_value,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value,'sourceDigest',rtrim(replay.source_digest)));IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Imported vehicle and equipment outcome key conflict' USING ERRCODE='23505';END IF;
  SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;SELECT * INTO consent_row FROM public.canonical_external_asset_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_asset_utilization_cost_variance_v1' ORDER BY revision DESC LIMIT 1;
  active_value:=source_consent.id IS NOT NULL AND source_consent.action='grant' AND consent_row.id IS NOT NULL AND consent_row.action='grant' AND consent_row.source_consent_id=source_consent.id AND rtrim(consent_row.source_consent_digest)=rtrim(source_consent.canonical_digest) AND replay.consent_id=consent_row.id;projection:=public.canonical_imported_asset_outcome_projection(replay);
  IF active_value THEN BEGIN basis:=public.canonical_imported_asset_learning_basis(org,source_value,estimate,job_reference);fresh_value:=rtrim(replay.source_digest)=basis->>'sourceDigest';EXCEPTION WHEN SQLSTATE 'P0002' THEN fresh_value:=FALSE;END;END IF;
  IF NOT active_value THEN projection:=jsonb_build_object('id',replay.id,'estimateId',replay.estimate_id,'revision',replay.revision,'digest',rtrim(replay.canonical_digest),'createdAt',replay.created_at,'hiddenByConsent',TRUE,'fresh',FALSE,'advisoryAvailable',FALSE,'metrics',public.canonical_imported_asset_unavailable_metrics('Current consent is required before using this observation.'));
  ELSIF NOT fresh_value THEN projection:=projection||jsonb_build_object('hiddenByConsent',FALSE,'fresh',FALSE,'advisoryAvailable',FALSE,'metrics',public.canonical_imported_asset_unavailable_metrics('Refresh current evidence before using this observation.'));
  ELSE projection:=projection||jsonb_build_object('hiddenByConsent',FALSE,'fresh',TRUE,'advisoryAvailable',TRUE);END IF;RETURN jsonb_build_object('observation',projection,'replayed',TRUE);
 END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1 FOR SHARE;SELECT * INTO consent_row FROM public.canonical_external_asset_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_asset_utilization_cost_variance_v1' ORDER BY revision DESC LIMIT 1 FOR SHARE;
 IF source_consent.id IS NULL OR source_consent.action<>'grant' OR consent_row.id IS NULL OR consent_row.action<>'grant' OR consent_row.source_consent_id<>source_consent.id OR rtrim(consent_row.source_consent_digest)<>rtrim(source_consent.canonical_digest) OR consent_row.revision<>expected_consent_revision OR rtrim(consent_row.canonical_digest) IS DISTINCT FROM expected_consent_digest THEN RAISE EXCEPTION 'Active imported vehicle and equipment learning consent changed' USING ERRCODE='40001';END IF;
 basis:=public.canonical_imported_asset_learning_basis(org,source_value,estimate,job_reference);request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'estimateId',estimate,'externalJobReference',job_reference,'consentRevision',expected_consent_revision,'consentDigest',expected_consent_digest,'reason',reason_value,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value,'sourceDigest',basis->>'sourceDigest'));
 SELECT * INTO replay FROM public.canonical_external_asset_outcome_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate AND external_job_reference=job_reference AND source_digest=(basis->>'sourceDigest')::char(64) AND consent_id=consent_row.id;IF FOUND THEN RAISE EXCEPTION 'The current imported vehicle and equipment outcome was already observed' USING ERRCODE='22023',CONSTRAINT='imported_asset_outcome_already_current';END IF;
 SELECT * INTO current_row FROM public.canonical_external_asset_outcome_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate AND external_job_reference=job_reference ORDER BY revision DESC LIMIT 1 FOR UPDATE;next_revision:=COALESCE(current_row.revision,0)+1;
 digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'estimateId',estimate,'externalJobReference',job_reference,'revision',next_revision,'previousId',current_row.id,'consentId',consent_row.id,'consentRevision',consent_row.revision,'consentDigest',rtrim(consent_row.canonical_digest),'sourceDigest',basis->>'sourceDigest','metrics',basis->'metrics','actorUserId',actor,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value,'calculationVersion','m25-imported-asset-utilization-cost-v1','requestDigest',request_hash));
 INSERT INTO public.canonical_external_asset_outcome_observations(organization_id,source_key,estimate_id,external_job_reference,revision,previous_id,consent_id,consent_revision,consent_digest,source_manifest,source_digest,metrics,scope_note,adoption_boundary,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,calculation_version,request_key_hash,request_digest,canonical_digest) VALUES(org,source_value,estimate,job_reference,next_revision,current_row.id,consent_row.id,consent_row.revision,rtrim(consent_row.canonical_digest),basis->'sourceManifest',basis->>'sourceDigest',basis->'metrics',basis->>'scopeNote',basis->>'adoptionBoundary',actor,(authority->>'membershipId')::uuid,session_value,reason_value,confirmed_value,confirmation_version_value,'m25-imported-asset-utilization-cost-v1',key_hash,request_hash,digest_value) RETURNING * INTO inserted;
 RETURN jsonb_build_object('observation',public.canonical_imported_asset_outcome_projection(inserted)||jsonb_build_object('fresh',TRUE,'advisoryAvailable',TRUE),'replayed',FALSE);
END $$;

CREATE FUNCTION public.canonical_imported_asset_outcome_read(org UUID,actor UUID,role_value TEXT,session_value UUID,source_value TEXT,estimate UUID) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_consent public.canonical_external_asset_import_consents%ROWTYPE;consent_row public.canonical_external_asset_outcome_consents%ROWTYPE;current_row public.canonical_external_asset_outcome_observations%ROWTYPE;basis JSONB;fresh BOOLEAN;history JSONB;total BIGINT;
BEGIN
 IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Imported vehicle and equipment learning review is restricted' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'External vehicle and equipment source invalid' USING ERRCODE='22023';END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;SELECT * INTO consent_row FROM public.canonical_external_asset_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_asset_utilization_cost_variance_v1' ORDER BY revision DESC LIMIT 1;
 IF source_consent.id IS NULL OR source_consent.action<>'grant' OR consent_row.id IS NULL OR consent_row.action<>'grant' OR consent_row.source_consent_id<>source_consent.id OR rtrim(consent_row.source_consent_digest)<>rtrim(source_consent.canonical_digest) THEN RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',FALSE,'current',NULL,'history','[]'::jsonb,'total',0,'truncated',FALSE,'blockedReason','Current source and vehicle and equipment learning consent are required.');END IF;
 SELECT * INTO current_row FROM public.canonical_external_asset_outcome_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate ORDER BY created_at DESC,id DESC LIMIT 1;IF NOT FOUND THEN RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',TRUE,'consent',public.canonical_imported_asset_learning_consent_projection(consent_row),'current',NULL,'history','[]'::jsonb,'total',0,'truncated',FALSE,'refreshRequired',TRUE);END IF;
 BEGIN basis:=public.canonical_imported_asset_learning_basis(org,source_value,estimate,current_row.external_job_reference);fresh:=rtrim(current_row.source_digest)=basis->>'sourceDigest' AND current_row.consent_id=consent_row.id;EXCEPTION WHEN SQLSTATE 'P0002' THEN basis:=NULL;fresh:=FALSE;END;
 SELECT count(*) INTO total FROM public.canonical_external_asset_outcome_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate;
 SELECT COALESCE(jsonb_agg(public.canonical_imported_asset_outcome_projection(item)||jsonb_build_object('fresh',rtrim(item.source_digest)=COALESCE(basis->>'sourceDigest','') AND item.consent_id=consent_row.id,'advisoryAvailable',rtrim(item.source_digest)=COALESCE(basis->>'sourceDigest','') AND item.consent_id=consent_row.id,'metrics',CASE WHEN rtrim(item.source_digest)=COALESCE(basis->>'sourceDigest','') AND item.consent_id=consent_row.id THEN item.metrics ELSE public.canonical_imported_asset_unavailable_metrics('Refresh current evidence before using this observation.') END) ORDER BY created_at DESC,id DESC),'[]'::jsonb) INTO history FROM(SELECT * FROM public.canonical_external_asset_outcome_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate ORDER BY created_at DESC,id DESC LIMIT 20)item;
 RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',TRUE,'consent',public.canonical_imported_asset_learning_consent_projection(consent_row),'current',public.canonical_imported_asset_outcome_projection(current_row)||jsonb_build_object('fresh',fresh,'advisoryAvailable',fresh,'metrics',CASE WHEN fresh THEN current_row.metrics ELSE public.canonical_imported_asset_unavailable_metrics('Refresh current evidence before using this observation.') END),'history',history,'total',total,'truncated',total>20,'refreshRequired',NOT fresh);
END $$;

REVOKE ALL ON TABLE public.canonical_external_asset_outcome_consents,public.canonical_external_asset_outcome_observations FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_metric(NUMERIC,NUMERIC,TEXT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_metric_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_metrics_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_planned_operating_cost(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_unavailable_metrics(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_learning_consent_projection(public.canonical_external_asset_outcome_consents) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_learning_basis(UUID,TEXT,UUID,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_outcome_projection(public.canonical_external_asset_outcome_observations) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_learning_consent_read(UUID,UUID,TEXT,UUID,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_learning_consent_mutate(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_outcome_observe(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,UUID,TEXT,BIGINT,TEXT,TEXT,BOOLEAN,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_outcome_read(UUID,UUID,TEXT,UUID,TEXT,UUID) FROM PUBLIC;
