-- Mission 25 Part 10E: exact-lineage maintenance, downtime, condition and availability outcomes.
-- Outcomes are advisory evidence only. They never alter assets, jobs, estimates, prices, schedules or policy.

CREATE TABLE public.canonical_external_asset_health_consents (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES public.organizations(id),
 source_key TEXT NOT NULL CHECK(source_key~'^[a-z0-9][a-z0-9._-]{1,63}$'), purpose TEXT NOT NULL CHECK(purpose='imported_asset_health_outcomes_v1'),
 revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000), previous_id UUID, action TEXT NOT NULL CHECK(action IN ('grant','revoke')),
 source_consent_id UUID NOT NULL, source_consent_revision BIGINT NOT NULL CHECK(source_consent_revision BETWEEN 1 AND 10000), source_consent_digest TEXT NOT NULL CHECK(source_consent_digest~'^[0-9a-f]{64}$'),
 actor_user_id UUID NOT NULL, membership_id UUID NOT NULL, auth_session_id UUID NOT NULL,
 source_scope JSONB NOT NULL CHECK(source_scope='["external_asset_maintenance_downtime_v1"]'::jsonb),
 consent_version TEXT NOT NULL CHECK(consent_version='m25-imported-asset-health-consent-v1'), reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)),
 request_key_hash TEXT NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'), request_digest TEXT NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),
 canonical_digest TEXT NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'), created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(organization_id,source_key,revision), UNIQUE(organization_id,actor_user_id,request_key_hash), UNIQUE(organization_id,source_key,id),
 FOREIGN KEY(organization_id,source_key,source_consent_id) REFERENCES public.canonical_external_asset_import_consents(organization_id,source_key,id),
 FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id),
 FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id),
 FOREIGN KEY(organization_id,source_key,previous_id) REFERENCES public.canonical_external_asset_health_consents(organization_id,source_key,id),
 CHECK((revision=1 AND previous_id IS NULL) OR (revision>1 AND previous_id IS NOT NULL))
);

CREATE FUNCTION public.canonical_imported_asset_health_unavailable(reason_value TEXT) RETURNS JSONB LANGUAGE sql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_build_object(
  'maintenance',jsonb_build_object('status','unavailable','recordCount',NULL,'completedCount',NULL,'deferredCount',NULL,'cancelledCount',NULL,'kindCounts',NULL,'periodStartedAt',NULL,'periodEndedAt',NULL,'unavailableReason',reason_value),
  'downtime',jsonb_build_object('status','unavailable','recordCount',NULL,'durationHours',NULL,'scheduledCount',NULL,'unscheduledCount',NULL,'reasonCounts',NULL,'periodStartedAt',NULL,'periodEndedAt',NULL,'unavailableReason',reason_value),
  'condition',jsonb_build_object('status','unavailable','value',NULL,'unavailableReason','No current condition observation was recorded. Maintenance and downtime do not establish condition.'),
  'availability',jsonb_build_object('status','unavailable','percent',NULL,'observationWindow',NULL,'unavailableReason','No complete availability observation window was recorded. Downtime alone does not establish availability.')
 ) $$;

CREATE FUNCTION public.canonical_imported_asset_health_maintenance_valid(value JSONB) RETURNS BOOLEAN LANGUAGE sql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT public.canonical_field_evidence_object_keys_exact(value,ARRAY['status','recordCount','completedCount','deferredCount','cancelledCount','kindCounts','periodStartedAt','periodEndedAt','unavailableReason'])
 AND value->>'status' IN ('recorded','unavailable')
 AND CASE WHEN value->>'status'='recorded' THEN
  jsonb_typeof(value->'recordCount')='number' AND (value->>'recordCount')::numeric BETWEEN 1 AND 500
  AND jsonb_typeof(value->'completedCount')='number' AND jsonb_typeof(value->'deferredCount')='number' AND jsonb_typeof(value->'cancelledCount')='number'
  AND (value->>'completedCount')::numeric+(value->>'deferredCount')::numeric+(value->>'cancelledCount')::numeric=(value->>'recordCount')::numeric
  AND public.canonical_field_evidence_object_keys_exact(value->'kindCounts',ARRAY['preventive','corrective','inspection','scheduledService'])
  AND (value->'kindCounts'->>'preventive')::numeric+(value->'kindCounts'->>'corrective')::numeric+(value->'kindCounts'->>'inspection')::numeric+(value->'kindCounts'->>'scheduledService')::numeric=(value->>'recordCount')::numeric
  AND jsonb_typeof(value->'periodStartedAt')='string' AND jsonb_typeof(value->'periodEndedAt')='string' AND value->'unavailableReason'='null'::jsonb
 ELSE value->'recordCount'='null'::jsonb AND value->'completedCount'='null'::jsonb AND value->'deferredCount'='null'::jsonb AND value->'cancelledCount'='null'::jsonb AND value->'kindCounts'='null'::jsonb AND value->'periodStartedAt'='null'::jsonb AND value->'periodEndedAt'='null'::jsonb AND jsonb_typeof(value->'unavailableReason')='string' END $$;

CREATE FUNCTION public.canonical_imported_asset_health_downtime_valid(value JSONB) RETURNS BOOLEAN LANGUAGE sql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT public.canonical_field_evidence_object_keys_exact(value,ARRAY['status','recordCount','durationHours','scheduledCount','unscheduledCount','reasonCounts','periodStartedAt','periodEndedAt','unavailableReason'])
 AND value->>'status' IN ('recorded','unavailable')
 AND CASE WHEN value->>'status'='recorded' THEN
  jsonb_typeof(value->'recordCount')='number' AND (value->>'recordCount')::numeric BETWEEN 1 AND 500 AND jsonb_typeof(value->'durationHours')='number' AND (value->>'durationHours')::numeric>0
  AND jsonb_typeof(value->'scheduledCount')='number' AND jsonb_typeof(value->'unscheduledCount')='number' AND (value->>'scheduledCount')::numeric+(value->>'unscheduledCount')::numeric=(value->>'recordCount')::numeric
  AND public.canonical_field_evidence_object_keys_exact(value->'reasonCounts',ARRAY['maintenance','fault','damage','inspection','unavailable','other'])
  AND (value->'reasonCounts'->>'maintenance')::numeric+(value->'reasonCounts'->>'fault')::numeric+(value->'reasonCounts'->>'damage')::numeric+(value->'reasonCounts'->>'inspection')::numeric+(value->'reasonCounts'->>'unavailable')::numeric+(value->'reasonCounts'->>'other')::numeric=(value->>'recordCount')::numeric
  AND jsonb_typeof(value->'periodStartedAt')='string' AND jsonb_typeof(value->'periodEndedAt')='string' AND value->'unavailableReason'='null'::jsonb
 ELSE (value->'recordCount'='null'::jsonb OR (jsonb_typeof(value->'recordCount')='number' AND (value->>'recordCount')::numeric BETWEEN 1 AND 500)) AND value->'durationHours'='null'::jsonb AND value->'scheduledCount'='null'::jsonb AND value->'unscheduledCount'='null'::jsonb AND value->'reasonCounts'='null'::jsonb AND value->'periodStartedAt'='null'::jsonb AND value->'periodEndedAt'='null'::jsonb AND jsonb_typeof(value->'unavailableReason')='string' END $$;

CREATE FUNCTION public.canonical_imported_asset_health_outcomes_valid(value JSONB) RETURNS BOOLEAN LANGUAGE sql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT public.canonical_field_evidence_object_keys_exact(value,ARRAY['maintenance','downtime','condition','availability'])
 AND public.canonical_imported_asset_health_maintenance_valid(value->'maintenance')
 AND public.canonical_imported_asset_health_downtime_valid(value->'downtime')
 AND value->'condition'=jsonb_build_object('status','unavailable','value',NULL,'unavailableReason','No current condition observation was recorded. Maintenance and downtime do not establish condition.')
 AND value->'availability'=jsonb_build_object('status','unavailable','percent',NULL,'observationWindow',NULL,'unavailableReason','No complete availability observation window was recorded. Downtime alone does not establish availability.') $$;

CREATE TABLE public.canonical_external_asset_health_observations (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES public.organizations(id), source_key TEXT NOT NULL,
 asset_category TEXT NOT NULL CHECK(asset_category IN ('vehicle','equipment')), external_asset_reference TEXT NOT NULL CHECK(length(external_asset_reference) BETWEEN 1 AND 128 AND external_asset_reference~'^[!-~]+$'),
 target_asset_id UUID NOT NULL, revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000), previous_id UUID,
 consent_id UUID NOT NULL, consent_revision BIGINT NOT NULL CHECK(consent_revision BETWEEN 1 AND 10000), consent_digest TEXT NOT NULL CHECK(consent_digest~'^[0-9a-f]{64}$'),
 source_manifest JSONB NOT NULL CHECK(jsonb_typeof(source_manifest)='object'), source_digest TEXT NOT NULL CHECK(source_digest~'^[0-9a-f]{64}$'),
 outcomes JSONB NOT NULL CHECK(public.canonical_imported_asset_health_outcomes_valid(outcomes)),
 scope_note TEXT NOT NULL CHECK(scope_note='Maintenance and downtime are summarized independently from current imported records. Condition and availability remain unavailable without direct, complete evidence.'),
 adoption_boundary TEXT NOT NULL CHECK(adoption_boundary='No estimate, price, schedule, job, vehicle, equipment, maintenance plan, allocation, reimbursement, payroll or policy was changed.'),
 actor_user_id UUID NOT NULL, membership_id UUID NOT NULL, auth_session_id UUID NOT NULL,
 reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)), confirmed BOOLEAN NOT NULL CHECK(confirmed),
 confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-imported-asset-health-observation-v1'), calculation_version TEXT NOT NULL CHECK(calculation_version='m25-imported-asset-health-v1'),
 request_key_hash TEXT NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'), request_digest TEXT NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'), canonical_digest TEXT NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'),
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(organization_id,source_key,asset_category,external_asset_reference,revision), UNIQUE(organization_id,actor_user_id,request_key_hash), UNIQUE(organization_id,source_key,asset_category,external_asset_reference,id),
 FOREIGN KEY(organization_id,source_key,consent_id) REFERENCES public.canonical_external_asset_health_consents(organization_id,source_key,id),
 FOREIGN KEY(organization_id,target_asset_id) REFERENCES public.tenant_assets(organization_id,id),
 FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id),
 FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id),
 FOREIGN KEY(organization_id,source_key,asset_category,external_asset_reference,previous_id) REFERENCES public.canonical_external_asset_health_observations(organization_id,source_key,asset_category,external_asset_reference,id),
 CHECK((revision=1 AND previous_id IS NULL) OR (revision>1 AND previous_id IS NOT NULL))
);
CREATE INDEX canonical_external_asset_health_observations_current_idx ON public.canonical_external_asset_health_observations(organization_id,source_key,asset_category,external_asset_reference,revision DESC);
CREATE TRIGGER canonical_external_asset_health_consents_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_external_asset_health_consents FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_external_asset_immutable();
CREATE TRIGGER canonical_external_asset_health_observations_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_external_asset_health_observations FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_external_asset_immutable();

CREATE FUNCTION public.canonical_imported_asset_health_consent_projection(value public.canonical_external_asset_health_consents) RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_build_object('id',value.id,'sourceKey',value.source_key,'purpose',value.purpose,'revision',value.revision,'previousId',value.previous_id,'action',value.action,'sourceConsent',jsonb_build_object('id',value.source_consent_id,'revision',value.source_consent_revision,'digest',rtrim(value.source_consent_digest)),'sourceScope',value.source_scope,'consentVersion',value.consent_version,'reason',value.reason,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at) $$;

CREATE FUNCTION public.canonical_imported_asset_health_consent_read(org UUID,actor UUID,role_value TEXT,session_value UUID,source_value TEXT) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE current_row public.canonical_external_asset_health_consents%ROWTYPE; source_consent public.canonical_external_asset_import_consents%ROWTYPE; history JSONB; total BIGINT;active_value BOOLEAN;
BEGIN IF role_value IS NULL OR role_value NOT IN ('owner','admin') THEN RAISE EXCEPTION 'Asset health learning restricted' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'Asset health source invalid' USING ERRCODE='22023';END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;
 SELECT * INTO current_row FROM public.canonical_external_asset_health_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;
 SELECT count(*) INTO total FROM public.canonical_external_asset_health_consents WHERE organization_id=org AND source_key=source_value;
 SELECT COALESCE(jsonb_agg(public.canonical_imported_asset_health_consent_projection(x) ORDER BY revision DESC),'[]'::jsonb) INTO history FROM(SELECT * FROM public.canonical_external_asset_health_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 20)x;
 active_value:=source_consent.id IS NOT NULL AND source_consent.action='grant' AND current_row.id IS NOT NULL AND current_row.action='grant' AND current_row.source_consent_id=source_consent.id AND rtrim(current_row.source_consent_digest)=rtrim(source_consent.canonical_digest);
 RETURN jsonb_build_object('sourceKey',source_value,'sourceConsentActive',source_consent.id IS NOT NULL AND source_consent.action='grant','active',active_value,'current',CASE WHEN current_row.id IS NULL THEN NULL ELSE public.canonical_imported_asset_health_consent_projection(current_row) END,'history',history,'total',total,'truncated',total>20,'blockedReason',CASE WHEN active_value THEN NULL WHEN source_consent.id IS NULL OR source_consent.action<>'grant' THEN 'External vehicle and equipment source consent is not active.' WHEN current_row.id IS NOT NULL AND current_row.action='grant' THEN 'Asset health learning consent must be renewed for the current source consent.' ELSE 'Asset health learning consent is not active.' END,'scopeNote','This separate consent permits current maintenance and downtime evidence to be summarized for a reviewed asset.');END $$;

CREATE FUNCTION public.canonical_imported_asset_health_consent_mutate(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,body JSONB) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;source_consent public.canonical_external_asset_import_consents%ROWTYPE;current_row public.canonical_external_asset_health_consents%ROWTYPE;replay public.canonical_external_asset_health_consents%ROWTYPE;inserted public.canonical_external_asset_health_consents%ROWTYPE;key_hash TEXT;request_hash TEXT;digest_value TEXT;next_revision BIGINT;currently_active BOOLEAN;
BEGIN IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;IF role_value IS NULL OR role_value NOT IN ('owner','admin') THEN RAISE EXCEPTION 'Asset health learning restricted' USING ERRCODE='42501';END IF;
 PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR octet_length(body::text)>8192 OR public.canonical_field_evidence_object_keys_exact(body,ARRAY['action','expectedRevision','expectedDigest','reason','confirmed','confirmationVersion']) IS NOT TRUE OR body->>'action' NOT IN ('grant','revoke') OR jsonb_typeof(body->'expectedRevision') IS DISTINCT FROM 'number' OR (body->>'expectedRevision')!~'^(0|[1-9][0-9]{0,3}|10000)$' OR jsonb_typeof(body->'expectedDigest') IS DISTINCT FROM 'string' OR body->>'expectedDigest'!~'^(none|[0-9a-f]{64})$' OR (((body->>'expectedRevision')::bigint=0)<>(body->>'expectedDigest'='none')) OR body->'confirmed' IS DISTINCT FROM 'true'::jsonb OR body->>'confirmationVersion' IS DISTINCT FROM 'm25-imported-asset-health-consent-v1' OR jsonb_typeof(body->'reason') IS DISTINCT FROM 'string' OR public.canonical_learning_text_valid(body->>'reason',2000) IS NOT TRUE THEN RAISE EXCEPTION 'Asset health learning consent invalid' USING ERRCODE='22023';END IF;
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'body',body));PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':asset-health-consent:'||source_value,0));
 SELECT * INTO replay FROM public.canonical_external_asset_health_consents WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Asset health consent key conflict' USING ERRCODE='23505';END IF;RETURN jsonb_build_object('consent',public.canonical_imported_asset_health_consent_projection(replay),'replayed',TRUE);END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;IF source_consent.id IS NULL THEN RAISE EXCEPTION 'Current source consent required' USING ERRCODE='P0002',CONSTRAINT='asset_health_source_consent_unavailable';END IF;
 SELECT * INTO current_row FROM public.canonical_external_asset_health_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1 FOR UPDATE;IF (body->>'expectedRevision')::bigint<>COALESCE(current_row.revision,0) OR body->>'expectedDigest' IS DISTINCT FROM COALESCE(rtrim(current_row.canonical_digest),'none') THEN RAISE EXCEPTION 'Asset health consent changed' USING ERRCODE='40001';END IF;
 currently_active:=current_row.id IS NOT NULL AND current_row.action='grant' AND source_consent.action='grant' AND current_row.source_consent_id=source_consent.id AND rtrim(current_row.source_consent_digest)=rtrim(source_consent.canonical_digest);
 IF body->>'action'='grant' AND source_consent.action<>'grant' THEN RAISE EXCEPTION 'Current source consent required' USING ERRCODE='P0002',CONSTRAINT='asset_health_source_consent_unavailable';END IF;IF body->>'action'='grant' AND currently_active THEN RAISE EXCEPTION 'Asset health consent already active' USING ERRCODE='22023';END IF;IF body->>'action'='revoke' AND(current_row.id IS NULL OR current_row.action<>'grant') THEN RAISE EXCEPTION 'Asset health consent action invalid' USING ERRCODE='22023';END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'purpose','imported_asset_health_outcomes_v1','revision',next_revision,'previousId',current_row.id,'action',body->>'action','sourceConsentId',source_consent.id,'sourceConsentRevision',source_consent.revision,'sourceConsentDigest',rtrim(source_consent.canonical_digest),'actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'authSessionId',session_value,'sourceScope','["external_asset_maintenance_downtime_v1"]'::jsonb,'consentVersion','m25-imported-asset-health-consent-v1','reason',body->>'reason','requestDigest',request_hash));
 INSERT INTO public.canonical_external_asset_health_consents(organization_id,source_key,purpose,revision,previous_id,action,source_consent_id,source_consent_revision,source_consent_digest,actor_user_id,membership_id,auth_session_id,source_scope,consent_version,reason,request_key_hash,request_digest,canonical_digest) VALUES(org,source_value,'imported_asset_health_outcomes_v1',next_revision,current_row.id,body->>'action',source_consent.id,source_consent.revision,rtrim(source_consent.canonical_digest),actor,(authority->>'membershipId')::uuid,session_value,'["external_asset_maintenance_downtime_v1"]'::jsonb,'m25-imported-asset-health-consent-v1',body->>'reason',key_hash,request_hash,digest_value) RETURNING * INTO inserted;RETURN jsonb_build_object('consent',public.canonical_imported_asset_health_consent_projection(inserted),'replayed',FALSE);END $$;

CREATE FUNCTION public.canonical_imported_asset_health_basis(org UUID,source_value TEXT,category_value TEXT,reference_value TEXT) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_consent public.canonical_external_asset_import_consents%ROWTYPE;match_row public.canonical_external_asset_reference_matches%ROWTYPE;source_basis JSONB;target_basis JSONB;records JSONB;record_total BIGINT;maintenance_total BIGINT;downtime_total BIGINT;overlap_exists BOOLEAN;maintenance JSONB;downtime JSONB;manifest JSONB;digest_value TEXT;
BEGIN IF category_value NOT IN ('vehicle','equipment') OR reference_value IS NULL OR length(reference_value) NOT BETWEEN 1 AND 128 OR reference_value!~'^[!-~]+$' THEN RETURN NULL;END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;IF source_consent.id IS NULL OR source_consent.action<>'grant' THEN RETURN NULL;END IF;
 SELECT * INTO match_row FROM public.canonical_external_asset_reference_matches WHERE organization_id=org AND source_key=source_value AND reference_kind=category_value AND external_reference=reference_value ORDER BY revision DESC LIMIT 1;IF match_row.id IS NULL OR match_row.action<>'link' OR match_row.consent_id<>source_consent.id OR rtrim(match_row.consent_digest)<>rtrim(source_consent.canonical_digest) THEN RETURN NULL;END IF;
 source_basis:=public.canonical_external_asset_reference_source_basis(org,source_value,category_value,reference_value);target_basis:=public.canonical_external_asset_reference_target_basis(org,category_value,match_row.target_id);IF source_basis IS NULL OR target_basis IS NULL OR source_basis->>'digest'<>match_row.source_digest OR target_basis->>'digest'<>match_row.target_digest THEN RETURN NULL;END IF;
 WITH current_records AS(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_asset_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC),selected AS(SELECT * FROM current_records WHERE state='active' AND asset_category=category_value AND asset_reference=reference_value AND record_type IN ('maintenance','downtime') ORDER BY external_record_id LIMIT 501)
 SELECT count(*),count(*)FILTER(WHERE record_type='maintenance'),count(*)FILTER(WHERE record_type='downtime'),COALESCE(jsonb_agg(public.canonical_external_asset_record_projection(s) ORDER BY external_record_id),'[]'::jsonb) INTO record_total,maintenance_total,downtime_total,records FROM selected s;
 IF record_total=0 OR record_total>500 THEN RETURN NULL;END IF;
 WITH current_records AS(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_asset_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC),d AS(SELECT external_record_id,period_started_at,period_ended_at FROM current_records WHERE state='active' AND source_key=source_value AND asset_category=category_value AND asset_reference=reference_value AND record_type='downtime') SELECT EXISTS(SELECT 1 FROM d a JOIN d b ON a.external_record_id<b.external_record_id AND a.period_started_at<b.period_ended_at AND b.period_started_at<a.period_ended_at) INTO overlap_exists;
 IF maintenance_total=0 THEN maintenance:=jsonb_build_object('status','unavailable','recordCount',NULL,'completedCount',NULL,'deferredCount',NULL,'cancelledCount',NULL,'kindCounts',NULL,'periodStartedAt',NULL,'periodEndedAt',NULL,'unavailableReason','No current maintenance record was imported for this exact asset.');ELSE
  WITH current_records AS(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_asset_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC),m AS(SELECT * FROM current_records WHERE state='active' AND source_key=source_value AND asset_category=category_value AND asset_reference=reference_value AND record_type='maintenance')
  SELECT jsonb_build_object('status','recorded','recordCount',count(*),'completedCount',count(*)FILTER(WHERE normalized_evidence->'maintenance'->>'status'='completed'),'deferredCount',count(*)FILTER(WHERE normalized_evidence->'maintenance'->>'status'='deferred'),'cancelledCount',count(*)FILTER(WHERE normalized_evidence->'maintenance'->>'status'='cancelled'),'kindCounts',jsonb_build_object('preventive',count(*)FILTER(WHERE normalized_evidence->'maintenance'->>'kind'='preventive'),'corrective',count(*)FILTER(WHERE normalized_evidence->'maintenance'->>'kind'='corrective'),'inspection',count(*)FILTER(WHERE normalized_evidence->'maintenance'->>'kind'='inspection'),'scheduledService',count(*)FILTER(WHERE normalized_evidence->'maintenance'->>'kind'='scheduled_service')),'periodStartedAt',min(period_started_at),'periodEndedAt',max(period_ended_at),'unavailableReason',NULL) INTO maintenance FROM m;END IF;
 IF downtime_total=0 THEN downtime:=jsonb_build_object('status','unavailable','recordCount',NULL,'durationHours',NULL,'scheduledCount',NULL,'unscheduledCount',NULL,'reasonCounts',NULL,'periodStartedAt',NULL,'periodEndedAt',NULL,'unavailableReason','No current downtime record was imported for this exact asset.');ELSIF overlap_exists THEN downtime:=jsonb_build_object('status','unavailable','recordCount',downtime_total,'durationHours',NULL,'scheduledCount',NULL,'unscheduledCount',NULL,'reasonCounts',NULL,'periodStartedAt',NULL,'periodEndedAt',NULL,'unavailableReason','Overlapping downtime periods need source review before duration can be summarized.');ELSE
  WITH current_records AS(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_asset_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC),d AS(SELECT * FROM current_records WHERE state='active' AND source_key=source_value AND asset_category=category_value AND asset_reference=reference_value AND record_type='downtime')
  SELECT jsonb_build_object('status','recorded','recordCount',count(*),'durationHours',round(sum(extract(epoch FROM(period_ended_at-period_started_at)))/3600,6),'scheduledCount',count(*)FILTER(WHERE (normalized_evidence->'downtime'->>'scheduled')::boolean),'unscheduledCount',count(*)FILTER(WHERE NOT(normalized_evidence->'downtime'->>'scheduled')::boolean),'reasonCounts',jsonb_build_object('maintenance',count(*)FILTER(WHERE normalized_evidence->'downtime'->>'reasonClass'='maintenance'),'fault',count(*)FILTER(WHERE normalized_evidence->'downtime'->>'reasonClass'='fault'),'damage',count(*)FILTER(WHERE normalized_evidence->'downtime'->>'reasonClass'='damage'),'inspection',count(*)FILTER(WHERE normalized_evidence->'downtime'->>'reasonClass'='inspection'),'unavailable',count(*)FILTER(WHERE normalized_evidence->'downtime'->>'reasonClass'='unavailable'),'other',count(*)FILTER(WHERE normalized_evidence->'downtime'->>'reasonClass'='other')),'periodStartedAt',min(period_started_at),'periodEndedAt',max(period_ended_at),'unavailableReason',NULL) INTO downtime FROM d;END IF;
 manifest:=jsonb_build_object('sourceConsent',public.canonical_external_asset_consent_projection(source_consent),'reviewedMatch',jsonb_build_object('id',match_row.id,'revision',match_row.revision,'digest',rtrim(match_row.canonical_digest),'sourceDigest',match_row.source_digest,'targetDigest',match_row.target_digest,'targetId',match_row.target_id),'referenceSourceManifest',source_basis->'manifest','targetBasis',target_basis,'healthRecords',records);
 digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'assetCategory',category_value,'externalAssetReference',reference_value,'sourceManifest',manifest,'calculationVersion','m25-imported-asset-health-v1'));
 RETURN jsonb_build_object('targetAssetId',match_row.target_id,'sourceManifest',manifest,'sourceDigest',digest_value,'outcomes',jsonb_build_object('maintenance',maintenance,'downtime',downtime,'condition',jsonb_build_object('status','unavailable','value',NULL,'unavailableReason','No current condition observation was recorded. Maintenance and downtime do not establish condition.'),'availability',jsonb_build_object('status','unavailable','percent',NULL,'observationWindow',NULL,'unavailableReason','No complete availability observation window was recorded. Downtime alone does not establish availability.')));END $$;

CREATE FUNCTION public.canonical_imported_asset_health_projection(value public.canonical_external_asset_health_observations,current_basis JSONB,current_consent public.canonical_external_asset_health_consents,current_source_consent public.canonical_external_asset_import_consents) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE fresh BOOLEAN;hidden BOOLEAN;result JSONB;
BEGIN hidden:=current_consent.id IS NULL OR current_consent.action<>'grant' OR current_source_consent.id IS NULL OR current_source_consent.action<>'grant' OR current_consent.source_consent_id<>current_source_consent.id OR rtrim(current_consent.source_consent_digest)<>rtrim(current_source_consent.canonical_digest);fresh:=NOT hidden AND current_consent.id=value.consent_id AND rtrim(current_consent.canonical_digest)=rtrim(value.consent_digest) AND current_basis IS NOT NULL AND current_basis->>'sourceDigest'=value.source_digest AND (current_basis->>'targetAssetId')::uuid=value.target_asset_id;
 IF hidden THEN RETURN jsonb_build_object('id',value.id,'sourceKey',value.source_key,'targetAssetId',value.target_asset_id,'revision',value.revision,'fresh',FALSE,'advisoryAvailable',FALSE,'hiddenByConsent',TRUE,'refreshRequired',TRUE,'outcomes',public.canonical_imported_asset_health_unavailable('Asset health advice is hidden because source or learning consent is inactive.'),'scopeNote',value.scope_note,'adoptionBoundary',value.adoption_boundary,'calculationVersion',value.calculation_version,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at);END IF;
 result:=jsonb_build_object('id',value.id,'sourceKey',value.source_key,'assetCategory',value.asset_category,'externalAssetReference',value.external_asset_reference,'targetAssetId',value.target_asset_id,'revision',value.revision,'previousId',value.previous_id,'consent',jsonb_build_object('id',value.consent_id,'revision',value.consent_revision,'digest',rtrim(value.consent_digest)),'sourceManifest',value.source_manifest,'sourceDigest',rtrim(value.source_digest),'outcomes',CASE WHEN fresh THEN value.outcomes ELSE public.canonical_imported_asset_health_unavailable('Current source evidence, reviewed asset match, asset record or consent changed. Refresh before using this advice.') END,'fresh',fresh,'advisoryAvailable',fresh,'hiddenByConsent',FALSE,'refreshRequired',NOT fresh,'scopeNote',value.scope_note,'adoptionBoundary',value.adoption_boundary,'confirmed',value.confirmed,'confirmationVersion',value.confirmation_version,'calculationVersion',value.calculation_version,'reason',value.reason,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at);RETURN result;END $$;

CREATE FUNCTION public.canonical_imported_asset_health_observe(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,category_value TEXT,reference_value TEXT,expected_consent_revision BIGINT,expected_consent_digest TEXT,reason_value TEXT,confirmed_value BOOLEAN,confirmation_version_value TEXT) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;source_consent public.canonical_external_asset_import_consents%ROWTYPE;consent_row public.canonical_external_asset_health_consents%ROWTYPE;current_row public.canonical_external_asset_health_observations%ROWTYPE;replay public.canonical_external_asset_health_observations%ROWTYPE;inserted public.canonical_external_asset_health_observations%ROWTYPE;basis JSONB;key_hash TEXT;request_hash TEXT;digest_value TEXT;next_revision BIGINT;
BEGIN IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;IF role_value IS NULL OR role_value NOT IN ('owner','admin') THEN RAISE EXCEPTION 'Asset health learning restricted' USING ERRCODE='42501';END IF;PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR category_value NOT IN ('vehicle','equipment') OR reference_value IS NULL OR length(reference_value) NOT BETWEEN 1 AND 128 OR reference_value!~'^[!-~]+$' OR key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR expected_consent_revision NOT BETWEEN 1 AND 10000 OR expected_consent_digest!~'^[0-9a-f]{64}$' OR public.canonical_learning_text_valid(reason_value,2000) IS NOT TRUE OR confirmed_value IS DISTINCT FROM TRUE OR confirmation_version_value IS DISTINCT FROM 'm25-imported-asset-health-observation-v1' THEN RAISE EXCEPTION 'Asset health observation invalid' USING ERRCODE='22023';END IF;
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'assetCategory',category_value,'externalAssetReference',reference_value,'expectedConsentRevision',expected_consent_revision,'expectedConsentDigest',expected_consent_digest,'reason',reason_value,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value));PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':asset-health:'||source_value||':'||category_value||':'||reference_value,0));
 SELECT * INTO replay FROM public.canonical_external_asset_health_observations WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Asset health observation key conflict' USING ERRCODE='23505';END IF;SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;SELECT * INTO consent_row FROM public.canonical_external_asset_health_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;basis:=public.canonical_imported_asset_health_basis(org,source_value,replay.asset_category,replay.external_asset_reference);RETURN jsonb_build_object('observation',public.canonical_imported_asset_health_projection(replay,basis,consent_row,source_consent),'replayed',TRUE);END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;SELECT * INTO consent_row FROM public.canonical_external_asset_health_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;IF source_consent.id IS NULL OR source_consent.action<>'grant' OR consent_row.id IS NULL OR consent_row.action<>'grant' THEN RAISE EXCEPTION 'Current asset health consent required' USING ERRCODE='P0002',CONSTRAINT='asset_health_consent_unavailable';END IF;IF consent_row.revision<>expected_consent_revision OR rtrim(consent_row.canonical_digest)<>expected_consent_digest OR consent_row.source_consent_id<>source_consent.id OR rtrim(consent_row.source_consent_digest)<>rtrim(source_consent.canonical_digest) THEN RAISE EXCEPTION 'Asset health consent changed' USING ERRCODE='40001';END IF;
 basis:=public.canonical_imported_asset_health_basis(org,source_value,category_value,reference_value);IF basis IS NULL THEN RAISE EXCEPTION 'Current reviewed asset match and health evidence required' USING ERRCODE='P0002',CONSTRAINT='asset_health_lineage_unavailable';END IF;
 SELECT * INTO current_row FROM public.canonical_external_asset_health_observations WHERE organization_id=org AND source_key=source_value AND asset_category=category_value AND external_asset_reference=reference_value ORDER BY revision DESC LIMIT 1 FOR UPDATE;IF current_row.id IS NOT NULL AND current_row.consent_id=consent_row.id AND current_row.source_digest=basis->>'sourceDigest' THEN RAISE EXCEPTION 'Current asset health outcome already recorded' USING ERRCODE='22023',CONSTRAINT='asset_health_outcome_already_current';END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'assetCategory',category_value,'externalAssetReference',reference_value,'targetAssetId',basis->>'targetAssetId','revision',next_revision,'previousId',current_row.id,'consentId',consent_row.id,'consentRevision',consent_row.revision,'consentDigest',rtrim(consent_row.canonical_digest),'sourceDigest',basis->>'sourceDigest','outcomes',basis->'outcomes','actorUserId',actor,'confirmationVersion',confirmation_version_value,'calculationVersion','m25-imported-asset-health-v1','requestDigest',request_hash));
 INSERT INTO public.canonical_external_asset_health_observations(organization_id,source_key,asset_category,external_asset_reference,target_asset_id,revision,previous_id,consent_id,consent_revision,consent_digest,source_manifest,source_digest,outcomes,scope_note,adoption_boundary,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,calculation_version,request_key_hash,request_digest,canonical_digest) VALUES(org,source_value,category_value,reference_value,(basis->>'targetAssetId')::uuid,next_revision,current_row.id,consent_row.id,consent_row.revision,rtrim(consent_row.canonical_digest),basis->'sourceManifest',basis->>'sourceDigest',basis->'outcomes','Maintenance and downtime are summarized independently from current imported records. Condition and availability remain unavailable without direct, complete evidence.','No estimate, price, schedule, job, vehicle, equipment, maintenance plan, allocation, reimbursement, payroll or policy was changed.',actor,(authority->>'membershipId')::uuid,session_value,reason_value,confirmed_value,confirmation_version_value,'m25-imported-asset-health-v1',key_hash,request_hash,digest_value) RETURNING * INTO inserted;RETURN jsonb_build_object('observation',public.canonical_imported_asset_health_projection(inserted,basis,consent_row,source_consent),'replayed',FALSE);END $$;

CREATE FUNCTION public.canonical_imported_asset_health_read(org UUID,actor UUID,role_value TEXT,session_value UUID,source_value TEXT,category_value TEXT,reference_value TEXT) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_consent public.canonical_external_asset_import_consents%ROWTYPE;consent_row public.canonical_external_asset_health_consents%ROWTYPE;current_row public.canonical_external_asset_health_observations%ROWTYPE;basis JSONB;history JSONB;total BIGINT;active_value BOOLEAN;
BEGIN IF role_value IS NULL OR role_value NOT IN ('owner','admin') THEN RAISE EXCEPTION 'Asset health learning restricted' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR category_value NOT IN ('vehicle','equipment') OR reference_value IS NULL OR length(reference_value) NOT BETWEEN 1 AND 128 OR reference_value!~'^[!-~]+$' THEN RAISE EXCEPTION 'Asset health read invalid' USING ERRCODE='22023';END IF;
 SELECT * INTO source_consent FROM public.canonical_external_asset_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;SELECT * INTO consent_row FROM public.canonical_external_asset_health_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;SELECT * INTO current_row FROM public.canonical_external_asset_health_observations WHERE organization_id=org AND source_key=source_value AND asset_category=category_value AND external_asset_reference=reference_value ORDER BY revision DESC LIMIT 1;basis:=public.canonical_imported_asset_health_basis(org,source_value,category_value,reference_value);
 active_value:=source_consent.id IS NOT NULL AND source_consent.action='grant' AND consent_row.id IS NOT NULL AND consent_row.action='grant' AND consent_row.source_consent_id=source_consent.id AND rtrim(consent_row.source_consent_digest)=rtrim(source_consent.canonical_digest);
 IF NOT active_value THEN RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',FALSE,'current',NULL,'history','[]'::jsonb,'total',0,'truncated',FALSE,'consumptionBoundary','Asset health advice is unavailable until learning consent is granted for the current source consent.');END IF;
 SELECT count(*) INTO total FROM public.canonical_external_asset_health_observations WHERE organization_id=org AND source_key=source_value AND asset_category=category_value AND external_asset_reference=reference_value;
 SELECT COALESCE(jsonb_agg(public.canonical_imported_asset_health_projection(x,basis,consent_row,source_consent) ORDER BY revision DESC),'[]'::jsonb) INTO history FROM(SELECT * FROM public.canonical_external_asset_health_observations WHERE organization_id=org AND source_key=source_value AND asset_category=category_value AND external_asset_reference=reference_value ORDER BY revision DESC LIMIT 20)x;
 RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',TRUE,'current',CASE WHEN current_row.id IS NULL THEN NULL ELSE public.canonical_imported_asset_health_projection(current_row,basis,consent_row,source_consent) END,'history',history,'total',total,'truncated',total>20,'consumptionBoundary','Recorded outcomes are advisory only. Review current evidence before any operational decision.');END $$;

REVOKE ALL ON TABLE public.canonical_external_asset_health_consents,public.canonical_external_asset_health_observations FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_unavailable(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_maintenance_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_downtime_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_outcomes_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_consent_projection(public.canonical_external_asset_health_consents) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_consent_read(UUID,UUID,TEXT,UUID,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_consent_mutate(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_basis(UUID,TEXT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_projection(public.canonical_external_asset_health_observations,JSONB,public.canonical_external_asset_health_consents,public.canonical_external_asset_import_consents) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_observe(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT,BOOLEAN,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_asset_health_read(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT) FROM PUBLIC;
