-- Mission 25 Part 11C: explicit reviewed reconciliation for external material evidence.
-- Links are immutable lineage only and never change jobs, estimates, inventory, purchases, vendors, costs or policy.

CREATE TABLE public.canonical_external_material_reference_matches (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES public.organizations(id),
 source_key TEXT NOT NULL CHECK(source_key~'^[a-z0-9][a-z0-9._-]{1,63}$'), consent_id UUID NOT NULL,
 consent_revision BIGINT NOT NULL CHECK(consent_revision BETWEEN 1 AND 10000), consent_digest TEXT NOT NULL CHECK(consent_digest~'^[0-9a-f]{64}$'),
 reference_kind TEXT NOT NULL CHECK(reference_kind IN ('job','material','vendor','inventory_location')),
 external_reference TEXT NOT NULL CHECK(length(external_reference) BETWEEN 1 AND 128 AND external_reference~'^[!-~]+$'),
 revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000), previous_id UUID,
 action TEXT NOT NULL CHECK(action IN ('link','unlink')), target_reference TEXT,
 source_manifest JSONB NOT NULL CHECK(jsonb_typeof(source_manifest)='array'), source_digest TEXT NOT NULL CHECK(source_digest='unavailable' OR source_digest~'^[0-9a-f]{64}$'),
 target_manifest JSONB NOT NULL CHECK(jsonb_typeof(target_manifest)='array'), target_digest TEXT NOT NULL CHECK(target_digest='unavailable' OR target_digest~'^[0-9a-f]{64}$'),
 actor_user_id UUID NOT NULL, membership_id UUID NOT NULL, auth_session_id UUID NOT NULL,
 reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)), confirmed BOOLEAN NOT NULL CHECK(confirmed),
 confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-external-material-reference-match-v1'),
 request_key_hash TEXT NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'), request_digest TEXT NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),
 canonical_digest TEXT NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'), created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(organization_id,source_key,consent_id,reference_kind,external_reference,revision), UNIQUE(organization_id,actor_user_id,request_key_hash),
 UNIQUE(organization_id,source_key,consent_id,reference_kind,external_reference,id),
 FOREIGN KEY(organization_id,source_key,consent_id) REFERENCES public.canonical_external_material_import_consents(organization_id,source_key,id),
 FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id),
 FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id),
 FOREIGN KEY(organization_id,source_key,consent_id,reference_kind,external_reference,previous_id)
  REFERENCES public.canonical_external_material_reference_matches(organization_id,source_key,consent_id,reference_kind,external_reference,id),
 CHECK((revision=1 AND previous_id IS NULL) OR (revision>1 AND previous_id IS NOT NULL)),
 CHECK((action='link' AND target_reference IS NOT NULL AND length(target_reference) BETWEEN 1 AND 160 AND source_digest<>'unavailable' AND target_digest<>'unavailable')
    OR (action='unlink' AND target_reference IS NULL AND target_digest='unavailable' AND target_manifest='[]'::jsonb))
);
CREATE INDEX canonical_external_material_reference_matches_current_idx ON public.canonical_external_material_reference_matches(organization_id,source_key,consent_id,reference_kind,external_reference,revision DESC);
CREATE TRIGGER canonical_external_material_reference_matches_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_external_material_reference_matches FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_external_material_immutable();

CREATE FUNCTION public.canonical_external_material_reference_source_basis(org UUID,source_value TEXT,kind_value TEXT,reference_value TEXT) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_row public.canonical_external_material_import_consents%ROWTYPE;manifest JSONB;total BIGINT;
BEGIN
 IF kind_value NOT IN ('job','material','vendor','inventory_location') OR reference_value IS NULL THEN RETURN NULL; END IF;
 SELECT * INTO consent_row FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;
 IF consent_row.id IS NULL OR consent_row.action<>'grant' THEN RETURN NULL; END IF;
 WITH current_records AS(
  SELECT DISTINCT ON(r.external_record_id)r.* FROM public.canonical_external_material_import_records r
  JOIN public.canonical_external_material_import_runs run ON run.organization_id=r.organization_id AND run.source_key=r.source_key AND run.id=r.import_run_id
  WHERE r.organization_id=org AND r.source_key=source_value AND run.consent_id=consent_row.id ORDER BY r.external_record_id,r.revision DESC),
 selected AS(SELECT external_record_id,revision,external_version,rtrim(source_digest) source_digest FROM current_records WHERE state='active' AND CASE kind_value WHEN 'job' THEN job_reference=reference_value WHEN 'material' THEN material_reference=reference_value WHEN 'vendor' THEN vendor_reference=reference_value ELSE location_reference=reference_value END ORDER BY external_record_id LIMIT 1001)
 SELECT count(*),COALESCE(jsonb_agg(jsonb_build_object('externalRecordId',external_record_id,'revision',revision,'externalVersion',external_version,'sourceDigest',source_digest) ORDER BY external_record_id),'[]'::jsonb) INTO total,manifest FROM selected;
 IF total=0 OR total>1000 THEN RETURN NULL; END IF;
 RETURN jsonb_build_object('consentId',consent_row.id,'manifest',manifest,'recordCount',total,'digest',public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'consentId',consent_row.id,'referenceKind',kind_value,'externalReference',reference_value,'records',manifest)));
END $$;

CREATE FUNCTION public.canonical_external_material_reference_target_basis(org UUID,kind_value TEXT,target_value TEXT) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE manifest JSONB;total BIGINT;accepted BIGINT;normalized_target TEXT;
BEGIN
 IF target_value IS NULL OR length(target_value) NOT BETWEEN 1 AND 160 THEN RETURN NULL; END IF;
 IF kind_value='job' THEN
  IF NOT pg_input_is_valid(target_value,'uuid') THEN RETURN NULL; END IF;
  SELECT jsonb_build_array(jsonb_build_object('targetReference',e.id::text,'operationId',e.operation_id,'graphId',e.graph_id,'opportunityId',e.opportunity_id,'snapshotDigest',rtrim(e.snapshot_digest),'createdAt',e.created_at)) INTO manifest FROM public.canonical_estimates e WHERE e.organization_id=org AND e.id=target_value::uuid;
 ELSIF kind_value='material' THEN
  WITH selected AS(SELECT * FROM public.canonical_material_movements WHERE organization_id=org AND item_key=target_value ORDER BY id LIMIT 1001)
  SELECT count(*),count(*) FILTER(WHERE review_state='accepted'),COALESCE(jsonb_agg(jsonb_build_object('id',id,'executionId',execution_id,'revision',revision,'digest',rtrim(canonical_digest),'reviewState',review_state,'itemKey',item_key,'unit',unit_code,'location',location_key,'destinationLocation',destination_location_key) ORDER BY id),'[]'::jsonb) INTO total,accepted,manifest FROM selected;
  IF total=0 OR total>1000 OR accepted=0 THEN RETURN NULL; END IF;
 ELSIF kind_value='inventory_location' THEN
  WITH selected AS(SELECT * FROM public.canonical_material_movements WHERE organization_id=org AND (location_key=target_value OR destination_location_key=target_value) ORDER BY id LIMIT 1001)
  SELECT count(*),count(*) FILTER(WHERE review_state='accepted' AND (location_key=target_value OR destination_location_key=target_value)),COALESCE(jsonb_agg(jsonb_build_object('id',id,'executionId',execution_id,'revision',revision,'digest',rtrim(canonical_digest),'reviewState',review_state,'itemKey',item_key,'unit',unit_code,'location',location_key,'destinationLocation',destination_location_key) ORDER BY id),'[]'::jsonb) INTO total,accepted,manifest FROM selected;
  IF total=0 OR total>1000 OR accepted=0 THEN RETURN NULL; END IF;
 ELSIF kind_value='vendor' THEN
  normalized_target:=public.canonical_material_source_identity_text(target_value);IF normalized_target IS NULL OR normalized_target<>target_value THEN RETURN NULL;END IF;
  WITH latest_revision AS(SELECT DISTINCT ON(estimate_id)* FROM public.canonical_estimate_revisions WHERE organization_id=org ORDER BY estimate_id,revision DESC),
  selected AS(SELECT r.estimate_id,r.id estimate_revision_id,r.revision estimate_revision,r.digest estimate_revision_digest,p.id plan_id,p.revision plan_revision,p.digest plan_digest,line.value line
   FROM latest_revision r JOIN public.canonical_material_plans p ON p.organization_id=r.organization_id AND p.estimate_id=r.estimate_id AND p.id=r.material_plan_id AND p.action='save'
   CROSS JOIN LATERAL jsonb_array_elements(p.inputs->'lines')line(value)
   WHERE p.calculation_version IN ('estimate-material-plan-v3','estimate-material-plan-v4') AND line.value#>>'{evidence,kind}'='supplier_quote' AND public.canonical_material_source_identity_text(line.value#>>'{evidence,issuer}')=normalized_target
   ORDER BY r.estimate_id,line.value->>'lineId' LIMIT 1001)
  SELECT count(*),COALESCE(jsonb_agg(jsonb_build_object('estimateId',estimate_id,'estimateRevisionId',estimate_revision_id,'estimateRevision',estimate_revision,'estimateRevisionDigest',rtrim(estimate_revision_digest),'planId',plan_id,'planRevision',plan_revision,'planDigest',rtrim(plan_digest),'line',line) ORDER BY estimate_id,line->>'lineId'),'[]'::jsonb) INTO total,manifest FROM selected;
  IF total=0 OR total>1000 THEN RETURN NULL; END IF;
 ELSE RETURN NULL; END IF;
 IF manifest IS NULL THEN RETURN NULL; END IF;
 RETURN jsonb_build_object('manifest',manifest,'digest',public.canonical_completion_digest(jsonb_build_object('organizationId',org,'referenceKind',kind_value,'targetReference',target_value,'records',manifest)));
END $$;

CREATE FUNCTION public.canonical_external_material_reference_match_projection(value public.canonical_external_material_reference_matches,current_source JSONB,current_target JSONB,current_consent JSONB) RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_build_object('id',value.id,'sourceKey',value.source_key,'referenceKind',value.reference_kind,'externalReference',value.external_reference,'revision',value.revision,'previousId',value.previous_id,'consentId',value.consent_id,'consentRevision',value.consent_revision,'consentDigest',rtrim(value.consent_digest),'action',value.action,'targetReference',value.target_reference,'sourceManifest',value.source_manifest,'sourceDigest',value.source_digest,'targetManifest',value.target_manifest,'targetDigest',value.target_digest,'reason',value.reason,'confirmed',value.confirmed,'confirmationVersion',value.confirmation_version,'digest',rtrim(value.canonical_digest),'status',CASE WHEN value.action='unlink' THEN 'unmatched' WHEN current_consent->>'id' IS DISTINCT FROM value.consent_id::text OR current_consent->>'digest' IS DISTINCT FROM rtrim(value.consent_digest) OR current_source IS NULL OR current_target IS NULL OR current_source->>'digest' IS DISTINCT FROM value.source_digest OR current_target->>'digest' IS DISTINCT FROM value.target_digest THEN 'stale' ELSE 'matched' END,'createdAt',value.created_at) $$;

CREATE FUNCTION public.canonical_external_material_reference_matches_read(org UUID,actor UUID,role_value TEXT,session_value UUID,source_value TEXT) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_row public.canonical_external_material_import_consents%ROWTYPE;references_value JSONB;job_targets JSONB;material_targets JSONB;vendor_targets JSONB;location_targets JSONB;reference_total BIGINT;job_total BIGINT;material_total BIGINT;vendor_total BIGINT;location_total BIGINT;
BEGIN
 IF role_value IS NULL OR role_value NOT IN ('owner','admin') THEN RAISE EXCEPTION 'Material reference review restricted' USING ERRCODE='42501'; END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'Material source invalid' USING ERRCODE='22023'; END IF;
 SELECT * INTO consent_row FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;
 IF consent_row.id IS NULL OR consent_row.action<>'grant' THEN RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',FALSE,'references','[]'::jsonb,'referenceTotal',0,'referencesTruncated',FALSE,'jobTargets','[]'::jsonb,'jobTargetTotal',0,'materialTargets','[]'::jsonb,'materialTargetTotal',0,'vendorTargets','[]'::jsonb,'vendorTargetTotal',0,'inventoryLocationTargets','[]'::jsonb,'inventoryLocationTargetTotal',0,'consumptionBoundary','Reference review is unavailable while source permission is inactive.');END IF;
 WITH current_records AS(SELECT DISTINCT ON(r.external_record_id)r.* FROM public.canonical_external_material_import_records r JOIN public.canonical_external_material_import_runs run ON run.organization_id=r.organization_id AND run.source_key=r.source_key AND run.id=r.import_run_id WHERE r.organization_id=org AND r.source_key=source_value AND run.consent_id=consent_row.id ORDER BY r.external_record_id,r.revision DESC),
 refs AS(SELECT DISTINCT 'job'::text kind,job_reference reference FROM current_records WHERE state='active' AND job_reference IS NOT NULL UNION SELECT DISTINCT 'material',material_reference FROM current_records WHERE state='active' AND material_reference IS NOT NULL UNION SELECT DISTINCT 'vendor',vendor_reference FROM current_records WHERE state='active' AND vendor_reference IS NOT NULL UNION SELECT DISTINCT 'inventory_location',location_reference FROM current_records WHERE state='active' AND location_reference IS NOT NULL),
 latest AS(SELECT DISTINCT ON(reference_kind,external_reference)* FROM public.canonical_external_material_reference_matches WHERE organization_id=org AND source_key=source_value AND consent_id=consent_row.id ORDER BY reference_kind,external_reference,revision DESC),all_refs AS(SELECT kind,reference FROM refs UNION SELECT reference_kind,external_reference FROM latest) SELECT count(*) INTO reference_total FROM all_refs;
 WITH current_records AS(SELECT DISTINCT ON(r.external_record_id)r.* FROM public.canonical_external_material_import_records r JOIN public.canonical_external_material_import_runs run ON run.organization_id=r.organization_id AND run.source_key=r.source_key AND run.id=r.import_run_id WHERE r.organization_id=org AND r.source_key=source_value AND run.consent_id=consent_row.id ORDER BY r.external_record_id,r.revision DESC),refs AS(SELECT DISTINCT 'job'::text kind,job_reference reference FROM current_records WHERE state='active' AND job_reference IS NOT NULL UNION SELECT DISTINCT 'material',material_reference FROM current_records WHERE state='active' AND material_reference IS NOT NULL UNION SELECT DISTINCT 'vendor',vendor_reference FROM current_records WHERE state='active' AND vendor_reference IS NOT NULL UNION SELECT DISTINCT 'inventory_location',location_reference FROM current_records WHERE state='active' AND location_reference IS NOT NULL),latest AS(SELECT DISTINCT ON(reference_kind,external_reference)* FROM public.canonical_external_material_reference_matches WHERE organization_id=org AND source_key=source_value AND consent_id=consent_row.id ORDER BY reference_kind,external_reference,revision DESC),selected AS(SELECT * FROM(SELECT kind,reference FROM refs UNION SELECT reference_kind,external_reference FROM latest)q ORDER BY kind,reference LIMIT 100)
 SELECT COALESCE(jsonb_agg(jsonb_build_object('referenceKind',r.kind,'externalReference',r.reference,'sourceRecordCount',(sb.value->>'recordCount')::bigint,'sourceDigest',COALESCE(sb.value->>'digest','unavailable'),'match',CASE WHEN m.id IS NULL THEN NULL ELSE public.canonical_external_material_reference_match_projection(m,sb.value,tb.value,public.canonical_external_material_consent_projection(consent_row))END)ORDER BY r.kind,r.reference),'[]'::jsonb) INTO references_value FROM selected r LEFT JOIN LATERAL(SELECT public.canonical_external_material_reference_source_basis(org,source_value,r.kind,r.reference)value)sb ON TRUE LEFT JOIN latest m ON m.reference_kind=r.kind AND m.external_reference=r.reference LEFT JOIN LATERAL(SELECT public.canonical_external_material_reference_target_basis(org,r.kind,m.target_reference)value)tb ON m.target_reference IS NOT NULL;
 SELECT count(*) INTO job_total FROM public.canonical_estimates WHERE organization_id=org;
 SELECT COALESCE(jsonb_agg(jsonb_build_object('targetReference',e.id::text,'label',COALESCE(e.opportunity_id::text,'Recorded job'),'digest',b.value->>'digest')ORDER BY e.created_at DESC,e.id DESC),'[]'::jsonb) INTO job_targets FROM(SELECT * FROM public.canonical_estimates WHERE organization_id=org ORDER BY created_at DESC,id DESC LIMIT 100)e CROSS JOIN LATERAL(SELECT public.canonical_external_material_reference_target_basis(org,'job',e.id::text)value)b;
 SELECT count(DISTINCT item_key) INTO material_total FROM public.canonical_material_movements WHERE organization_id=org AND review_state='accepted';
 SELECT COALESCE(jsonb_agg(jsonb_build_object('targetReference',q.item_key,'label',q.description,'digest',b.value->>'digest')ORDER BY q.item_key),'[]'::jsonb) INTO material_targets FROM(SELECT DISTINCT ON(item_key)item_key,description FROM public.canonical_material_movements WHERE organization_id=org AND review_state='accepted' ORDER BY item_key,updated_at DESC LIMIT 100)q CROSS JOIN LATERAL(SELECT public.canonical_external_material_reference_target_basis(org,'material',q.item_key)value)b;
 WITH locations AS(SELECT location_key key FROM public.canonical_material_movements WHERE organization_id=org AND review_state='accepted' AND location_key IS NOT NULL UNION SELECT destination_location_key FROM public.canonical_material_movements WHERE organization_id=org AND review_state='accepted' AND destination_location_key IS NOT NULL)SELECT count(*) INTO location_total FROM locations;
 WITH locations AS(SELECT location_key key FROM public.canonical_material_movements WHERE organization_id=org AND review_state='accepted' AND location_key IS NOT NULL UNION SELECT destination_location_key FROM public.canonical_material_movements WHERE organization_id=org AND review_state='accepted' AND destination_location_key IS NOT NULL),selected AS(SELECT key FROM locations ORDER BY key LIMIT 100)SELECT COALESCE(jsonb_agg(jsonb_build_object('targetReference',key,'label',key,'digest',b.value->>'digest')ORDER BY key),'[]'::jsonb) INTO location_targets FROM selected CROSS JOIN LATERAL(SELECT public.canonical_external_material_reference_target_basis(org,'inventory_location',key)value)b;
 WITH latest_revision AS(SELECT DISTINCT ON(estimate_id)* FROM public.canonical_estimate_revisions WHERE organization_id=org ORDER BY estimate_id,revision DESC),vendors AS(SELECT DISTINCT public.canonical_material_source_identity_text(line.value#>>'{evidence,issuer}') vendor FROM latest_revision r JOIN public.canonical_material_plans p ON p.organization_id=r.organization_id AND p.estimate_id=r.estimate_id AND p.id=r.material_plan_id AND p.action='save' CROSS JOIN LATERAL jsonb_array_elements(p.inputs->'lines')line(value) WHERE p.calculation_version IN('estimate-material-plan-v3','estimate-material-plan-v4') AND line.value#>>'{evidence,kind}'='supplier_quote')SELECT count(*) INTO vendor_total FROM vendors WHERE vendor IS NOT NULL;
 WITH latest_revision AS(SELECT DISTINCT ON(estimate_id)* FROM public.canonical_estimate_revisions WHERE organization_id=org ORDER BY estimate_id,revision DESC),vendors AS(SELECT DISTINCT public.canonical_material_source_identity_text(line.value#>>'{evidence,issuer}') vendor FROM latest_revision r JOIN public.canonical_material_plans p ON p.organization_id=r.organization_id AND p.estimate_id=r.estimate_id AND p.id=r.material_plan_id AND p.action='save' CROSS JOIN LATERAL jsonb_array_elements(p.inputs->'lines')line(value) WHERE p.calculation_version IN('estimate-material-plan-v3','estimate-material-plan-v4') AND line.value#>>'{evidence,kind}'='supplier_quote'),selected AS(SELECT vendor FROM vendors WHERE vendor IS NOT NULL ORDER BY vendor LIMIT 100)SELECT COALESCE(jsonb_agg(jsonb_build_object('targetReference',vendor,'label',vendor,'digest',b.value->>'digest')ORDER BY vendor),'[]'::jsonb) INTO vendor_targets FROM selected CROSS JOIN LATERAL(SELECT public.canonical_external_material_reference_target_basis(org,'vendor',vendor)value)b;
 RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',TRUE,'consent',public.canonical_external_material_consent_projection(consent_row),'references',references_value,'referenceTotal',reference_total,'referencesTruncated',reference_total>100,'jobTargets',job_targets,'jobTargetTotal',job_total,'jobTargetsTruncated',job_total>100,'materialTargets',material_targets,'materialTargetTotal',material_total,'materialTargetsTruncated',material_total>100,'vendorTargets',vendor_targets,'vendorTargetTotal',vendor_total,'vendorTargetsTruncated',vendor_total>100,'inventoryLocationTargets',location_targets,'inventoryLocationTargetTotal',location_total,'inventoryLocationTargetsTruncated',location_total>100,'consumptionBoundary','Reviewed links provide lineage only. Supplier quote labels are owner-reviewed source evidence, not verified supplier truth. No link changes a job, estimate, inventory record, purchase, vendor, cost or policy.');
END $$;

CREATE FUNCTION public.canonical_external_material_reference_match_mutate(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,body JSONB) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;consent_row public.canonical_external_material_import_consents%ROWTYPE;current_row public.canonical_external_material_reference_matches%ROWTYPE;replay public.canonical_external_material_reference_matches%ROWTYPE;inserted public.canonical_external_material_reference_matches%ROWTYPE;source_basis JSONB;target_basis JSONB;key_hash TEXT;request_hash TEXT;digest_value TEXT;next_revision BIGINT;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;
 IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Material reference review restricted' USING ERRCODE='42501';END IF;
 PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR octet_length(body::text)>16384 OR public.canonical_field_evidence_object_keys_exact(body,ARRAY['action','referenceKind','externalReference','targetReference','expectedRevision','expectedDigest','expectedSourceDigest','expectedTargetDigest','reason','confirmed','confirmationVersion']) IS NOT TRUE
 OR jsonb_typeof(body->'action') IS DISTINCT FROM 'string' OR body->>'action' IS NULL OR body->>'action' NOT IN('link','unlink') OR jsonb_typeof(body->'referenceKind') IS DISTINCT FROM 'string' OR body->>'referenceKind' IS NULL OR body->>'referenceKind' NOT IN('job','material','vendor','inventory_location') OR jsonb_typeof(body->'externalReference') IS DISTINCT FROM 'string' OR length(body->>'externalReference') NOT BETWEEN 1 AND 128 OR body->>'externalReference'!~'^[!-~]+$'
 OR jsonb_typeof(body->'expectedRevision') IS DISTINCT FROM 'number' OR (body->>'expectedRevision')!~'^(0|[1-9][0-9]{0,3}|10000)$' OR jsonb_typeof(body->'expectedDigest') IS DISTINCT FROM 'string' OR body->>'expectedDigest'!~'^(none|[0-9a-f]{64})$' OR (((body->>'expectedRevision')::bigint=0)<>(body->>'expectedDigest'='none')) OR jsonb_typeof(body->'expectedSourceDigest') IS DISTINCT FROM 'string' OR body->>'expectedSourceDigest'!~'^(unavailable|[0-9a-f]{64})$' OR jsonb_typeof(body->'expectedTargetDigest') IS DISTINCT FROM 'string' OR body->>'expectedTargetDigest'!~'^(unavailable|[0-9a-f]{64})$'
 OR jsonb_typeof(body->'reason') IS DISTINCT FROM 'string' OR public.canonical_learning_text_valid(body->>'reason',2000) IS NOT TRUE OR body->'confirmed' IS DISTINCT FROM 'true'::jsonb OR jsonb_typeof(body->'confirmationVersion') IS DISTINCT FROM 'string' OR body->>'confirmationVersion' IS DISTINCT FROM 'm25-external-material-reference-match-v1'
 OR (body->>'action'='link' AND (jsonb_typeof(body->'targetReference') IS DISTINCT FROM 'string' OR length(body->>'targetReference') NOT BETWEEN 1 AND 160 OR body->>'targetReference'<>btrim(body->>'targetReference') OR body->>'targetReference'~U&'[\0001-\001f\007f-\009f]' OR body->>'expectedSourceDigest'='unavailable' OR body->>'expectedTargetDigest'='unavailable')) OR (body->>'action'='unlink' AND (body->'targetReference'<>'null'::jsonb OR body->>'expectedTargetDigest'<>'unavailable')) THEN RAISE EXCEPTION 'Material reference match invalid' USING ERRCODE='22023';END IF;
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'body',body));
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':external-material-match:'||source_value||':'||(body->>'referenceKind')||':'||(body->>'externalReference'),0));
 SELECT * INTO replay FROM public.canonical_external_material_reference_matches WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;
 IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Material reference match key conflict' USING ERRCODE='23505';END IF;SELECT * INTO consent_row FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;IF consent_row.id IS NULL OR consent_row.action<>'grant' OR consent_row.id<>replay.consent_id THEN RETURN jsonb_build_object('match',jsonb_build_object('revision',replay.revision,'status','unavailable','action',replay.action),'replayed',TRUE);END IF;source_basis:=public.canonical_external_material_reference_source_basis(org,source_value,replay.reference_kind,replay.external_reference);target_basis:=public.canonical_external_material_reference_target_basis(org,replay.reference_kind,replay.target_reference);RETURN jsonb_build_object('match',public.canonical_external_material_reference_match_projection(replay,source_basis,target_basis,public.canonical_external_material_consent_projection(consent_row)),'replayed',TRUE);END IF;
 SELECT * INTO consent_row FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1 FOR UPDATE;IF consent_row.id IS NULL OR consent_row.action<>'grant' THEN RAISE EXCEPTION 'Material source permission changed' USING ERRCODE='40001',CONSTRAINT='material_match_source_changed';END IF;
 SELECT * INTO current_row FROM public.canonical_external_material_reference_matches WHERE organization_id=org AND source_key=source_value AND consent_id=consent_row.id AND reference_kind=body->>'referenceKind' AND external_reference=body->>'externalReference' ORDER BY revision DESC LIMIT 1 FOR UPDATE;
 IF (body->>'expectedRevision')::bigint IS DISTINCT FROM COALESCE(current_row.revision,0) OR body->>'expectedDigest' IS DISTINCT FROM COALESCE(rtrim(current_row.canonical_digest),'none') THEN RAISE EXCEPTION 'Material reference match changed' USING ERRCODE='40001';END IF;
 source_basis:=public.canonical_external_material_reference_source_basis(org,source_value,body->>'referenceKind',body->>'externalReference');IF body->>'expectedSourceDigest' IS DISTINCT FROM COALESCE(source_basis->>'digest','unavailable') THEN RAISE EXCEPTION 'Imported material evidence changed' USING ERRCODE='40001',CONSTRAINT='material_match_source_changed';END IF;
 IF body->>'action'='link' THEN target_basis:=public.canonical_external_material_reference_target_basis(org,body->>'referenceKind',body->>'targetReference');IF source_basis IS NULL OR target_basis IS NULL THEN RAISE EXCEPTION 'Material reference target unavailable' USING ERRCODE='22023';END IF;IF body->>'expectedTargetDigest' IS DISTINCT FROM target_basis->>'digest' THEN RAISE EXCEPTION 'NorthStar material record changed' USING ERRCODE='40001',CONSTRAINT='material_match_target_changed';END IF;ELSE target_basis:=NULL;IF current_row.id IS NULL OR current_row.action<>'link' THEN RAISE EXCEPTION 'Material unlink invalid' USING ERRCODE='22023';END IF;END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'consentId',consent_row.id,'referenceKind',body->>'referenceKind','externalReference',body->>'externalReference','revision',next_revision,'previousId',current_row.id,'action',body->>'action','targetReference',body->>'targetReference','sourceDigest',COALESCE(source_basis->>'digest','unavailable'),'targetDigest',COALESCE(target_basis->>'digest','unavailable'),'actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'authSessionId',session_value,'reason',body->>'reason','confirmationVersion','m25-external-material-reference-match-v1','requestDigest',request_hash));
 INSERT INTO public.canonical_external_material_reference_matches(organization_id,source_key,consent_id,consent_revision,consent_digest,reference_kind,external_reference,revision,previous_id,action,target_reference,source_manifest,source_digest,target_manifest,target_digest,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,request_key_hash,request_digest,canonical_digest)
 VALUES(org,source_value,consent_row.id,consent_row.revision,rtrim(consent_row.canonical_digest),body->>'referenceKind',body->>'externalReference',next_revision,current_row.id,body->>'action',body->>'targetReference',COALESCE(source_basis->'manifest','[]'::jsonb),COALESCE(source_basis->>'digest','unavailable'),COALESCE(target_basis->'manifest','[]'::jsonb),COALESCE(target_basis->>'digest','unavailable'),actor,(authority->>'membershipId')::uuid,session_value,body->>'reason',TRUE,'m25-external-material-reference-match-v1',key_hash,request_hash,digest_value)RETURNING * INTO inserted;
 RETURN jsonb_build_object('match',public.canonical_external_material_reference_match_projection(inserted,source_basis,target_basis,public.canonical_external_material_consent_projection(consent_row)),'replayed',FALSE);
END $$;

REVOKE ALL ON TABLE public.canonical_external_material_reference_matches FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_material_reference_source_basis(UUID,TEXT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_material_reference_target_basis(UUID,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_material_reference_match_projection(public.canonical_external_material_reference_matches,JSONB,JSONB,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_material_reference_matches_read(UUID,UUID,TEXT,UUID,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_material_reference_match_mutate(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,JSONB) FROM PUBLIC;
