-- Mission 25 Part 11D: tenant-private imported material quantity, consumption and waste observations.
-- Dimensions are compared independently. Missing or incompatible evidence remains explicitly unavailable.

CREATE TABLE public.canonical_external_material_outcome_consents (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES public.organizations(id),
 source_key TEXT NOT NULL CHECK(source_key~'^[a-z0-9][a-z0-9._-]{1,63}$'), purpose TEXT NOT NULL CHECK(purpose='imported_material_quantity_variance_v1'),
 revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000), previous_id UUID, action TEXT NOT NULL CHECK(action IN('grant','revoke')),
 source_consent_id UUID NOT NULL, source_consent_revision BIGINT NOT NULL, source_consent_digest TEXT NOT NULL CHECK(source_consent_digest~'^[0-9a-f]{64}$'),
 actor_user_id UUID NOT NULL, membership_id UUID NOT NULL, auth_session_id UUID NOT NULL,
 source_scope JSONB NOT NULL CHECK(source_scope='["canonical_estimates","canonical_estimate_revisions","canonical_material_plans","canonical_external_material_import_records","canonical_external_material_reference_matches"]'::jsonb),
 consent_version TEXT NOT NULL CHECK(consent_version='m25-imported-material-quantity-consent-v1'), reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)),
 request_key_hash TEXT NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'), request_digest TEXT NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),
 canonical_digest TEXT NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'), created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
 UNIQUE(organization_id,source_key,purpose,revision), UNIQUE(organization_id,actor_user_id,request_key_hash), UNIQUE(organization_id,source_key,id),
 FOREIGN KEY(organization_id,source_key,previous_id) REFERENCES public.canonical_external_material_outcome_consents(organization_id,source_key,id),
 FOREIGN KEY(organization_id,source_key,source_consent_id) REFERENCES public.canonical_external_material_import_consents(organization_id,source_key,id),
 FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id),
 FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id),
 CHECK((revision=1 AND previous_id IS NULL) OR (revision>1 AND previous_id IS NOT NULL))
);

CREATE FUNCTION public.canonical_imported_material_outcome_consent_projection(v public.canonical_external_material_outcome_consents) RETURNS JSONB
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT jsonb_build_object('id',v.id,'sourceKey',v.source_key,'purpose',v.purpose,'revision',v.revision,'previousId',v.previous_id,'action',v.action,'sourceConsent',jsonb_build_object('id',v.source_consent_id,'revision',v.source_consent_revision,'digest',rtrim(v.source_consent_digest)),'sourceScope',v.source_scope,'consentVersion',v.consent_version,'reason',v.reason,'digest',rtrim(v.canonical_digest),'createdAt',v.created_at) $$;

CREATE FUNCTION public.canonical_imported_material_outcome_consent_read(org UUID,actor UUID,role_value TEXT,session_value UUID,source_value TEXT) RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_consent public.canonical_external_material_import_consents%ROWTYPE; current_row public.canonical_external_material_outcome_consents%ROWTYPE; history JSONB; total BIGINT; active_value BOOLEAN;
BEGIN
 IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Imported material outcome review restricted' USING ERRCODE='42501';END IF;
 PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'Material source invalid' USING ERRCODE='22023';END IF;
 SELECT * INTO source_consent FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;
 SELECT * INTO current_row FROM public.canonical_external_material_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_material_quantity_variance_v1' ORDER BY revision DESC LIMIT 1;
 active_value:=source_consent.id IS NOT NULL AND source_consent.action='grant' AND current_row.id IS NOT NULL AND current_row.action='grant' AND current_row.source_consent_id=source_consent.id AND rtrim(current_row.source_consent_digest)=rtrim(source_consent.canonical_digest);
 SELECT count(*) INTO total FROM public.canonical_external_material_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_material_quantity_variance_v1';
 SELECT COALESCE(jsonb_agg(public.canonical_imported_material_outcome_consent_projection(x) ORDER BY revision DESC),'[]'::jsonb) INTO history FROM(SELECT * FROM public.canonical_external_material_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_material_quantity_variance_v1' ORDER BY revision DESC LIMIT 20)x;
 RETURN jsonb_build_object('sourceKey',source_value,'active',active_value,'current',CASE WHEN current_row.id IS NULL THEN NULL ELSE public.canonical_imported_material_outcome_consent_projection(current_row)END,'history',history,'total',total,'truncated',total>20,'blockedReason',CASE WHEN active_value THEN NULL WHEN source_consent.id IS NULL OR source_consent.action<>'grant' THEN 'External material source permission is not active.' WHEN current_row.id IS NOT NULL AND current_row.action='grant' THEN 'Imported material outcome consent must be renewed for the current source permission.' ELSE 'Imported material outcome consent is not active.' END);
END $$;

CREATE FUNCTION public.canonical_imported_material_outcome_consent_mutate(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,body JSONB) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB; source_consent public.canonical_external_material_import_consents%ROWTYPE; current_row public.canonical_external_material_outcome_consents%ROWTYPE; replay public.canonical_external_material_outcome_consents%ROWTYPE; inserted public.canonical_external_material_outcome_consents%ROWTYPE; key_hash TEXT;request_hash TEXT;digest_value TEXT;next_revision BIGINT;currently_active BOOLEAN;scope_value JSONB:='["canonical_estimates","canonical_estimate_revisions","canonical_material_plans","canonical_external_material_import_records","canonical_external_material_reference_matches"]'::jsonb;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;
 IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Imported material outcome review restricted' USING ERRCODE='42501';END IF;
 PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501';END IF;
 authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR octet_length(body::text)>8192 OR public.canonical_field_evidence_object_keys_exact(body,ARRAY['action','expectedRevision','expectedDigest','reason','confirmed','confirmationVersion']) IS NOT TRUE OR jsonb_typeof(body->'action') IS DISTINCT FROM 'string' OR body->>'action' NOT IN('grant','revoke') OR jsonb_typeof(body->'expectedRevision') IS DISTINCT FROM 'number' OR (body->>'expectedRevision')!~'^(0|[1-9][0-9]{0,3}|10000)$' OR jsonb_typeof(body->'expectedDigest') IS DISTINCT FROM 'string' OR body->>'expectedDigest'!~'^(none|[0-9a-f]{64})$' OR (((body->>'expectedRevision')::bigint=0)<>(body->>'expectedDigest'='none')) OR jsonb_typeof(body->'reason') IS DISTINCT FROM 'string' OR public.canonical_learning_text_valid(body->>'reason',2000) IS NOT TRUE OR body->'confirmed' IS DISTINCT FROM 'true'::jsonb OR body->>'confirmationVersion' IS DISTINCT FROM 'm25-imported-material-quantity-consent-v1' THEN RAISE EXCEPTION 'Imported material outcome consent invalid' USING ERRCODE='22023';END IF;
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'body',body));
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':imported-material-outcome-consent:'||source_value,0));
 SELECT * INTO replay FROM public.canonical_external_material_outcome_consents WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;
 IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Imported material consent key conflict' USING ERRCODE='23505';END IF;RETURN jsonb_build_object('consent',public.canonical_imported_material_outcome_consent_projection(replay),'replayed',TRUE);END IF;
 SELECT * INTO source_consent FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1 FOR SHARE;
 IF source_consent.id IS NULL THEN RAISE EXCEPTION 'Material source permission unavailable' USING ERRCODE='40001',CONSTRAINT='imported_material_source_consent_stale';END IF;
 SELECT * INTO current_row FROM public.canonical_external_material_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_material_quantity_variance_v1' ORDER BY revision DESC LIMIT 1 FOR UPDATE;
 IF (body->>'expectedRevision')::bigint<>COALESCE(current_row.revision,0) OR body->>'expectedDigest' IS DISTINCT FROM COALESCE(rtrim(current_row.canonical_digest),'none') THEN RAISE EXCEPTION 'Imported material outcome consent changed' USING ERRCODE='40001';END IF;
 currently_active:=current_row.id IS NOT NULL AND current_row.action='grant' AND source_consent.action='grant' AND current_row.source_consent_id=source_consent.id AND rtrim(current_row.source_consent_digest)=rtrim(source_consent.canonical_digest);
 IF body->>'action'='grant' AND source_consent.action<>'grant' THEN RAISE EXCEPTION 'Material source permission inactive' USING ERRCODE='40001';END IF;
 IF body->>'action'='grant' AND currently_active OR body->>'action'='revoke' AND(current_row.id IS NULL OR current_row.action<>'grant') THEN RAISE EXCEPTION 'Imported material outcome consent action invalid' USING ERRCODE='22023';END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'purpose','imported_material_quantity_variance_v1','revision',next_revision,'previousId',current_row.id,'action',body->>'action','sourceConsentId',source_consent.id,'sourceConsentRevision',source_consent.revision,'sourceConsentDigest',rtrim(source_consent.canonical_digest),'actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'authSessionId',session_value,'sourceScope',scope_value,'consentVersion','m25-imported-material-quantity-consent-v1','reason',body->>'reason','requestDigest',request_hash));
 INSERT INTO public.canonical_external_material_outcome_consents(organization_id,source_key,purpose,revision,previous_id,action,source_consent_id,source_consent_revision,source_consent_digest,actor_user_id,membership_id,auth_session_id,source_scope,consent_version,reason,request_key_hash,request_digest,canonical_digest) VALUES(org,source_value,'imported_material_quantity_variance_v1',next_revision,current_row.id,body->>'action',source_consent.id,source_consent.revision,rtrim(source_consent.canonical_digest),actor,(authority->>'membershipId')::uuid,session_value,scope_value,'m25-imported-material-quantity-consent-v1',body->>'reason',key_hash,request_hash,digest_value)RETURNING * INTO inserted;
 RETURN jsonb_build_object('consent',public.canonical_imported_material_outcome_consent_projection(inserted),'replayed',FALSE);
END $$;

CREATE FUNCTION public.canonical_imported_material_bindings_valid(value JSONB) RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE entry JSONB;lines TEXT[]:=ARRAY[]::text[];refs TEXT[]:=ARRAY[]::text[];
BEGIN IF jsonb_typeof(value) IS DISTINCT FROM 'array' OR jsonb_array_length(value) NOT BETWEEN 1 AND 20 THEN RETURN FALSE;END IF;
 FOR entry IN SELECT item FROM jsonb_array_elements(value)item LOOP IF public.canonical_field_evidence_object_keys_exact(entry,ARRAY['lineId','externalMaterialReference']) IS NOT TRUE OR jsonb_typeof(entry->'lineId') IS DISTINCT FROM 'string' OR (entry->>'lineId')!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' OR jsonb_typeof(entry->'externalMaterialReference') IS DISTINCT FROM 'string' OR length(entry->>'externalMaterialReference') NOT BETWEEN 1 AND 128 OR (entry->>'externalMaterialReference')!~'^[!-~]+$' OR entry->>'lineId'=ANY(lines) OR entry->>'externalMaterialReference'=ANY(refs) THEN RETURN FALSE;END IF;lines:=array_append(lines,entry->>'lineId');refs:=array_append(refs,entry->>'externalMaterialReference');END LOOP;RETURN TRUE;
END $$;

CREATE FUNCTION public.canonical_imported_material_dimension(actual NUMERIC,unit_value TEXT,available_value BOOLEAN,reason_value TEXT) RETURNS JSONB LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$ SELECT CASE WHEN available_value THEN jsonb_build_object('status','recorded','quantity',round(actual,6)::text,'unit',unit_value,'unavailableReason',NULL) ELSE jsonb_build_object('status','unavailable','quantity',NULL,'unit',NULL,'unavailableReason',reason_value) END $$;

CREATE FUNCTION public.canonical_imported_material_outcome_basis(org UUID,source_value TEXT,estimate UUID,job_reference_value TEXT,bindings JSONB) RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_consent public.canonical_external_material_import_consents%ROWTYPE;estimate_row public.canonical_estimates%ROWTYPE;revision_row public.canonical_estimate_revisions%ROWTYPE;plan_row public.canonical_material_plans%ROWTYPE;job_match public.canonical_external_material_reference_matches%ROWTYPE;job_source JSONB;job_target JSONB;component JSONB;sorted_bindings JSONB;binding JSONB;plan_line JSONB;material_match public.canonical_external_material_reference_matches%ROWTYPE;material_source JSONB;material_target JSONB;material_matches JSONB:='[]'::jsonb;imported_records JSONB;relevant_refs JSONB;result_lines JSONB:='[]'::jsonb;planned NUMERIC;consumed NUMERIC;wasted NUMERIC;used NUMERIC;variance NUMERIC;pct NUMERIC;consumed_count INTEGER;waste_count INTEGER;plan_count INTEGER;binding_count INTEGER;record_count INTEGER;compared_count INTEGER:=0;within_count INTEGER:=0;above_count INTEGER:=0;below_count INTEGER:=0;code TEXT;message TEXT;target_keys TEXT[]:=ARRAY[]::text[];manifest JSONB;
BEGIN
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR job_reference_value IS NULL OR job_reference_value!~'^[!-~]{1,128}$' OR public.canonical_imported_material_bindings_valid(bindings) IS NOT TRUE THEN RAISE EXCEPTION 'Imported material outcome input invalid' USING ERRCODE='22023';END IF;
 SELECT COALESCE(jsonb_agg(value ORDER BY value->>'lineId'),'[]'::jsonb)INTO sorted_bindings FROM jsonb_array_elements(bindings)value;
 SELECT * INTO source_consent FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;
 IF source_consent.id IS NULL OR source_consent.action<>'grant' THEN RAISE EXCEPTION 'Material source permission unavailable' USING ERRCODE='P0002',CONSTRAINT='imported_material_source_unavailable';END IF;
 SELECT * INTO estimate_row FROM public.canonical_estimates WHERE organization_id=org AND id=estimate;IF NOT FOUND THEN RAISE EXCEPTION 'Estimate unavailable' USING ERRCODE='P0002';END IF;
 SELECT * INTO revision_row FROM public.canonical_estimate_revisions WHERE organization_id=org AND estimate_id=estimate ORDER BY revision DESC LIMIT 1;IF NOT FOUND THEN RAISE EXCEPTION 'Adopted material plan required' USING ERRCODE='P0002',CONSTRAINT='imported_material_plan_unavailable';END IF;
 component:=public.canonical_estimate_revision_components(revision_row)->'material';IF component->>'kind' IS DISTINCT FROM 'plan' THEN RAISE EXCEPTION 'Adopted material plan required' USING ERRCODE='P0002',CONSTRAINT='imported_material_plan_unavailable';END IF;
 SELECT * INTO plan_row FROM public.canonical_material_plans WHERE organization_id=org AND estimate_id=estimate AND id=(component->>'id')::uuid AND revision=(component->>'revision')::bigint AND digest=component->>'digest' AND action='save';IF NOT FOUND OR jsonb_typeof(plan_row.inputs->'lines') IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'Current material plan required' USING ERRCODE='P0002',CONSTRAINT='imported_material_plan_unavailable';END IF;
 SELECT * INTO job_match FROM public.canonical_external_material_reference_matches WHERE organization_id=org AND source_key=source_value AND consent_id=source_consent.id AND reference_kind='job' AND external_reference=job_reference_value ORDER BY revision DESC LIMIT 1;
 job_source:=public.canonical_external_material_reference_source_basis(org,source_value,'job',job_reference_value);job_target:=public.canonical_external_material_reference_target_basis(org,'job',estimate::text);
 IF job_match.id IS NULL OR job_match.action<>'link' OR job_match.target_reference<>estimate::text OR job_source IS NULL OR job_target IS NULL OR rtrim(job_match.source_digest)<>job_source->>'digest' OR rtrim(job_match.target_digest)<>job_target->>'digest' THEN RAISE EXCEPTION 'Current reviewed job match required' USING ERRCODE='P0002',CONSTRAINT='imported_material_match_unavailable';END IF;
 WITH current_records AS(SELECT DISTINCT ON(r.external_record_id)r.* FROM public.canonical_external_material_import_records r JOIN public.canonical_external_material_import_runs run ON run.organization_id=r.organization_id AND run.source_key=r.source_key AND run.id=r.import_run_id WHERE r.organization_id=org AND r.source_key=source_value AND run.consent_id=source_consent.id ORDER BY r.external_record_id,r.revision DESC),selected AS(SELECT * FROM current_records WHERE state='active' AND job_reference=job_reference_value ORDER BY external_record_id LIMIT 1001) SELECT count(*),COALESCE(jsonb_agg(jsonb_build_object('externalRecordId',external_record_id,'revision',revision,'externalVersion',external_version,'sourceDigest',rtrim(source_digest),'recordType',record_type,'materialReference',material_reference,'movementKind',movement_kind,'quantity',normalized_evidence->'quantity','occurredAt',occurred_at)ORDER BY external_record_id),'[]'::jsonb) INTO record_count,imported_records FROM selected;
 IF record_count=0 OR record_count>1000 THEN RAISE EXCEPTION 'Bounded current job evidence required' USING ERRCODE='P0002',CONSTRAINT='imported_material_evidence_unavailable';END IF;
 WITH current_records AS(SELECT DISTINCT ON(r.external_record_id)r.* FROM public.canonical_external_material_import_records r JOIN public.canonical_external_material_import_runs run ON run.organization_id=r.organization_id AND run.source_key=r.source_key AND run.id=r.import_run_id WHERE r.organization_id=org AND r.source_key=source_value AND run.consent_id=source_consent.id ORDER BY r.external_record_id,r.revision DESC) SELECT COALESCE(jsonb_agg(material_reference ORDER BY material_reference),'[]'::jsonb) INTO relevant_refs FROM(SELECT DISTINCT material_reference FROM current_records WHERE state='active' AND job_reference=job_reference_value AND record_type='inventory_movement' AND movement_kind IN('consumed','waste'))q;
 plan_count:=jsonb_array_length(plan_row.inputs->'lines');binding_count:=jsonb_array_length(sorted_bindings);
 IF plan_count<>binding_count OR relevant_refs<>COALESCE((SELECT jsonb_agg(value->>'externalMaterialReference' ORDER BY value->>'externalMaterialReference')FROM jsonb_array_elements(sorted_bindings)value),'[]'::jsonb) OR EXISTS(SELECT 1 FROM jsonb_array_elements(plan_row.inputs->'lines')line FULL JOIN jsonb_array_elements(sorted_bindings)bind ON bind->>'lineId'=line->>'lineId' WHERE line IS NULL OR bind IS NULL) THEN RAISE EXCEPTION 'Exact plan and recorded material coverage required' USING ERRCODE='P0002',CONSTRAINT='imported_material_binding_unavailable';END IF;
 FOR binding IN SELECT value FROM jsonb_array_elements(sorted_bindings)value ORDER BY value->>'lineId' LOOP
  SELECT value INTO plan_line FROM jsonb_array_elements(plan_row.inputs->'lines')value WHERE value->>'lineId'=binding->>'lineId';
  SELECT * INTO material_match FROM public.canonical_external_material_reference_matches WHERE organization_id=org AND source_key=source_value AND consent_id=source_consent.id AND reference_kind='material' AND external_reference=binding->>'externalMaterialReference' ORDER BY revision DESC LIMIT 1;
  material_source:=public.canonical_external_material_reference_source_basis(org,source_value,'material',binding->>'externalMaterialReference');material_target:=public.canonical_external_material_reference_target_basis(org,'material',material_match.target_reference);
  IF material_match.id IS NULL OR material_match.action<>'link' OR material_source IS NULL OR material_target IS NULL OR rtrim(material_match.source_digest)<>material_source->>'digest' OR rtrim(material_match.target_digest)<>material_target->>'digest' OR material_match.target_reference=ANY(target_keys) THEN RAISE EXCEPTION 'Distinct current reviewed material matches required' USING ERRCODE='P0002',CONSTRAINT='imported_material_match_unavailable';END IF;
  target_keys:=array_append(target_keys,material_match.target_reference);material_matches:=material_matches||jsonb_build_array(jsonb_build_object('id',material_match.id,'revision',material_match.revision,'digest',rtrim(material_match.canonical_digest),'externalMaterialReference',material_match.external_reference,'targetItemKey',material_match.target_reference,'sourceDigest',material_source->>'digest','targetDigest',material_target->>'digest'));
  planned:=(plan_line->>'quantity')::numeric*(1+(plan_line->>'wastePercent')::numeric/100);planned:=(CASE WHEN plan_line->>'unit'='ea' THEN ceil(planned) ELSE ceil(planned*1000000)/1000000 END)::numeric(20,6);
  WITH current_records AS(SELECT DISTINCT ON(r.external_record_id)r.* FROM public.canonical_external_material_import_records r JOIN public.canonical_external_material_import_runs run ON run.organization_id=r.organization_id AND run.source_key=r.source_key AND run.id=r.import_run_id WHERE r.organization_id=org AND r.source_key=source_value AND run.consent_id=source_consent.id ORDER BY r.external_record_id,r.revision DESC),selected AS(SELECT * FROM current_records WHERE state='active' AND job_reference=job_reference_value AND material_reference=binding->>'externalMaterialReference' AND record_type='inventory_movement') SELECT count(*)FILTER(WHERE movement_kind='consumed'),count(*)FILTER(WHERE movement_kind='waste'),COALESCE(sum((normalized_evidence#>>'{quantity,value}')::numeric)FILTER(WHERE movement_kind='consumed' AND normalized_evidence#>>'{quantity,unit}'=plan_line->>'unit'),0),COALESCE(sum((normalized_evidence#>>'{quantity,value}')::numeric)FILTER(WHERE movement_kind='waste' AND normalized_evidence#>>'{quantity,unit}'=plan_line->>'unit'),0) INTO consumed_count,waste_count,consumed,wasted FROM selected;
  IF consumed_count>0 AND EXISTS(WITH current_records AS(SELECT DISTINCT ON(r.external_record_id)r.* FROM public.canonical_external_material_import_records r JOIN public.canonical_external_material_import_runs run ON run.organization_id=r.organization_id AND run.source_key=r.source_key AND run.id=r.import_run_id WHERE r.organization_id=org AND r.source_key=source_value AND run.consent_id=source_consent.id ORDER BY r.external_record_id,r.revision DESC)SELECT 1 FROM current_records WHERE state='active' AND job_reference=job_reference_value AND material_reference=binding->>'externalMaterialReference' AND record_type='inventory_movement' AND movement_kind='consumed' AND normalized_evidence#>>'{quantity,unit}'<>plan_line->>'unit') THEN consumed_count:=-1;END IF;
  IF waste_count>0 AND EXISTS(WITH current_records AS(SELECT DISTINCT ON(r.external_record_id)r.* FROM public.canonical_external_material_import_records r JOIN public.canonical_external_material_import_runs run ON run.organization_id=r.organization_id AND run.source_key=r.source_key AND run.id=r.import_run_id WHERE r.organization_id=org AND r.source_key=source_value AND run.consent_id=source_consent.id ORDER BY r.external_record_id,r.revision DESC)SELECT 1 FROM current_records WHERE state='active' AND job_reference=job_reference_value AND material_reference=binding->>'externalMaterialReference' AND record_type='inventory_movement' AND movement_kind='waste' AND normalized_evidence#>>'{quantity,unit}'<>plan_line->>'unit') THEN waste_count:=-1;END IF;
  code:=NULL;message:=NULL;variance:=NULL;pct:=NULL;
  IF consumed_count>0 AND waste_count>0 THEN used:=consumed+wasted;variance:=round(used-planned,6);pct:=round((variance/planned)*100,2);compared_count:=compared_count+1;IF abs(pct)<=5 THEN code:='within_expected_range';message:='Recorded material use was within 5% of the planned quantity.';within_count:=within_count+1;ELSIF pct>0 THEN code:='actual_above_plan';message:='Recorded material use was higher than the planned quantity.';above_count:=above_count+1;ELSE code:='actual_below_plan';message:='Recorded material use was lower than the planned quantity.';below_count:=below_count+1;END IF;ELSE used:=NULL;END IF;
  result_lines:=result_lines||jsonb_build_array(jsonb_build_object('lineId',binding->>'lineId','material',plan_line->>'material','externalMaterialReference',binding->>'externalMaterialReference','targetItemKey',material_match.target_reference,'plannedQuantity',planned::text,'plannedUnit',plan_line->>'unit','consumption',public.canonical_imported_material_dimension(consumed,plan_line->>'unit',consumed_count>0,CASE WHEN consumed_count<0 THEN 'Recorded consumption uses a different unit.' ELSE 'No recorded consumption is available.' END),'waste',public.canonical_imported_material_dimension(wasted,plan_line->>'unit',waste_count>0,CASE WHEN waste_count<0 THEN 'Recorded waste uses a different unit.' ELSE 'No recorded waste is available.' END),'totalQuantity',CASE WHEN used IS NULL THEN jsonb_build_object('status','unavailable','quantity',NULL,'unit',NULL,'varianceQuantity',NULL,'variancePercent',NULL,'advisoryCode',NULL,'advisoryMessage',NULL,'unavailableReason','Both compatible recorded consumption and recorded waste are required.') ELSE jsonb_build_object('status','compared','quantity',used::text,'unit',plan_line->>'unit','varianceQuantity',variance::text,'variancePercent',pct::text,'advisoryCode',code,'advisoryMessage',message,'unavailableReason',NULL)END));
 END LOOP;
 IF compared_count<>plan_count THEN code:=NULL;message:='Some material quantities cannot be compared until both consumption and waste are recorded in the planned unit.';ELSIF above_count>0 AND below_count>0 THEN code:='mixed_variance';message:='Some recorded material quantities were above plan and others were below plan.';ELSIF above_count>0 THEN code:='some_above_plan';message:='At least one recorded material quantity was higher than planned.';ELSIF below_count>0 THEN code:='some_below_plan';message:='At least one recorded material quantity was lower than planned.';ELSE code:='all_within_expected_range';message:='All recorded material quantities were within 5% of plan.';END IF;
 manifest:=jsonb_build_object('estimate',jsonb_build_object('id',estimate_row.id,'digest',rtrim(estimate_row.snapshot_digest)),'estimateRevision',jsonb_build_object('id',revision_row.id,'revision',revision_row.revision,'digest',revision_row.digest),'materialPlan',jsonb_build_object('id',plan_row.id,'revision',plan_row.revision,'digest',plan_row.digest,'calculationVersion',plan_row.calculation_version),'sourceConsent',jsonb_build_object('id',source_consent.id,'revision',source_consent.revision,'digest',rtrim(source_consent.canonical_digest)),'jobMatch',jsonb_build_object('id',job_match.id,'revision',job_match.revision,'digest',rtrim(job_match.canonical_digest),'externalJobReference',job_reference_value,'estimateId',estimate),'materialMatches',material_matches,'bindings',sorted_bindings,'importedRecords',imported_records);
 RETURN jsonb_build_object('sourceManifest',manifest,'sourceDigest',public.canonical_completion_digest(manifest),'result',jsonb_build_object('lineCount',plan_count,'comparedLineCount',compared_count,'unavailableLineCount',plan_count-compared_count,'withinRangeCount',within_count,'abovePlanCount',above_count,'belowPlanCount',below_count,'advisoryCode',code,'advisoryMessage',message,'lines',result_lines),'scopeNote','Recorded consumption and recorded waste are separate external material dimensions. Missing records are unavailable, not zero. Only exact reviewed links and already matching units are compared.','adoptionBoundary','Review this evidence before changing future material assumptions. No estimate, price, job, inventory balance, purchase, vendor record, material record or business policy was changed.');
END $$;

CREATE TABLE public.canonical_external_material_quantity_observations (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id),source_key TEXT NOT NULL,estimate_id UUID NOT NULL,external_job_reference TEXT NOT NULL CHECK(length(external_job_reference)BETWEEN 1 AND 128 AND external_job_reference~'^[!-~]+$'),revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000),previous_id UUID,consent_id UUID NOT NULL,consent_revision BIGINT NOT NULL,consent_digest TEXT NOT NULL CHECK(consent_digest~'^[0-9a-f]{64}$'),source_manifest JSONB NOT NULL CHECK(jsonb_typeof(source_manifest)='object' AND octet_length(source_manifest::text)<=1048576),source_digest TEXT NOT NULL CHECK(source_digest~'^[0-9a-f]{64}$'),result JSONB NOT NULL CHECK(jsonb_typeof(result)='object' AND octet_length(result::text)<=524288),scope_note TEXT NOT NULL CHECK(public.canonical_learning_text_valid(scope_note,1000)),adoption_boundary TEXT NOT NULL CHECK(public.canonical_learning_text_valid(adoption_boundary,1000)),actor_user_id UUID NOT NULL,membership_id UUID NOT NULL,auth_session_id UUID NOT NULL,reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)),confirmed BOOLEAN NOT NULL CHECK(confirmed),confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-imported-material-quantity-observation-v1'),calculation_version TEXT NOT NULL CHECK(calculation_version='m25-imported-material-quantity-variance-v1'),request_key_hash TEXT NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'),request_digest TEXT NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),canonical_digest TEXT NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'),created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),UNIQUE(organization_id,source_key,estimate_id,external_job_reference,revision),UNIQUE(organization_id,source_key,estimate_id,external_job_reference,source_digest,consent_id),UNIQUE(organization_id,actor_user_id,request_key_hash),UNIQUE(organization_id,source_key,id),FOREIGN KEY(organization_id,estimate_id)REFERENCES public.canonical_estimates(organization_id,id),FOREIGN KEY(organization_id,source_key,previous_id)REFERENCES public.canonical_external_material_quantity_observations(organization_id,source_key,id),FOREIGN KEY(organization_id,source_key,consent_id)REFERENCES public.canonical_external_material_outcome_consents(organization_id,source_key,id),FOREIGN KEY(organization_id,membership_id)REFERENCES public.organization_memberships(organization_id,id),FOREIGN KEY(organization_id,actor_user_id,auth_session_id)REFERENCES public.auth_sessions(organization_id,user_id,id),CHECK((revision=1 AND previous_id IS NULL)OR(revision>1 AND previous_id IS NOT NULL)),CHECK(public.canonical_field_evidence_object_keys_exact(source_manifest,ARRAY['estimate','estimateRevision','materialPlan','sourceConsent','jobMatch','materialMatches','bindings','importedRecords'])),CHECK(rtrim(source_digest)=public.canonical_completion_digest(source_manifest))
);
CREATE TRIGGER canonical_external_material_outcome_consents_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_external_material_outcome_consents FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_external_material_immutable();
CREATE TRIGGER canonical_external_material_quantity_observations_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_external_material_quantity_observations FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_external_material_immutable();

CREATE FUNCTION public.canonical_imported_material_quantity_projection(v public.canonical_external_material_quantity_observations)RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT jsonb_build_object('id',v.id,'sourceKey',v.source_key,'estimateId',v.estimate_id,'externalJobReference',v.external_job_reference,'revision',v.revision,'previousId',v.previous_id,'consent',jsonb_build_object('id',v.consent_id,'revision',v.consent_revision,'digest',rtrim(v.consent_digest)),'sourceManifest',v.source_manifest,'sourceDigest',rtrim(v.source_digest),'result',v.result,'scopeNote',v.scope_note,'adoptionBoundary',v.adoption_boundary,'reason',v.reason,'confirmed',v.confirmed,'confirmationVersion',v.confirmation_version,'calculationVersion',v.calculation_version,'digest',rtrim(v.canonical_digest),'createdAt',v.created_at) $$;

CREATE FUNCTION public.canonical_imported_material_quantity_observe(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,estimate UUID,job_reference_value TEXT,expected_consent_revision BIGINT,expected_consent_digest TEXT,bindings JSONB,reason_value TEXT,confirmed_value BOOLEAN,confirmation_version_value TEXT)RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;source_consent public.canonical_external_material_import_consents%ROWTYPE;consent_row public.canonical_external_material_outcome_consents%ROWTYPE;current_row public.canonical_external_material_quantity_observations%ROWTYPE;replay public.canonical_external_material_quantity_observations%ROWTYPE;inserted public.canonical_external_material_quantity_observations%ROWTYPE;basis JSONB;key_hash TEXT;request_hash TEXT;digest_value TEXT;next_revision BIGINT;fresh BOOLEAN;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Imported material outcome review restricted' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR expected_consent_revision IS NULL OR expected_consent_revision NOT BETWEEN 1 AND 10000 OR expected_consent_digest IS NULL OR expected_consent_digest!~'^[0-9a-f]{64}$' OR public.canonical_imported_material_bindings_valid(bindings) IS NOT TRUE OR public.canonical_learning_text_valid(reason_value,2000) IS NOT TRUE OR confirmed_value IS DISTINCT FROM TRUE OR confirmation_version_value IS DISTINCT FROM 'm25-imported-material-quantity-observation-v1' THEN RAISE EXCEPTION 'Imported material outcome input invalid' USING ERRCODE='22023';END IF;
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'estimateId',estimate,'externalJobReference',job_reference_value,'consentRevision',expected_consent_revision,'consentDigest',expected_consent_digest,'bindings',bindings,'reason',reason_value,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value));
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':imported-material-quantity:'||source_value||':'||estimate::text||':'||job_reference_value,0));
 SELECT * INTO replay FROM public.canonical_external_material_quantity_observations WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;
 IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Imported material outcome key conflict' USING ERRCODE='23505';END IF;SELECT * INTO source_consent FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;SELECT * INTO consent_row FROM public.canonical_external_material_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_material_quantity_variance_v1' ORDER BY revision DESC LIMIT 1;IF source_consent.id IS NULL OR source_consent.action<>'grant' OR consent_row.id IS NULL OR consent_row.action<>'grant' OR consent_row.source_consent_id<>source_consent.id OR replay.consent_id<>consent_row.id THEN RETURN jsonb_build_object('observation',jsonb_build_object('id',replay.id,'revision',replay.revision,'fresh',FALSE,'advisoryAvailable',FALSE,'hiddenByConsent',TRUE),'replayed',TRUE);END IF;BEGIN basis:=public.canonical_imported_material_outcome_basis(org,source_value,estimate,job_reference_value,replay.source_manifest->'bindings');fresh:=rtrim(replay.source_digest)=basis->>'sourceDigest';EXCEPTION WHEN SQLSTATE 'P0002' THEN fresh:=FALSE;END;RETURN jsonb_build_object('observation',public.canonical_imported_material_quantity_projection(replay)||jsonb_build_object('fresh',fresh,'advisoryAvailable',fresh AND replay.result->>'advisoryCode' IS NOT NULL,'result',CASE WHEN fresh THEN replay.result ELSE jsonb_build_object('advisoryCode',NULL,'advisoryMessage','Refresh current evidence before using this observation.','lines','[]'::jsonb)END),'replayed',TRUE);END IF;
 SELECT * INTO source_consent FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1 FOR SHARE;SELECT * INTO consent_row FROM public.canonical_external_material_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_material_quantity_variance_v1' ORDER BY revision DESC LIMIT 1 FOR SHARE;
 IF source_consent.id IS NULL OR source_consent.action<>'grant' OR consent_row.id IS NULL OR consent_row.action<>'grant' OR consent_row.source_consent_id<>source_consent.id OR rtrim(consent_row.source_consent_digest)<>rtrim(source_consent.canonical_digest) OR consent_row.revision<>expected_consent_revision OR rtrim(consent_row.canonical_digest)<>expected_consent_digest THEN RAISE EXCEPTION 'Imported material outcome consent changed' USING ERRCODE='40001';END IF;
 basis:=public.canonical_imported_material_outcome_basis(org,source_value,estimate,job_reference_value,bindings);SELECT * INTO current_row FROM public.canonical_external_material_quantity_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate AND external_job_reference=job_reference_value ORDER BY revision DESC LIMIT 1 FOR UPDATE;IF current_row.id IS NOT NULL AND rtrim(current_row.source_digest)=basis->>'sourceDigest' AND current_row.consent_id=consent_row.id THEN RAISE EXCEPTION 'Current imported material outcome already recorded' USING ERRCODE='22023',CONSTRAINT='imported_material_outcome_already_current';END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'estimateId',estimate,'externalJobReference',job_reference_value,'revision',next_revision,'previousId',current_row.id,'consentId',consent_row.id,'sourceDigest',basis->>'sourceDigest','result',basis->'result','actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'reason',reason_value,'confirmationVersion',confirmation_version_value,'requestDigest',request_hash));
 INSERT INTO public.canonical_external_material_quantity_observations(organization_id,source_key,estimate_id,external_job_reference,revision,previous_id,consent_id,consent_revision,consent_digest,source_manifest,source_digest,result,scope_note,adoption_boundary,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,calculation_version,request_key_hash,request_digest,canonical_digest)VALUES(org,source_value,estimate,job_reference_value,next_revision,current_row.id,consent_row.id,consent_row.revision,rtrim(consent_row.canonical_digest),basis->'sourceManifest',basis->>'sourceDigest',basis->'result',basis->>'scopeNote',basis->>'adoptionBoundary',actor,(authority->>'membershipId')::uuid,session_value,reason_value,confirmed_value,confirmation_version_value,'m25-imported-material-quantity-variance-v1',key_hash,request_hash,digest_value)RETURNING * INTO inserted;RETURN jsonb_build_object('observation',public.canonical_imported_material_quantity_projection(inserted)||jsonb_build_object('fresh',TRUE,'advisoryAvailable',inserted.result->>'advisoryCode' IS NOT NULL),'replayed',FALSE);
END $$;

CREATE FUNCTION public.canonical_imported_material_quantity_read(org UUID,actor UUID,role_value TEXT,session_value UUID,source_value TEXT,estimate UUID)RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_consent public.canonical_external_material_import_consents%ROWTYPE;consent_row public.canonical_external_material_outcome_consents%ROWTYPE;current_row public.canonical_external_material_quantity_observations%ROWTYPE;basis JSONB;fresh BOOLEAN;history JSONB;total BIGINT;
BEGIN IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Imported material outcome review restricted' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);SELECT * INTO source_consent FROM public.canonical_external_material_import_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1;SELECT * INTO consent_row FROM public.canonical_external_material_outcome_consents WHERE organization_id=org AND source_key=source_value AND purpose='imported_material_quantity_variance_v1' ORDER BY revision DESC LIMIT 1;IF source_consent.id IS NULL OR source_consent.action<>'grant' OR consent_row.id IS NULL OR consent_row.action<>'grant' OR consent_row.source_consent_id<>source_consent.id OR rtrim(consent_row.source_consent_digest)<>rtrim(source_consent.canonical_digest) THEN RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',FALSE,'current',NULL,'history','[]'::jsonb,'total',0,'truncated',FALSE,'blockedReason','Imported material outcome consent is not active for the current source permission.');END IF;
 SELECT * INTO current_row FROM public.canonical_external_material_quantity_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate AND consent_id=consent_row.id ORDER BY revision DESC LIMIT 1;IF NOT FOUND THEN RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',TRUE,'consent',public.canonical_imported_material_outcome_consent_projection(consent_row),'current',NULL,'history','[]'::jsonb,'total',0,'truncated',FALSE,'refreshRequired',TRUE);END IF;
 BEGIN basis:=public.canonical_imported_material_outcome_basis(org,source_value,estimate,current_row.external_job_reference,current_row.source_manifest->'bindings');fresh:=rtrim(current_row.source_digest)=basis->>'sourceDigest';EXCEPTION WHEN SQLSTATE 'P0002' THEN fresh:=FALSE;END;SELECT count(*)INTO total FROM public.canonical_external_material_quantity_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate AND consent_id=consent_row.id;SELECT COALESCE(jsonb_agg(public.canonical_imported_material_quantity_projection(x)||jsonb_build_object('fresh',x.id=current_row.id AND fresh,'advisoryAvailable',x.id=current_row.id AND fresh AND x.result->>'advisoryCode' IS NOT NULL,'result',CASE WHEN x.id=current_row.id AND fresh THEN x.result ELSE jsonb_build_object('advisoryCode',NULL,'advisoryMessage','Refresh current evidence before using this observation.','lines','[]'::jsonb)END)ORDER BY revision DESC),'[]'::jsonb)INTO history FROM(SELECT * FROM public.canonical_external_material_quantity_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate AND consent_id=consent_row.id ORDER BY revision DESC LIMIT 20)x;RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',TRUE,'consent',public.canonical_imported_material_outcome_consent_projection(consent_row),'current',public.canonical_imported_material_quantity_projection(current_row)||jsonb_build_object('fresh',fresh,'advisoryAvailable',fresh AND current_row.result->>'advisoryCode' IS NOT NULL,'result',CASE WHEN fresh THEN current_row.result ELSE jsonb_build_object('advisoryCode',NULL,'advisoryMessage','Refresh current evidence before using this observation.','lines','[]'::jsonb)END),'history',history,'total',total,'truncated',total>20,'refreshRequired',NOT fresh);
END $$;

REVOKE ALL ON TABLE public.canonical_external_material_outcome_consents,public.canonical_external_material_quantity_observations FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_material_outcome_consent_projection(public.canonical_external_material_outcome_consents) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_material_bindings_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_material_dimension(NUMERIC,TEXT,BOOLEAN,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_material_outcome_basis(UUID,TEXT,UUID,TEXT,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_material_quantity_projection(public.canonical_external_material_quantity_observations) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_material_outcome_consent_read(UUID,UUID,TEXT,UUID,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_material_outcome_consent_mutate(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_material_quantity_observe(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,UUID,TEXT,BIGINT,TEXT,JSONB,TEXT,BOOLEAN,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_imported_material_quantity_read(UUID,UUID,TEXT,UUID,TEXT,UUID) FROM PUBLIC;
