-- Mission 25 Part 12H: tenant-private external financial outcome observations.
-- This authority records advice only. It creates no native NorthStar financial record.

CREATE TABLE public.canonical_external_financial_outcome_consents (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES public.organizations(id),
 source_key TEXT NOT NULL CHECK(source_key~'^[a-z0-9][a-z0-9._-]{1,63}$'), revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000), previous_id UUID,
 action TEXT NOT NULL CHECK(action IN ('grant','revoke')), source_consent_id UUID, source_consent_revision BIGINT, source_consent_digest TEXT,
 actor_user_id UUID NOT NULL, membership_id UUID NOT NULL, auth_session_id UUID NOT NULL,
 reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)), confirmed BOOLEAN NOT NULL CHECK(confirmed),
 confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-external-financial-outcome-consent-v1'),
 request_key_hash TEXT NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'), request_digest TEXT NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),
 canonical_digest TEXT NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'), created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(organization_id,source_key,revision), UNIQUE(organization_id,actor_user_id,request_key_hash), UNIQUE(organization_id,source_key,id),
 FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id),
 FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id),
 FOREIGN KEY(organization_id,source_key,previous_id) REFERENCES public.canonical_external_financial_outcome_consents(organization_id,source_key,id),
 CHECK((revision=1 AND previous_id IS NULL) OR (revision>1 AND previous_id IS NOT NULL)),
 CHECK((action='grant' AND source_consent_id IS NOT NULL AND source_consent_revision BETWEEN 1 AND 10000 AND source_consent_digest~'^[0-9a-f]{64}$')
  OR (action='revoke' AND source_consent_id IS NULL AND source_consent_revision IS NULL AND source_consent_digest IS NULL))
);

CREATE TABLE public.canonical_external_financial_outcome_observations (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES public.organizations(id),
 source_key TEXT NOT NULL CHECK(source_key~'^[a-z0-9][a-z0-9._-]{1,63}$'), estimate_id UUID NOT NULL,
 revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000), previous_id UUID,
 consent_id UUID NOT NULL, consent_revision BIGINT NOT NULL CHECK(consent_revision BETWEEN 1 AND 10000), consent_digest TEXT NOT NULL CHECK(consent_digest~'^[0-9a-f]{64}$'),
 target_digest TEXT NOT NULL CHECK(target_digest~'^[0-9a-f]{64}$'),
 source_manifest JSONB NOT NULL CHECK(jsonb_typeof(source_manifest)='array'),
 reference_matches JSONB NOT NULL CHECK(jsonb_typeof(reference_matches)='array'),
 source_digest TEXT NOT NULL CHECK(source_digest~'^[0-9a-f]{64}$'), outcomes JSONB NOT NULL,
 actor_user_id UUID NOT NULL, membership_id UUID NOT NULL, auth_session_id UUID NOT NULL,
 reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)), confirmed BOOLEAN NOT NULL CHECK(confirmed),
 confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-external-financial-outcome-observation-v1'),
 calculation_version TEXT NOT NULL CHECK(calculation_version='m25-external-financial-outcome-v1'),
 request_key_hash TEXT NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'), request_digest TEXT NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),
 canonical_digest TEXT NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'), created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(organization_id,source_key,estimate_id,revision), UNIQUE(organization_id,actor_user_id,request_key_hash), UNIQUE(organization_id,source_key,estimate_id,id),
 FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id),
 FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id),
 FOREIGN KEY(organization_id,source_key,consent_id) REFERENCES public.canonical_external_financial_outcome_consents(organization_id,source_key,id),
 FOREIGN KEY(organization_id,source_key,estimate_id,previous_id) REFERENCES public.canonical_external_financial_outcome_observations(organization_id,source_key,estimate_id,id),
 CHECK((revision=1 AND previous_id IS NULL) OR (revision>1 AND previous_id IS NOT NULL))
);
CREATE INDEX canonical_external_financial_outcomes_current_idx ON public.canonical_external_financial_outcome_observations(organization_id,source_key,estimate_id,revision DESC);

CREATE FUNCTION public.canonical_external_financial_outcome_immutable() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN RAISE EXCEPTION 'Financial outcome history is immutable' USING ERRCODE='23514'; END $$;
CREATE TRIGGER canonical_external_financial_outcome_consents_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_external_financial_outcome_consents FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_external_financial_outcome_immutable();
CREATE TRIGGER canonical_external_financial_outcome_observations_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_external_financial_outcome_observations FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_external_financial_outcome_immutable();

CREATE FUNCTION public.canonical_external_financial_outcome_amount_valid(value JSONB,signed_value BOOLEAN) RETURNS BOOLEAN LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_typeof(value)='object' AND public.canonical_field_evidence_object_keys_exact(value,ARRAY['status','recordCount','amount','currency','reason'])
 AND ((value->>'status'='unavailable' AND value->'recordCount'='null'::jsonb AND value->'amount'='null'::jsonb AND value->'currency'='null'::jsonb AND jsonb_typeof(value->'reason')='string' AND public.canonical_learning_text_valid(value->>'reason',500))
 OR (value->>'status'='recorded' AND jsonb_typeof(value->'recordCount')='number' AND value->>'recordCount'~'^[1-9][0-9]{0,5}$'
  AND jsonb_typeof(value->'amount')='string' AND ((signed_value AND value->>'amount'~'^-?(0|[1-9][0-9]{0,14})(\.[0-9]{1,6})?$') OR (NOT signed_value AND value->>'amount'~'^(0|[1-9][0-9]{0,14})(\.[0-9]{1,6})?$'))
  AND jsonb_typeof(value->'currency')='string' AND value->>'currency'~'^[A-Z]{3}$' AND value->'reason'='null'::jsonb)) $$;

CREATE FUNCTION public.canonical_external_financial_outcomes_valid(value JSONB) RETURNS BOOLEAN LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_typeof(value)='object' AND public.canonical_field_evidence_object_keys_exact(value,ARRAY['revenue','collection','realizedCost','margin'])
 AND public.canonical_external_financial_outcome_amount_valid(value->'revenue',FALSE)
 AND public.canonical_external_financial_outcome_amount_valid(value->'collection',FALSE)
 AND public.canonical_external_financial_outcome_amount_valid(value->'realizedCost',FALSE)
 AND jsonb_typeof(value->'margin')='object' AND public.canonical_field_evidence_object_keys_exact(value->'margin',ARRAY['status','revenueRecordCount','costRecordCount','amount','percent','currency','reason'])
 AND ((value->'margin'->>'status'='unavailable' AND value->'margin'->'revenueRecordCount'='null'::jsonb AND value->'margin'->'costRecordCount'='null'::jsonb AND value->'margin'->'amount'='null'::jsonb AND value->'margin'->'percent'='null'::jsonb AND value->'margin'->'currency'='null'::jsonb AND jsonb_typeof(value->'margin'->'reason')='string' AND public.canonical_learning_text_valid(value->'margin'->>'reason',500))
  OR (value->'margin'->>'status'='recorded' AND jsonb_typeof(value->'margin'->'revenueRecordCount')='number' AND value->'margin'->>'revenueRecordCount'~'^[1-9][0-9]{0,5}$'
   AND jsonb_typeof(value->'margin'->'costRecordCount')='number' AND value->'margin'->>'costRecordCount'~'^[1-9][0-9]{0,5}$'
   AND jsonb_typeof(value->'margin'->'amount')='string' AND value->'margin'->>'amount'~'^-?(0|[1-9][0-9]{0,14})(\.[0-9]{1,6})?$'
   AND jsonb_typeof(value->'margin'->'percent')='string' AND value->'margin'->>'percent'~'^-?(0|[1-9][0-9]{0,8})(\.[0-9]{1,6})?$'
   AND jsonb_typeof(value->'margin'->'currency')='string' AND value->'margin'->>'currency'~'^[A-Z]{3}$' AND value->'margin'->'reason'='null'::jsonb)) $$;
ALTER TABLE public.canonical_external_financial_outcome_observations ADD CONSTRAINT canonical_external_financial_outcomes_valid_check CHECK(public.canonical_external_financial_outcomes_valid(outcomes));

CREATE FUNCTION public.canonical_external_financial_outcome_unavailable(reason_value TEXT) RETURNS JSONB LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_build_object(
  'revenue',jsonb_build_object('status','unavailable','recordCount',NULL,'amount',NULL,'currency',NULL,'reason',reason_value),
  'collection',jsonb_build_object('status','unavailable','recordCount',NULL,'amount',NULL,'currency',NULL,'reason',reason_value),
  'realizedCost',jsonb_build_object('status','unavailable','recordCount',NULL,'amount',NULL,'currency',NULL,'reason',reason_value),
  'margin',jsonb_build_object('status','unavailable','revenueRecordCount',NULL,'costRecordCount',NULL,'amount',NULL,'percent',NULL,'currency',NULL,'reason',reason_value)) $$;

CREATE FUNCTION public.canonical_external_financial_outcome_consent_projection(value public.canonical_external_financial_outcome_consents,source_current JSONB) RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_build_object('id',value.id,'sourceKey',value.source_key,'revision',value.revision,'previousId',value.previous_id,'action',value.action,
  'sourcePermissionCurrent',COALESCE(value.action='grant' AND source_current->>'id'=value.source_consent_id::text AND source_current->>'digest'=rtrim(value.source_consent_digest),FALSE),
  'reason',value.reason,'confirmed',value.confirmed,'confirmationVersion',value.confirmation_version,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at) $$;

CREATE FUNCTION public.canonical_external_financial_outcome_consent_guard() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_current JSONB; previous_row public.canonical_external_financial_outcome_consents%ROWTYPE; expected_digest TEXT;
BEGIN
 source_current:=public.canonical_external_business_source_consent_basis(NEW.organization_id,'financial',NEW.source_key);
 IF NEW.action='grant' AND (source_current IS NULL OR NEW.source_consent_id<>(source_current->>'id')::uuid OR NEW.source_consent_revision<>(source_current->>'revision')::bigint OR rtrim(NEW.source_consent_digest)<>source_current->>'digest') THEN RAISE EXCEPTION 'Financial outcome source permission invalid' USING ERRCODE='23514'; END IF;
 IF NEW.revision>1 THEN SELECT * INTO previous_row FROM public.canonical_external_financial_outcome_consents WHERE organization_id=NEW.organization_id AND source_key=NEW.source_key AND id=NEW.previous_id; IF previous_row.id IS NULL OR previous_row.revision+1<>NEW.revision THEN RAISE EXCEPTION 'Financial outcome permission revision invalid' USING ERRCODE='23514'; END IF; END IF;
 expected_digest:=public.canonical_completion_digest(jsonb_build_object('organizationId',NEW.organization_id,'sourceKey',NEW.source_key,'revision',NEW.revision,'previousId',NEW.previous_id,'action',NEW.action,'sourceConsentId',NEW.source_consent_id,'sourceConsentRevision',NEW.source_consent_revision,'sourceConsentDigest',rtrim(NEW.source_consent_digest),'actorUserId',NEW.actor_user_id,'reason',NEW.reason,'confirmationVersion',NEW.confirmation_version,'requestDigest',rtrim(NEW.request_digest)));
 IF rtrim(NEW.canonical_digest)<>expected_digest THEN RAISE EXCEPTION 'Financial outcome permission digest invalid' USING ERRCODE='23514'; END IF; RETURN NEW;
END $$;
CREATE TRIGGER canonical_external_financial_outcome_consent_guard BEFORE INSERT ON public.canonical_external_financial_outcome_consents FOR EACH ROW EXECUTE FUNCTION public.canonical_external_financial_outcome_consent_guard();

CREATE FUNCTION public.canonical_external_financial_outcome_basis(org UUID,source_value TEXT,estimate_value UUID) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_consent JSONB; target_basis JSONB; source_manifest JSONB; reference_matches JSONB; linked_total BIGINT; current_total BIGINT;
 revenue_count BIGINT; revenue_invalid BIGINT; revenue_currencies BIGINT; revenue_amount NUMERIC; revenue_currency TEXT;
 collection_count BIGINT; collection_invalid BIGINT; collection_currencies BIGINT; collection_amount NUMERIC; collection_currency TEXT;
 cost_count BIGINT; cost_invalid BIGINT; cost_currencies BIGINT; cost_amount NUMERIC; cost_currency TEXT; unknown_accounting BIGINT; unavailable_accounting BIGINT; unavailable_collection BIGINT;
 revenue_value JSONB; collection_value JSONB; cost_value JSONB; margin_value JSONB; margin_amount NUMERIC; margin_percent NUMERIC; outcomes_value JSONB; digest_value TEXT;
BEGIN
 source_consent:=public.canonical_external_business_source_consent_basis(org,'financial',source_value); IF source_consent IS NULL THEN RETURN NULL; END IF;
 target_basis:=public.canonical_external_business_reference_target_basis(org,'estimate',estimate_value); IF target_basis IS NULL THEN RETURN NULL; END IF;
 WITH latest_matches AS MATERIALIZED(
  SELECT DISTINCT ON(reference_kind,external_reference)* FROM public.canonical_external_business_reference_matches
  WHERE organization_id=org AND source_class='financial' AND source_key=source_value AND consent_id=(source_consent->>'id')::uuid AND reference_kind IN('collection','accounting_entry')
  ORDER BY reference_kind,external_reference,revision DESC
 ), linked AS MATERIALIZED(
  SELECT * FROM latest_matches WHERE action='link' AND target_kind='estimate' AND target_id=estimate_value
 ), details AS(
  SELECT m.reference_kind,m.external_reference,m.id match_id,m.revision match_revision,rtrim(m.canonical_digest) match_digest,m.source_digest match_source_digest,m.target_digest match_target_digest,
   s.source_digest,s.record_count,s.manifest,
   COALESCE(s.source_digest IS NOT NULL AND s.record_count=1 AND m.source_digest=s.source_digest AND m.target_digest=target_basis->>'digest',FALSE) current
  FROM linked m LEFT JOIN LATERAL(SELECT * FROM public.canonical_external_business_source_references(org,'financial',source_value)x WHERE x.reference_kind=m.reference_kind AND x.external_reference=m.external_reference)s ON TRUE
 )
 SELECT count(*),count(*)FILTER(WHERE current),
  COALESCE(jsonb_agg(jsonb_build_object('referenceKind',reference_kind,'externalReference',external_reference,'recordCount',record_count,'sourceDigest',source_digest,'matchId',match_id,'matchRevision',match_revision,'matchDigest',match_digest,'current',current)ORDER BY reference_kind,external_reference),'[]'::jsonb),
  COALESCE(jsonb_agg(jsonb_build_object('referenceKind',reference_kind,'externalReference',external_reference,'manifest',COALESCE(manifest,'[]'::jsonb))ORDER BY reference_kind,external_reference),'[]'::jsonb)
 INTO linked_total,current_total,reference_matches,source_manifest FROM details;
 IF linked_total=0 OR current_total=0 THEN RETURN NULL; END IF;

 WITH latest_matches AS MATERIALIZED(
  SELECT DISTINCT ON(reference_kind,external_reference)* FROM public.canonical_external_business_reference_matches
  WHERE organization_id=org AND source_class='financial' AND source_key=source_value AND consent_id=(source_consent->>'id')::uuid AND reference_kind IN('collection','accounting_entry')
  ORDER BY reference_kind,external_reference,revision DESC
 ), linked AS MATERIALIZED(SELECT * FROM latest_matches WHERE action='link' AND target_kind='estimate' AND target_id=estimate_value),
 current_records AS MATERIALIZED(SELECT DISTINCT ON(external_record_id)* FROM public.canonical_external_financial_import_records WHERE organization_id=org AND source_key=source_value AND consent_id=(source_consent->>'id')::uuid ORDER BY external_record_id,revision DESC),
 relevant AS MATERIALIZED(
  SELECT r.*,m.reference_kind,m.external_reference,m.source_digest match_source_digest,m.target_digest match_target_digest,s.source_digest,s.record_count,
   COALESCE(s.source_digest IS NOT NULL AND s.record_count=1 AND m.source_digest=s.source_digest AND m.target_digest=target_basis->>'digest',FALSE) current
  FROM linked m LEFT JOIN LATERAL(SELECT * FROM public.canonical_external_business_source_references(org,'financial',source_value)x WHERE x.reference_kind=m.reference_kind AND x.external_reference=m.external_reference)s ON TRUE
  LEFT JOIN current_records r ON r.state='active' AND ((m.reference_kind='collection' AND r.record_type='collection' AND r.collection_reference=m.external_reference) OR (m.reference_kind='accounting_entry' AND r.record_type='accounting_entry' AND r.accounting_reference=m.external_reference))
 )
 SELECT
  count(*)FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'basis'='revenue'),
  count(*)FILTER(WHERE reference_kind='accounting_entry' AND ((id IS NULL AND NOT current) OR amount_claim->>'status'='unavailable' OR amount_claim->>'basis'='unknown' OR (amount_claim->>'basis'='revenue' AND (NOT current OR record_state<>'posted' OR amount_claim->>'status'<>'recorded')))),
  count(DISTINCT amount_claim->>'currency')FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'basis'='revenue' AND amount_claim->>'status'='recorded'),
  sum((amount_claim->>'amount')::numeric)FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'basis'='revenue' AND amount_claim->>'status'='recorded'),
  min(amount_claim->>'currency')FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'basis'='revenue' AND amount_claim->>'status'='recorded'),
  count(*)FILTER(WHERE reference_kind='collection' AND amount_claim->>'basis'='amount_collected'),
  count(*)FILTER(WHERE reference_kind='collection' AND (NOT current OR amount_claim->>'status'='unavailable' OR (amount_claim->>'basis'='amount_collected' AND amount_claim->>'status'<>'recorded'))),
  count(DISTINCT amount_claim->>'currency')FILTER(WHERE reference_kind='collection' AND amount_claim->>'basis'='amount_collected' AND amount_claim->>'status'='recorded'),
  sum((amount_claim->>'amount')::numeric)FILTER(WHERE reference_kind='collection' AND amount_claim->>'basis'='amount_collected' AND amount_claim->>'status'='recorded'),
  min(amount_claim->>'currency')FILTER(WHERE reference_kind='collection' AND amount_claim->>'basis'='amount_collected' AND amount_claim->>'status'='recorded'),
  count(*)FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'basis' IN('direct_cost','overhead_cost','other_cost')),
  count(*)FILTER(WHERE reference_kind='accounting_entry' AND ((id IS NULL AND NOT current) OR amount_claim->>'status'='unavailable' OR amount_claim->>'basis'='unknown' OR (amount_claim->>'basis' IN('direct_cost','overhead_cost','other_cost') AND (NOT current OR record_state<>'posted' OR amount_claim->>'status'<>'recorded')))),
  count(DISTINCT amount_claim->>'currency')FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'basis' IN('direct_cost','overhead_cost','other_cost') AND amount_claim->>'status'='recorded'),
  sum((amount_claim->>'amount')::numeric)FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'basis' IN('direct_cost','overhead_cost','other_cost') AND amount_claim->>'status'='recorded'),
  min(amount_claim->>'currency')FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'basis' IN('direct_cost','overhead_cost','other_cost') AND amount_claim->>'status'='recorded'),
  count(*)FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'basis'='unknown'),
  count(*)FILTER(WHERE reference_kind='accounting_entry' AND amount_claim->>'status'='unavailable'),
  count(*)FILTER(WHERE reference_kind='collection' AND amount_claim->>'status'='unavailable')
 INTO revenue_count,revenue_invalid,revenue_currencies,revenue_amount,revenue_currency,collection_count,collection_invalid,collection_currencies,collection_amount,collection_currency,cost_count,cost_invalid,cost_currencies,cost_amount,cost_currency,unknown_accounting,unavailable_accounting,unavailable_collection
 FROM relevant;

 IF revenue_count>0 AND revenue_invalid=0 AND revenue_currencies=1 THEN revenue_value:=jsonb_build_object('status','recorded','recordCount',revenue_count,'amount',revenue_amount::text,'currency',revenue_currency,'reason',NULL);
 ELSE revenue_value:=jsonb_build_object('status','unavailable','recordCount',NULL,'amount',NULL,'currency',NULL,'reason',CASE WHEN unavailable_accounting>0 THEN 'A reviewed accounting entry has no recorded amount or category.' WHEN unknown_accounting>0 THEN 'An accounting entry does not identify whether it is revenue or cost.' WHEN revenue_count=0 THEN 'No posted revenue entry is recorded for this estimate.' ELSE 'Revenue entries need one current reviewed record, a posted state, an amount and one currency.' END); END IF;
 IF collection_count>0 AND collection_invalid=0 AND collection_currencies=1 THEN collection_value:=jsonb_build_object('status','recorded','recordCount',collection_count,'amount',collection_amount::text,'currency',collection_currency,'reason',NULL);
 ELSE collection_value:=jsonb_build_object('status','unavailable','recordCount',NULL,'amount',NULL,'currency',NULL,'reason',CASE WHEN unavailable_collection>0 THEN 'A reviewed collection entry has no recorded amount.' WHEN collection_count=0 THEN 'No collected amount is recorded for this estimate.' ELSE 'Collection entries need one current reviewed record, an amount and one currency.' END); END IF;
 IF cost_count>0 AND cost_invalid=0 AND cost_currencies=1 THEN cost_value:=jsonb_build_object('status','recorded','recordCount',cost_count,'amount',cost_amount::text,'currency',cost_currency,'reason',NULL);
 ELSE cost_value:=jsonb_build_object('status','unavailable','recordCount',NULL,'amount',NULL,'currency',NULL,'reason',CASE WHEN unavailable_accounting>0 THEN 'A reviewed accounting entry has no recorded amount or category.' WHEN unknown_accounting>0 THEN 'An accounting entry does not identify whether it is revenue or cost.' WHEN cost_count=0 THEN 'No posted realized-cost entry is recorded for this estimate.' ELSE 'Realized-cost entries need one current reviewed record, a posted state, an amount and one currency.' END); END IF;
 IF revenue_value->>'status'='recorded' AND cost_value->>'status'='recorded' AND revenue_currency=cost_currency AND revenue_amount>0 THEN margin_amount:=revenue_amount-cost_amount; margin_percent:=round((margin_amount/revenue_amount)*100,6); IF abs(margin_percent)<=999999999 THEN margin_value:=jsonb_build_object('status','recorded','revenueRecordCount',revenue_count,'costRecordCount',cost_count,'amount',margin_amount::text,'percent',margin_percent::text,'currency',revenue_currency,'reason',NULL); ELSE margin_value:=jsonb_build_object('status','unavailable','revenueRecordCount',NULL,'costRecordCount',NULL,'amount',NULL,'percent',NULL,'currency',NULL,'reason','The recorded margin percentage is outside the bounded review range.'); END IF;
 ELSE margin_value:=jsonb_build_object('status','unavailable','revenueRecordCount',NULL,'costRecordCount',NULL,'amount',NULL,'percent',NULL,'currency',NULL,'reason',CASE WHEN revenue_value->>'status'<>'recorded' OR cost_value->>'status'<>'recorded' THEN 'Recorded revenue and realized cost are both required for margin.' WHEN revenue_currency<>cost_currency THEN 'Revenue and realized cost use different currencies.' ELSE 'Margin percentage requires recorded revenue greater than zero.' END); END IF;
 outcomes_value:=jsonb_build_object('revenue',revenue_value,'collection',collection_value,'realizedCost',cost_value,'margin',margin_value);
 digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'sourceConsent',source_consent,'estimateId',estimate_value,'targetDigest',target_basis->>'digest','sourceManifest',source_manifest,'referenceMatches',reference_matches,'outcomes',outcomes_value));
 RETURN jsonb_build_object('sourceConsent',source_consent,'targetDigest',target_basis->>'digest','sourceManifest',source_manifest,'referenceMatches',reference_matches,'outcomes',outcomes_value,'sourceDigest',digest_value);
END $$;

CREATE FUNCTION public.canonical_external_financial_outcome_consent_read(org UUID,actor UUID,role_value TEXT,session_value UUID,source_value TEXT) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE current_row public.canonical_external_financial_outcome_consents%ROWTYPE; source_current JSONB; history JSONB; total BIGINT;
BEGIN IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Financial outcome learning restricted' USING ERRCODE='42501'; END IF; PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'Financial outcome source invalid' USING ERRCODE='22023'; END IF; source_current:=public.canonical_external_business_source_consent_basis(org,'financial',source_value);
 SELECT * INTO current_row FROM public.canonical_external_financial_outcome_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1; SELECT count(*) INTO total FROM public.canonical_external_financial_outcome_consents WHERE organization_id=org AND source_key=source_value;
 SELECT COALESCE(jsonb_agg(public.canonical_external_financial_outcome_consent_projection(x,source_current)ORDER BY revision DESC),'[]'::jsonb) INTO history FROM(SELECT * FROM public.canonical_external_financial_outcome_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 20)x;
 RETURN jsonb_build_object('sourceKey',source_value,'sourcePermissionAvailable',source_current IS NOT NULL,'current',CASE WHEN current_row.id IS NULL THEN NULL ELSE public.canonical_external_financial_outcome_consent_projection(current_row,source_current)END,'history',history,'total',total,'truncated',total>20,'consumptionBoundary','Permission allows advisory comparisons only. It does not create or change financial records.'); END $$;

CREATE FUNCTION public.canonical_external_financial_outcome_consent_mutate(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,body JSONB) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB; source_current JSONB; current_row public.canonical_external_financial_outcome_consents%ROWTYPE; replay public.canonical_external_financial_outcome_consents%ROWTYPE; inserted public.canonical_external_financial_outcome_consents%ROWTYPE; key_hash TEXT; request_hash TEXT; digest_value TEXT; next_revision BIGINT;
BEGIN IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001'; END IF; IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Financial outcome learning restricted' USING ERRCODE='42501'; END IF; PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE; IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501'; END IF; authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR octet_length(body::text)>8192 OR public.canonical_field_evidence_object_keys_exact(body,ARRAY['action','expectedRevision','expectedDigest','reason','confirmed','confirmationVersion']) IS NOT TRUE OR body->>'action' NOT IN('grant','revoke') OR jsonb_typeof(body->'expectedRevision')<>'number' OR body->>'expectedRevision'!~'^(0|[1-9][0-9]{0,4})$' OR NOT(body->>'expectedDigest'='none' OR body->>'expectedDigest'~'^[0-9a-f]{64}$') OR ((body->>'expectedRevision')::bigint=0)<>(body->>'expectedDigest'='none') OR public.canonical_learning_text_valid(body->>'reason',2000) IS NOT TRUE OR body->'confirmed'<>'true'::jsonb OR body->>'confirmationVersion'<>'m25-external-financial-outcome-consent-v1' THEN RAISE EXCEPTION 'Financial outcome permission details invalid' USING ERRCODE='22023'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':external-financial-outcome:'||source_value,0)); key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex'); request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'body',body)); SELECT * INTO replay FROM public.canonical_external_financial_outcome_consents WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash; IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Financial outcome permission key conflict' USING ERRCODE='23505'; END IF; source_current:=public.canonical_external_business_source_consent_basis(org,'financial',source_value); RETURN jsonb_build_object('consent',public.canonical_external_financial_outcome_consent_projection(replay,source_current),'replayed',TRUE); END IF;
 SELECT * INTO current_row FROM public.canonical_external_financial_outcome_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1 FOR UPDATE; IF COALESCE(current_row.revision,0)<>(body->>'expectedRevision')::bigint OR COALESCE(rtrim(current_row.canonical_digest),'none')<>body->>'expectedDigest' THEN RAISE EXCEPTION 'Financial outcome permission changed' USING ERRCODE='40001'; END IF; source_current:=public.canonical_external_business_source_consent_basis(org,'financial',source_value); IF body->>'action'='grant' AND source_current IS NULL THEN RAISE EXCEPTION 'Current financial source permission required' USING ERRCODE='P0002',CONSTRAINT='financial_outcome_source_unavailable'; END IF;
 next_revision:=COALESCE(current_row.revision,0)+1; digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'revision',next_revision,'previousId',current_row.id,'action',body->>'action','sourceConsentId',CASE WHEN body->>'action'='grant' THEN source_current->>'id' END,'sourceConsentRevision',CASE WHEN body->>'action'='grant' THEN (source_current->>'revision')::bigint END,'sourceConsentDigest',CASE WHEN body->>'action'='grant' THEN source_current->>'digest' END,'actorUserId',actor,'reason',body->>'reason','confirmationVersion',body->>'confirmationVersion','requestDigest',request_hash));
 INSERT INTO public.canonical_external_financial_outcome_consents(organization_id,source_key,revision,previous_id,action,source_consent_id,source_consent_revision,source_consent_digest,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,request_key_hash,request_digest,canonical_digest) VALUES(org,source_value,next_revision,current_row.id,body->>'action',CASE WHEN body->>'action'='grant' THEN (source_current->>'id')::uuid END,CASE WHEN body->>'action'='grant' THEN (source_current->>'revision')::bigint END,CASE WHEN body->>'action'='grant' THEN source_current->>'digest' END,actor,(authority->>'membershipId')::uuid,session_value,body->>'reason',TRUE,body->>'confirmationVersion',key_hash,request_hash,digest_value) RETURNING * INTO inserted;
 RETURN jsonb_build_object('consent',public.canonical_external_financial_outcome_consent_projection(inserted,source_current),'replayed',FALSE); END $$;

CREATE FUNCTION public.canonical_external_financial_outcome_projection(value public.canonical_external_financial_outcome_observations,basis JSONB,consent_value public.canonical_external_financial_outcome_consents,source_current JSONB) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE active_value BOOLEAN; fresh_value BOOLEAN;
BEGIN active_value:=COALESCE(consent_value.id=value.consent_id AND consent_value.action='grant' AND source_current->>'id'=consent_value.source_consent_id::text AND source_current->>'digest'=rtrim(consent_value.source_consent_digest),FALSE); IF NOT active_value THEN RETURN jsonb_build_object('id',value.id,'revision',value.revision,'fresh',FALSE,'hiddenByConsent',TRUE,'advisoryAvailable',FALSE,'refreshRequired',TRUE,'outcomes',public.canonical_external_financial_outcome_unavailable('Financial outcome advice is hidden because permission is inactive.'),'digest',rtrim(value.canonical_digest),'createdAt',value.created_at); END IF;
 fresh_value:=basis IS NOT NULL AND basis->>'sourceDigest'=value.source_digest; RETURN jsonb_build_object('id',value.id,'sourceKey',value.source_key,'estimateId',value.estimate_id,'revision',value.revision,'previousId',value.previous_id,'consentId',value.consent_id,'consentRevision',value.consent_revision,'consentDigest',rtrim(value.consent_digest),'targetDigest',rtrim(value.target_digest),'sourceManifest',value.source_manifest,'referenceMatches',value.reference_matches,'sourceDigest',rtrim(value.source_digest),'outcomes',CASE WHEN fresh_value THEN value.outcomes ELSE public.canonical_external_financial_outcome_unavailable('Current evidence, reviewed links or company records changed. Refresh before using this advice.')END,'fresh',fresh_value,'hiddenByConsent',FALSE,'advisoryAvailable',fresh_value,'refreshRequired',NOT fresh_value,'reason',value.reason,'confirmed',value.confirmed,'confirmationVersion',value.confirmation_version,'calculationVersion',value.calculation_version,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at,'nativeFinancialBoundary','These external observations do not create NorthStar invoices, payments, collections, accounting entries, revenue, costs or margin records.','adoptionBoundary','No customer, job, estimate, schedule, price, financial record, source record or company policy was changed.'); END $$;

CREATE FUNCTION public.canonical_external_financial_outcome_observation_guard() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE basis JSONB; consent_value public.canonical_external_financial_outcome_consents%ROWTYPE; source_current JSONB; previous_row public.canonical_external_financial_outcome_observations%ROWTYPE; expected_digest TEXT;
BEGIN SELECT * INTO consent_value FROM public.canonical_external_financial_outcome_consents WHERE id=NEW.consent_id AND organization_id=NEW.organization_id; source_current:=public.canonical_external_business_source_consent_basis(NEW.organization_id,'financial',NEW.source_key); basis:=public.canonical_external_financial_outcome_basis(NEW.organization_id,NEW.source_key,NEW.estimate_id);
 IF consent_value.id IS NULL OR consent_value.action<>'grant' OR consent_value.revision<>NEW.consent_revision OR rtrim(consent_value.canonical_digest)<>rtrim(NEW.consent_digest) OR source_current IS NULL OR consent_value.source_consent_id<>(source_current->>'id')::uuid OR consent_value.source_consent_revision<>(source_current->>'revision')::bigint OR rtrim(consent_value.source_consent_digest)<>source_current->>'digest' OR basis IS NULL OR basis->>'sourceDigest'<>NEW.source_digest OR basis->'outcomes'<>NEW.outcomes OR basis->'sourceManifest'<>NEW.source_manifest OR basis->'referenceMatches'<>NEW.reference_matches OR basis->>'targetDigest'<>rtrim(NEW.target_digest) THEN RAISE EXCEPTION 'Financial outcome lineage invalid' USING ERRCODE='23514'; END IF;
 IF NEW.revision>1 THEN SELECT * INTO previous_row FROM public.canonical_external_financial_outcome_observations WHERE organization_id=NEW.organization_id AND source_key=NEW.source_key AND estimate_id=NEW.estimate_id AND id=NEW.previous_id; IF previous_row.id IS NULL OR previous_row.revision+1<>NEW.revision THEN RAISE EXCEPTION 'Financial outcome observation revision invalid' USING ERRCODE='23514'; END IF; END IF;
 expected_digest:=public.canonical_completion_digest(jsonb_build_object('organizationId',NEW.organization_id,'sourceKey',NEW.source_key,'estimateId',NEW.estimate_id,'revision',NEW.revision,'previousId',NEW.previous_id,'consentId',NEW.consent_id,'consentRevision',NEW.consent_revision,'consentDigest',rtrim(NEW.consent_digest),'targetDigest',rtrim(NEW.target_digest),'sourceManifest',NEW.source_manifest,'referenceMatches',NEW.reference_matches,'sourceDigest',NEW.source_digest,'outcomes',NEW.outcomes,'actorUserId',NEW.actor_user_id,'confirmationVersion',NEW.confirmation_version,'calculationVersion',NEW.calculation_version,'requestDigest',rtrim(NEW.request_digest))); IF rtrim(NEW.canonical_digest)<>expected_digest THEN RAISE EXCEPTION 'Financial outcome observation digest invalid' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER canonical_external_financial_outcome_observation_guard BEFORE INSERT ON public.canonical_external_financial_outcome_observations FOR EACH ROW EXECUTE FUNCTION public.canonical_external_financial_outcome_observation_guard();

CREATE FUNCTION public.canonical_external_financial_outcome_observe(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,estimate_value UUID,expected_consent_revision BIGINT,expected_consent_digest TEXT,reason_value TEXT,confirmed_value BOOLEAN,confirmation_version_value TEXT) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB; consent_value public.canonical_external_financial_outcome_consents%ROWTYPE; current_row public.canonical_external_financial_outcome_observations%ROWTYPE; replay public.canonical_external_financial_outcome_observations%ROWTYPE; inserted public.canonical_external_financial_outcome_observations%ROWTYPE; source_current JSONB; basis JSONB; key_hash TEXT; request_hash TEXT; digest_value TEXT; next_revision BIGINT;
BEGIN IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001'; END IF; IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Financial outcome learning restricted' USING ERRCODE='42501'; END IF; PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE; IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501'; END IF; authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR expected_consent_revision NOT BETWEEN 1 AND 10000 OR expected_consent_digest!~'^[0-9a-f]{64}$' OR public.canonical_learning_text_valid(reason_value,2000) IS NOT TRUE OR confirmed_value IS DISTINCT FROM TRUE OR confirmation_version_value<>'m25-external-financial-outcome-observation-v1' THEN RAISE EXCEPTION 'Financial outcome observation details invalid' USING ERRCODE='22023'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':external-financial-outcome:'||source_value,0)); PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':external-financial-outcome-observation:'||estimate_value::text,0)); key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex'); request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'sourceKey',source_value,'estimateId',estimate_value,'expectedConsentRevision',expected_consent_revision,'expectedConsentDigest',expected_consent_digest,'reason',reason_value,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value));
 SELECT * INTO replay FROM public.canonical_external_financial_outcome_observations WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash; IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Financial outcome observation key conflict' USING ERRCODE='23505'; END IF; SELECT * INTO consent_value FROM public.canonical_external_financial_outcome_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1; source_current:=public.canonical_external_business_source_consent_basis(org,'financial',source_value); basis:=public.canonical_external_financial_outcome_basis(org,source_value,replay.estimate_id); RETURN jsonb_build_object('observation',public.canonical_external_financial_outcome_projection(replay,basis,consent_value,source_current),'replayed',TRUE); END IF;
 SELECT * INTO consent_value FROM public.canonical_external_financial_outcome_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1; source_current:=public.canonical_external_business_source_consent_basis(org,'financial',source_value); IF consent_value.id IS NULL OR consent_value.action<>'grant' OR source_current IS NULL OR consent_value.source_consent_id<>(source_current->>'id')::uuid OR consent_value.source_consent_revision<>(source_current->>'revision')::bigint OR rtrim(consent_value.source_consent_digest)<>source_current->>'digest' THEN RAISE EXCEPTION 'Current source and financial outcome permissions required' USING ERRCODE='P0002',CONSTRAINT='financial_outcome_consent_unavailable'; END IF; IF consent_value.revision<>expected_consent_revision OR rtrim(consent_value.canonical_digest)<>expected_consent_digest THEN RAISE EXCEPTION 'Financial outcome permission changed' USING ERRCODE='40001'; END IF;
 basis:=public.canonical_external_financial_outcome_basis(org,source_value,estimate_value); IF basis IS NULL THEN RAISE EXCEPTION 'Current reviewed financial links and evidence required' USING ERRCODE='P0002',CONSTRAINT='financial_outcome_lineage_unavailable'; END IF; SELECT * INTO current_row FROM public.canonical_external_financial_outcome_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate_value ORDER BY revision DESC LIMIT 1 FOR UPDATE; IF current_row.id IS NOT NULL AND current_row.consent_id=consent_value.id AND current_row.source_digest=basis->>'sourceDigest' THEN RAISE EXCEPTION 'Current financial outcome already recorded' USING ERRCODE='22023',CONSTRAINT='financial_outcome_already_current'; END IF;
 next_revision:=COALESCE(current_row.revision,0)+1; digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'estimateId',estimate_value,'revision',next_revision,'previousId',current_row.id,'consentId',consent_value.id,'consentRevision',consent_value.revision,'consentDigest',rtrim(consent_value.canonical_digest),'targetDigest',basis->>'targetDigest','sourceManifest',basis->'sourceManifest','referenceMatches',basis->'referenceMatches','sourceDigest',basis->>'sourceDigest','outcomes',basis->'outcomes','actorUserId',actor,'confirmationVersion',confirmation_version_value,'calculationVersion','m25-external-financial-outcome-v1','requestDigest',request_hash));
 INSERT INTO public.canonical_external_financial_outcome_observations(organization_id,source_key,estimate_id,revision,previous_id,consent_id,consent_revision,consent_digest,target_digest,source_manifest,reference_matches,source_digest,outcomes,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,calculation_version,request_key_hash,request_digest,canonical_digest) VALUES(org,source_value,estimate_value,next_revision,current_row.id,consent_value.id,consent_value.revision,rtrim(consent_value.canonical_digest),basis->>'targetDigest',basis->'sourceManifest',basis->'referenceMatches',basis->>'sourceDigest',basis->'outcomes',actor,(authority->>'membershipId')::uuid,session_value,reason_value,TRUE,confirmation_version_value,'m25-external-financial-outcome-v1',key_hash,request_hash,digest_value) RETURNING * INTO inserted;
 RETURN jsonb_build_object('observation',public.canonical_external_financial_outcome_projection(inserted,basis,consent_value,source_current),'replayed',FALSE); END $$;

CREATE FUNCTION public.canonical_external_financial_outcome_read(org UUID,actor UUID,role_value TEXT,session_value UUID,source_value TEXT,estimate_value UUID) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_value public.canonical_external_financial_outcome_consents%ROWTYPE; current_row public.canonical_external_financial_outcome_observations%ROWTYPE; source_current JSONB; basis JSONB; history JSONB; total BIGINT; active_value BOOLEAN;
BEGIN IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Financial outcome learning restricted' USING ERRCODE='42501'; END IF; PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE); IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'Financial outcome read invalid' USING ERRCODE='22023'; END IF;
 SELECT * INTO consent_value FROM public.canonical_external_financial_outcome_consents WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1; source_current:=public.canonical_external_business_source_consent_basis(org,'financial',source_value); active_value:=COALESCE(consent_value.id IS NOT NULL AND consent_value.action='grant' AND source_current->>'id'=consent_value.source_consent_id::text AND source_current->>'digest'=rtrim(consent_value.source_consent_digest),FALSE); IF NOT active_value THEN RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',FALSE,'current',NULL,'history','[]'::jsonb,'total',0,'truncated',FALSE,'nativeFinancialBoundary','NorthStar financial records remain unavailable until Mission 27.','consumptionBoundary','Financial outcome advice is unavailable until permission is granted for the current financial source.'); END IF;
 basis:=public.canonical_external_financial_outcome_basis(org,source_value,estimate_value); SELECT * INTO current_row FROM public.canonical_external_financial_outcome_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate_value ORDER BY revision DESC LIMIT 1; SELECT count(*) INTO total FROM public.canonical_external_financial_outcome_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate_value; SELECT COALESCE(jsonb_agg(public.canonical_external_financial_outcome_projection(x,basis,consent_value,source_current)ORDER BY revision DESC),'[]'::jsonb) INTO history FROM(SELECT * FROM public.canonical_external_financial_outcome_observations WHERE organization_id=org AND source_key=source_value AND estimate_id=estimate_value ORDER BY revision DESC LIMIT 20)x;
 RETURN jsonb_build_object('sourceKey',source_value,'activeConsent',TRUE,'current',CASE WHEN current_row.id IS NULL THEN NULL ELSE public.canonical_external_financial_outcome_projection(current_row,basis,consent_value,source_current)END,'history',history,'total',total,'truncated',total>20,'nativeFinancialBoundary','NorthStar financial records remain unavailable until Mission 27.','consumptionBoundary','Recorded external amounts are advisory evidence. Invoice and payment states do not become revenue or collection.'); END $$;

REVOKE ALL ON TABLE public.canonical_external_financial_outcome_consents,public.canonical_external_financial_outcome_observations FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_immutable() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_amount_valid(JSONB,BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcomes_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_unavailable(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_consent_projection(public.canonical_external_financial_outcome_consents,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_consent_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_basis(UUID,TEXT,UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_consent_read(UUID,UUID,TEXT,UUID,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_consent_mutate(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_projection(public.canonical_external_financial_outcome_observations,JSONB,public.canonical_external_financial_outcome_consents,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_observation_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_observe(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,UUID,BIGINT,TEXT,TEXT,BOOLEAN,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_financial_outcome_read(UUID,UUID,TEXT,UUID,TEXT,UUID) FROM PUBLIC;
