-- Mission 25 Part 13D: consent-bound cross-job proposal generation.
-- Proposals are advisory snapshots over an explicit, current, same-service cohort.

CREATE TABLE public.canonical_job_outcome_proposal_consents(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
 revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000),previous_id UUID,action TEXT NOT NULL CHECK(action IN('grant','revoke')),
 graph_consent_id UUID NOT NULL,graph_consent_revision BIGINT NOT NULL CHECK(graph_consent_revision BETWEEN 1 AND 10000),graph_consent_digest CHAR(64) NOT NULL CHECK(graph_consent_digest~'^[0-9a-f]{64}$'),
 actor_user_id UUID NOT NULL,membership_id UUID NOT NULL,auth_session_id UUID NOT NULL,reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)),confirmed BOOLEAN NOT NULL CHECK(confirmed),confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-job-outcome-proposal-consent-v1'),
 request_key_hash CHAR(64) NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'),request_digest CHAR(64) NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),canonical_digest CHAR(64) NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'),created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
 UNIQUE(organization_id,revision),UNIQUE(organization_id,actor_user_id,request_key_hash),UNIQUE(organization_id,id),
 FOREIGN KEY(organization_id,previous_id) REFERENCES public.canonical_job_outcome_proposal_consents(organization_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,graph_consent_id) REFERENCES public.canonical_job_outcome_graph_consents(organization_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id) ON DELETE RESTRICT,
 FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id) ON DELETE RESTRICT,
 CHECK((revision=1 AND previous_id IS NULL)OR(revision>1 AND previous_id IS NOT NULL))
);

CREATE FUNCTION public.canonical_job_outcome_proposal_consent_projection(value public.canonical_job_outcome_proposal_consents)
RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_build_object('id',value.id,'revision',value.revision,'previousId',value.previous_id,'action',value.action,'active',value.action='grant','reason',value.reason,'confirmed',value.confirmed,'confirmationVersion',value.confirmation_version,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at,'purpose','Prepare advice from comparable completed jobs','learningBoundary','Permission allows proposal preparation from the selected job summaries. It does not change an estimate, price, schedule, job, financial record or company setting.')
$$;

CREATE FUNCTION public.canonical_job_outcome_proposal_consent_current(org UUID)
RETURNS public.canonical_job_outcome_proposal_consents LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE proposal_consent public.canonical_job_outcome_proposal_consents%ROWTYPE;graph_consent public.canonical_job_outcome_graph_consents%ROWTYPE;
BEGIN
 SELECT * INTO proposal_consent FROM public.canonical_job_outcome_proposal_consents WHERE organization_id=org ORDER BY revision DESC LIMIT 1;
 SELECT * INTO graph_consent FROM public.canonical_job_outcome_graph_consents WHERE organization_id=org ORDER BY revision DESC LIMIT 1;
 IF proposal_consent.id IS NULL OR proposal_consent.action<>'grant' OR graph_consent.id IS NULL OR graph_consent.action<>'grant' OR proposal_consent.graph_consent_id<>graph_consent.id OR proposal_consent.graph_consent_revision<>graph_consent.revision OR rtrim(proposal_consent.graph_consent_digest)<>rtrim(graph_consent.canonical_digest) THEN proposal_consent.id:=NULL;END IF;
 RETURN proposal_consent;
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_basis(org UUID,actor UUID,role_value TEXT,session_value UUID,service_value TEXT,summary_ids JSONB)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_value public.canonical_job_outcome_proposal_consents%ROWTYPE;graph_consent public.canonical_job_outcome_graph_consents%ROWTYPE;summary_row public.canonical_job_outcome_summaries%ROWTYPE;summary_projection JSONB;summary_id_value UUID;manifest JSONB:='[]'::jsonb;observations JSONB:='[]'::jsonb;metrics_value JSONB:='[]'::jsonb;domains_value JSONB:='[]'::jsonb;domain_name TEXT;metric_group RECORD;domain_metrics JSONB;domain_available BOOLEAN;cohort_size_value INTEGER;observation_count INTEGER;canonical_ids JSONB;proposal_value JSONB;cohort_digest_value TEXT;
BEGIN
 IF service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR jsonb_typeof(summary_ids)<>'array' OR jsonb_array_length(summary_ids) NOT BETWEEN 5 AND 100 OR octet_length(summary_ids::text)>8192 OR EXISTS(SELECT 1 FROM jsonb_array_elements(summary_ids)x WHERE jsonb_typeof(x)<>'string' OR x#>>'{}'!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') THEN RAISE EXCEPTION 'Cross-job proposal cohort invalid' USING ERRCODE='22023';END IF;
 SELECT jsonb_agg(to_jsonb(id)ORDER BY id)INTO canonical_ids FROM(SELECT DISTINCT (x#>>'{}')::uuid id FROM jsonb_array_elements(summary_ids)x)s;IF jsonb_array_length(canonical_ids)<>jsonb_array_length(summary_ids) OR canonical_ids<>summary_ids THEN RAISE EXCEPTION 'Cross-job proposal cohort must contain distinct sorted job summaries' USING ERRCODE='22023';END IF;
 consent_value:=public.canonical_job_outcome_proposal_consent_current(org);IF consent_value.id IS NULL THEN RAISE EXCEPTION 'Current cross-job proposal permission required' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_consent_unavailable';END IF;SELECT * INTO graph_consent FROM public.canonical_job_outcome_graph_consents WHERE organization_id=org AND id=consent_value.graph_consent_id;
 FOR summary_id_value IN SELECT (x#>>'{}')::uuid FROM jsonb_array_elements(summary_ids)x LOOP
  SELECT * INTO summary_row FROM public.canonical_job_outcome_summaries WHERE organization_id=org AND id=summary_id_value;
  IF summary_row.id IS NULL OR summary_row.consent_id<>graph_consent.id OR summary_row.id<>(SELECT id FROM public.canonical_job_outcome_summaries WHERE organization_id=org AND estimate_id=summary_row.estimate_id AND consent_id=graph_consent.id ORDER BY revision DESC,id DESC LIMIT 1) OR service_value<>(SELECT lower(btrim(opportunity.service_type)) FROM public.canonical_estimates estimate JOIN public.canonical_opportunities opportunity ON opportunity.organization_id=estimate.organization_id AND opportunity.id=estimate.opportunity_id WHERE estimate.organization_id=org AND estimate.id=summary_row.estimate_id) THEN RAISE EXCEPTION 'Every selected summary must be current and use the same service' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_cohort_unavailable';END IF;
  summary_projection:=public.canonical_job_outcome_summary_projection(summary_row,actor,role_value,session_value);IF summary_projection->'fresh' IS DISTINCT FROM 'true'::jsonb OR summary_projection->'summary' IS NULL THEN RAISE EXCEPTION 'Every selected summary must be current and available' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_cohort_unavailable';END IF;
  manifest:=manifest||jsonb_build_array(jsonb_build_object('summaryId',summary_row.id,'estimateId',summary_row.estimate_id,'summaryRevision',summary_row.revision,'summaryDigest',rtrim(summary_row.canonical_digest),'summarySourceDigest',rtrim(summary_row.source_digest),'graphId',summary_row.graph_id,'graphRevision',summary_row.graph_revision,'graphDigest',rtrim(summary_row.graph_digest),'evaluationId',summary_row.evaluation_id,'evaluationRevision',summary_row.evaluation_revision,'evaluationDigest',rtrim(summary_row.evaluation_digest)));
  metrics_value:=public.canonical_job_outcome_proposal_summary_metrics(summary_row.summary);observations:=observations||COALESCE((SELECT jsonb_agg(item||jsonb_build_object('summaryId',summary_row.id)ORDER BY item->>'domain',item->>'metricKey',item->>'basis')FROM jsonb_array_elements(metrics_value)item),'[]'::jsonb);
 END LOOP;
 cohort_size_value:=jsonb_array_length(manifest);observation_count:=jsonb_array_length(observations);IF observation_count>10000 OR octet_length(observations::text)>2097152 THEN RAISE EXCEPTION 'Cross-job proposal evidence exceeds the bounded review size' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_cohort_too_broad';END IF;
 FOR domain_name IN SELECT unnest(ARRAY['labor','travel','equipment','materials','scope','financial']) LOOP
  domain_metrics:='[]'::jsonb;domain_available:=FALSE;
  IF domain_name<>'scope' THEN
   FOR metric_group IN SELECT item->>'metricKey' metric_key,item->>'basis' basis,min(item->>'label') label,min(item->>'kind') kind FROM jsonb_array_elements(observations)item WHERE item->>'domain'=domain_name GROUP BY item->>'metricKey',item->>'basis' ORDER BY item->>'metricKey',item->>'basis' LOOP
    metrics_value:=public.canonical_job_outcome_proposal_metric(observations,cohort_size_value,domain_name,metric_group.metric_key,metric_group.basis,metric_group.label,metric_group.kind);domain_metrics:=domain_metrics||jsonb_build_array(metrics_value);IF metrics_value->'advisoryAvailable'='true'::jsonb THEN domain_available:=TRUE;END IF;
   END LOOP;
  END IF;
  domains_value:=domains_value||jsonb_build_array(jsonb_build_object('domain',domain_name,'status',CASE WHEN domain_available THEN 'advisory_available' ELSE 'unavailable' END,'metrics',domain_metrics,'message',CASE WHEN domain_available THEN 'Comparable recorded outcomes are available for owner review.' WHEN domain_name='scope' THEN 'Current scope records do not establish one reusable numeric planning value.' WHEN jsonb_array_length(domain_metrics)=0 THEN 'The selected jobs do not contain one comparable recorded measure for this area.' ELSE 'This area does not yet have five compatible current outcomes inside the advisory range.' END));
 END LOOP;
 cohort_digest_value:=public.canonical_completion_digest(jsonb_build_object('serviceKey',service_value,'graphConsentId',graph_consent.id,'graphConsentRevision',graph_consent.revision,'graphConsentDigest',rtrim(graph_consent.canonical_digest),'proposalConsentId',consent_value.id,'proposalConsentRevision',consent_value.revision,'proposalConsentDigest',rtrim(consent_value.canonical_digest),'summaries',manifest));
 proposal_value:=jsonb_build_object('version','m25-cross-job-proposal-generation-v1','serviceKey',service_value,'cohortSize',cohort_size_value,'domains',domains_value,'uncertaintyBoundary','Sample size, coverage, median, lower quartile, upper quartile and interquartile range describe only the selected comparable jobs. They are not a forecast or probability.','evidenceBoundary','Only current same-service job summaries with exact units, currencies and source lineage are compared. Missing, conflicting, stale or incompatible evidence remains unavailable and is never treated as zero.','adoptionBoundary','Review the cited jobs before changing a planning assumption. This proposal does not change an estimate, price, schedule, job, asset, material, financial record or company setting.');
 RETURN jsonb_build_object('graphConsent',jsonb_build_object('id',graph_consent.id,'revision',graph_consent.revision,'digest',rtrim(graph_consent.canonical_digest)),'proposalConsent',jsonb_build_object('id',consent_value.id,'revision',consent_value.revision,'digest',rtrim(consent_value.canonical_digest)),'cohortManifest',manifest,'cohortDigest',cohort_digest_value,'proposal',proposal_value,'sourceDigest',public.canonical_completion_digest(jsonb_build_object('cohortDigest',cohort_digest_value,'proposal',proposal_value)));
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_manifest_valid(value JSONB)
RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE item JSONB;item_count INTEGER;summary_count INTEGER;estimate_count INTEGER;ordered_ids JSONB;observed_ids JSONB;
BEGIN
 IF jsonb_typeof(value) IS DISTINCT FROM 'array' OR octet_length(value::text)>1048576 OR jsonb_array_length(value) NOT BETWEEN 5 AND 100 THEN RETURN FALSE;END IF;
 SELECT count(*),count(DISTINCT x->>'summaryId'),count(DISTINCT x->>'estimateId'),jsonb_agg(x->'summaryId'),jsonb_agg(x->'summaryId' ORDER BY x->>'summaryId') INTO item_count,summary_count,estimate_count,observed_ids,ordered_ids FROM jsonb_array_elements(value)x;
 IF item_count<>summary_count OR item_count<>estimate_count OR observed_ids<>ordered_ids THEN RETURN FALSE;END IF;
 FOR item IN SELECT x FROM jsonb_array_elements(value)x LOOP
  IF public.canonical_field_evidence_object_keys_exact(item,ARRAY['summaryId','estimateId','summaryRevision','summaryDigest','summarySourceDigest','graphId','graphRevision','graphDigest','evaluationId','evaluationRevision','evaluationDigest']) IS NOT TRUE OR (item->>'summaryId'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (item->>'estimateId'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (item->>'graphId'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (item->>'evaluationId'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (item->>'summaryRevision'~'^[1-9][0-9]{0,3}$|^10000$') IS NOT TRUE OR (item->>'graphRevision'~'^[1-9][0-9]{0,3}$|^10000$') IS NOT TRUE OR (item->>'evaluationRevision'~'^[1-9][0-9]{0,3}$|^10000$') IS NOT TRUE OR (item->>'summaryDigest'~'^[0-9a-f]{64}$') IS NOT TRUE OR (item->>'summarySourceDigest'~'^[0-9a-f]{64}$') IS NOT TRUE OR (item->>'graphDigest'~'^[0-9a-f]{64}$') IS NOT TRUE OR (item->>'evaluationDigest'~'^[0-9a-f]{64}$') IS NOT TRUE THEN RETURN FALSE;END IF;
 END LOOP;
 RETURN TRUE;
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_metric_valid(value JSONB,cohort_size_value INTEGER)
RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE sample_size_value INTEGER;coverage_value NUMERIC;median_value NUMERIC;lower_value NUMERIC;upper_value NUMERIC;iqr_value NUMERIC;available_value BOOLEAN;numeric_pattern TEXT:='^-?(0|[1-9][0-9]{0,11})(\.[0-9]{1,6})?$';
BEGIN
 IF jsonb_typeof(value) IS DISTINCT FROM 'object' OR public.canonical_field_evidence_object_keys_exact(value,ARRAY['metricKey','label','kind','basis','sampleSize','cohortSize','coveragePercent','median','lowerQuartile','upperQuartile','interquartileRange','advisoryAvailable','proposedValue','advisoryCode','advisoryMessage','unavailableReason']) IS NOT TRUE OR (value->>'metricKey'~'^[a-z][a-z0-9_]{1,63}$') IS NOT TRUE OR public.canonical_learning_text_valid(value->>'label',120) IS NOT TRUE OR (value->>'kind' IN('multiplier','percentage')) IS NOT TRUE OR (length(value->>'basis') BETWEEN 1 AND 200) IS NOT TRUE OR (value->>'basis'~'^[A-Za-z0-9._:/| -]+$') IS NOT TRUE OR jsonb_typeof(value->'sampleSize') IS DISTINCT FROM 'number' OR (value->>'sampleSize'~'^(0|[1-9][0-9]{0,2})$') IS NOT TRUE OR jsonb_typeof(value->'cohortSize') IS DISTINCT FROM 'number' OR (value->>'cohortSize'~'^[1-9][0-9]{0,2}$') IS NOT TRUE OR (value->>'cohortSize')::integer<>cohort_size_value OR jsonb_typeof(value->'coveragePercent') IS DISTINCT FROM 'string' OR (value->>'coveragePercent'~'^(0|[1-9][0-9]{0,2})(\.[0-9]{1,2})?$') IS NOT TRUE OR jsonb_typeof(value->'advisoryAvailable') IS DISTINCT FROM 'boolean' THEN RETURN FALSE;END IF;
 sample_size_value:=(value->>'sampleSize')::integer;coverage_value:=(value->>'coveragePercent')::numeric;available_value:=(value->>'advisoryAvailable')::boolean;
 IF sample_size_value>cohort_size_value OR coverage_value<0 OR coverage_value>100 OR coverage_value<>round((sample_size_value::numeric/cohort_size_value)*100,2) THEN RETURN FALSE;END IF;
 IF sample_size_value<5 THEN
  IF value->'median'<>'null'::jsonb OR value->'lowerQuartile'<>'null'::jsonb OR value->'upperQuartile'<>'null'::jsonb OR value->'interquartileRange'<>'null'::jsonb OR available_value THEN RETURN FALSE;END IF;
 ELSE
  IF jsonb_typeof(value->'median') IS DISTINCT FROM 'string' OR (value->>'median'~numeric_pattern) IS NOT TRUE OR jsonb_typeof(value->'lowerQuartile') IS DISTINCT FROM 'string' OR (value->>'lowerQuartile'~numeric_pattern) IS NOT TRUE OR jsonb_typeof(value->'upperQuartile') IS DISTINCT FROM 'string' OR (value->>'upperQuartile'~numeric_pattern) IS NOT TRUE OR jsonb_typeof(value->'interquartileRange') IS DISTINCT FROM 'string' OR (value->>'interquartileRange'~numeric_pattern) IS NOT TRUE THEN RETURN FALSE;END IF;
  median_value:=(value->>'median')::numeric;lower_value:=(value->>'lowerQuartile')::numeric;upper_value:=(value->>'upperQuartile')::numeric;iqr_value:=(value->>'interquartileRange')::numeric;
  IF lower_value>median_value OR median_value>upper_value OR iqr_value<>round(upper_value-lower_value,6) THEN RETURN FALSE;END IF;
 END IF;
 IF available_value THEN
  IF sample_size_value<5 OR jsonb_typeof(value->'proposedValue') IS DISTINCT FROM 'string' OR (value->>'proposedValue'~numeric_pattern) IS NOT TRUE OR value->>'proposedValue'<>value->>'median' OR (value->>'advisoryCode' IN('review_recorded_margin','keep_current_assumption','increase_planned_amount','decrease_planned_amount')) IS NOT TRUE OR public.canonical_learning_text_valid(value->>'advisoryMessage',500) IS NOT TRUE OR value->'unavailableReason'<>'null'::jsonb OR (value->>'kind'='multiplier' AND (median_value<.25 OR median_value>4)) OR (value->>'kind'='percentage' AND (median_value<0 OR median_value>100)) THEN RETURN FALSE;END IF;
 ELSE
  IF value->'proposedValue'<>'null'::jsonb OR value->'advisoryCode'<>'null'::jsonb OR value->'advisoryMessage'<>'null'::jsonb OR public.canonical_learning_text_valid(value->>'unavailableReason',500) IS NOT TRUE THEN RETURN FALSE;END IF;
 END IF;
 RETURN TRUE;
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_valid(value JSONB)
RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE domain_item JSONB;metric_item JSONB;domains_seen JSONB;cohort_size_value INTEGER;available_count INTEGER;metric_count INTEGER;
BEGIN
 IF jsonb_typeof(value) IS DISTINCT FROM 'object' OR octet_length(value::text)>1048576 OR public.canonical_field_evidence_object_keys_exact(value,ARRAY['version','serviceKey','cohortSize','domains','uncertaintyBoundary','evidenceBoundary','adoptionBoundary']) IS NOT TRUE OR value->>'version' IS DISTINCT FROM 'm25-cross-job-proposal-generation-v1' OR (value->>'serviceKey'~'^[a-z0-9][a-z0-9._-]{1,63}$') IS NOT TRUE OR jsonb_typeof(value->'cohortSize') IS DISTINCT FROM 'number' OR (value->>'cohortSize'~'^[1-9][0-9]{0,2}$') IS NOT TRUE OR (value->>'cohortSize')::integer NOT BETWEEN 5 AND 100 OR jsonb_typeof(value->'domains') IS DISTINCT FROM 'array' OR jsonb_array_length(value->'domains')<>6 OR public.canonical_learning_text_valid(value->>'uncertaintyBoundary',1000) IS NOT TRUE OR public.canonical_learning_text_valid(value->>'evidenceBoundary',1000) IS NOT TRUE OR public.canonical_learning_text_valid(value->>'adoptionBoundary',1000) IS NOT TRUE THEN RETURN FALSE;END IF;
 cohort_size_value:=(value->>'cohortSize')::integer;SELECT jsonb_agg(x->'domain')INTO domains_seen FROM jsonb_array_elements(value->'domains')x;IF domains_seen<>'["labor","travel","equipment","materials","scope","financial"]'::jsonb THEN RETURN FALSE;END IF;
 FOR domain_item IN SELECT x FROM jsonb_array_elements(value->'domains')x LOOP
  IF public.canonical_field_evidence_object_keys_exact(domain_item,ARRAY['domain','status','metrics','message']) IS NOT TRUE OR (domain_item->>'status' IN('advisory_available','unavailable')) IS NOT TRUE OR jsonb_typeof(domain_item->'metrics') IS DISTINCT FROM 'array' OR jsonb_array_length(domain_item->'metrics')>100 OR public.canonical_learning_text_valid(domain_item->>'message',500) IS NOT TRUE THEN RETURN FALSE;END IF;
  IF domain_item->>'domain'='scope' AND (domain_item->>'status'<>'unavailable' OR jsonb_array_length(domain_item->'metrics')<>0) THEN RETURN FALSE;END IF;
  available_count:=0;metric_count:=0;
  FOR metric_item IN SELECT x FROM jsonb_array_elements(domain_item->'metrics')x LOOP
   IF public.canonical_job_outcome_proposal_metric_valid(metric_item,cohort_size_value) IS NOT TRUE THEN RETURN FALSE;END IF;metric_count:=metric_count+1;IF metric_item->'advisoryAvailable'='true'::jsonb THEN available_count:=available_count+1;END IF;
  END LOOP;
  IF metric_count<>(SELECT count(DISTINCT (x->>'metricKey')||E'\n'||(x->>'basis')) FROM jsonb_array_elements(domain_item->'metrics')x) OR (domain_item->>'status'='advisory_available')<>(available_count>0) THEN RETURN FALSE;END IF;
 END LOOP;
 RETURN TRUE;
END $$;

CREATE TABLE public.canonical_job_outcome_cross_job_proposals(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,service_key TEXT NOT NULL CHECK(service_key~'^[a-z0-9][a-z0-9._-]{1,63}$'),
 graph_consent_id UUID NOT NULL,graph_consent_revision BIGINT NOT NULL CHECK(graph_consent_revision BETWEEN 1 AND 10000),graph_consent_digest CHAR(64) NOT NULL CHECK(graph_consent_digest~'^[0-9a-f]{64}$'),proposal_consent_id UUID NOT NULL,proposal_consent_revision BIGINT NOT NULL CHECK(proposal_consent_revision BETWEEN 1 AND 10000),proposal_consent_digest CHAR(64) NOT NULL CHECK(proposal_consent_digest~'^[0-9a-f]{64}$'),
 cohort_manifest JSONB NOT NULL CHECK(public.canonical_job_outcome_proposal_manifest_valid(cohort_manifest)),cohort_digest CHAR(64) NOT NULL CHECK(cohort_digest~'^[0-9a-f]{64}$'),proposal JSONB NOT NULL CHECK(public.canonical_job_outcome_proposal_valid(proposal)),source_digest CHAR(64) NOT NULL CHECK(source_digest~'^[0-9a-f]{64}$'),calculation_version TEXT NOT NULL CHECK(calculation_version='m25-cross-job-proposal-generation-v1'),
 actor_user_id UUID NOT NULL,membership_id UUID NOT NULL,auth_session_id UUID NOT NULL,reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)),confirmed BOOLEAN NOT NULL CHECK(confirmed),confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-cross-job-proposal-generation-v1'),request_key_hash CHAR(64) NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'),request_digest CHAR(64) NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),canonical_digest CHAR(64) NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'),created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
 UNIQUE(organization_id,actor_user_id,request_key_hash),UNIQUE(organization_id,id),
 FOREIGN KEY(organization_id,graph_consent_id) REFERENCES public.canonical_job_outcome_graph_consents(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,proposal_consent_id) REFERENCES public.canonical_job_outcome_proposal_consents(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id) ON DELETE RESTRICT,
 CHECK(rtrim(source_digest)=public.canonical_completion_digest(jsonb_build_object('cohortDigest',rtrim(cohort_digest),'proposal',proposal)))
);
CREATE INDEX canonical_job_outcome_cross_job_proposals_current_idx ON public.canonical_job_outcome_cross_job_proposals(organization_id,service_key,created_at DESC,id DESC);
CREATE TRIGGER canonical_job_outcome_cross_job_proposals_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_job_outcome_cross_job_proposals FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_job_outcome_graph_immutable();

CREATE FUNCTION public.canonical_job_outcome_proposal_ratio(metric_key_value TEXT,label_value TEXT,basis_value TEXT,planned_text TEXT,actual_text TEXT)
RETURNS JSONB LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE planned_value NUMERIC;actual_value NUMERIC;
BEGIN
 IF metric_key_value!~'^[a-z][a-z0-9_]{1,63}$' OR public.canonical_learning_text_valid(label_value,120) IS NOT TRUE OR basis_value IS NULL OR length(basis_value) NOT BETWEEN 1 AND 200 OR basis_value!~'^[A-Za-z0-9._:/| -]+$' OR planned_text IS NULL OR actual_text IS NULL OR planned_text!~'^(0|[1-9][0-9]{0,11})(\.[0-9]{1,6})?$' OR actual_text!~'^(0|[1-9][0-9]{0,11})(\.[0-9]{1,6})?$' THEN RETURN NULL;END IF;
 planned_value:=planned_text::numeric;actual_value:=actual_text::numeric;IF planned_value<=0 OR actual_value<0 THEN RETURN NULL;END IF;
 RETURN jsonb_build_object('metricKey',metric_key_value,'label',label_value,'kind','multiplier','basis',basis_value,'value',round(actual_value/planned_value,6)::text);
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_percentage(metric_key_value TEXT,label_value TEXT,basis_value TEXT,value_text TEXT)
RETURNS JSONB LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE number_value NUMERIC;
BEGIN
 IF metric_key_value!~'^[a-z][a-z0-9_]{1,63}$' OR public.canonical_learning_text_valid(label_value,120) IS NOT TRUE OR basis_value IS NULL OR length(basis_value) NOT BETWEEN 1 AND 200 OR basis_value!~'^[A-Za-z0-9._:/| -]+$' OR value_text IS NULL OR value_text!~'^-?(0|[1-9][0-9]{0,11})(\.[0-9]{1,6})?$' THEN RETURN NULL;END IF;
 number_value:=value_text::numeric;IF number_value<0 OR number_value>100 THEN RETURN NULL;END IF;
 RETURN jsonb_build_object('metricKey',metric_key_value,'label',label_value,'kind','percentage','basis',basis_value,'value',round(number_value,6)::text);
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_summary_metrics(summary_value JSONB)
RETURNS JSONB LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE domain_value JSONB;source_value JSONB;details JSONB;line_value JSONB;metric_value JSONB;key_value TEXT;result JSONB:='[]'::jsonb;
BEGIN
 IF public.canonical_job_outcome_summary_valid(summary_value) IS NOT TRUE THEN RAISE EXCEPTION 'Current job summary details invalid' USING ERRCODE='22023';END IF;
 FOR domain_value IN SELECT x FROM jsonb_array_elements(summary_value->'domains')x LOOP
  IF domain_value->>'status'<>'recorded' OR jsonb_array_length(domain_value->'sources')<>1 THEN CONTINUE;END IF;source_value:=domain_value->'sources'->0;details:=source_value->'details';
  CASE source_value->>'nodeKind'
   WHEN 'native_labor','imported_labor' THEN metric_value:=public.canonical_job_outcome_proposal_ratio('worker_hours','Worker hours',CASE source_value->>'nodeKind' WHEN 'native_labor' THEN 'NorthStar worker hours' ELSE 'Connected worker hours' END,details->>'plannedWorkerHours',details->>'recordedWorkerHours');IF metric_value IS NOT NULL THEN result:=result||jsonb_build_array(metric_value||jsonb_build_object('domain','labor'));END IF;
   WHEN 'imported_travel' THEN
    FOR key_value IN SELECT unnest(ARRAY['routeDuration','distance','fuelQuantity','fuelCost']) LOOP
     IF details#>>ARRAY[key_value,'status']='compared' THEN metric_value:=public.canonical_job_outcome_proposal_ratio(CASE key_value WHEN 'routeDuration' THEN 'route_duration' WHEN 'fuelQuantity' THEN 'fuel_quantity' WHEN 'fuelCost' THEN 'fuel_cost' ELSE 'distance' END,CASE key_value WHEN 'routeDuration' THEN 'Route duration' WHEN 'fuelQuantity' THEN 'Fuel quantity' WHEN 'fuelCost' THEN 'Fuel cost' ELSE 'Travel distance' END,'Connected travel|'||(details#>>ARRAY[key_value,'unit']),details#>>ARRAY[key_value,'planned'],details#>>ARRAY[key_value,'actual']);IF metric_value IS NOT NULL THEN result:=result||jsonb_build_array(metric_value||jsonb_build_object('domain','travel'));END IF;END IF;
    END LOOP;
   WHEN 'native_equipment' THEN metric_value:=public.canonical_job_outcome_proposal_ratio('equipment_hours','Equipment hours','NorthStar equipment|machine_hour',details->>'plannedHours',details->>'recordedCheckoutHours');IF metric_value IS NOT NULL THEN result:=result||jsonb_build_array(metric_value||jsonb_build_object('domain','equipment'));END IF;
   WHEN 'imported_asset' THEN
    FOR key_value IN SELECT unnest(ARRAY['utilization','operatingCost']) LOOP
     IF details#>>ARRAY[key_value,'status']='compared' THEN metric_value:=public.canonical_job_outcome_proposal_ratio(CASE key_value WHEN 'utilization' THEN 'equipment_utilization' ELSE 'equipment_operating_cost' END,CASE key_value WHEN 'utilization' THEN 'Equipment utilization' ELSE 'Equipment operating cost' END,'Connected equipment|'||(details#>>ARRAY[key_value,'unit']),details#>>ARRAY[key_value,'planned'],details#>>ARRAY[key_value,'actual']);IF metric_value IS NOT NULL THEN result:=result||jsonb_build_array(metric_value||jsonb_build_object('domain','equipment'));END IF;END IF;
    END LOOP;
   WHEN 'native_material' THEN
    FOR line_value IN SELECT x FROM jsonb_array_elements(details->'lines')x LOOP metric_value:=public.canonical_job_outcome_proposal_ratio('material_use','Material use','NorthStar material|'||(line_value->>'itemKey')||'|'||(line_value->>'unit'),line_value->>'plannedQuantity',line_value->>'recordedUsedQuantity');IF metric_value IS NOT NULL THEN result:=result||jsonb_build_array(metric_value||jsonb_build_object('domain','materials'));END IF;END LOOP;
   WHEN 'imported_material_quantity' THEN
    FOR line_value IN SELECT x FROM jsonb_array_elements(details->'lines')x LOOP IF line_value#>>'{totalQuantity,status}'='compared' THEN metric_value:=public.canonical_job_outcome_proposal_ratio('material_use','Material use','Connected material|'||(line_value->>'targetItemKey')||'|'||(line_value->>'plannedUnit'),line_value->>'plannedQuantity',line_value#>>'{totalQuantity,quantity}');IF metric_value IS NOT NULL THEN result:=result||jsonb_build_array(metric_value||jsonb_build_object('domain','materials'));END IF;END IF;END LOOP;
   WHEN 'imported_material_cost' THEN
    FOR line_value IN SELECT x FROM jsonb_array_elements(details->'lines')x LOOP
     IF line_value#>>'{unitCost,status}'='compared' THEN metric_value:=public.canonical_job_outcome_proposal_ratio('material_unit_cost','Material unit cost','Connected material cost|'||(line_value->>'material')||'|'||(line_value#>>'{unitCost,unit}')||'|'||(line_value#>>'{unitCost,currency}'),line_value#>>'{unitCost,plannedUnitCost}',line_value#>>'{unitCost,recordedUnitCost}');IF metric_value IS NOT NULL THEN result:=result||jsonb_build_array(metric_value||jsonb_build_object('domain','materials'));END IF;END IF;
     IF line_value#>>'{purchasing,quantity,status}'='compared' THEN metric_value:=public.canonical_job_outcome_proposal_ratio('material_purchase_quantity','Material purchase quantity','Connected material purchase|'||(line_value->>'material')||'|'||(line_value#>>'{purchasing,quantity,unit}'),line_value#>>'{purchasing,quantity,plannedQuantity}',line_value#>>'{purchasing,quantity,recordedQuantity}');IF metric_value IS NOT NULL THEN result:=result||jsonb_build_array(metric_value||jsonb_build_object('domain','materials'));END IF;END IF;
    END LOOP;
   WHEN 'external_financial' THEN IF details#>>'{margin,status}'='recorded' THEN metric_value:=public.canonical_job_outcome_proposal_percentage('gross_margin','Gross margin','Connected financial|'||(details#>>'{margin,currency}'),details#>>'{margin,percent}');IF metric_value IS NOT NULL THEN result:=result||jsonb_build_array(metric_value||jsonb_build_object('domain','financial'));END IF;END IF;
   ELSE NULL;
  END CASE;
 END LOOP;
 RETURN result;
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_metric(observations JSONB,cohort_size_value INTEGER,domain_value TEXT,metric_key_value TEXT,basis_value TEXT,label_value TEXT,kind_value TEXT)
RETURNS JSONB LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE sample_count INTEGER;row_count INTEGER;median_value NUMERIC;lower_value NUMERIC;upper_value NUMERIC;iqr_value NUMERIC;available_value BOOLEAN;code_value TEXT;message_value TEXT;coverage_value NUMERIC;
BEGIN
 WITH per_job AS(SELECT item->>'summaryId' summary_id,min((item->>'value')::numeric)value,count(*)records FROM jsonb_array_elements(observations)item WHERE item->>'domain'=domain_value AND item->>'metricKey'=metric_key_value AND item->>'basis'=basis_value AND item->>'kind'=kind_value GROUP BY item->>'summaryId'),eligible AS(SELECT value FROM per_job WHERE records=1)
 SELECT count(*)::integer,(SELECT count(*)::integer FROM jsonb_array_elements(observations)item WHERE item->>'domain'=domain_value AND item->>'metricKey'=metric_key_value AND item->>'basis'=basis_value AND item->>'kind'=kind_value),round(percentile_cont(.5)WITHIN GROUP(ORDER BY value)::numeric,6),round(percentile_cont(.25)WITHIN GROUP(ORDER BY value)::numeric,6),round(percentile_cont(.75)WITHIN GROUP(ORDER BY value)::numeric,6) INTO sample_count,row_count,median_value,lower_value,upper_value FROM eligible;
 coverage_value:=round((sample_count::numeric/cohort_size_value)*100,2);iqr_value:=CASE WHEN lower_value IS NULL THEN NULL ELSE round(upper_value-lower_value,6) END;
 available_value:=sample_count>=5 AND row_count=sample_count AND ((kind_value='multiplier' AND median_value BETWEEN .25 AND 4)OR(kind_value='percentage' AND median_value BETWEEN 0 AND 100));
 code_value:=CASE WHEN NOT available_value THEN NULL WHEN kind_value='percentage' THEN 'review_recorded_margin' WHEN median_value BETWEEN .95 AND 1.05 THEN 'keep_current_assumption' WHEN median_value>1.05 THEN 'increase_planned_amount' ELSE 'decrease_planned_amount' END;
 message_value:=CASE code_value WHEN 'review_recorded_margin' THEN 'The proposed margin is the median recorded margin in this comparable sample.' WHEN 'keep_current_assumption' THEN 'The median recorded result is within 5% of the current planning amount.' WHEN 'increase_planned_amount' THEN 'The median recorded result is higher than the current planning amount.' WHEN 'decrease_planned_amount' THEN 'The median recorded result is lower than the current planning amount.' ELSE NULL END;
 RETURN jsonb_build_object('metricKey',metric_key_value,'label',label_value,'kind',kind_value,'basis',basis_value,'sampleSize',sample_count,'cohortSize',cohort_size_value,'coveragePercent',coverage_value::text,'median',CASE WHEN sample_count>=5 THEN median_value::text ELSE NULL END,'lowerQuartile',CASE WHEN sample_count>=5 THEN lower_value::text ELSE NULL END,'upperQuartile',CASE WHEN sample_count>=5 THEN upper_value::text ELSE NULL END,'interquartileRange',CASE WHEN sample_count>=5 THEN iqr_value::text ELSE NULL END,'advisoryAvailable',available_value,'proposedValue',CASE WHEN available_value THEN median_value::text ELSE NULL END,'advisoryCode',code_value,'advisoryMessage',message_value,'unavailableReason',CASE WHEN sample_count<5 THEN 'At least five comparable current job outcomes are required for this measure.' WHEN row_count<>sample_count THEN 'More than one value from a job covers this measure. Review the evidence before preparing advice.' WHEN kind_value='multiplier' AND median_value NOT BETWEEN .25 AND 4 THEN 'The median result is outside the 0.25 to 4.00 advisory multiplier range.' ELSE NULL END);
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_consent_guard() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE prior public.canonical_job_outcome_proposal_consents%ROWTYPE;current_row public.canonical_job_outcome_proposal_consents%ROWTYPE;graph_consent public.canonical_job_outcome_graph_consents%ROWTYPE;role_value TEXT;expected TEXT;
BEGIN
 SELECT * INTO graph_consent FROM public.canonical_job_outcome_graph_consents WHERE organization_id=NEW.organization_id ORDER BY revision DESC LIMIT 1;
 IF graph_consent.id IS NULL OR graph_consent.id<>NEW.graph_consent_id OR graph_consent.revision<>NEW.graph_consent_revision OR rtrim(graph_consent.canonical_digest)<>rtrim(NEW.graph_consent_digest) OR (NEW.action='grant' AND graph_consent.action<>'grant') THEN RAISE EXCEPTION 'Cross-job proposal permission source invalid' USING ERRCODE='23514';END IF;
 SELECT role INTO role_value FROM public.organization_memberships WHERE organization_id=NEW.organization_id AND id=NEW.membership_id AND user_id=NEW.actor_user_id AND status='active';IF role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Cross-job proposal permission authority invalid' USING ERRCODE='23514';END IF;
 PERFORM public.canonical_field_execution_actor_authority(NEW.organization_id,NEW.actor_user_id,role_value,NEW.auth_session_id,NULL,FALSE);
 SELECT * INTO current_row FROM public.canonical_job_outcome_proposal_consents WHERE organization_id=NEW.organization_id ORDER BY revision DESC LIMIT 1;
 IF NEW.revision=1 THEN IF current_row.id IS NOT NULL OR NEW.previous_id IS NOT NULL OR NEW.action<>'grant' THEN RAISE EXCEPTION 'Cross-job proposal permission revision invalid' USING ERRCODE='23514';END IF;
 ELSE SELECT * INTO prior FROM public.canonical_job_outcome_proposal_consents WHERE organization_id=NEW.organization_id AND id=NEW.previous_id;IF prior.id IS NULL OR current_row.id IS DISTINCT FROM prior.id OR prior.revision+1<>NEW.revision THEN RAISE EXCEPTION 'Cross-job proposal permission revision invalid' USING ERRCODE='23514';END IF;IF prior.action=NEW.action AND prior.graph_consent_id=NEW.graph_consent_id THEN RAISE EXCEPTION 'Cross-job proposal permission action invalid' USING ERRCODE='23514';END IF;END IF;
 expected:=public.canonical_completion_digest(jsonb_build_object('organizationId',NEW.organization_id,'revision',NEW.revision,'previousId',NEW.previous_id,'action',NEW.action,'graphConsentId',NEW.graph_consent_id,'graphConsentRevision',NEW.graph_consent_revision,'graphConsentDigest',rtrim(NEW.graph_consent_digest),'actorUserId',NEW.actor_user_id,'membershipId',NEW.membership_id,'authSessionId',NEW.auth_session_id,'reason',NEW.reason,'confirmationVersion',NEW.confirmation_version,'requestDigest',rtrim(NEW.request_digest)));IF rtrim(NEW.canonical_digest)<>expected THEN RAISE EXCEPTION 'Cross-job proposal permission digest invalid' USING ERRCODE='23514';END IF;RETURN NEW;
END $$;
CREATE TRIGGER canonical_job_outcome_proposal_consents_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_job_outcome_proposal_consents FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_job_outcome_graph_immutable();
CREATE TRIGGER canonical_job_outcome_proposal_consent_guard BEFORE INSERT ON public.canonical_job_outcome_proposal_consents FOR EACH ROW EXECUTE FUNCTION public.canonical_job_outcome_proposal_consent_guard();

CREATE FUNCTION public.canonical_job_outcome_proposal_consent_read(org UUID,actor UUID,role_value TEXT,session_value UUID)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE current_row public.canonical_job_outcome_proposal_consents%ROWTYPE;active_row public.canonical_job_outcome_proposal_consents%ROWTYPE;history JSONB;total BIGINT;
BEGIN
 IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Cross-job proposal review restricted' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);
 SELECT * INTO current_row FROM public.canonical_job_outcome_proposal_consents WHERE organization_id=org ORDER BY revision DESC LIMIT 1;active_row:=public.canonical_job_outcome_proposal_consent_current(org);
 SELECT count(*) INTO total FROM public.canonical_job_outcome_proposal_consents WHERE organization_id=org;SELECT COALESCE(jsonb_agg(public.canonical_job_outcome_proposal_consent_projection(x)ORDER BY revision DESC),'[]'::jsonb)INTO history FROM(SELECT * FROM public.canonical_job_outcome_proposal_consents WHERE organization_id=org ORDER BY revision DESC LIMIT 20)x;
 RETURN jsonb_build_object('current',CASE WHEN current_row.id IS NULL THEN NULL ELSE public.canonical_job_outcome_proposal_consent_projection(current_row)||jsonb_build_object('active',active_row.id=current_row.id)END,'history',history,'total',total,'truncated',total>20,'purpose','Prepare advice from comparable completed jobs','consumptionBoundary','New permission is required whenever the connected job-outcome permission period changes. Earlier proposals do not return automatically.');
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_consent_mutate(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,body JSONB)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;current_row public.canonical_job_outcome_proposal_consents%ROWTYPE;replay public.canonical_job_outcome_proposal_consents%ROWTYPE;inserted public.canonical_job_outcome_proposal_consents%ROWTYPE;graph_consent public.canonical_job_outcome_graph_consents%ROWTYPE;key_hash TEXT;request_hash TEXT;digest_value TEXT;next_revision BIGINT;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Cross-job proposal review restricted' USING ERRCODE='42501';END IF;PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR octet_length(body::text)>8192 OR public.canonical_field_evidence_object_keys_exact(body,ARRAY['action','expectedRevision','expectedDigest','reason','confirmed','confirmationVersion']) IS NOT TRUE OR body->>'action' NOT IN('grant','revoke') OR jsonb_typeof(body->'expectedRevision')<>'number' OR body->>'expectedRevision'!~'^(0|[1-9][0-9]{0,3}|10000)$' OR body->>'expectedDigest'!~'^(none|[0-9a-f]{64})$' OR (((body->>'expectedRevision')::bigint=0)<>(body->>'expectedDigest'='none')) OR public.canonical_learning_text_valid(body->>'reason',2000) IS NOT TRUE OR body->'confirmed' IS DISTINCT FROM 'true'::jsonb OR body->>'confirmationVersion'<>'m25-job-outcome-proposal-consent-v1' THEN RAISE EXCEPTION 'Cross-job proposal permission details invalid' USING ERRCODE='22023';END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-graph-consent',0));PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-proposal-consent',0));key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'body',body));
 SELECT * INTO graph_consent FROM public.canonical_job_outcome_graph_consents WHERE organization_id=org ORDER BY revision DESC LIMIT 1 FOR SHARE;SELECT * INTO replay FROM public.canonical_job_outcome_proposal_consents WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;
 IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Cross-job proposal permission key conflict' USING ERRCODE='23505';END IF;SELECT * INTO current_row FROM public.canonical_job_outcome_proposal_consents WHERE organization_id=org ORDER BY revision DESC LIMIT 1;IF current_row.id<>replay.id OR graph_consent.id<>replay.graph_consent_id OR graph_consent.revision<>replay.graph_consent_revision OR rtrim(graph_consent.canonical_digest)<>rtrim(replay.graph_consent_digest) OR (replay.action='grant' AND graph_consent.action<>'grant') THEN RAISE EXCEPTION 'Cross-job proposal permission changed' USING ERRCODE='40001';END IF;RETURN jsonb_build_object('consent',public.canonical_job_outcome_proposal_consent_projection(replay),'replayed',TRUE);END IF;
 IF graph_consent.id IS NULL OR (body->>'action'='grant' AND graph_consent.action<>'grant') THEN RAISE EXCEPTION 'Current job outcome permission required' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_source_consent_unavailable';END IF;
 SELECT * INTO current_row FROM public.canonical_job_outcome_proposal_consents WHERE organization_id=org ORDER BY revision DESC LIMIT 1 FOR UPDATE;IF COALESCE(current_row.revision,0)<>(body->>'expectedRevision')::bigint OR COALESCE(rtrim(current_row.canonical_digest),'none')<>body->>'expectedDigest' THEN RAISE EXCEPTION 'Cross-job proposal permission changed' USING ERRCODE='40001';END IF;IF body->>'action'='grant' AND current_row.action='grant' AND current_row.graph_consent_id=graph_consent.id OR body->>'action'='revoke' AND(current_row.id IS NULL OR current_row.action<>'grant') THEN RAISE EXCEPTION 'Cross-job proposal permission action invalid' USING ERRCODE='22023';END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'revision',next_revision,'previousId',current_row.id,'action',body->>'action','graphConsentId',graph_consent.id,'graphConsentRevision',graph_consent.revision,'graphConsentDigest',rtrim(graph_consent.canonical_digest),'actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'authSessionId',session_value,'reason',body->>'reason','confirmationVersion',body->>'confirmationVersion','requestDigest',request_hash));
 INSERT INTO public.canonical_job_outcome_proposal_consents(organization_id,revision,previous_id,action,graph_consent_id,graph_consent_revision,graph_consent_digest,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,request_key_hash,request_digest,canonical_digest)VALUES(org,next_revision,current_row.id,body->>'action',graph_consent.id,graph_consent.revision,rtrim(graph_consent.canonical_digest),actor,(authority->>'membershipId')::uuid,session_value,body->>'reason',TRUE,body->>'confirmationVersion',key_hash,request_hash,digest_value)RETURNING * INTO inserted;RETURN jsonb_build_object('consent',public.canonical_job_outcome_proposal_consent_projection(inserted),'replayed',FALSE);
END $$;

CREATE FUNCTION public.canonical_job_outcome_cross_job_proposal_guard() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE role_value TEXT;basis JSONB;expected TEXT;summary_ids JSONB;
BEGIN
 SELECT role INTO role_value FROM public.organization_memberships WHERE organization_id=NEW.organization_id AND id=NEW.membership_id AND user_id=NEW.actor_user_id AND status='active';IF role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Cross-job proposal authority invalid' USING ERRCODE='23514';END IF;
 SELECT jsonb_agg(item->'summaryId'ORDER BY item->>'summaryId')INTO summary_ids FROM jsonb_array_elements(NEW.cohort_manifest)item;basis:=public.canonical_job_outcome_proposal_basis(NEW.organization_id,NEW.actor_user_id,role_value,NEW.auth_session_id,NEW.service_key,summary_ids);
 IF basis#>>'{graphConsent,id}'<>NEW.graph_consent_id::text OR (basis#>>'{graphConsent,revision}')::bigint<>NEW.graph_consent_revision OR basis#>>'{graphConsent,digest}'<>rtrim(NEW.graph_consent_digest) OR basis#>>'{proposalConsent,id}'<>NEW.proposal_consent_id::text OR (basis#>>'{proposalConsent,revision}')::bigint<>NEW.proposal_consent_revision OR basis#>>'{proposalConsent,digest}'<>rtrim(NEW.proposal_consent_digest) OR basis->'cohortManifest'<>NEW.cohort_manifest OR basis->>'cohortDigest'<>rtrim(NEW.cohort_digest) OR basis->'proposal'<>NEW.proposal OR basis->>'sourceDigest'<>rtrim(NEW.source_digest) THEN RAISE EXCEPTION 'Cross-job proposal lineage invalid' USING ERRCODE='23514';END IF;
 expected:=public.canonical_completion_digest(jsonb_build_object('organizationId',NEW.organization_id,'serviceKey',NEW.service_key,'graphConsentId',NEW.graph_consent_id,'graphConsentRevision',NEW.graph_consent_revision,'graphConsentDigest',rtrim(NEW.graph_consent_digest),'proposalConsentId',NEW.proposal_consent_id,'proposalConsentRevision',NEW.proposal_consent_revision,'proposalConsentDigest',rtrim(NEW.proposal_consent_digest),'cohortDigest',rtrim(NEW.cohort_digest),'proposal',NEW.proposal,'sourceDigest',rtrim(NEW.source_digest),'calculationVersion',NEW.calculation_version,'actorUserId',NEW.actor_user_id,'membershipId',NEW.membership_id,'authSessionId',NEW.auth_session_id,'reason',NEW.reason,'confirmationVersion',NEW.confirmation_version,'requestDigest',rtrim(NEW.request_digest)));IF rtrim(NEW.canonical_digest)<>expected THEN RAISE EXCEPTION 'Cross-job proposal digest invalid' USING ERRCODE='23514';END IF;RETURN NEW;
END $$;
CREATE TRIGGER canonical_job_outcome_cross_job_proposal_guard BEFORE INSERT ON public.canonical_job_outcome_cross_job_proposals FOR EACH ROW EXECUTE FUNCTION public.canonical_job_outcome_cross_job_proposal_guard();

CREATE FUNCTION public.canonical_job_outcome_cross_job_proposal_projection(value public.canonical_job_outcome_cross_job_proposals,actor UUID,role_value TEXT,session_value UUID)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE basis JSONB;summary_ids JSONB;fresh_value BOOLEAN:=FALSE;
BEGIN
 BEGIN SELECT jsonb_agg(item->'summaryId'ORDER BY item->>'summaryId')INTO summary_ids FROM jsonb_array_elements(value.cohort_manifest)item;basis:=public.canonical_job_outcome_proposal_basis(value.organization_id,actor,role_value,session_value,value.service_key,summary_ids);fresh_value:=basis#>>'{proposalConsent,id}'=value.proposal_consent_id::text AND basis->>'cohortDigest'=rtrim(value.cohort_digest) AND basis->>'sourceDigest'=rtrim(value.source_digest) AND basis->'proposal'=value.proposal;EXCEPTION WHEN SQLSTATE 'P0002' OR SQLSTATE '22023' THEN fresh_value:=FALSE;END;
 RETURN jsonb_build_object('id',value.id,'serviceKey',value.service_key,'cohortSize',jsonb_array_length(value.cohort_manifest),'cohortManifest',CASE WHEN fresh_value THEN value.cohort_manifest ELSE '[]'::jsonb END,'cohortDigest',CASE WHEN fresh_value THEN rtrim(value.cohort_digest) ELSE NULL END,'proposal',CASE WHEN fresh_value THEN value.proposal ELSE NULL END,'fresh',fresh_value,'available',fresh_value,'needsRefresh',NOT fresh_value,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at,'statusMessage',CASE WHEN fresh_value THEN 'Advice from the selected comparable jobs is ready for review.' ELSE 'Permission or one of the selected job summaries changed. Prepare the advice again.' END,'adoptionBoundary','This advice does not change an estimate, price, schedule, job, asset, material, financial record or company setting.');
END $$;

CREATE FUNCTION public.canonical_job_outcome_cross_job_proposal_build(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,service_value TEXT,expected_consent_revision BIGINT,expected_consent_digest TEXT,summary_ids JSONB,reason_value TEXT,confirmed_value BOOLEAN,confirmation_version_value TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;consent_value public.canonical_job_outcome_proposal_consents%ROWTYPE;replay public.canonical_job_outcome_cross_job_proposals%ROWTYPE;inserted public.canonical_job_outcome_cross_job_proposals%ROWTYPE;basis JSONB;key_hash TEXT;request_hash TEXT;digest_value TEXT;projection JSONB;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Cross-job proposal review restricted' USING ERRCODE='42501';END IF;PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR expected_consent_revision NOT BETWEEN 1 AND 10000 OR expected_consent_digest!~'^[0-9a-f]{64}$' OR jsonb_typeof(summary_ids)<>'array' OR public.canonical_learning_text_valid(reason_value,2000) IS NOT TRUE OR confirmed_value IS DISTINCT FROM TRUE OR confirmation_version_value<>'m25-cross-job-proposal-generation-v1' THEN RAISE EXCEPTION 'Cross-job proposal details invalid' USING ERRCODE='22023';END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-graph-consent',0));PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-proposal-consent',0));PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-proposal:'||service_value,0));key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'serviceKey',service_value,'expectedConsentRevision',expected_consent_revision,'expectedConsentDigest',expected_consent_digest,'summaryIds',summary_ids,'reason',reason_value,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value));
 SELECT * INTO replay FROM public.canonical_job_outcome_cross_job_proposals WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Cross-job proposal key conflict' USING ERRCODE='23505';END IF;projection:=public.canonical_job_outcome_cross_job_proposal_projection(replay,actor,role_value,session_value);IF projection->'fresh' IS DISTINCT FROM 'true'::jsonb THEN RAISE EXCEPTION 'Cross-job proposal evidence changed' USING ERRCODE='40001';END IF;RETURN jsonb_build_object('proposal',projection,'replayed',TRUE);END IF;
 consent_value:=public.canonical_job_outcome_proposal_consent_current(org);IF consent_value.id IS NULL THEN RAISE EXCEPTION 'Current cross-job proposal permission required' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_consent_unavailable';END IF;IF consent_value.revision<>expected_consent_revision OR rtrim(consent_value.canonical_digest)<>expected_consent_digest THEN RAISE EXCEPTION 'Cross-job proposal permission changed' USING ERRCODE='40001';END IF;
 basis:=public.canonical_job_outcome_proposal_basis(org,actor,role_value,session_value,service_value,summary_ids);digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'serviceKey',service_value,'graphConsentId',basis#>>'{graphConsent,id}','graphConsentRevision',(basis#>>'{graphConsent,revision}')::bigint,'graphConsentDigest',basis#>>'{graphConsent,digest}','proposalConsentId',basis#>>'{proposalConsent,id}','proposalConsentRevision',(basis#>>'{proposalConsent,revision}')::bigint,'proposalConsentDigest',basis#>>'{proposalConsent,digest}','cohortDigest',basis->>'cohortDigest','proposal',basis->'proposal','sourceDigest',basis->>'sourceDigest','calculationVersion','m25-cross-job-proposal-generation-v1','actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'authSessionId',session_value,'reason',reason_value,'confirmationVersion',confirmation_version_value,'requestDigest',request_hash));
 INSERT INTO public.canonical_job_outcome_cross_job_proposals(organization_id,service_key,graph_consent_id,graph_consent_revision,graph_consent_digest,proposal_consent_id,proposal_consent_revision,proposal_consent_digest,cohort_manifest,cohort_digest,proposal,source_digest,calculation_version,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,request_key_hash,request_digest,canonical_digest)VALUES(org,service_value,(basis#>>'{graphConsent,id}')::uuid,(basis#>>'{graphConsent,revision}')::bigint,basis#>>'{graphConsent,digest}',(basis#>>'{proposalConsent,id}')::uuid,(basis#>>'{proposalConsent,revision}')::bigint,basis#>>'{proposalConsent,digest}',basis->'cohortManifest',basis->>'cohortDigest',basis->'proposal',basis->>'sourceDigest','m25-cross-job-proposal-generation-v1',actor,(authority->>'membershipId')::uuid,session_value,reason_value,TRUE,confirmation_version_value,key_hash,request_hash,digest_value)RETURNING * INTO inserted;RETURN jsonb_build_object('proposal',public.canonical_job_outcome_cross_job_proposal_projection(inserted,actor,role_value,session_value),'replayed',FALSE);
END $$;

CREATE FUNCTION public.canonical_job_outcome_cross_job_proposal_read(org UUID,actor UUID,role_value TEXT,session_value UUID,service_value TEXT)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_value public.canonical_job_outcome_proposal_consents%ROWTYPE;current_row public.canonical_job_outcome_cross_job_proposals%ROWTYPE;history JSONB;total BIGINT;
BEGIN
 IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Cross-job proposal review restricted' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);IF service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'Cross-job proposal service invalid' USING ERRCODE='22023';END IF;
 consent_value:=public.canonical_job_outcome_proposal_consent_current(org);IF consent_value.id IS NULL THEN RETURN jsonb_build_object('activeConsent',FALSE,'current',NULL,'history','[]'::jsonb,'total',0,'truncated',FALSE,'statusMessage','Permission is required before advice can be prepared from comparable jobs.','adoptionBoundary','No company record or recommendation was changed.');END IF;
 SELECT * INTO current_row FROM public.canonical_job_outcome_cross_job_proposals WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id ORDER BY created_at DESC,id DESC LIMIT 1;SELECT count(*)INTO total FROM public.canonical_job_outcome_cross_job_proposals WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id;SELECT COALESCE(jsonb_agg(public.canonical_job_outcome_cross_job_proposal_projection(x,actor,role_value,session_value)ORDER BY created_at DESC,id DESC),'[]'::jsonb)INTO history FROM(SELECT * FROM public.canonical_job_outcome_cross_job_proposals WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id ORDER BY created_at DESC,id DESC LIMIT 20)x;
 RETURN jsonb_build_object('activeConsent',TRUE,'consent',public.canonical_job_outcome_proposal_consent_projection(consent_value),'current',CASE WHEN current_row.id IS NULL THEN NULL ELSE public.canonical_job_outcome_cross_job_proposal_projection(current_row,actor,role_value,session_value)END,'history',history,'total',total,'truncated',total>20,'statusMessage',CASE WHEN current_row.id IS NULL THEN 'Select at least five current comparable job summaries to prepare advice.' ELSE 'Cross-job advice is available for review.' END,'adoptionBoundary','Applying any planning change remains a separate future owner action.');
END $$;

REVOKE ALL ON TABLE public.canonical_job_outcome_proposal_consents,public.canonical_job_outcome_cross_job_proposals FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_consent_projection(public.canonical_job_outcome_proposal_consents) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_consent_current(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_ratio(TEXT,TEXT,TEXT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_percentage(TEXT,TEXT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_summary_metrics(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_metric(JSONB,INTEGER,TEXT,TEXT,TEXT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_basis(UUID,UUID,TEXT,UUID,TEXT,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_manifest_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_metric_valid(JSONB,INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_consent_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_consent_read(UUID,UUID,TEXT,UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_consent_mutate(UUID,UUID,TEXT,UUID,TEXT,TEXT,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_cross_job_proposal_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_cross_job_proposal_projection(public.canonical_job_outcome_cross_job_proposals,UUID,TEXT,UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_cross_job_proposal_build(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,BIGINT,TEXT,JSONB,TEXT,BOOLEAN,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_cross_job_proposal_read(UUID,UUID,TEXT,UUID,TEXT) FROM PUBLIC;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='northstar_app_runtime') THEN
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_proposal_consent_read(UUID,UUID,TEXT,UUID) TO northstar_app_runtime;
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_proposal_consent_mutate(UUID,UUID,TEXT,UUID,TEXT,TEXT,JSONB) TO northstar_app_runtime;
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_cross_job_proposal_build(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,BIGINT,TEXT,JSONB,TEXT,BOOLEAN,TEXT) TO northstar_app_runtime;
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_cross_job_proposal_read(UUID,UUID,TEXT,UUID,TEXT) TO northstar_app_runtime;
END IF;END $$;
