-- Mission 25 Part 13E: versioned cross-job proposal registry and impact preview.
-- Registry versions remain advisory and never mutate a planning or operating authority.

CREATE FUNCTION public.canonical_job_outcome_registry_preview_valid(value JSONB)
RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE area_item JSONB;measure_item JSONB;impact_item JSONB;areas_seen JSONB;cohort_size_value INTEGER;available_count INTEGER:=0;unavailable_count INTEGER:=0;
BEGIN
 IF jsonb_typeof(value) IS DISTINCT FROM 'object' OR octet_length(value::text)>1048576 OR public.canonical_field_evidence_object_keys_exact(value,ARRAY['version','serviceKey','cohortSize','status','availableImpactCount','unavailableImpactCount','areas','uncertaintyBoundary','valueBoundary','adoptionBoundary']) IS NOT TRUE OR value->>'version' IS DISTINCT FROM 'm25-job-outcome-proposal-registry-preview-v1' OR (value->>'serviceKey'~'^[a-z0-9][a-z0-9._-]{1,63}$') IS NOT TRUE OR jsonb_typeof(value->'cohortSize') IS DISTINCT FROM 'number' OR (value->>'cohortSize'~'^[1-9][0-9]{0,2}$') IS NOT TRUE OR (value->>'cohortSize')::integer NOT BETWEEN 5 AND 100 OR (value->>'status' IN('review_available','unavailable')) IS NOT TRUE OR jsonb_typeof(value->'availableImpactCount') IS DISTINCT FROM 'number' OR (value->>'availableImpactCount'~'^(0|[1-9][0-9]{0,2})$') IS NOT TRUE OR jsonb_typeof(value->'unavailableImpactCount') IS DISTINCT FROM 'number' OR (value->>'unavailableImpactCount'~'^(0|[1-9][0-9]{0,2})$') IS NOT TRUE OR jsonb_typeof(value->'areas') IS DISTINCT FROM 'array' OR jsonb_array_length(value->'areas')<>6 OR public.canonical_learning_text_valid(value->>'uncertaintyBoundary',1000) IS NOT TRUE OR public.canonical_learning_text_valid(value->>'valueBoundary',1000) IS NOT TRUE OR public.canonical_learning_text_valid(value->>'adoptionBoundary',1000) IS NOT TRUE THEN RETURN FALSE;END IF;
 cohort_size_value:=(value->>'cohortSize')::integer;SELECT jsonb_agg(x->'area')INTO areas_seen FROM jsonb_array_elements(value->'areas')x;IF areas_seen<>'["labor","travel","equipment","materials","scope","financial"]'::jsonb THEN RETURN FALSE;END IF;
 FOR area_item IN SELECT x FROM jsonb_array_elements(value->'areas')x LOOP
  IF public.canonical_field_evidence_object_keys_exact(area_item,ARRAY['area','label','status','measures','message']) IS NOT TRUE OR public.canonical_learning_text_valid(area_item->>'label',120) IS NOT TRUE OR (area_item->>'status' IN('review_available','unavailable')) IS NOT TRUE OR jsonb_typeof(area_item->'measures') IS DISTINCT FROM 'array' OR jsonb_array_length(area_item->'measures')>100 OR public.canonical_learning_text_valid(area_item->>'message',500) IS NOT TRUE THEN RETURN FALSE;END IF;
  IF area_item->>'area'='scope' AND (area_item->>'status'<>'unavailable' OR jsonb_array_length(area_item->'measures')<>0) THEN RETURN FALSE;END IF;
  FOR measure_item IN SELECT x FROM jsonb_array_elements(area_item->'measures')x LOOP
   IF public.canonical_field_evidence_object_keys_exact(measure_item,ARRAY['metric','impact']) IS NOT TRUE OR public.canonical_job_outcome_proposal_metric_valid(measure_item->'metric',cohort_size_value) IS NOT TRUE OR jsonb_typeof(measure_item->'impact') IS DISTINCT FROM 'object' THEN RETURN FALSE;END IF;impact_item:=measure_item->'impact';
   IF public.canonical_field_evidence_object_keys_exact(impact_item,ARRAY['status','planningArea','direction','changePercent','statement','absoluteValueStatus','absoluteValueMessage']) IS NOT TRUE OR (impact_item->>'status' IN('relative_review','reference_only','unavailable')) IS NOT TRUE OR (impact_item->>'planningArea' IN('labor_planning','travel_planning','equipment_planning','material_planning','scope_planning','financial_reference')) IS NOT TRUE OR (impact_item->>'direction' IN('increase','decrease','keep','review','unavailable')) IS NOT TRUE OR public.canonical_learning_text_valid(impact_item->>'statement',500) IS NOT TRUE OR impact_item->>'absoluteValueStatus' IS DISTINCT FROM 'unavailable' OR public.canonical_learning_text_valid(impact_item->>'absoluteValueMessage',500) IS NOT TRUE THEN RETURN FALSE;END IF;
   IF impact_item->>'status'='relative_review' THEN IF measure_item#>>'{metric,kind}'<>'multiplier' OR measure_item#>'{metric,advisoryAvailable}' IS DISTINCT FROM 'true'::jsonb OR impact_item->>'direction' NOT IN('increase','decrease','keep') OR jsonb_typeof(impact_item->'changePercent') IS DISTINCT FROM 'string' OR (impact_item->>'changePercent'~'^-?(0|[1-9][0-9]{0,2})(\.[0-9]{1,2})?$') IS NOT TRUE OR (impact_item->>'changePercent')::numeric NOT BETWEEN -75 AND 300 THEN RETURN FALSE;END IF;available_count:=available_count+1;
   ELSIF impact_item->>'status'='reference_only' THEN IF area_item->>'area'<>'financial' OR measure_item#>>'{metric,kind}'<>'percentage' OR measure_item#>'{metric,advisoryAvailable}' IS DISTINCT FROM 'true'::jsonb OR impact_item->>'direction'<>'review' OR impact_item->'changePercent'<>'null'::jsonb THEN RETURN FALSE;END IF;available_count:=available_count+1;
   ELSE IF measure_item#>'{metric,advisoryAvailable}' IS DISTINCT FROM 'false'::jsonb OR impact_item->>'direction'<>'unavailable' OR impact_item->'changePercent'<>'null'::jsonb THEN RETURN FALSE;END IF;unavailable_count:=unavailable_count+1;END IF;
  END LOOP;
  IF (area_item->>'status'='review_available')<>EXISTS(SELECT 1 FROM jsonb_array_elements(area_item->'measures')m WHERE m#>>'{impact,status}' IN('relative_review','reference_only')) THEN RETURN FALSE;END IF;
 END LOOP;
 RETURN available_count=(value->>'availableImpactCount')::integer AND unavailable_count=(value->>'unavailableImpactCount')::integer AND (value->>'status'='review_available')=(available_count>0);
END $$;

CREATE FUNCTION public.canonical_job_outcome_registry_impact(org UUID,actor UUID,role_value TEXT,session_value UUID,service_value TEXT,proposal_id_value UUID,expected_proposal_digest TEXT)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_value public.canonical_job_outcome_proposal_consents%ROWTYPE;proposal_row public.canonical_job_outcome_cross_job_proposals%ROWTYPE;proposal_projection JSONB;domain_item JSONB;metric_item JSONB;impact_item JSONB;measures_value JSONB;areas_value JSONB:='[]'::jsonb;area_name TEXT;area_label TEXT;planning_area TEXT;area_available BOOLEAN;available_count INTEGER:=0;unavailable_count INTEGER:=0;change_value NUMERIC;direction_value TEXT;statement_value TEXT;preview_value JSONB;preview_digest_value TEXT;
BEGIN
 IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Proposal registry review restricted' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);IF service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR proposal_id_value IS NULL OR expected_proposal_digest!~'^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'Proposal impact details invalid' USING ERRCODE='22023';END IF;
 consent_value:=public.canonical_job_outcome_proposal_consent_current(org);IF consent_value.id IS NULL THEN RAISE EXCEPTION 'Current cross-job proposal permission required' USING ERRCODE='P0002',CONSTRAINT='job_outcome_registry_consent_unavailable';END IF;
 SELECT * INTO proposal_row FROM public.canonical_job_outcome_cross_job_proposals WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id AND id=proposal_id_value;IF proposal_row.id IS NULL OR rtrim(proposal_row.canonical_digest)<>expected_proposal_digest THEN RAISE EXCEPTION 'Selected proposal changed or is unavailable' USING ERRCODE='40001';END IF;proposal_projection:=public.canonical_job_outcome_cross_job_proposal_projection(proposal_row,actor,role_value,session_value);IF proposal_projection->'fresh' IS DISTINCT FROM 'true'::jsonb OR proposal_projection->'proposal' IS NULL THEN RAISE EXCEPTION 'Selected proposal changed or is unavailable' USING ERRCODE='40001';END IF;
 FOR domain_item IN SELECT x FROM jsonb_array_elements(proposal_projection#>'{proposal,domains}')x LOOP
  area_name:=domain_item->>'domain';area_label:=CASE area_name WHEN 'labor' THEN 'Labor' WHEN 'travel' THEN 'Travel' WHEN 'equipment' THEN 'Vehicles And Equipment' WHEN 'materials' THEN 'Materials' WHEN 'scope' THEN 'Scope' ELSE 'Financial Results' END;planning_area:=CASE area_name WHEN 'labor' THEN 'labor_planning' WHEN 'travel' THEN 'travel_planning' WHEN 'equipment' THEN 'equipment_planning' WHEN 'materials' THEN 'material_planning' WHEN 'scope' THEN 'scope_planning' ELSE 'financial_reference' END;measures_value:='[]'::jsonb;area_available:=FALSE;
  FOR metric_item IN SELECT x FROM jsonb_array_elements(domain_item->'metrics')x LOOP
   IF metric_item->'advisoryAvailable'='true'::jsonb AND metric_item->>'kind'='multiplier' AND area_name<>'financial' THEN change_value:=round(((metric_item->>'proposedValue')::numeric-1)*100,2);direction_value:=CASE WHEN change_value>5 THEN 'increase' WHEN change_value< -5 THEN 'decrease' ELSE 'keep' END;statement_value:=CASE direction_value WHEN 'increase' THEN format('Future %s planning for %s would be reviewed at %s percent higher.',lower(metric_item->>'label'),initcap(replace(service_value,'_',' ')),trim(to_char(abs(change_value),'FM999999990.00'))) WHEN 'decrease' THEN format('Future %s planning for %s would be reviewed at %s percent lower.',lower(metric_item->>'label'),initcap(replace(service_value,'_',' ')),trim(to_char(abs(change_value),'FM999999990.00'))) ELSE format('Future %s planning for %s would remain inside the five percent keep range.',lower(metric_item->>'label'),initcap(replace(service_value,'_',' '))) END;impact_item:=jsonb_build_object('status','relative_review','planningArea',planning_area,'direction',direction_value,'changePercent',change_value::text,'statement',statement_value,'absoluteValueStatus','unavailable','absoluteValueMessage','This evidence supports a relative planning review. It does not establish one reusable company amount.');available_count:=available_count+1;area_available:=TRUE;
   ELSIF metric_item->'advisoryAvailable'='true'::jsonb AND metric_item->>'kind'='percentage' AND area_name='financial' THEN impact_item:=jsonb_build_object('status','reference_only','planningArea',planning_area,'direction','review','changePercent',NULL,'statement',format('A recorded %s percent %s would remain a reference for owner review.',metric_item->>'proposedValue',lower(metric_item->>'label')),'absoluteValueStatus','unavailable','absoluteValueMessage','NorthStar financial records are not available for this action.');available_count:=available_count+1;area_available:=TRUE;
   ELSE impact_item:=jsonb_build_object('status','unavailable','planningArea',planning_area,'direction','unavailable','changePercent',NULL,'statement',COALESCE(metric_item->>'unavailableReason','Current evidence does not support a planning preview for this measure.'),'absoluteValueStatus','unavailable','absoluteValueMessage','No before-and-after company value is available for this measure.');unavailable_count:=unavailable_count+1;END IF;
   measures_value:=measures_value||jsonb_build_array(jsonb_build_object('metric',metric_item,'impact',impact_item));
  END LOOP;
  areas_value:=areas_value||jsonb_build_array(jsonb_build_object('area',area_name,'label',area_label,'status',CASE WHEN area_available THEN 'review_available' ELSE 'unavailable' END,'measures',measures_value,'message',CASE WHEN area_available THEN 'A planning impact is ready for owner review.' WHEN area_name='scope' THEN 'Current scope evidence does not establish one reusable planning value.' ELSE 'Current evidence does not support a planning impact for this area.' END));
 END LOOP;
 preview_value:=jsonb_build_object('version','m25-job-outcome-proposal-registry-preview-v1','serviceKey',service_value,'cohortSize',proposal_projection#>'{proposal,cohortSize}','status',CASE WHEN available_count>0 THEN 'review_available' ELSE 'unavailable' END,'availableImpactCount',available_count,'unavailableImpactCount',unavailable_count,'areas',areas_value,'uncertaintyBoundary','The sample and range describe only the selected completed jobs. They are not a forecast or promise.','valueBoundary','Relative suggestions do not establish an absolute company value. Financial percentages remain reference-only until compatible NorthStar financial authority exists.','adoptionBoundary','Saving this preview records it for review. It does not change a business profile, planning value, estimate, price, schedule, job or financial record.');IF public.canonical_job_outcome_registry_preview_valid(preview_value) IS NOT TRUE THEN RAISE EXCEPTION 'Proposal impact preview invalid' USING ERRCODE='22023';END IF;preview_digest_value:=public.canonical_completion_digest(preview_value);
 RETURN jsonb_build_object('proposalPin',jsonb_build_object('id',proposal_row.id,'digest',rtrim(proposal_row.canonical_digest),'sourceDigest',rtrim(proposal_row.source_digest),'consentId',proposal_row.proposal_consent_id,'consentRevision',proposal_row.proposal_consent_revision,'consentDigest',rtrim(proposal_row.proposal_consent_digest)),'preview',preview_value,'previewDigest',preview_digest_value);
END $$;

CREATE TABLE public.canonical_job_outcome_proposal_registry_versions(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,service_key TEXT NOT NULL CHECK(service_key~'^[a-z0-9][a-z0-9._-]{1,63}$'),proposal_consent_id UUID NOT NULL,revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000),previous_id UUID,
 proposal_id UUID NOT NULL,proposal_digest CHAR(64) NOT NULL CHECK(proposal_digest~'^[0-9a-f]{64}$'),proposal_source_digest CHAR(64) NOT NULL CHECK(proposal_source_digest~'^[0-9a-f]{64}$'),preview JSONB NOT NULL CHECK(public.canonical_job_outcome_registry_preview_valid(preview)),preview_digest CHAR(64) NOT NULL CHECK(preview_digest~'^[0-9a-f]{64}$' AND rtrim(preview_digest)=public.canonical_completion_digest(preview)),source_digest CHAR(64) NOT NULL CHECK(source_digest~'^[0-9a-f]{64}$'),calculation_version TEXT NOT NULL CHECK(calculation_version='m25-job-outcome-proposal-registry-v1'),
 actor_user_id UUID NOT NULL,membership_id UUID NOT NULL,auth_session_id UUID NOT NULL,reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)),confirmed BOOLEAN NOT NULL CHECK(confirmed),confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-job-outcome-proposal-registry-v1'),request_key_hash CHAR(64) NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'),request_digest CHAR(64) NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),canonical_digest CHAR(64) NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'),created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
 UNIQUE(organization_id,service_key,proposal_consent_id,revision),UNIQUE(organization_id,actor_user_id,request_key_hash),UNIQUE(organization_id,id),
 FOREIGN KEY(organization_id,previous_id) REFERENCES public.canonical_job_outcome_proposal_registry_versions(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,proposal_consent_id) REFERENCES public.canonical_job_outcome_proposal_consents(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,proposal_id) REFERENCES public.canonical_job_outcome_cross_job_proposals(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id) ON DELETE RESTRICT,
 CHECK((revision=1 AND previous_id IS NULL)OR(revision>1 AND previous_id IS NOT NULL)),CHECK(rtrim(source_digest)=public.canonical_completion_digest(jsonb_build_object('proposalId',proposal_id,'proposalDigest',rtrim(proposal_digest),'proposalSourceDigest',rtrim(proposal_source_digest),'previewDigest',rtrim(preview_digest))))
);
CREATE INDEX canonical_job_outcome_proposal_registry_current_idx ON public.canonical_job_outcome_proposal_registry_versions(organization_id,service_key,proposal_consent_id,revision DESC,id DESC);
CREATE TRIGGER canonical_job_outcome_proposal_registry_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_job_outcome_proposal_registry_versions FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_job_outcome_graph_immutable();

CREATE FUNCTION public.canonical_job_outcome_proposal_registry_guard() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_value public.canonical_job_outcome_proposal_consents%ROWTYPE;current_row public.canonical_job_outcome_proposal_registry_versions%ROWTYPE;prior_row public.canonical_job_outcome_proposal_registry_versions%ROWTYPE;impact_value JSONB;role_value TEXT;expected TEXT;
BEGIN
 consent_value:=public.canonical_job_outcome_proposal_consent_current(NEW.organization_id);IF consent_value.id IS NULL OR consent_value.id<>NEW.proposal_consent_id THEN RAISE EXCEPTION 'Proposal registry permission invalid' USING ERRCODE='23514';END IF;SELECT role INTO role_value FROM public.organization_memberships WHERE organization_id=NEW.organization_id AND id=NEW.membership_id AND user_id=NEW.actor_user_id AND status='active';IF role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Proposal registry authority invalid' USING ERRCODE='23514';END IF;PERFORM public.canonical_field_execution_actor_authority(NEW.organization_id,NEW.actor_user_id,role_value,NEW.auth_session_id,NULL,FALSE);
 SELECT * INTO current_row FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=NEW.organization_id AND service_key=NEW.service_key AND proposal_consent_id=NEW.proposal_consent_id ORDER BY revision DESC,id DESC LIMIT 1;IF NEW.revision=1 THEN IF current_row.id IS NOT NULL OR NEW.previous_id IS NOT NULL THEN RAISE EXCEPTION 'Proposal registry revision invalid' USING ERRCODE='23514';END IF;ELSE SELECT * INTO prior_row FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=NEW.organization_id AND id=NEW.previous_id;IF prior_row.id IS NULL OR current_row.id IS DISTINCT FROM prior_row.id OR prior_row.proposal_consent_id<>NEW.proposal_consent_id OR prior_row.service_key<>NEW.service_key OR prior_row.revision+1<>NEW.revision THEN RAISE EXCEPTION 'Proposal registry revision invalid' USING ERRCODE='23514';END IF;END IF;
 impact_value:=public.canonical_job_outcome_registry_impact(NEW.organization_id,NEW.actor_user_id,role_value,NEW.auth_session_id,NEW.service_key,NEW.proposal_id,rtrim(NEW.proposal_digest));IF impact_value#>>'{proposalPin,sourceDigest}'<>rtrim(NEW.proposal_source_digest) OR impact_value->'preview'<>NEW.preview OR impact_value->>'previewDigest'<>rtrim(NEW.preview_digest) THEN RAISE EXCEPTION 'Proposal registry lineage invalid' USING ERRCODE='23514';END IF;
 expected:=public.canonical_completion_digest(jsonb_build_object('organizationId',NEW.organization_id,'serviceKey',NEW.service_key,'proposalConsentId',NEW.proposal_consent_id,'revision',NEW.revision,'previousId',NEW.previous_id,'proposalId',NEW.proposal_id,'proposalDigest',rtrim(NEW.proposal_digest),'proposalSourceDigest',rtrim(NEW.proposal_source_digest),'previewDigest',rtrim(NEW.preview_digest),'sourceDigest',rtrim(NEW.source_digest),'calculationVersion',NEW.calculation_version,'actorUserId',NEW.actor_user_id,'membershipId',NEW.membership_id,'authSessionId',NEW.auth_session_id,'reason',NEW.reason,'confirmationVersion',NEW.confirmation_version,'requestDigest',rtrim(NEW.request_digest)));IF rtrim(NEW.canonical_digest)<>expected THEN RAISE EXCEPTION 'Proposal registry digest invalid' USING ERRCODE='23514';END IF;RETURN NEW;
END $$;
CREATE TRIGGER canonical_job_outcome_proposal_registry_guard BEFORE INSERT ON public.canonical_job_outcome_proposal_registry_versions FOR EACH ROW EXECUTE FUNCTION public.canonical_job_outcome_proposal_registry_guard();

CREATE FUNCTION public.canonical_job_outcome_proposal_registry_projection(value public.canonical_job_outcome_proposal_registry_versions,actor UUID,role_value TEXT,session_value UUID)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE impact_value JSONB;fresh_value BOOLEAN:=FALSE;
BEGIN
 BEGIN impact_value:=public.canonical_job_outcome_registry_impact(value.organization_id,actor,role_value,session_value,value.service_key,value.proposal_id,rtrim(value.proposal_digest));fresh_value:=impact_value#>>'{proposalPin,sourceDigest}'=rtrim(value.proposal_source_digest) AND impact_value->>'previewDigest'=rtrim(value.preview_digest) AND impact_value->'preview'=value.preview;EXCEPTION WHEN SQLSTATE 'P0002' OR SQLSTATE '22023' OR SQLSTATE '40001' THEN fresh_value:=FALSE;END;
 RETURN jsonb_build_object('id',value.id,'serviceKey',value.service_key,'revision',value.revision,'previousId',value.previous_id,'proposalId',CASE WHEN fresh_value THEN value.proposal_id ELSE NULL END,'preview',CASE WHEN fresh_value THEN value.preview ELSE NULL END,'previewDigest',CASE WHEN fresh_value THEN rtrim(value.preview_digest) ELSE NULL END,'fresh',fresh_value,'available',fresh_value,'needsRefresh',NOT fresh_value,'reason',value.reason,'digest',rtrim(value.canonical_digest),'createdAt',value.created_at,'statusMessage',CASE WHEN fresh_value THEN 'This saved proposal preview is ready for owner review.' ELSE 'The proposal evidence or permission changed. Save a new preview before continuing.' END,'adoptionBoundary','This registry entry does not change any company plan or record.');
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_registry_create(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,service_value TEXT,proposal_id_value UUID,expected_proposal_digest TEXT,expected_preview_digest TEXT,expected_registry_revision BIGINT,expected_registry_digest TEXT,reason_value TEXT,confirmed_value BOOLEAN,confirmation_version_value TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;consent_value public.canonical_job_outcome_proposal_consents%ROWTYPE;current_row public.canonical_job_outcome_proposal_registry_versions%ROWTYPE;replay public.canonical_job_outcome_proposal_registry_versions%ROWTYPE;inserted public.canonical_job_outcome_proposal_registry_versions%ROWTYPE;impact_value JSONB;key_hash TEXT;request_hash TEXT;source_hash TEXT;digest_value TEXT;next_revision BIGINT;projection JSONB;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Proposal registry review restricted' USING ERRCODE='42501';END IF;PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR proposal_id_value IS NULL OR expected_proposal_digest!~'^[0-9a-f]{64}$' OR expected_preview_digest!~'^[0-9a-f]{64}$' OR expected_registry_revision NOT BETWEEN 0 AND 10000 OR expected_registry_digest!~'^(none|[0-9a-f]{64})$' OR ((expected_registry_revision=0)<>(expected_registry_digest='none')) OR public.canonical_learning_text_valid(reason_value,2000) IS NOT TRUE OR confirmed_value IS DISTINCT FROM TRUE OR confirmation_version_value<>'m25-job-outcome-proposal-registry-v1' THEN RAISE EXCEPTION 'Proposal registry details invalid' USING ERRCODE='22023';END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-proposal-consent',0));PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-proposal-registry:'||service_value,0));consent_value:=public.canonical_job_outcome_proposal_consent_current(org);IF consent_value.id IS NULL THEN RAISE EXCEPTION 'Current cross-job proposal permission required' USING ERRCODE='P0002',CONSTRAINT='job_outcome_registry_consent_unavailable';END IF;key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'serviceKey',service_value,'proposalId',proposal_id_value,'expectedProposalDigest',expected_proposal_digest,'expectedPreviewDigest',expected_preview_digest,'expectedRegistryRevision',expected_registry_revision,'expectedRegistryDigest',expected_registry_digest,'reason',reason_value,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value));
 SELECT * INTO replay FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash OR replay.proposal_consent_id<>consent_value.id THEN RAISE EXCEPTION 'Proposal registry request changed' USING ERRCODE='40001';END IF;SELECT * INTO current_row FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id ORDER BY revision DESC,id DESC LIMIT 1;projection:=public.canonical_job_outcome_proposal_registry_projection(replay,actor,role_value,session_value);IF current_row.id IS DISTINCT FROM replay.id OR projection->'fresh' IS DISTINCT FROM 'true'::jsonb THEN RAISE EXCEPTION 'Proposal registry changed' USING ERRCODE='40001';END IF;RETURN jsonb_build_object('registry',projection,'replayed',TRUE);END IF;
 SELECT * INTO current_row FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id ORDER BY revision DESC,id DESC LIMIT 1 FOR UPDATE;IF COALESCE(current_row.revision,0)<>expected_registry_revision OR COALESCE(rtrim(current_row.canonical_digest),'none')<>expected_registry_digest THEN RAISE EXCEPTION 'Proposal registry changed' USING ERRCODE='40001';END IF;impact_value:=public.canonical_job_outcome_registry_impact(org,actor,role_value,session_value,service_value,proposal_id_value,expected_proposal_digest);IF impact_value->>'previewDigest'<>expected_preview_digest THEN RAISE EXCEPTION 'Proposal impact preview changed' USING ERRCODE='40001';END IF;IF current_row.proposal_id=proposal_id_value AND rtrim(current_row.preview_digest)=expected_preview_digest THEN RAISE EXCEPTION 'This proposal preview is already the current registry version' USING ERRCODE='22023';END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;source_hash:=public.canonical_completion_digest(jsonb_build_object('proposalId',proposal_id_value,'proposalDigest',expected_proposal_digest,'proposalSourceDigest',impact_value#>>'{proposalPin,sourceDigest}','previewDigest',expected_preview_digest));digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'serviceKey',service_value,'proposalConsentId',consent_value.id,'revision',next_revision,'previousId',current_row.id,'proposalId',proposal_id_value,'proposalDigest',expected_proposal_digest,'proposalSourceDigest',impact_value#>>'{proposalPin,sourceDigest}','previewDigest',expected_preview_digest,'sourceDigest',source_hash,'calculationVersion','m25-job-outcome-proposal-registry-v1','actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'authSessionId',session_value,'reason',reason_value,'confirmationVersion',confirmation_version_value,'requestDigest',request_hash));
 INSERT INTO public.canonical_job_outcome_proposal_registry_versions(organization_id,service_key,proposal_consent_id,revision,previous_id,proposal_id,proposal_digest,proposal_source_digest,preview,preview_digest,source_digest,calculation_version,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,request_key_hash,request_digest,canonical_digest)VALUES(org,service_value,consent_value.id,next_revision,current_row.id,proposal_id_value,expected_proposal_digest,impact_value#>>'{proposalPin,sourceDigest}',impact_value->'preview',expected_preview_digest,source_hash,'m25-job-outcome-proposal-registry-v1',actor,(authority->>'membershipId')::uuid,session_value,reason_value,TRUE,confirmation_version_value,key_hash,request_hash,digest_value)RETURNING * INTO inserted;RETURN jsonb_build_object('registry',public.canonical_job_outcome_proposal_registry_projection(inserted,actor,role_value,session_value),'replayed',FALSE);
END $$;

CREATE FUNCTION public.canonical_job_outcome_proposal_registry_read(org UUID,actor UUID,role_value TEXT,session_value UUID,service_value TEXT)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_value public.canonical_job_outcome_proposal_consents%ROWTYPE;current_row public.canonical_job_outcome_proposal_registry_versions%ROWTYPE;history JSONB;total BIGINT;
BEGIN
 IF role_value IS NULL OR role_value NOT IN('owner','admin') THEN RAISE EXCEPTION 'Proposal registry review restricted' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);IF service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'Proposal registry service invalid' USING ERRCODE='22023';END IF;consent_value:=public.canonical_job_outcome_proposal_consent_current(org);IF consent_value.id IS NULL THEN RETURN jsonb_build_object('activeConsent',FALSE,'current',NULL,'history','[]'::jsonb,'total',0,'truncated',FALSE,'statusMessage','Current permission is required before proposal previews can be saved.','adoptionBoundary','No company plan or record was changed.');END IF;
 SELECT * INTO current_row FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id ORDER BY revision DESC,id DESC LIMIT 1;SELECT count(*)INTO total FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id;SELECT COALESCE(jsonb_agg(public.canonical_job_outcome_proposal_registry_projection(x,actor,role_value,session_value)ORDER BY revision DESC),'[]'::jsonb)INTO history FROM(SELECT * FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id ORDER BY revision DESC,id DESC LIMIT 20)x;
 RETURN jsonb_build_object('activeConsent',TRUE,'current',CASE WHEN current_row.id IS NULL THEN NULL ELSE public.canonical_job_outcome_proposal_registry_projection(current_row,actor,role_value,session_value)END,'history',history,'total',total,'truncated',total>20,'statusMessage',CASE WHEN current_row.id IS NULL THEN 'Review a current proposal impact before saving the first registry version.' ELSE 'Saved proposal previews are available for owner review.' END,'adoptionBoundary','Applying a planning change remains a separate future owner action.');
END $$;

REVOKE ALL ON TABLE public.canonical_job_outcome_proposal_registry_versions FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_registry_preview_valid(JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_registry_impact(UUID,UUID,TEXT,UUID,TEXT,UUID,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_registry_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_registry_projection(public.canonical_job_outcome_proposal_registry_versions,UUID,TEXT,UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_registry_create(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,BOOLEAN,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_registry_read(UUID,UUID,TEXT,UUID,TEXT) FROM PUBLIC;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='northstar_app_runtime') THEN
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_registry_impact(UUID,UUID,TEXT,UUID,TEXT,UUID,TEXT) TO northstar_app_runtime;
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_proposal_registry_create(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,BOOLEAN,TEXT) TO northstar_app_runtime;
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_proposal_registry_read(UUID,UUID,TEXT,UUID,TEXT) TO northstar_app_runtime;
END IF;END $$;
