-- Mission 25 Part 13F: explicit owner adoption into versioned service planning values.
-- Adoption is exact, owner initiated and isolated from estimates and other operating truth.

CREATE FUNCTION public.canonical_job_outcome_planning_selection(org UUID,actor UUID,role_value TEXT,session_value UUID,service_value TEXT,registry_id_value UUID,expected_registry_digest TEXT,expected_preview_digest TEXT,planning_area_value TEXT,metric_key_value TEXT,basis_value TEXT)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_value public.canonical_job_outcome_proposal_consents%ROWTYPE;registry_row public.canonical_job_outcome_proposal_registry_versions%ROWTYPE;current_registry public.canonical_job_outcome_proposal_registry_versions%ROWTYPE;registry_projection JSONB;area_item JSONB;measure_item JSONB;selected JSONB;selection_value JSONB;
BEGIN
 IF role_value IS DISTINCT FROM 'owner' THEN RAISE EXCEPTION 'Planning changes require the current owner' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);
 IF service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR registry_id_value IS NULL OR expected_registry_digest IS NULL OR expected_registry_digest!~'^[0-9a-f]{64}$' OR expected_preview_digest IS NULL OR expected_preview_digest!~'^[0-9a-f]{64}$' OR planning_area_value IS NULL OR planning_area_value NOT IN('labor_planning','travel_planning','equipment_planning','material_planning') OR metric_key_value IS NULL OR metric_key_value!~'^[a-z][a-z0-9_]{1,63}$' OR basis_value IS NULL OR length(basis_value) NOT BETWEEN 1 AND 200 OR basis_value!~'^[A-Za-z0-9._:/| -]+$' THEN RAISE EXCEPTION 'Planning selection invalid' USING ERRCODE='22023';END IF;
 consent_value:=public.canonical_job_outcome_proposal_consent_current(org);IF consent_value.id IS NULL THEN RAISE EXCEPTION 'Current proposal permission required' USING ERRCODE='P0002',CONSTRAINT='job_outcome_planning_consent_unavailable';END IF;
 SELECT * INTO registry_row FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id AND id=registry_id_value;SELECT * INTO current_registry FROM public.canonical_job_outcome_proposal_registry_versions WHERE organization_id=org AND service_key=service_value AND proposal_consent_id=consent_value.id ORDER BY revision DESC,id DESC LIMIT 1;
 IF registry_row.id IS NULL OR current_registry.id IS DISTINCT FROM registry_row.id OR rtrim(registry_row.canonical_digest)<>expected_registry_digest OR rtrim(registry_row.preview_digest)<>expected_preview_digest THEN RAISE EXCEPTION 'Saved proposal preview changed' USING ERRCODE='40001';END IF;
 registry_projection:=public.canonical_job_outcome_proposal_registry_projection(registry_row,actor,role_value,session_value);IF registry_projection->'fresh' IS DISTINCT FROM 'true'::jsonb OR registry_projection->'preview' IS NULL THEN RAISE EXCEPTION 'Saved proposal preview changed' USING ERRCODE='40001';END IF;
 FOR area_item IN SELECT x FROM jsonb_array_elements(registry_projection#>'{preview,areas}')x LOOP
  FOR measure_item IN SELECT x FROM jsonb_array_elements(area_item->'measures')x LOOP
   IF measure_item#>>'{impact,planningArea}'=planning_area_value AND measure_item#>>'{metric,metricKey}'=metric_key_value AND measure_item#>>'{metric,basis}'=basis_value THEN IF selected IS NOT NULL THEN RAISE EXCEPTION 'Planning selection is ambiguous' USING ERRCODE='22023';END IF;selected:=measure_item;END IF;
  END LOOP;
 END LOOP;
 IF selected IS NULL OR selected#>>'{impact,status}'<>'relative_review' OR selected#>>'{metric,kind}'<>'multiplier' OR selected#>'{metric,advisoryAvailable}' IS DISTINCT FROM 'true'::jsonb OR selected#>>'{metric,proposedValue}'!~'^(0|[1-9][0-9]{0,11})(\.[0-9]{1,6})?$' OR (selected#>>'{metric,proposedValue}')::numeric NOT BETWEEN .25 AND 4 THEN RAISE EXCEPTION 'This proposal measure is not available for adoption' USING ERRCODE='22023';END IF;
 selection_value:=jsonb_build_object('version','m25-job-outcome-planning-selection-v1','serviceKey',service_value,'planningArea',planning_area_value,'metricKey',metric_key_value,'label',selected#>>'{metric,label}','basis',basis_value,'multiplier',selected#>>'{metric,proposedValue}','direction',selected#>>'{impact,direction}','changePercent',selected#>>'{impact,changePercent}','registryVersionId',registry_row.id,'registryRevision',registry_row.revision,'registryDigest',rtrim(registry_row.canonical_digest),'previewDigest',rtrim(registry_row.preview_digest),'proposalId',registry_row.proposal_id,'proposalDigest',rtrim(registry_row.proposal_digest),'proposalSourceDigest',rtrim(registry_row.proposal_source_digest),'statusMessage','This exact planning value is ready for owner review.','changeBoundary','Adopting this value changes only this service planning multiplier. It does not rewrite an estimate, price, schedule, job or financial record.');
 RETURN selection_value||jsonb_build_object('selectionDigest',public.canonical_completion_digest(selection_value));
END $$;

CREATE TABLE public.canonical_job_outcome_planning_value_versions(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,service_key TEXT NOT NULL CHECK(service_key~'^[a-z0-9][a-z0-9._-]{1,63}$'),planning_area TEXT NOT NULL CHECK(planning_area IN('labor_planning','travel_planning','equipment_planning','material_planning')),metric_key TEXT NOT NULL CHECK(metric_key~'^[a-z][a-z0-9_]{1,63}$'),basis TEXT NOT NULL CHECK(length(basis)BETWEEN 1 AND 200 AND basis~'^[A-Za-z0-9._:/| -]+$'),revision BIGINT NOT NULL CHECK(revision BETWEEN 1 AND 10000),previous_id UUID,
 action TEXT NOT NULL CHECK(action IN('adopt','rollback')),value_state TEXT NOT NULL CHECK(value_state IN('active','unset')),multiplier NUMERIC(12,6),source_registry_id UUID,source_registry_digest CHAR(64),source_preview_digest CHAR(64),source_selection_digest CHAR(64),rollback_to_id UUID,rollback_to_digest CHAR(64),effective_digest CHAR(64) NOT NULL CHECK(effective_digest~'^[0-9a-f]{64}$'),
 actor_user_id UUID NOT NULL,membership_id UUID NOT NULL,auth_session_id UUID NOT NULL,reason TEXT NOT NULL CHECK(public.canonical_learning_text_valid(reason,2000)),confirmed BOOLEAN NOT NULL CHECK(confirmed),confirmation_version TEXT NOT NULL CHECK(confirmation_version='m25-job-outcome-planning-adoption-v1'),request_key_hash CHAR(64) NOT NULL CHECK(request_key_hash~'^[0-9a-f]{64}$'),request_digest CHAR(64) NOT NULL CHECK(request_digest~'^[0-9a-f]{64}$'),canonical_digest CHAR(64) NOT NULL CHECK(canonical_digest~'^[0-9a-f]{64}$'),created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
 UNIQUE(organization_id,service_key,planning_area,metric_key,basis,revision),UNIQUE(organization_id,actor_user_id,request_key_hash),UNIQUE(organization_id,id),
 FOREIGN KEY(organization_id,previous_id) REFERENCES public.canonical_job_outcome_planning_value_versions(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,source_registry_id) REFERENCES public.canonical_job_outcome_proposal_registry_versions(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,rollback_to_id) REFERENCES public.canonical_job_outcome_planning_value_versions(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,membership_id) REFERENCES public.organization_memberships(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,actor_user_id,auth_session_id) REFERENCES public.auth_sessions(organization_id,user_id,id) ON DELETE RESTRICT,
 CHECK((revision=1 AND previous_id IS NULL)OR(revision>1 AND previous_id IS NOT NULL)),
 CHECK(((value_state='active' AND multiplier BETWEEN .25 AND 4 AND source_registry_id IS NOT NULL AND source_registry_digest~'^[0-9a-f]{64}$' AND source_preview_digest~'^[0-9a-f]{64}$' AND source_selection_digest~'^[0-9a-f]{64}$')OR(value_state='unset' AND multiplier IS NULL AND source_registry_id IS NULL AND source_registry_digest IS NULL AND source_preview_digest IS NULL AND source_selection_digest IS NULL))IS TRUE),
 CHECK(((action='adopt' AND rollback_to_id IS NULL AND rollback_to_digest IS NULL AND value_state='active')OR(action='rollback' AND ((rollback_to_id IS NULL AND rollback_to_digest IS NULL AND value_state='unset')OR(rollback_to_id IS NOT NULL AND rollback_to_digest~'^[0-9a-f]{64}$'))))IS TRUE),
 CHECK(rtrim(effective_digest)=public.canonical_completion_digest(jsonb_build_object('state',value_state,'multiplier',multiplier::text,'sourceRegistryId',source_registry_id,'sourceRegistryDigest',rtrim(source_registry_digest),'sourcePreviewDigest',rtrim(source_preview_digest),'sourceSelectionDigest',rtrim(source_selection_digest))))
);
CREATE INDEX canonical_job_outcome_planning_values_current_idx ON public.canonical_job_outcome_planning_value_versions(organization_id,service_key,planning_area,metric_key,basis,revision DESC,id DESC);
CREATE TRIGGER canonical_job_outcome_planning_values_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON public.canonical_job_outcome_planning_value_versions FOR EACH STATEMENT EXECUTE FUNCTION public.canonical_job_outcome_graph_immutable();

CREATE FUNCTION public.canonical_job_outcome_planning_value_guard() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE role_value TEXT;current_row public.canonical_job_outcome_planning_value_versions%ROWTYPE;prior_row public.canonical_job_outcome_planning_value_versions%ROWTYPE;target_row public.canonical_job_outcome_planning_value_versions%ROWTYPE;selection JSONB;expected TEXT;
BEGIN
 SELECT role INTO role_value FROM public.organization_memberships WHERE organization_id=NEW.organization_id AND id=NEW.membership_id AND user_id=NEW.actor_user_id AND status='active';IF role_value IS DISTINCT FROM 'owner' THEN RAISE EXCEPTION 'Planning adoption authority invalid' USING ERRCODE='23514';END IF;PERFORM public.canonical_field_execution_actor_authority(NEW.organization_id,NEW.actor_user_id,role_value,NEW.auth_session_id,NULL,FALSE);
 SELECT * INTO current_row FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=NEW.organization_id AND service_key=NEW.service_key AND planning_area=NEW.planning_area AND metric_key=NEW.metric_key AND basis=NEW.basis ORDER BY revision DESC,id DESC LIMIT 1;IF NEW.revision=1 THEN IF current_row.id IS NOT NULL OR NEW.previous_id IS NOT NULL THEN RAISE EXCEPTION 'Planning value revision invalid' USING ERRCODE='23514';END IF;ELSE SELECT * INTO prior_row FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=NEW.organization_id AND id=NEW.previous_id;IF prior_row.id IS NULL OR current_row.id IS DISTINCT FROM prior_row.id OR prior_row.service_key<>NEW.service_key OR prior_row.planning_area<>NEW.planning_area OR prior_row.metric_key<>NEW.metric_key OR prior_row.basis<>NEW.basis OR prior_row.revision+1<>NEW.revision THEN RAISE EXCEPTION 'Planning value revision invalid' USING ERRCODE='23514';END IF;END IF;
 IF NEW.action='adopt' THEN selection:=public.canonical_job_outcome_planning_selection(NEW.organization_id,NEW.actor_user_id,role_value,NEW.auth_session_id,NEW.service_key,NEW.source_registry_id,rtrim(NEW.source_registry_digest),rtrim(NEW.source_preview_digest),NEW.planning_area,NEW.metric_key,NEW.basis);IF selection->>'selectionDigest'<>rtrim(NEW.source_selection_digest) OR (selection->>'multiplier')::numeric<>NEW.multiplier THEN RAISE EXCEPTION 'Planning selection lineage invalid' USING ERRCODE='23514';END IF;
 ELSE IF NEW.rollback_to_id IS NULL THEN IF NEW.value_state<>'unset' THEN RAISE EXCEPTION 'Planning rollback invalid' USING ERRCODE='23514';END IF;ELSE SELECT * INTO target_row FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=NEW.organization_id AND id=NEW.rollback_to_id;IF target_row.id IS NULL OR target_row.service_key<>NEW.service_key OR target_row.planning_area<>NEW.planning_area OR target_row.metric_key<>NEW.metric_key OR target_row.basis<>NEW.basis OR target_row.revision>=NEW.revision OR rtrim(target_row.canonical_digest)<>rtrim(NEW.rollback_to_digest) OR target_row.value_state<>NEW.value_state OR target_row.multiplier IS DISTINCT FROM NEW.multiplier OR target_row.source_registry_id IS DISTINCT FROM NEW.source_registry_id OR rtrim(target_row.source_registry_digest) IS DISTINCT FROM rtrim(NEW.source_registry_digest) OR rtrim(target_row.source_preview_digest) IS DISTINCT FROM rtrim(NEW.source_preview_digest) OR rtrim(target_row.source_selection_digest) IS DISTINCT FROM rtrim(NEW.source_selection_digest) THEN RAISE EXCEPTION 'Planning rollback target invalid' USING ERRCODE='23514';END IF;END IF;END IF;
 expected:=public.canonical_completion_digest(jsonb_build_object('organizationId',NEW.organization_id,'serviceKey',NEW.service_key,'planningArea',NEW.planning_area,'metricKey',NEW.metric_key,'basis',NEW.basis,'revision',NEW.revision,'previousId',NEW.previous_id,'action',NEW.action,'valueState',NEW.value_state,'multiplier',NEW.multiplier::text,'sourceRegistryId',NEW.source_registry_id,'sourceRegistryDigest',rtrim(NEW.source_registry_digest),'sourcePreviewDigest',rtrim(NEW.source_preview_digest),'sourceSelectionDigest',rtrim(NEW.source_selection_digest),'rollbackToId',NEW.rollback_to_id,'rollbackToDigest',rtrim(NEW.rollback_to_digest),'effectiveDigest',rtrim(NEW.effective_digest),'actorUserId',NEW.actor_user_id,'membershipId',NEW.membership_id,'authSessionId',NEW.auth_session_id,'reason',NEW.reason,'confirmationVersion',NEW.confirmation_version,'requestDigest',rtrim(NEW.request_digest)));IF rtrim(NEW.canonical_digest)<>expected THEN RAISE EXCEPTION 'Planning adoption digest invalid' USING ERRCODE='23514';END IF;RETURN NEW;
END $$;
CREATE TRIGGER canonical_job_outcome_planning_value_guard BEFORE INSERT ON public.canonical_job_outcome_planning_value_versions FOR EACH ROW EXECUTE FUNCTION public.canonical_job_outcome_planning_value_guard();

CREATE FUNCTION public.canonical_job_outcome_planning_value_projection(value public.canonical_job_outcome_planning_value_versions,actor UUID,role_value TEXT,session_value UUID)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE source_fresh BOOLEAN:=FALSE;selection JSONB;
BEGIN
 IF value.value_state='active' THEN BEGIN selection:=public.canonical_job_outcome_planning_selection(value.organization_id,actor,role_value,session_value,value.service_key,value.source_registry_id,rtrim(value.source_registry_digest),rtrim(value.source_preview_digest),value.planning_area,value.metric_key,value.basis);source_fresh:=selection->>'selectionDigest'=rtrim(value.source_selection_digest) AND (selection->>'multiplier')::numeric=value.multiplier;EXCEPTION WHEN SQLSTATE 'P0002' OR SQLSTATE '22023' OR SQLSTATE '40001' THEN source_fresh:=FALSE;END;END IF;
 RETURN jsonb_build_object('id',value.id,'serviceKey',value.service_key,'planningArea',value.planning_area,'metricKey',value.metric_key,'basis',value.basis,'revision',value.revision,'previousId',value.previous_id,'action',value.action,'state',value.value_state,'multiplier',CASE WHEN value.value_state='active' THEN value.multiplier::text ELSE NULL END,'sourceFresh',source_fresh,'sourceNeedsReview',value.value_state='active' AND NOT source_fresh,'rollbackToId',value.rollback_to_id,'effectiveDigest',rtrim(value.effective_digest),'digest',rtrim(value.canonical_digest),'reason',value.reason,'createdAt',value.created_at,'statusMessage',CASE WHEN value.value_state='unset' THEN 'This service planning value is not set.' WHEN source_fresh THEN 'This owner-adopted service planning value is current.' ELSE 'The source proposal changed. The adopted value remains in place until the owner reviews or rolls it back.' END,'operatingBoundary','This planning value does not rewrite an existing estimate, price, schedule, job or financial record.');
END $$;

CREATE FUNCTION public.canonical_job_outcome_planning_value_adopt(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,service_value TEXT,registry_id_value UUID,expected_registry_digest TEXT,expected_preview_digest TEXT,planning_area_value TEXT,metric_key_value TEXT,basis_value TEXT,expected_selection_digest TEXT,expected_planning_revision BIGINT,expected_planning_digest TEXT,reason_value TEXT,confirmed_value BOOLEAN,confirmation_version_value TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;selection JSONB;current_row public.canonical_job_outcome_planning_value_versions%ROWTYPE;replay public.canonical_job_outcome_planning_value_versions%ROWTYPE;inserted public.canonical_job_outcome_planning_value_versions%ROWTYPE;key_hash TEXT;request_hash TEXT;effective_hash TEXT;digest_value TEXT;next_revision BIGINT;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;IF role_value IS DISTINCT FROM 'owner' THEN RAISE EXCEPTION 'Planning changes require the current owner' USING ERRCODE='42501';END IF;PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR expected_selection_digest IS NULL OR expected_selection_digest!~'^[0-9a-f]{64}$' OR expected_planning_revision IS NULL OR expected_planning_revision NOT BETWEEN 0 AND 10000 OR expected_planning_digest IS NULL OR expected_planning_digest!~'^(none|[0-9a-f]{64})$' OR ((expected_planning_revision=0)<>(expected_planning_digest='none')) OR public.canonical_learning_text_valid(reason_value,2000) IS NOT TRUE OR confirmed_value IS DISTINCT FROM TRUE OR confirmation_version_value IS DISTINCT FROM 'm25-job-outcome-planning-adoption-v1' THEN RAISE EXCEPTION 'Planning adoption details invalid' USING ERRCODE='22023';END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-proposal-consent',0));PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-proposal-registry:'||service_value,0));PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-planning:'||service_value||':'||planning_area_value||':'||metric_key_value||':'||basis_value,0));key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'serviceKey',service_value,'registryVersionId',registry_id_value,'expectedRegistryDigest',expected_registry_digest,'expectedPreviewDigest',expected_preview_digest,'planningArea',planning_area_value,'metricKey',metric_key_value,'basis',basis_value,'expectedSelectionDigest',expected_selection_digest,'expectedPlanningRevision',expected_planning_revision,'expectedPlanningDigest',expected_planning_digest,'reason',reason_value,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value));
 SELECT * INTO replay FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Planning adoption request changed' USING ERRCODE='23505';END IF;SELECT * INTO current_row FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND service_key=replay.service_key AND planning_area=replay.planning_area AND metric_key=replay.metric_key AND basis=replay.basis ORDER BY revision DESC,id DESC LIMIT 1;selection:=public.canonical_job_outcome_planning_selection(org,actor,role_value,session_value,replay.service_key,replay.source_registry_id,rtrim(replay.source_registry_digest),rtrim(replay.source_preview_digest),replay.planning_area,replay.metric_key,replay.basis);IF current_row.id IS DISTINCT FROM replay.id OR selection->>'selectionDigest'<>rtrim(replay.source_selection_digest) THEN RAISE EXCEPTION 'Planning adoption changed' USING ERRCODE='40001';END IF;RETURN jsonb_build_object('planningValue',public.canonical_job_outcome_planning_value_projection(replay,actor,role_value,session_value),'replayed',TRUE);END IF;
 selection:=public.canonical_job_outcome_planning_selection(org,actor,role_value,session_value,service_value,registry_id_value,expected_registry_digest,expected_preview_digest,planning_area_value,metric_key_value,basis_value);IF selection->>'selectionDigest'<>expected_selection_digest THEN RAISE EXCEPTION 'Planning selection changed' USING ERRCODE='40001';END IF;SELECT * INTO current_row FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND service_key=service_value AND planning_area=planning_area_value AND metric_key=metric_key_value AND basis=basis_value ORDER BY revision DESC,id DESC LIMIT 1 FOR UPDATE;IF COALESCE(current_row.revision,0)<>expected_planning_revision OR COALESCE(rtrim(current_row.canonical_digest),'none')<>expected_planning_digest THEN RAISE EXCEPTION 'Planning value changed' USING ERRCODE='40001';END IF;
 next_revision:=COALESCE(current_row.revision,0)+1;effective_hash:=public.canonical_completion_digest(jsonb_build_object('state','active','multiplier',selection->>'multiplier','sourceRegistryId',registry_id_value,'sourceRegistryDigest',expected_registry_digest,'sourcePreviewDigest',expected_preview_digest,'sourceSelectionDigest',expected_selection_digest));IF current_row.value_state='active' AND rtrim(current_row.effective_digest)=effective_hash THEN RAISE EXCEPTION 'This exact planning value is already current' USING ERRCODE='22023';END IF;digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'serviceKey',service_value,'planningArea',planning_area_value,'metricKey',metric_key_value,'basis',basis_value,'revision',next_revision,'previousId',current_row.id,'action','adopt','valueState','active','multiplier',selection->>'multiplier','sourceRegistryId',registry_id_value,'sourceRegistryDigest',expected_registry_digest,'sourcePreviewDigest',expected_preview_digest,'sourceSelectionDigest',expected_selection_digest,'rollbackToId',NULL,'rollbackToDigest',NULL,'effectiveDigest',effective_hash,'actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'authSessionId',session_value,'reason',reason_value,'confirmationVersion',confirmation_version_value,'requestDigest',request_hash));
 INSERT INTO public.canonical_job_outcome_planning_value_versions(organization_id,service_key,planning_area,metric_key,basis,revision,previous_id,action,value_state,multiplier,source_registry_id,source_registry_digest,source_preview_digest,source_selection_digest,rollback_to_id,rollback_to_digest,effective_digest,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,request_key_hash,request_digest,canonical_digest)VALUES(org,service_value,planning_area_value,metric_key_value,basis_value,next_revision,current_row.id,'adopt','active',(selection->>'multiplier')::numeric,registry_id_value,expected_registry_digest,expected_preview_digest,expected_selection_digest,NULL,NULL,effective_hash,actor,(authority->>'membershipId')::uuid,session_value,reason_value,TRUE,confirmation_version_value,key_hash,request_hash,digest_value)RETURNING * INTO inserted;RETURN jsonb_build_object('planningValue',public.canonical_job_outcome_planning_value_projection(inserted,actor,role_value,session_value),'replayed',FALSE);
END $$;

CREATE FUNCTION public.canonical_job_outcome_planning_value_rollback(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,service_value TEXT,planning_area_value TEXT,metric_key_value TEXT,basis_value TEXT,expected_planning_revision BIGINT,expected_planning_digest TEXT,rollback_to_id_value UUID,expected_rollback_to_digest TEXT,reason_value TEXT,confirmed_value BOOLEAN,confirmation_version_value TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB;current_row public.canonical_job_outcome_planning_value_versions%ROWTYPE;target_row public.canonical_job_outcome_planning_value_versions%ROWTYPE;replay public.canonical_job_outcome_planning_value_versions%ROWTYPE;inserted public.canonical_job_outcome_planning_value_versions%ROWTYPE;key_hash TEXT;request_hash TEXT;effective_hash TEXT;digest_value TEXT;next_revision BIGINT;state_value TEXT;multiplier_value NUMERIC;registry_id_value UUID;registry_digest_value TEXT;preview_digest_value TEXT;selection_digest_value TEXT;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001';END IF;IF role_value IS DISTINCT FROM 'owner' THEN RAISE EXCEPTION 'Planning changes require the current owner' USING ERRCODE='42501';END IF;PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501';END IF;authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE);
 IF key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR planning_area_value IS NULL OR planning_area_value NOT IN('labor_planning','travel_planning','equipment_planning','material_planning') OR metric_key_value IS NULL OR metric_key_value!~'^[a-z][a-z0-9_]{1,63}$' OR basis_value IS NULL OR length(basis_value)NOT BETWEEN 1 AND 200 OR basis_value!~'^[A-Za-z0-9._:/| -]+$' OR expected_planning_revision IS NULL OR expected_planning_revision NOT BETWEEN 1 AND 10000 OR expected_planning_digest IS NULL OR expected_planning_digest!~'^[0-9a-f]{64}$' OR expected_rollback_to_digest IS NULL OR ((rollback_to_id_value IS NULL)<>(expected_rollback_to_digest='none')) OR (rollback_to_id_value IS NOT NULL AND expected_rollback_to_digest!~'^[0-9a-f]{64}$') OR public.canonical_learning_text_valid(reason_value,2000) IS NOT TRUE OR confirmed_value IS DISTINCT FROM TRUE OR confirmation_version_value IS DISTINCT FROM 'm25-job-outcome-planning-adoption-v1' THEN RAISE EXCEPTION 'Planning rollback details invalid' USING ERRCODE='22023';END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':job-outcome-planning:'||service_value||':'||planning_area_value||':'||metric_key_value||':'||basis_value,0));key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex');request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'actorUserId',actor,'serviceKey',service_value,'planningArea',planning_area_value,'metricKey',metric_key_value,'basis',basis_value,'expectedPlanningRevision',expected_planning_revision,'expectedPlanningDigest',expected_planning_digest,'rollbackToId',rollback_to_id_value,'expectedRollbackToDigest',expected_rollback_to_digest,'reason',reason_value,'confirmed',confirmed_value,'confirmationVersion',confirmation_version_value));
 SELECT * INTO replay FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;IF FOUND THEN IF rtrim(replay.request_digest)<>request_hash THEN RAISE EXCEPTION 'Planning rollback request changed' USING ERRCODE='23505';END IF;SELECT * INTO current_row FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND service_key=replay.service_key AND planning_area=replay.planning_area AND metric_key=replay.metric_key AND basis=replay.basis ORDER BY revision DESC,id DESC LIMIT 1;IF current_row.id IS DISTINCT FROM replay.id THEN RAISE EXCEPTION 'Planning rollback changed' USING ERRCODE='40001';END IF;RETURN jsonb_build_object('planningValue',public.canonical_job_outcome_planning_value_projection(replay,actor,role_value,session_value),'replayed',TRUE);END IF;
 SELECT * INTO current_row FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND service_key=service_value AND planning_area=planning_area_value AND metric_key=metric_key_value AND basis=basis_value ORDER BY revision DESC,id DESC LIMIT 1 FOR UPDATE;IF current_row.id IS NULL OR current_row.revision<>expected_planning_revision OR rtrim(current_row.canonical_digest)<>expected_planning_digest THEN RAISE EXCEPTION 'Planning value changed' USING ERRCODE='40001';END IF;
 IF rollback_to_id_value IS NULL THEN state_value:='unset';multiplier_value:=NULL;registry_id_value:=NULL;registry_digest_value:=NULL;preview_digest_value:=NULL;selection_digest_value:=NULL;ELSE SELECT * INTO target_row FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND id=rollback_to_id_value;IF target_row.id IS NULL OR target_row.service_key<>service_value OR target_row.planning_area<>planning_area_value OR target_row.metric_key<>metric_key_value OR target_row.basis<>basis_value OR target_row.revision>=current_row.revision OR rtrim(target_row.canonical_digest)<>expected_rollback_to_digest THEN RAISE EXCEPTION 'Rollback target changed' USING ERRCODE='40001';END IF;state_value:=target_row.value_state;multiplier_value:=target_row.multiplier;registry_id_value:=target_row.source_registry_id;registry_digest_value:=rtrim(target_row.source_registry_digest);preview_digest_value:=rtrim(target_row.source_preview_digest);selection_digest_value:=rtrim(target_row.source_selection_digest);END IF;
 effective_hash:=public.canonical_completion_digest(jsonb_build_object('state',state_value,'multiplier',multiplier_value::text,'sourceRegistryId',registry_id_value,'sourceRegistryDigest',registry_digest_value,'sourcePreviewDigest',preview_digest_value,'sourceSelectionDigest',selection_digest_value));IF rtrim(current_row.effective_digest)=effective_hash THEN RAISE EXCEPTION 'The selected rollback value is already current' USING ERRCODE='22023';END IF;next_revision:=current_row.revision+1;digest_value:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'serviceKey',service_value,'planningArea',planning_area_value,'metricKey',metric_key_value,'basis',basis_value,'revision',next_revision,'previousId',current_row.id,'action','rollback','valueState',state_value,'multiplier',multiplier_value::text,'sourceRegistryId',registry_id_value,'sourceRegistryDigest',registry_digest_value,'sourcePreviewDigest',preview_digest_value,'sourceSelectionDigest',selection_digest_value,'rollbackToId',rollback_to_id_value,'rollbackToDigest',CASE WHEN rollback_to_id_value IS NULL THEN NULL ELSE expected_rollback_to_digest END,'effectiveDigest',effective_hash,'actorUserId',actor,'membershipId',(authority->>'membershipId')::uuid,'authSessionId',session_value,'reason',reason_value,'confirmationVersion',confirmation_version_value,'requestDigest',request_hash));
 INSERT INTO public.canonical_job_outcome_planning_value_versions(organization_id,service_key,planning_area,metric_key,basis,revision,previous_id,action,value_state,multiplier,source_registry_id,source_registry_digest,source_preview_digest,source_selection_digest,rollback_to_id,rollback_to_digest,effective_digest,actor_user_id,membership_id,auth_session_id,reason,confirmed,confirmation_version,request_key_hash,request_digest,canonical_digest)VALUES(org,service_value,planning_area_value,metric_key_value,basis_value,next_revision,current_row.id,'rollback',state_value,multiplier_value,registry_id_value,registry_digest_value,preview_digest_value,selection_digest_value,rollback_to_id_value,CASE WHEN rollback_to_id_value IS NULL THEN NULL ELSE expected_rollback_to_digest END,effective_hash,actor,(authority->>'membershipId')::uuid,session_value,reason_value,TRUE,confirmation_version_value,key_hash,request_hash,digest_value)RETURNING * INTO inserted;RETURN jsonb_build_object('planningValue',public.canonical_job_outcome_planning_value_projection(inserted,actor,role_value,session_value),'replayed',FALSE);
END $$;

CREATE FUNCTION public.canonical_job_outcome_planning_value_read(org UUID,actor UUID,role_value TEXT,session_value UUID,service_value TEXT)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE current_values JSONB;history_values JSONB;total BIGINT;
BEGIN
 IF role_value IS DISTINCT FROM 'owner' THEN RAISE EXCEPTION 'Planning changes require the current owner' USING ERRCODE='42501';END IF;PERFORM public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,NULL,FALSE);IF service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' THEN RAISE EXCEPTION 'Planning service invalid' USING ERRCODE='22023';END IF;
 SELECT COALESCE(jsonb_agg(public.canonical_job_outcome_planning_value_projection(x,actor,role_value,session_value)ORDER BY planning_area,metric_key,basis),'[]'::jsonb)INTO current_values FROM(SELECT DISTINCT ON(planning_area,metric_key,basis)* FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND service_key=service_value ORDER BY planning_area,metric_key,basis,revision DESC,id DESC)x;SELECT count(*)INTO total FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND service_key=service_value;SELECT COALESCE(jsonb_agg(public.canonical_job_outcome_planning_value_projection(x,actor,role_value,session_value)ORDER BY created_at DESC,id DESC),'[]'::jsonb)INTO history_values FROM(SELECT * FROM public.canonical_job_outcome_planning_value_versions WHERE organization_id=org AND service_key=service_value ORDER BY created_at DESC,id DESC LIMIT 50)x;
 RETURN jsonb_build_object('serviceKey',service_value,'current',current_values,'history',history_values,'total',total,'truncated',total>50,'statusMessage',CASE WHEN total=0 THEN 'No owner-adopted planning values have been saved for this service.' ELSE 'Owner-adopted service planning values are available for review.' END,'changeBoundary','Only an explicit owner adoption or rollback changes these planning values.');
END $$;

REVOKE ALL ON TABLE public.canonical_job_outcome_planning_value_versions FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_planning_selection(UUID,UUID,TEXT,UUID,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_planning_value_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_planning_value_projection(public.canonical_job_outcome_planning_value_versions,UUID,TEXT,UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_planning_value_adopt(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT,BOOLEAN,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_planning_value_rollback(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,UUID,TEXT,TEXT,BOOLEAN,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_planning_value_read(UUID,UUID,TEXT,UUID,TEXT) FROM PUBLIC;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='northstar_app_runtime') THEN
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_planning_selection(UUID,UUID,TEXT,UUID,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT) TO northstar_app_runtime;
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_planning_value_adopt(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT,BOOLEAN,TEXT) TO northstar_app_runtime;
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_planning_value_rollback(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,UUID,TEXT,TEXT,BOOLEAN,TEXT) TO northstar_app_runtime;
 GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_planning_value_read(UUID,UUID,TEXT,UUID,TEXT) TO northstar_app_runtime;
END IF;END $$;
