-- Mission 25 Part 14A: bind imported-labor advice to one exact current calibration.
-- Native-labor proposals keep their accepted path. Imported-labor proposals fail closed
-- unless the selected summaries exactly equal one fresh calibration sample.

CREATE OR REPLACE FUNCTION public.canonical_job_outcome_proposal_basis(org UUID,actor UUID,role_value TEXT,session_value UUID,service_value TEXT,summary_ids JSONB)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE consent_value public.canonical_job_outcome_proposal_consents%ROWTYPE;graph_consent public.canonical_job_outcome_graph_consents%ROWTYPE;summary_row public.canonical_job_outcome_summaries%ROWTYPE;graph_row public.canonical_job_outcome_graphs%ROWTYPE;summary_projection JSONB;summary_id_value UUID;manifest JSONB:='[]'::jsonb;observations JSONB:='[]'::jsonb;metrics_value JSONB:='[]'::jsonb;domains_value JSONB:='[]'::jsonb;domain_name TEXT;metric_group RECORD;domain_metrics JSONB;domain_available BOOLEAN;cohort_size_value INTEGER;observation_count INTEGER;canonical_ids JSONB;proposal_value JSONB;cohort_digest_value TEXT;labor_node JSONB;labor_node_count INTEGER;imported_labor_count INTEGER:=0;native_labor_count INTEGER:=0;labor_source_value TEXT;selected_labor_ids JSONB:='[]'::jsonb;canonical_selected_labor_ids JSONB;calibration_read JSONB;calibration_current JSONB;calibration_observation_ids JSONB;calibration_pin JSONB;calibration_metric JSONB;
BEGIN
 IF service_value IS NULL OR service_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR jsonb_typeof(summary_ids)<>'array' OR jsonb_array_length(summary_ids) NOT BETWEEN 5 AND 100 OR octet_length(summary_ids::text)>8192 OR EXISTS(SELECT 1 FROM jsonb_array_elements(summary_ids)x WHERE jsonb_typeof(x)<>'string' OR x#>>'{}'!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') THEN RAISE EXCEPTION 'Cross-job proposal cohort invalid' USING ERRCODE='22023';END IF;
 SELECT jsonb_agg(to_jsonb(id)ORDER BY id)INTO canonical_ids FROM(SELECT DISTINCT (x#>>'{}')::uuid id FROM jsonb_array_elements(summary_ids)x)s;IF jsonb_array_length(canonical_ids)<>jsonb_array_length(summary_ids) OR canonical_ids<>summary_ids THEN RAISE EXCEPTION 'Cross-job proposal cohort must contain distinct sorted job summaries' USING ERRCODE='22023';END IF;
 consent_value:=public.canonical_job_outcome_proposal_consent_current(org);IF consent_value.id IS NULL THEN RAISE EXCEPTION 'Current cross-job proposal permission required' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_consent_unavailable';END IF;SELECT * INTO graph_consent FROM public.canonical_job_outcome_graph_consents WHERE organization_id=org AND id=consent_value.graph_consent_id;
 FOR summary_id_value IN SELECT (x#>>'{}')::uuid FROM jsonb_array_elements(summary_ids)x LOOP
  SELECT * INTO summary_row FROM public.canonical_job_outcome_summaries WHERE organization_id=org AND id=summary_id_value;
  IF summary_row.id IS NULL OR summary_row.consent_id<>graph_consent.id OR summary_row.id<>(SELECT id FROM public.canonical_job_outcome_summaries WHERE organization_id=org AND estimate_id=summary_row.estimate_id AND consent_id=graph_consent.id ORDER BY revision DESC,id DESC LIMIT 1) OR service_value<>(SELECT lower(btrim(opportunity.service_type)) FROM public.canonical_estimates estimate JOIN public.canonical_opportunities opportunity ON opportunity.organization_id=estimate.organization_id AND opportunity.id=estimate.opportunity_id WHERE estimate.organization_id=org AND estimate.id=summary_row.estimate_id) THEN RAISE EXCEPTION 'Every selected summary must be current and use the same service' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_cohort_unavailable';END IF;
  summary_projection:=public.canonical_job_outcome_summary_projection(summary_row,actor,role_value,session_value);IF summary_projection->'fresh' IS DISTINCT FROM 'true'::jsonb OR summary_projection->'summary' IS NULL THEN RAISE EXCEPTION 'Every selected summary must be current and available' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_cohort_unavailable';END IF;
  SELECT * INTO graph_row FROM public.canonical_job_outcome_graphs WHERE organization_id=org AND id=summary_row.graph_id;
  SELECT count(*),min(x::text)::jsonb INTO labor_node_count,labor_node FROM jsonb_array_elements(graph_row.node_manifest)x WHERE x->>'nodeKind' IN('native_labor','imported_labor');
  IF labor_node_count>1 THEN RAISE EXCEPTION 'Selected labor evidence is ambiguous' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_calibration_unavailable';END IF;
  IF labor_node_count=1 AND labor_node->>'nodeKind'='imported_labor' THEN
   imported_labor_count:=imported_labor_count+1;
   IF labor_source_value IS NULL THEN labor_source_value:=labor_node#>>'{locator,sourceKey}';ELSIF labor_source_value IS DISTINCT FROM labor_node#>>'{locator,sourceKey}' THEN RAISE EXCEPTION 'Selected imported labor calibrations are incompatible' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_calibration_unavailable';END IF;
   selected_labor_ids:=selected_labor_ids||jsonb_build_array(labor_node->'observationId');
  ELSIF labor_node_count=1 THEN native_labor_count:=native_labor_count+1;END IF;
  manifest:=manifest||jsonb_build_array(jsonb_build_object('summaryId',summary_row.id,'estimateId',summary_row.estimate_id,'summaryRevision',summary_row.revision,'summaryDigest',rtrim(summary_row.canonical_digest),'summarySourceDigest',rtrim(summary_row.source_digest),'graphId',summary_row.graph_id,'graphRevision',summary_row.graph_revision,'graphDigest',rtrim(summary_row.graph_digest),'evaluationId',summary_row.evaluation_id,'evaluationRevision',summary_row.evaluation_revision,'evaluationDigest',rtrim(summary_row.evaluation_digest)));
  metrics_value:=public.canonical_job_outcome_proposal_summary_metrics(summary_row.summary);observations:=observations||COALESCE((SELECT jsonb_agg(item||jsonb_build_object('summaryId',summary_row.id)ORDER BY item->>'domain',item->>'metricKey',item->>'basis')FROM jsonb_array_elements(metrics_value)item),'[]'::jsonb);
 END LOOP;
 cohort_size_value:=jsonb_array_length(manifest);
 IF imported_labor_count>0 THEN
  IF native_labor_count>0 OR imported_labor_count<>cohort_size_value THEN RAISE EXCEPTION 'Every selected job must use the same imported labor calibration' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_calibration_unavailable';END IF;
  SELECT jsonb_agg(to_jsonb(id)ORDER BY id) INTO canonical_selected_labor_ids FROM(SELECT DISTINCT (x#>>'{}')::uuid id FROM jsonb_array_elements(selected_labor_ids)x)s;
  IF jsonb_array_length(canonical_selected_labor_ids)<>imported_labor_count THEN RAISE EXCEPTION 'Imported labor observations must be distinct' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_calibration_unavailable';END IF;
  calibration_read:=public.canonical_imported_labor_calibration_read(org,actor,role_value,session_value,labor_source_value,service_value);calibration_current:=calibration_read->'current';
  IF calibration_current IS NULL OR calibration_current->'fresh' IS DISTINCT FROM 'true'::jsonb OR calibration_current->'advisoryAvailable' IS DISTINCT FROM 'true'::jsonb THEN RAISE EXCEPTION 'Current reviewed labor calibration is required' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_calibration_unavailable';END IF;
  SELECT jsonb_agg(to_jsonb(id)ORDER BY id) INTO calibration_observation_ids FROM(SELECT DISTINCT (x->>'observationId')::uuid id FROM jsonb_array_elements(calibration_current#>'{sampleManifest,observations}')x)s;
  IF calibration_observation_ids IS DISTINCT FROM canonical_selected_labor_ids OR (calibration_current->>'sampleSize')::integer<>cohort_size_value THEN RAISE EXCEPTION 'Selected jobs must exactly match the current reviewed labor calibration' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_calibration_unavailable';END IF;
  calibration_pin:=jsonb_build_object('id',calibration_current->'id','sourceKey',labor_source_value,'serviceKey',service_value,'revision',calibration_current->'revision','digest',calibration_current->'digest','consentId',calibration_current#>'{consent,id}','consentRevision',calibration_current#>'{consent,revision}','consentDigest',calibration_current#>'{consent,digest}','sampleDigest',calibration_current->'sampleDigest','sampleSize',calibration_current->'sampleSize','calculationVersion',calibration_current->'calculationVersion');
  SELECT jsonb_agg(item||jsonb_build_object('laborCalibration',calibration_pin)ORDER BY item->>'summaryId') INTO manifest FROM jsonb_array_elements(manifest)item;
  calibration_metric:=jsonb_build_object('metricKey','worker_hours','label','Worker hours','kind','multiplier','basis','Connected worker hours','sampleSize',cohort_size_value,'cohortSize',cohort_size_value,'coveragePercent','100.00','median',round((calibration_current->>'medianActualToPlannedRatio')::numeric,6)::text,'lowerQuartile',round((calibration_current->>'lowerQuartileRatio')::numeric,6)::text,'upperQuartile',round((calibration_current->>'upperQuartileRatio')::numeric,6)::text,'interquartileRange',round((calibration_current->>'upperQuartileRatio')::numeric-(calibration_current->>'lowerQuartileRatio')::numeric,6)::text,'advisoryAvailable',TRUE,'proposedValue',round((calibration_current->>'proposedPlannedHoursMultiplier')::numeric,6)::text,'advisoryCode',CASE calibration_current->>'advisoryCode' WHEN 'increase_planned_hours' THEN 'increase_planned_amount' WHEN 'decrease_planned_hours' THEN 'decrease_planned_amount' ELSE 'keep_current_assumption' END,'advisoryMessage',calibration_current->>'advisoryMessage','unavailableReason',NULL);
  SELECT COALESCE(jsonb_agg(item),'[]'::jsonb) INTO observations FROM jsonb_array_elements(observations)item WHERE item->>'domain'<>'labor';
 END IF;
 observation_count:=jsonb_array_length(observations);IF observation_count>10000 OR octet_length(observations::text)>2097152 THEN RAISE EXCEPTION 'Cross-job proposal evidence exceeds the bounded review size' USING ERRCODE='P0002',CONSTRAINT='job_outcome_proposal_cohort_too_broad';END IF;
 FOR domain_name IN SELECT unnest(ARRAY['labor','travel','equipment','materials','scope','financial']) LOOP
  domain_metrics:='[]'::jsonb;domain_available:=FALSE;
  IF domain_name='labor' AND calibration_metric IS NOT NULL THEN domain_metrics:=jsonb_build_array(calibration_metric);domain_available:=TRUE;
  ELSIF domain_name<>'scope' THEN
   FOR metric_group IN SELECT item->>'metricKey' metric_key,item->>'basis' basis,min(item->>'label') label,min(item->>'kind') kind FROM jsonb_array_elements(observations)item WHERE item->>'domain'=domain_name GROUP BY item->>'metricKey',item->>'basis' ORDER BY item->>'metricKey',item->>'basis' LOOP
    metrics_value:=public.canonical_job_outcome_proposal_metric(observations,cohort_size_value,domain_name,metric_group.metric_key,metric_group.basis,metric_group.label,metric_group.kind);domain_metrics:=domain_metrics||jsonb_build_array(metrics_value);IF metrics_value->'advisoryAvailable'='true'::jsonb THEN domain_available:=TRUE;END IF;
   END LOOP;
  END IF;
  domains_value:=domains_value||jsonb_build_array(jsonb_build_object('domain',domain_name,'status',CASE WHEN domain_available THEN 'advisory_available' ELSE 'unavailable' END,'metrics',domain_metrics,'message',CASE WHEN domain_available THEN 'Comparable recorded outcomes are available for owner review.' WHEN domain_name='scope' THEN 'Current scope records do not establish one reusable numeric planning value.' WHEN jsonb_array_length(domain_metrics)=0 THEN 'The selected jobs do not contain one comparable recorded measure for this area.' ELSE 'This area does not yet have five compatible current outcomes inside the advisory range.' END));
 END LOOP;
 cohort_digest_value:=public.canonical_completion_digest(jsonb_build_object('serviceKey',service_value,'graphConsentId',graph_consent.id,'graphConsentRevision',graph_consent.revision,'graphConsentDigest',rtrim(graph_consent.canonical_digest),'proposalConsentId',consent_value.id,'proposalConsentRevision',consent_value.revision,'proposalConsentDigest',rtrim(consent_value.canonical_digest),'summaries',manifest));
 proposal_value:=jsonb_build_object('version','m25-cross-job-proposal-generation-v1','serviceKey',service_value,'cohortSize',cohort_size_value,'domains',domains_value,'uncertaintyBoundary','Sample size, coverage, median, lower quartile, upper quartile and interquartile range describe only the selected comparable jobs. They are not a forecast or probability.','evidenceBoundary','Only current same-service job summaries with exact units, currencies and source lineage are compared. Imported labor advice also requires the exact current reviewed calibration for the same selected jobs. Missing, conflicting, stale or incompatible evidence remains unavailable and is never treated as zero.','adoptionBoundary','Review the cited jobs before changing a planning assumption. This proposal does not change an estimate, price, schedule, job, asset, material, financial record or company setting.');
 RETURN jsonb_build_object('graphConsent',jsonb_build_object('id',graph_consent.id,'revision',graph_consent.revision,'digest',rtrim(graph_consent.canonical_digest)),'proposalConsent',jsonb_build_object('id',consent_value.id,'revision',consent_value.revision,'digest',rtrim(consent_value.canonical_digest)),'cohortManifest',manifest,'cohortDigest',cohort_digest_value,'proposal',proposal_value,'sourceDigest',public.canonical_completion_digest(jsonb_build_object('cohortDigest',cohort_digest_value,'proposal',proposal_value)));
END $$;

CREATE OR REPLACE FUNCTION public.canonical_job_outcome_proposal_manifest_valid(value JSONB)
RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE item JSONB;pin JSONB;item_count INTEGER;summary_count INTEGER;estimate_count INTEGER;ordered_ids JSONB;observed_ids JSONB;standard_keys TEXT[]:=ARRAY['summaryId','estimateId','summaryRevision','summaryDigest','summarySourceDigest','graphId','graphRevision','graphDigest','evaluationId','evaluationRevision','evaluationDigest'];pinned_keys TEXT[]:=ARRAY['summaryId','estimateId','summaryRevision','summaryDigest','summarySourceDigest','graphId','graphRevision','graphDigest','evaluationId','evaluationRevision','evaluationDigest','laborCalibration'];
BEGIN
 IF jsonb_typeof(value) IS DISTINCT FROM 'array' OR octet_length(value::text)>1048576 OR jsonb_array_length(value) NOT BETWEEN 5 AND 100 THEN RETURN FALSE;END IF;
 SELECT count(*),count(DISTINCT x->>'summaryId'),count(DISTINCT x->>'estimateId'),jsonb_agg(x->'summaryId'),jsonb_agg(x->'summaryId' ORDER BY x->>'summaryId') INTO item_count,summary_count,estimate_count,observed_ids,ordered_ids FROM jsonb_array_elements(value)x;
 IF item_count<>summary_count OR item_count<>estimate_count OR observed_ids<>ordered_ids THEN RETURN FALSE;END IF;
 FOR item IN SELECT x FROM jsonb_array_elements(value)x LOOP
  IF NOT(public.canonical_field_evidence_object_keys_exact(item,standard_keys) OR public.canonical_field_evidence_object_keys_exact(item,pinned_keys)) OR (item->>'summaryId'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (item->>'estimateId'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (item->>'graphId'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (item->>'evaluationId'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (item->>'summaryRevision'~'^[1-9][0-9]{0,3}$|^10000$') IS NOT TRUE OR (item->>'graphRevision'~'^[1-9][0-9]{0,3}$|^10000$') IS NOT TRUE OR (item->>'evaluationRevision'~'^[1-9][0-9]{0,3}$|^10000$') IS NOT TRUE OR (item->>'summaryDigest'~'^[0-9a-f]{64}$') IS NOT TRUE OR (item->>'summarySourceDigest'~'^[0-9a-f]{64}$') IS NOT TRUE OR (item->>'graphDigest'~'^[0-9a-f]{64}$') IS NOT TRUE OR (item->>'evaluationDigest'~'^[0-9a-f]{64}$') IS NOT TRUE THEN RETURN FALSE;END IF;
  IF item ? 'laborCalibration' THEN pin:=item->'laborCalibration';IF jsonb_typeof(pin) IS DISTINCT FROM 'object' OR public.canonical_field_evidence_object_keys_exact(pin,ARRAY['id','sourceKey','serviceKey','revision','digest','consentId','consentRevision','consentDigest','sampleDigest','sampleSize','calculationVersion']) IS NOT TRUE OR (pin->>'id'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (pin->>'consentId'~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') IS NOT TRUE OR (pin->>'sourceKey'~'^[a-z0-9][a-z0-9._-]{1,63}$') IS NOT TRUE OR (pin->>'serviceKey'~'^[a-z0-9][a-z0-9._-]{1,63}$') IS NOT TRUE OR (pin->>'revision'~'^[1-9][0-9]{0,3}$|^10000$') IS NOT TRUE OR (pin->>'consentRevision'~'^[1-9][0-9]{0,3}$|^10000$') IS NOT TRUE OR (pin->>'sampleSize'~'^(?:[5-9]|[1-9][0-9]|100)$') IS NOT TRUE OR (pin->>'digest'~'^[0-9a-f]{64}$') IS NOT TRUE OR (pin->>'consentDigest'~'^[0-9a-f]{64}$') IS NOT TRUE OR (pin->>'sampleDigest'~'^[0-9a-f]{64}$') IS NOT TRUE OR pin->>'calculationVersion'<>'m25-imported-labor-median-calibration-v1' THEN RETURN FALSE;END IF;END IF;
 END LOOP;
 RETURN TRUE;
END $$;

REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_basis(UUID,UUID,TEXT,UUID,TEXT,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_job_outcome_proposal_manifest_valid(JSONB) FROM PUBLIC;
