-- Mission 25 Part 14C correction: return one safe public cleanup shape on first execution and replay.
-- PostgreSQL 17/18 compatible; protected migration 089 remains immutable.

CREATE FUNCTION public.canonical_external_labor_cleanup_projection(value public.canonical_external_labor_cleanup_runs)
RETURNS JSONB LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_build_object('id',value.id,'operation',value.operation,'sequence',value.sequence,
  'cursorAfter',value.cursor_after,'complete',value.complete,'tombstonedCount',value.tombstoned_count,
  'digest',rtrim(value.canonical_digest))
$$;
CREATE OR REPLACE FUNCTION public.canonical_external_labor_cleanup_execute(org UUID,actor UUID,role_value TEXT,session_value UUID,csrf TEXT,key_value TEXT,source_value TEXT,body JSONB)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE authority JSONB; authority_value JSONB; previous_run public.canonical_external_labor_cleanup_runs%ROWTYPE; replay_run public.canonical_external_labor_cleanup_runs%ROWTYPE;
 key_hash TEXT; request_hash TEXT; run_id UUID:=gen_random_uuid(); digest_value TEXT; sequence_value BIGINT; selected_count INTEGER; has_more BOOLEAN; next_cursor TEXT; record_row public.canonical_external_labor_import_records%ROWTYPE; record_digest TEXT; operation_value TEXT;
BEGIN
 IF current_setting('transaction_isolation')<>'serializable' THEN RAISE EXCEPTION 'Serializable required' USING ERRCODE='25001'; END IF;
 IF role_value IS NULL OR role_value NOT IN ('owner','admin') THEN RAISE EXCEPTION 'Cleanup restricted' USING ERRCODE='42501'; END IF;
 PERFORM 1 FROM public.subscriptions WHERE organization_id=org FOR SHARE; IF NOT FOUND THEN RAISE EXCEPTION 'Subscription unavailable' USING ERRCODE='42501'; END IF;
 authority:=public.canonical_field_execution_actor_authority(org,actor,role_value,session_value,csrf,TRUE); operation_value:=body->>'operation';
 IF source_value IS NULL OR source_value!~'^[a-z0-9][a-z0-9._-]{1,63}$' OR key_value IS NULL OR key_value!~'^[A-Za-z0-9._:-]{16,128}$' OR operation_value NOT IN ('retention','deletion') OR public.canonical_field_evidence_object_keys_exact(body,ARRAY['operation','expectedRevision','expectedDigest','cursorBefore','limit','confirmed']) IS NOT TRUE OR body->'confirmed' IS DISTINCT FROM 'true'::jsonb OR (body->>'expectedRevision')!~'^([1-9][0-9]{0,3}|10000)$' OR body->>'expectedDigest'!~'^[0-9a-f]{64}$' OR (body->'cursorBefore'<>'null'::jsonb AND (jsonb_typeof(body->'cursorBefore') IS DISTINCT FROM 'string' OR char_length(body->>'cursorBefore') NOT BETWEEN 1 AND 128 OR body->>'cursorBefore'!~'^[!-~]+$')) OR (body->>'limit')!~'^[0-9]+$' OR (body->>'limit')::integer NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'Cleanup invalid' USING ERRCODE='22023'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(org::text||':external-labor-cleanup:'||source_value||':'||operation_value,0));
 key_hash:=encode(sha256(convert_to(key_value,'UTF8')),'hex'); request_hash:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'body',body));
 SELECT * INTO replay_run FROM public.canonical_external_labor_cleanup_runs WHERE organization_id=org AND actor_user_id=actor AND request_key_hash=key_hash;
 IF FOUND THEN IF rtrim(replay_run.request_digest)<>request_hash THEN RAISE EXCEPTION 'Cleanup key conflict' USING ERRCODE='23505'; END IF; RETURN jsonb_build_object('run',public.canonical_external_labor_cleanup_projection(replay_run),'replayed',TRUE); END IF;
 IF operation_value='retention' THEN SELECT to_jsonb(item) INTO authority_value FROM (SELECT * FROM public.canonical_external_labor_retention_revisions WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1 FOR UPDATE) item; ELSE SELECT to_jsonb(item) INTO authority_value FROM (SELECT * FROM public.canonical_external_labor_deletion_revisions WHERE organization_id=org AND source_key=source_value ORDER BY revision DESC LIMIT 1 FOR UPDATE) item; END IF;
 IF COALESCE((authority_value->>'revision')::bigint,0)<>(body->>'expectedRevision')::bigint OR COALESCE(rtrim(authority_value->>'canonical_digest'),'none') IS DISTINCT FROM body->>'expectedDigest' OR (operation_value='retention' AND authority_value->>'action'<>'set') OR (operation_value='deletion' AND authority_value->>'action'<>'request') THEN RAISE EXCEPTION 'Cleanup authority changed' USING ERRCODE='40001'; END IF;
 SELECT * INTO previous_run FROM public.canonical_external_labor_cleanup_runs WHERE organization_id=org AND source_key=source_value AND operation=operation_value
  AND authority_revision=(authority_value->>'revision')::bigint AND rtrim(authority_digest)=rtrim(authority_value->>'canonical_digest') ORDER BY sequence DESC LIMIT 1 FOR UPDATE;
 IF previous_run.id IS NOT NULL AND NOT previous_run.complete AND previous_run.cursor_after IS DISTINCT FROM body->>'cursorBefore' THEN RAISE EXCEPTION 'Cleanup cursor changed' USING ERRCODE='40001'; END IF;
 IF (previous_run.id IS NULL OR previous_run.complete) AND body->'cursorBefore'<>'null'::jsonb THEN RAISE EXCEPTION 'Cleanup cursor changed' USING ERRCODE='40001'; END IF;
 CREATE TEMP TABLE selected_cleanup_records ON COMMIT DROP AS WITH current_records AS (SELECT DISTINCT ON (external_record_id) * FROM public.canonical_external_labor_import_records WHERE organization_id=org AND source_key=source_value ORDER BY external_record_id,revision DESC) SELECT * FROM current_records WHERE state='active' AND (body->'cursorBefore'='null'::jsonb OR external_record_id>body->>'cursorBefore') AND (operation_value='deletion' OR source_updated_at<transaction_timestamp()-make_interval(days=>(authority_value->>'retention_days')::integer)) ORDER BY external_record_id LIMIT (body->>'limit')::integer+1;
 SELECT count(*) INTO selected_count FROM selected_cleanup_records; has_more:=selected_count>(body->>'limit')::integer;
 IF selected_count=0 THEN RETURN jsonb_build_object('run',NULL,'replayed',FALSE,'complete',TRUE,'tombstonedCount',0); END IF;
 DELETE FROM selected_cleanup_records WHERE external_record_id=(SELECT max(external_record_id) FROM selected_cleanup_records) AND has_more; SELECT count(*),max(external_record_id) INTO selected_count,next_cursor FROM selected_cleanup_records; IF NOT has_more THEN next_cursor:=NULL; END IF;
 SELECT COALESCE(max(sequence),0)+1 INTO sequence_value FROM public.canonical_external_labor_cleanup_runs WHERE organization_id=org AND source_key=source_value AND operation=operation_value;
 digest_value:=public.canonical_completion_digest(jsonb_build_object('id',run_id,'organizationId',org,'sourceKey',source_value,'operation',operation_value,'sequence',sequence_value,'previousRunId',previous_run.id,'authorityRevision',(authority_value->>'revision')::bigint,'authorityDigest',rtrim(authority_value->>'canonical_digest'),'cursorBefore',body->>'cursorBefore','cursorAfter',next_cursor,'complete',NOT has_more,'tombstonedCount',selected_count,'actorUserId',actor,'requestDigest',request_hash));
 INSERT INTO public.canonical_external_labor_cleanup_runs(id,organization_id,source_key,operation,sequence,previous_run_id,authority_revision,authority_digest,cursor_before,cursor_after,complete,tombstoned_count,actor_user_id,membership_id,auth_session_id,request_key_hash,request_digest,canonical_digest) VALUES(run_id,org,source_value,operation_value,sequence_value,previous_run.id,(authority_value->>'revision')::bigint,rtrim(authority_value->>'canonical_digest'),body->>'cursorBefore',next_cursor,NOT has_more,selected_count,actor,(authority->>'membershipId')::uuid,session_value,key_hash,request_hash,digest_value);
 FOR record_row IN SELECT * FROM selected_cleanup_records ORDER BY external_record_id LOOP
  record_digest:=public.canonical_completion_digest(jsonb_build_object('organizationId',org,'sourceKey',source_value,'externalRecordId',record_row.external_record_id,'externalVersion',record_row.external_version+1,'state','tombstone','workerReference',NULL,'jobReference',NULL,'category',NULL,'observedStart',NULL,'observedEnd',NULL,'sourceUpdatedAt',transaction_timestamp(),'cleanupRunId',run_id));
  INSERT INTO public.canonical_external_labor_import_records(organization_id,source_key,external_record_id,revision,previous_id,external_version,state,worker_reference,job_reference,category,observed_start,observed_end,source_updated_at,source_digest,import_run_id,cleanup_run_id) VALUES(org,source_value,record_row.external_record_id,record_row.revision+1,record_row.id,record_row.external_version+1,'tombstone',NULL,NULL,NULL,NULL,NULL,transaction_timestamp(),record_digest,record_row.import_run_id,run_id);
 END LOOP;
 SELECT * INTO replay_run FROM public.canonical_external_labor_cleanup_runs WHERE id=run_id;
 RETURN jsonb_build_object('run',public.canonical_external_labor_cleanup_projection(replay_run),'replayed',FALSE);
END $$;
REVOKE ALL ON FUNCTION public.canonical_external_labor_cleanup_projection(public.canonical_external_labor_cleanup_runs) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canonical_external_labor_cleanup_execute(UUID,UUID,TEXT,UUID,TEXT,TEXT,TEXT,JSONB) FROM PUBLIC;