'use strict';
function mapped(error){const constraint=String(error&&error.constraint||'');const result=Object.assign(new Error('Imported material outcome learning is temporarily unavailable.'),{code:'M25_IMPORTED_MATERIAL_OUTCOME_UNAVAILABLE',status:503,cause:error});if(error&&error.code==='42501')Object.assign(result,{code:'M25_IMPORTED_MATERIAL_OUTCOME_FORBIDDEN',status:403,message:'Imported material outcome learning is restricted to current owners and administrators.'});else if(error&&error.code==='40001')Object.assign(result,{code:'M25_IMPORTED_MATERIAL_OUTCOME_CHANGED',status:409,message:'Material source permission, outcome consent, plan, reviewed links or imported evidence changed. Refresh before continuing.'});else if(error&&error.code==='23505')Object.assign(result,{code:'M25_IMPORTED_MATERIAL_OUTCOME_KEY_CONFLICT',status:409,message:'That request key was already used for a different imported material decision.'});else if(error&&error.code==='22023')Object.assign(result,constraint==='imported_material_outcome_already_current'?{code:'M25_IMPORTED_MATERIAL_OUTCOME_CURRENT',status:409,message:'The current imported material outcome is already recorded.'}:{code:'M25_IMPORTED_MATERIAL_OUTCOME_INPUT_INVALID',status:400,message:'Imported material outcome details are invalid.'});else if(error&&error.code==='P0002')Object.assign(result,{code:'M25_IMPORTED_MATERIAL_OUTCOME_EVIDENCE_INCOMPLETE',status:409,message:constraint.includes('plan')?'A current adopted material plan is required.':constraint.includes('match')?'Current reviewed job and material links are required.':constraint.includes('binding')?'Every planned line needs one distinct recorded material reference.':'Current imported material evidence is incomplete.'});return result;}
async function tx(pool,isolation,work){for(let attempt=0;attempt<3;attempt+=1){const client=await pool.connect();try{await client.query(`BEGIN ISOLATION LEVEL ${isolation}`);await client.query("SET LOCAL statement_timeout='5000ms'");await client.query("SET LOCAL lock_timeout='2000ms'");await client.query("SET LOCAL idle_in_transaction_session_timeout='5000ms'");await client.query('SET LOCAL search_path=pg_catalog,public');const value=await work(client);await client.query('COMMIT');return value;}catch(error){await client.query('ROLLBACK').catch(()=>{});if(['40001','23505'].includes(error&&error.code)&&attempt<2)continue;throw mapped(error);}finally{client.release();}}throw mapped(Object.assign(new Error('Imported material outcome changed.'),{code:'40001'}));}
const actor=input=>[input.organizationId,input.actorUserId,input.actorAccessRole,input.authSessionId];
const readConsent=(pool,input)=>tx(pool,'REPEATABLE READ READ ONLY',async client=>(await client.query('SELECT public.canonical_imported_material_outcome_consent_read($1,$2,$3,$4,$5) value',[...actor(input),input.sourceKey])).rows[0].value);
const mutateConsent=(pool,input)=>tx(pool,'SERIALIZABLE',async client=>(await client.query('SELECT public.canonical_imported_material_outcome_consent_mutate($1,$2,$3,$4,$5,$6,$7,$8::jsonb) value',[...actor(input),input.csrfToken,input.idempotencyKey,input.sourceKey,JSON.stringify(input.body)])).rows[0].value);
const observe=(pool,input)=>tx(pool,'SERIALIZABLE',async client=>(await client.query('SELECT public.canonical_imported_material_quantity_observe($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13,$14,$15) value',[...actor(input),input.csrfToken,input.idempotencyKey,input.sourceKey,input.estimateId,input.externalJobReference,input.expectedConsentRevision,input.expectedConsentDigest,JSON.stringify(input.bindings),input.reason,input.confirmed,input.confirmationVersion])).rows[0].value);
const readOutcome=(pool,input)=>tx(pool,'REPEATABLE READ READ ONLY',async client=>(await client.query('SELECT public.canonical_imported_material_quantity_read($1,$2,$3,$4,$5,$6) value',[...actor(input),input.sourceKey,input.estimateId])).rows[0].value);
module.exports={readConsent,mutateConsent,observe,readOutcome};
