'use strict';
function mapped(error) {
  const constraint = String(error && error.constraint || '');
  const result = Object.assign(new Error('Imported asset health learning is temporarily unavailable.'), { code: 'M25_IMPORTED_ASSET_HEALTH_UNAVAILABLE', status: 503, cause: error });
  if (error && error.code === '42501') Object.assign(result, { code: 'M25_IMPORTED_ASSET_HEALTH_FORBIDDEN', status: 403, message: 'Imported asset health learning is restricted to current owners and administrators.' });
  else if (error && error.code === '40001') Object.assign(result, { code: 'M25_IMPORTED_ASSET_HEALTH_CHANGED', status: 409, message: 'Source consent, learning consent, reviewed asset match, asset record, or imported evidence changed. Refresh before continuing.' });
  else if (error && error.code === '23505') Object.assign(result, { code: 'M25_IMPORTED_ASSET_HEALTH_KEY_CONFLICT', status: 409, message: 'That request key was already used for a different asset health decision.' });
  else if (error && error.code === '22023') Object.assign(result, constraint === 'asset_health_outcome_already_current' ? { code: 'M25_IMPORTED_ASSET_HEALTH_CURRENT', status: 409, message: 'The current asset health outcome is already recorded.' } : { code: 'M25_IMPORTED_ASSET_HEALTH_INPUT_INVALID', status: 400, message: 'Imported asset health outcome details are invalid.' });
  else if (error && error.code === 'P0002') Object.assign(result, { code: 'M25_IMPORTED_ASSET_HEALTH_EVIDENCE_INCOMPLETE', status: 409, message: constraint.includes('lineage') ? 'A current reviewed asset match and current maintenance or downtime evidence are required.' : 'Current source and asset health learning consent are required.' });
  return result;
}
async function tx(pool, isolation, work) { const client = await pool.connect(); try { await client.query(`BEGIN ISOLATION LEVEL ${isolation}`); await client.query("SET LOCAL statement_timeout='5000ms'"); await client.query("SET LOCAL lock_timeout='2000ms'"); await client.query("SET LOCAL idle_in_transaction_session_timeout='5000ms'"); await client.query('SET LOCAL search_path=pg_catalog,public'); const value = await work(client); await client.query('COMMIT'); return value; } catch (error) { await client.query('ROLLBACK').catch(() => {}); throw mapped(error); } finally { client.release(); } }
const actor = input => [input.organizationId,input.actorUserId,input.actorAccessRole,input.authSessionId];
const readConsent = (pool,input) => tx(pool,'REPEATABLE READ READ ONLY',async client => (await client.query('SELECT public.canonical_imported_asset_health_consent_read($1,$2,$3,$4,$5) value',[...actor(input),input.sourceKey])).rows[0].value);
const mutateConsent = (pool,input) => tx(pool,'SERIALIZABLE',async client => (await client.query('SELECT public.canonical_imported_asset_health_consent_mutate($1,$2,$3,$4,$5,$6,$7,$8::jsonb) value',[...actor(input),input.csrfToken,input.idempotencyKey,input.sourceKey,JSON.stringify(input.body)])).rows[0].value);
const observe = (pool,input) => tx(pool,'SERIALIZABLE',async client => (await client.query('SELECT public.canonical_imported_asset_health_observe($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) value',[...actor(input),input.csrfToken,input.idempotencyKey,input.sourceKey,input.assetCategory,input.externalAssetReference,input.expectedConsentRevision,input.expectedConsentDigest,input.reason,input.confirmed,input.confirmationVersion])).rows[0].value);
const readOutcome = (pool,input) => tx(pool,'REPEATABLE READ READ ONLY',async client => (await client.query('SELECT public.canonical_imported_asset_health_read($1,$2,$3,$4,$5,$6,$7) value',[...actor(input),input.sourceKey,input.assetCategory,input.externalAssetReference])).rows[0].value);
module.exports = { readConsent, mutateConsent, observe, readOutcome };
