'use strict';
const { normalizeSourceKey }=require('./externalMaterialImportContract');
const DIGEST=/^[0-9a-f]{64}$/,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,OPAQUE=/^[\x21-\x7e]{1,128}$/;
const exact=(value,keys)=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join('|')===[...keys].sort().join('|');
const text=value=>typeof value==='string'&&value===value.trim()&&value===value.normalize('NFC')&&value.length>=1&&value.length<=2000&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(value);
function fail(){throw Object.assign(new Error('Imported material cost and purchasing details are invalid.'),{code:'M25_IMPORTED_MATERIAL_COST_INPUT_INVALID',status:400});}
function normalizeEstimateId(value){if(!UUID.test(String(value||'')))fail();return value.toLowerCase();}
function normalizeConsent(sourceKey,body){const source=normalizeSourceKey(sourceKey);if(!exact(body,['action','expectedRevision','expectedDigest','reason','confirmed','confirmationVersion'])||!['grant','revoke'].includes(body.action)||!Number.isInteger(body.expectedRevision)||body.expectedRevision<0||body.expectedRevision>10000||!(body.expectedDigest==='none'||DIGEST.test(String(body.expectedDigest||'')))||((body.expectedRevision===0)!==(body.expectedDigest==='none'))||!text(body.reason)||body.confirmed!==true||body.confirmationVersion!=='m25-imported-material-cost-consent-v1')fail();return Object.freeze({sourceKey:source,...body});}
function normalizeObservation(sourceKey,estimateId,body){const source=normalizeSourceKey(sourceKey),estimate=normalizeEstimateId(estimateId);if(!exact(body,['externalJobReference','expectedConsentRevision','expectedConsentDigest','bindings','reason','confirmed','confirmationVersion'])||!OPAQUE.test(String(body.externalJobReference||''))||!Number.isInteger(body.expectedConsentRevision)||body.expectedConsentRevision<1||body.expectedConsentRevision>10000||!DIGEST.test(String(body.expectedConsentDigest||''))||!Array.isArray(body.bindings)||body.bindings.length<1||body.bindings.length>20||!text(body.reason)||body.confirmed!==true||body.confirmationVersion!=='m25-imported-material-cost-observation-v1')fail();const lines=new Set(),materials=new Set();const normalized=[];for(const value of body.bindings){if(!exact(value,['lineId','externalMaterialReference','externalVendorReference','externalInventoryLocationReference'])||!UUID.test(String(value.lineId||''))||!OPAQUE.test(String(value.externalMaterialReference||''))||!(value.externalVendorReference===null||OPAQUE.test(String(value.externalVendorReference||'')))||!(value.externalInventoryLocationReference===null||OPAQUE.test(String(value.externalInventoryLocationReference||'')))||lines.has(value.lineId.toLowerCase())||materials.has(value.externalMaterialReference))fail();lines.add(value.lineId.toLowerCase());materials.add(value.externalMaterialReference);normalized.push(Object.freeze({...value,lineId:value.lineId.toLowerCase()}));}return Object.freeze({sourceKey:source,estimateId:estimate,...body,bindings:normalized});}
module.exports={normalizeEstimateId,normalizeConsent,normalizeObservation};
