'use strict';

function mapped(error){const constraint=String(error&&error.constraint||'');const result=Object.assign(new Error('Cross-job proposal review is temporarily unavailable.'),{code:'M25_JOB_OUTCOME_PROPOSAL_UNAVAILABLE',status:503,cause:error});if(error&&error.code==='42501')Object.assign(result,{code:'M25_JOB_OUTCOME_PROPOSAL_FORBIDDEN',status:403,message:'Cross-job proposal review is restricted to current owners and administrators.'});else if(error&&error.code==='40001')Object.assign(result,{code:'M25_JOB_OUTCOME_PROPOSAL_CHANGED',status:409,message:'Permission or one of the selected job summaries changed. Refresh before continuing.'});else if(error&&error.code==='23505')Object.assign(result,{code:'M25_JOB_OUTCOME_PROPOSAL_KEY_CONFLICT',status:409,message:'That request key was already used for different proposal details.'});else if(error&&error.code==='22023')Object.assign(result,{code:'M25_JOB_OUTCOME_PROPOSAL_INPUT_INVALID',status:400,message:constraint.includes('too_broad')?'The selected evidence is too large for one review.':'Cross-job proposal details are invalid.'});else if(error&&error.code==='P0002'&&constraint.includes('calibration'))Object.assign(result,{code:'M25_JOB_OUTCOME_PROPOSAL_CALIBRATION_REQUIRED',status:409,message:'The current labor calibration is missing, out of date, or does not cover the selected jobs. Create or refresh it before preparing this advice.'});else if(error&&error.code==='P0002')Object.assign(result,{code:'M25_JOB_OUTCOME_PROPOSAL_EVIDENCE_INCOMPLETE',status:409,message:constraint.includes('consent')?'Current permission is required before preparing cross-job advice.':'Every selected summary must be current and use the same service.'});return result;}
async function tx(pool,isolation,work){for(let attempt=0;attempt<3;attempt+=1){const client=await pool.connect();try{await client.query(`BEGIN ISOLATION LEVEL ${isolation}`);await client.query("SET LOCAL statement_timeout='5000ms'");await client.query("SET LOCAL lock_timeout='2000ms'");await client.query("SET LOCAL idle_in_transaction_session_timeout='5000ms'");await client.query('SET LOCAL search_path=pg_catalog,public');const value=await work(client);await client.query('COMMIT');return value;}catch(error){await client.query('ROLLBACK').catch(()=>{});if(error&&['40001','23505'].includes(error.code)&&attempt<2)continue;throw mapped(error);}finally{client.release();}}throw mapped(Object.assign(new Error('Cross-job proposal evidence changed.'),{code:'40001'}));}
const actor=input=>[input.organizationId,input.actorUserId,input.actorAccessRole,input.authSessionId];
const readConsent=(pool,input)=>tx(pool,'REPEATABLE READ READ ONLY',async client=>(await client.query('SELECT public.canonical_job_outcome_proposal_consent_read($1,$2,$3,$4) value',actor(input))).rows[0].value);
const mutateConsent=(pool,input)=>tx(pool,'SERIALIZABLE',async client=>(await client.query('SELECT public.canonical_job_outcome_proposal_consent_mutate($1,$2,$3,$4,$5,$6,$7::jsonb) value',[...actor(input),input.csrfToken,input.idempotencyKey,JSON.stringify(input.body)])).rows[0].value);
const build=(pool,input)=>tx(pool,'SERIALIZABLE',async client=>(await client.query('SELECT public.canonical_job_outcome_cross_job_proposal_build($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12,$13) value',[...actor(input),input.csrfToken,input.idempotencyKey,input.serviceKey,input.expectedConsentRevision,input.expectedConsentDigest,JSON.stringify(input.summaryIds),input.reason,input.confirmed,input.confirmationVersion])).rows[0].value);
const read=(pool,input)=>tx(pool,'REPEATABLE READ READ ONLY',async client=>(await client.query('SELECT public.canonical_job_outcome_cross_job_proposal_read($1,$2,$3,$4,$5) value',[...actor(input),input.serviceKey])).rows[0].value);
module.exports={build,mapped,mutateConsent,read,readConsent};
