'use strict';

function mapped(error){const constraint=String(error&&error.constraint||'');const result=Object.assign(new Error('Proposal registry review is temporarily unavailable.'),{code:'M25_JOB_OUTCOME_REGISTRY_UNAVAILABLE',status:503,cause:error});if(error&&error.code==='42501')Object.assign(result,{code:'M25_JOB_OUTCOME_REGISTRY_FORBIDDEN',status:403,message:'Proposal registry review is restricted to current owners and administrators.'});else if(error&&error.code==='40001')Object.assign(result,{code:'M25_JOB_OUTCOME_REGISTRY_CHANGED',status:409,message:'The proposal, preview or saved registry changed. Refresh before continuing.'});else if(error&&error.code==='23505')Object.assign(result,{code:'M25_JOB_OUTCOME_REGISTRY_KEY_CONFLICT',status:409,message:'That request key was already used for different registry details.'});else if(error&&error.code==='22023')Object.assign(result,{code:'M25_JOB_OUTCOME_REGISTRY_INPUT_INVALID',status:400,message:'Proposal registry details are invalid.'});else if(error&&error.code==='P0002')Object.assign(result,{code:'M25_JOB_OUTCOME_REGISTRY_EVIDENCE_UNAVAILABLE',status:409,message:constraint.includes('consent')?'Current permission is required before saving proposal previews.':'The selected proposal is no longer available.'});return result;}
async function tx(pool,isolation,work){for(let attempt=0;attempt<3;attempt+=1){const client=await pool.connect();try{await client.query(`BEGIN ISOLATION LEVEL ${isolation}`);await client.query("SET LOCAL statement_timeout='5000ms'");await client.query("SET LOCAL lock_timeout='2000ms'");await client.query("SET LOCAL idle_in_transaction_session_timeout='5000ms'");await client.query('SET LOCAL search_path=pg_catalog,public');const value=await work(client);await client.query('COMMIT');return value;}catch(error){await client.query('ROLLBACK').catch(()=>{});if(error&&['40001','23505'].includes(error.code)&&attempt<2)continue;throw mapped(error);}finally{client.release();}}throw mapped(Object.assign(new Error('Proposal registry changed.'),{code:'40001'}));}
const actor=input=>[input.organizationId,input.actorUserId,input.actorAccessRole,input.authSessionId];
const preview=(pool,input)=>tx(pool,'REPEATABLE READ READ ONLY',async client=>(await client.query('SELECT public.canonical_job_outcome_registry_impact($1,$2,$3,$4,$5,$6,$7) value',[...actor(input),input.serviceKey,input.proposalId,input.expectedProposalDigest])).rows[0].value);
const read=(pool,input)=>tx(pool,'REPEATABLE READ READ ONLY',async client=>(await client.query('SELECT public.canonical_job_outcome_proposal_registry_read($1,$2,$3,$4,$5) value',[...actor(input),input.serviceKey])).rows[0].value);
const save=(pool,input)=>tx(pool,'SERIALIZABLE',async client=>(await client.query('SELECT public.canonical_job_outcome_proposal_registry_create($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) value',[...actor(input),input.csrfToken,input.idempotencyKey,input.serviceKey,input.proposalId,input.expectedProposalDigest,input.expectedPreviewDigest,input.expectedRegistryRevision,input.expectedRegistryDigest,input.reason,input.confirmed,input.confirmationVersion])).rows[0].value);
module.exports={mapped,preview,read,save};
