'use strict';

function mapped(error){const constraint=String(error&&error.constraint||'');const result=Object.assign(new Error('Service planning values are temporarily unavailable.'),{code:'M25_JOB_OUTCOME_PLANNING_UNAVAILABLE',status:503,cause:error});if(error&&error.code==='42501')Object.assign(result,{code:'M25_JOB_OUTCOME_PLANNING_FORBIDDEN',status:403,message:'Planning changes require the current owner.'});else if(error&&error.code==='40001')Object.assign(result,{code:'M25_JOB_OUTCOME_PLANNING_CHANGED',status:409,message:'The saved proposal or planning value changed. Refresh before continuing.'});else if(error&&error.code==='23505')Object.assign(result,{code:'M25_JOB_OUTCOME_PLANNING_KEY_CONFLICT',status:409,message:'That request was already used with different planning details.'});else if(error&&error.code==='22023'||error&&error.code==='23514')Object.assign(result,{code:'M25_JOB_OUTCOME_PLANNING_INPUT_INVALID',status:400,message:'Planning value details are invalid.'});else if(error&&error.code==='P0002')Object.assign(result,{code:'M25_JOB_OUTCOME_PLANNING_EVIDENCE_UNAVAILABLE',status:409,message:constraint.includes('consent')?'Current proposal permission is required before adopting a planning value.':'The selected planning evidence is no longer available.'});return result;}
async function tx(pool,isolation,work){for(let attempt=0;attempt<3;attempt+=1){const client=await pool.connect();try{await client.query(`BEGIN ISOLATION LEVEL ${isolation}`);await client.query("SET LOCAL statement_timeout='5000ms'");await client.query("SET LOCAL lock_timeout='2000ms'");await client.query("SET LOCAL idle_in_transaction_session_timeout='5000ms'");await client.query('SET LOCAL search_path=pg_catalog,public');const value=await work(client);await client.query('COMMIT');return value;}catch(error){await client.query('ROLLBACK').catch(()=>{});if(error&&['40001','23505'].includes(error.code)&&attempt<2)continue;throw mapped(error);}finally{client.release();}}throw mapped(Object.assign(new Error('Planning value changed.'),{code:'40001'}));}
const actor=input=>[input.organizationId,input.actorUserId,input.actorAccessRole,input.authSessionId];
const preview=(pool,input)=>tx(pool,'REPEATABLE READ READ ONLY',async client=>(await client.query('SELECT public.canonical_job_outcome_planning_selection($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) value',[...actor(input),input.serviceKey,input.registryVersionId,input.expectedRegistryDigest,input.expectedPreviewDigest,input.planningArea,input.metricKey,input.basis])).rows[0].value);
const read=(pool,input)=>tx(pool,'REPEATABLE READ READ ONLY',async client=>(await client.query('SELECT public.canonical_job_outcome_planning_value_read($1,$2,$3,$4,$5) value',[...actor(input),input.serviceKey])).rows[0].value);
const adopt=(pool,input)=>tx(pool,'SERIALIZABLE',async client=>(await client.query('SELECT public.canonical_job_outcome_planning_value_adopt($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) value',[...actor(input),input.csrfToken,input.idempotencyKey,input.serviceKey,input.registryVersionId,input.expectedRegistryDigest,input.expectedPreviewDigest,input.planningArea,input.metricKey,input.basis,input.expectedSelectionDigest,input.expectedPlanningRevision,input.expectedPlanningDigest,input.reason,input.confirmed,input.confirmationVersion])).rows[0].value);
const rollback=(pool,input)=>tx(pool,'SERIALIZABLE',async client=>(await client.query('SELECT public.canonical_job_outcome_planning_value_rollback($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) value',[...actor(input),input.csrfToken,input.idempotencyKey,input.serviceKey,input.planningArea,input.metricKey,input.basis,input.expectedPlanningRevision,input.expectedPlanningDigest,input.rollbackToId,input.expectedRollbackToDigest,input.reason,input.confirmed,input.confirmationVersion])).rows[0].value);
module.exports={adopt,mapped,preview,read,rollback};
