'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'outputs/founder-pay-p2-correction'),base='2f0fa29da1bd5f35670448054cf9e047b7f047ba',fixtures=require('../helpers/founder-pay-p2-fixtures.cjs');fs.mkdirSync(out,{recursive:true});
const source=fs.readFileSync(path.join(root,'public/unlisted/investor-forecast.html'),'utf8').replace(/\r\n/g,'\n'),prior=cp.execFileSync('git',['show',base+':public/unlisted/investor-forecast.html'],{cwd:root,encoding:'utf8',maxBuffer:8e6}),scripts=s=>[...s.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]),currentScripts=scripts(source),oldScripts=scripts(prior),context=vm.createContext({console,setTimeout,clearTimeout});vm.runInContext(currentScripts[0],context);
const Model=context.NorthStarInvestorModelV33,realm=x=>vm.runInContext(`JSON.parse(${JSON.stringify(JSON.stringify(x))})`,context),run=x=>Model.runDriverForecast(realm(x));
context.money=v=>v==null?'N/A':Number(v).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});context.escapeHtml=x=>String(x);context.state={driver:null};
const ui=currentScripts[1].match(/  function fixedCostCell\(row\)[\s\S]*?\n  function renderAnnualAndMonthly/)[0].replace(/\n  function renderAnnualAndMonthly$/,'');vm.runInContext(ui,context);
const text=html=>html.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim(),owner=row=>{context.row=row;return text(vm.runInContext('ownerMoney(row)',context));},receipt=[];
test('financial engine, worker, header and exports remain byte-identical',()=>{assert.equal(currentScripts[0],oldScripts[0]);for(const re of [/<template id="monteCarloWorkerSource">[\s\S]*?<\/template>/,/<header[\s\S]*?<\/header>/])assert.equal(source.match(re)[0],prior.match(re)[0]);assert.equal(currentScripts[1].match(/  function annualCsv\(\)[\s\S]*?\n  function resetConfig/)[0],oldScripts[1].match(/  function annualCsv\(\)[\s\S]*?\n  function resetConfig/)[0]);});
for(const [name,input]of Object.entries(fixtures))test(name+' monthly/annual investor authority and collapsed withdrawal status',()=>{const result=run(input);context.state.driver=result;const row=result.rows[name==='default'?12:0],monthly=owner(row),annual=owner(result.annualSummary[0]);
if(['default','taxUnavailable'].includes(name)){assert.match(monthly,/FORECAST investor receipts: Unavailable \/ unconfigured/);assert.match(annual,/FORECAST investor receipts: Unavailable \/ unconfigured/);assert.doesNotMatch(monthly,/Investor receipts: \$0/);assert.match(monthly,/cash scenario assumes no additional owner withdrawals/);}
if(name==='configuredZero'){assert.match(monthly,/FORECAST investor receipts: \$0/);assert.match(annual,/FORECAST investor receipts: \$0/);}
if(name==='payout'){assert.match(monthly,/FORECAST investor receipts: \$100/);assert.match(monthly,/assumed founder\/other-owner profit withdrawals: \$9,900/);assert.match(monthly,/Combined assumed founder receipts: \$13,400/);}
if(name==='actual'){assert.match(monthly,/Recorded ACTUAL investor receipts: \$100/);assert.match(annual,/Recorded ACTUAL investor receipts: \$100/);assert.match(annual,/FORECAST investor receipts: Unavailable \/ unconfigured/);assert.match(annual,/Combined investor total unavailable/);assert.equal(row.founderPay,null);}
if(name==='actualYear'){assert.match(annual,/Recorded ACTUAL investor receipts: \$100/);assert.doesNotMatch(annual,/FORECAST investor receipts/);}
context.row=row;const collapsed=text(vm.runInContext('collapsedWithdrawals(row)',context));assert.match(collapsed,/Additional withdrawals \(company-wide\)/);if(name==='payout')assert.match(collapsed,/\$10,000/);else if(name==='configuredZero')assert.match(collapsed,/\$0/);else if(name.startsWith('actual'))assert.match(collapsed,/Unknown actual total/);else assert.match(collapsed,/Unavailable \/ unconfigured/);
assert.equal(result.rows.length,120);assert.ok(result.rows.every(r=>Math.abs(r.cashReconciliationDifference)<1e-7));receipt.push({name,monthly,annual,collapsed,endingCash:row.endingCash,operatingProfit:row.operatingProfit,founderPay:row.founderPay,investorDistribution:row.investorDistribution});});
test.after(()=>fs.writeFileSync(path.join(out,'focused-results.json'),JSON.stringify({base,sourceSha256:crypto.createHash('sha256').update(source).digest('hex'),cases:receipt},null,2)+'\n'));
