'use strict';
const fs=require('node:fs'),path=require('node:path');const read=p=>fs.readFileSync(path.join(__dirname,'../..',p),'utf8');
describe('Mission 25 Part 10 Slice D imported asset outcomes',()=>{
 const migration=read('migrations/099_canonical_imported_asset_outcomes.sql');
 test('pins the adopted equipment plans, current matches, asset basis and source records',()=>{for(const value of ['canonical_equipment_plans','canonical_equipment_cost_plans','canonical_external_asset_reference_matches','canonical_external_asset_reference_target_basis','equipmentPlan','equipmentCostPlan','assetMatches','planAssets','importedRecords'])expect(migration).toContain(value);});
 test('keeps dimensions independent without invented conversions or exchange rates',()=>{for(const value of ["ARRAY['utilization','operatingCost']","unit}'<>'machine_hour'",'no exchange rate was inferred','Engine hours, distance, cycles and job counts'])expect(migration).toContain(value);expect(migration).not.toMatch(/1\.609344|3\.785411784|exchange_rate/i);});
 test('requires exact reconciled target-set coverage for each dimension',()=>{for(const value of ['canonical_imported_asset_target_coverage','missingPlanTargetCount','extraTargetCount','duplicateTargetCoverageCount','Multiple external asset references resolve to the same target asset'])expect(migration).toContain(value);expect(migration).not.toContain('utilization_asset_total<>planned_asset_total');expect(migration).not.toContain('cost_asset_total<>planned_asset_total');});
 test('preserves stale masking, revocation and non-mutation boundaries',()=>{for(const value of ['canonical_imported_asset_unavailable_metrics','hiddenByConsent','refreshRequired','No estimate, price, schedule, job, vehicle, equipment, allocation, reimbursement, payroll or policy was changed'])expect(migration).toContain(value);});
 test('withholds storage and helpers while mounting guarded owner routes',()=>{const db=read('src/db.js'),routes=read('src/routes/learning.js');for(const value of ['imported_asset_outcome_tables_withheld','imported_asset_outcome_entry_execute','imported_asset_outcome_helpers_withheld','canonical_imported_asset_target_coverage',"'099_canonical_imported_asset_outcomes.sql'"])expect(db).toContain(value);for(const value of ["'/external-asset-sources/:sourceKey/imported-utilization-cost-consent'","'/external-asset-sources/:sourceKey/estimates/:estimateId/imported-utilization-cost-outcomes'",'importedAssetOutcomeContract.normalizeObservation'])expect(routes).toContain(value);expect(read('public/js/learning-center-page.js')).not.toContain('imported-utilization-cost');});
 test('documents the API-only Slice E boundary',()=>{const doc=read('docs/operations/M25_PART10_IMPORTED_ASSET_OUTCOMES.md');expect(doc).toContain('Maintenance-event, downtime, condition and availability outcomes remain unimplemented until Slice E.');expect(doc).toContain('adds no rendered owner surface');});
});
