'use strict';
const fs=require('node:fs'),path=require('node:path');const read=p=>fs.readFileSync(path.join(__dirname,'../..',p),'utf8');
describe('Mission 25 Part 10 Slice E imported asset health outcomes',()=>{
 const migration=read('migrations/100_canonical_imported_asset_health_outcomes.sql');
 test('pins current source permission, exact reviewed asset lineage and complete current evidence',()=>{for(const value of ['canonical_external_asset_reference_source_basis','canonical_external_asset_reference_target_basis','reviewedMatch','referenceSourceManifest','targetBasis','healthRecords','sourceConsent'])expect(migration).toContain(value);});
 test('evaluates maintenance and downtime independently and leaves unsupported dimensions unavailable',()=>{for(const value of ["record_type='maintenance'","record_type='downtime'",'Overlapping downtime periods need source review','Maintenance and downtime do not establish condition','Downtime alone does not establish availability'])expect(migration).toContain(value);expect(migration).not.toMatch(/availabilityPercent|conditionScore|engine.?on|productivity/i);});
 test('preserves correction, tombstone, consent, match, asset and ledger staleness',()=>{for(const value of ['current_basis->>\'sourceDigest\'=value.source_digest','current_consent.id=value.consent_id','targetAssetId','hiddenByConsent','refreshRequired'])expect(migration).toContain(value);});
 test('keeps outcomes advisory and operations unchanged',()=>{expect(migration).toContain('No estimate, price, schedule, job, vehicle, equipment, maintenance plan, allocation, reimbursement, payroll or policy was changed.');expect(migration).not.toMatch(/UPDATE public\.(canonical_estimates|tenant_assets|canonical_schedule|canonical_equipment_ledgers)/);});
 test('withholds storage and helpers while mounting guarded owner routes',()=>{const db=read('src/db.js'),routes=read('src/routes/learning.js');for(const value of ['imported_asset_health_tables_withheld','imported_asset_health_entry_execute','imported_asset_health_helpers_withheld',"'100_canonical_imported_asset_health_outcomes.sql'"])expect(db).toContain(value);for(const value of ["'/external-asset-sources/:sourceKey/imported-asset-health-consent'","'/external-asset-sources/:sourceKey/imported-asset-health-outcomes'",'importedAssetHealthContract.normalizeObservation'])expect(routes).toContain(value);expect(read('public/js/learning-center-page.js')).not.toContain('imported-asset-health');});
 test('documents the API-only later-slice boundary',()=>{const doc=read('docs/operations/M25_PART10_ASSET_HEALTH_OUTCOMES.md');expect(doc).toContain('This API-only slice adds no rendered owner surface.');expect(doc).toContain('Calibration, source lifecycle operations and the Learning Center experience remain Slices F-H.');});
});
