'use strict';
const fs=require('node:fs'),path=require('node:path');const read=p=>fs.readFileSync(path.join(__dirname,'../..',p),'utf8');
describe('Mission 25 Part 12F external customer outcomes',()=>{
 const migration=read('migrations/118_canonical_external_customer_outcomes.sql');
 test('pins current CRM, communication, reviewed-match and target lineage',()=>{for(const value of ['crm_source_consent_id','communication_source_consent_id','crm_match_id','communication_match_id','target_digest','crm_manifest','communication_manifest','source_digest'])expect(migration).toContain(value);});
 test('evaluates four outcome dimensions independently',()=>{for(const value of ["'lead'","'appointment'","'issuedEstimate'","'customerResponse'",'More than one current lead record needs source review','The issued estimate has no recorded appointment reference'])expect(migration).toContain(value);});
 test('does not promote delivery or provider-classified intent to verified customer response',()=>{expect(migration).toContain("direction='inbound'");expect(migration).toContain("intent_claim->>'basis' IN ('customer_explicit','human_reviewed')");expect(migration).not.toMatch(/delivery_state.*customerResponse|provider_classified.*customerResponse/);expect(migration).toContain('Delivery status and provider classifications do not become verified customer responses.');});
 test('preserves revocation, non-revival, correction and reviewed-link staleness',()=>{for(const value of ['sourcePermissionsCurrent','hiddenByConsent','fresh_value','basis->>\'sourceDigest\'=value.source_digest','consent_value.crm_source_consent_id','consent_value.communication_source_consent_id'])expect(migration).toContain(value);});
 test('keeps runtime entry-only and mounts guarded owner routes',()=>{const db=read('src/db.js'),routes=read('src/routes/learning.js');for(const value of ['external_customer_outcome_tables_withheld','external_customer_outcome_entry_execute','external_customer_outcome_helpers_withheld',"'118_canonical_external_customer_outcomes.sql'"])expect(db).toContain(value);for(const value of ['/external-customer-outcome-sources/:crmSourceKey/:communicationSourceKey/consent','/external-customer-outcome-sources/:crmSourceKey/:communicationSourceKey/outcomes','customerOutcomeContract.normalizeObservation'])expect(routes).toContain(value);});
 test('keeps the slice API-only and advisory',()=>{expect(migration).toContain('No customer, lead, appointment, estimate, schedule, price, message, source record or company policy was changed.');expect(migration).not.toMatch(/UPDATE public\.(canonical_customers|canonical_opportunities|canonical_appointments|canonical_estimates|canonical_schedule_assignments)/);const doc=read('docs/operations/M25_PART12_CUSTOMER_OUTCOMES.md');expect(doc).toContain('This API-only slice adds no rendered owner surface.');expect(doc).toContain('Slices G-K remain mandatory');});
});
