'use strict';
const fs=require('node:fs'),path=require('node:path');const read=p=>fs.readFileSync(path.join(__dirname,'../..',p),'utf8');
describe('Mission 25 Part 12G external project outcomes',()=>{
 const migration=read('migrations/119_canonical_external_project_outcomes.sql');
 test('pins current source, project, complete change-order and target lineage',()=>{for(const value of['source_consent_id','project_match_id','project_match_revision','project_match_digest','target_digest','source_manifest','change_order_matches','source_digest'])expect(migration).toContain(value);});
 test('evaluates scope, change orders and project delivery independently',()=>{for(const value of["'scope'","'changeOrders'","'projectDelivery'",'originalContract','currentContract','contractChange','signedValue','durationSeconds'])expect(migration).toContain(value);});
 test('does not collapse duplicate or unmatched change-order provenance',()=>{expect(migration).toContain("count(*)FILTER(WHERE record_count<>1)");expect(migration).toContain("match_id IS NULL OR action IS DISTINCT FROM 'link'");expect(migration).toContain('A change order has more than one current record and needs source review.');expect(migration).toContain('Every current change order must be reviewed against this NorthStar estimate.');});
 test('does not infer currency conversion, contract causation or an absent change order',()=>{expect(migration).toContain('No current change-order record is available for this reviewed project.');expect(migration).toContain("currency_total=1");expect(migration).toContain('Contract movement is not automatically attributed to change orders.');const doc=read('docs/operations/M25_PART12_PROJECT_OUTCOMES.md');expect(doc).toContain('does not claim that a contract change was caused by the imported change orders');expect(doc).toContain('No exchange rate');});
 test('preserves revocation, non-revival, staleness and entry-only runtime authority',()=>{const db=read('src/db.js');for(const value of['sourcePermissionCurrent','hiddenByConsent','fresh_value'])expect(migration).toContain(value);for(const value of['external_project_outcome_tables_withheld','external_project_outcome_entry_execute','external_project_outcome_helpers_withheld',"'119_canonical_external_project_outcomes.sql'"])expect(db).toContain(value);});
 test('keeps the slice API-only and advisory',()=>{expect(migration).toContain('No project, change order, customer, job, estimate, schedule, price, financial record, source record or company policy was changed.');expect(migration).not.toMatch(/UPDATE public\.(canonical_estimates|canonical_schedule_assignments|canonical_external_project_change_order_import_records)/);const doc=read('docs/operations/M25_PART12_PROJECT_OUTCOMES.md');expect(doc).toContain('This API-only slice adds no rendered owner surface.');expect(doc).toContain('Slices H-K remain mandatory');});
});
