'use strict';
const fs=require('node:fs'),path=require('node:path');const read=p=>fs.readFileSync(path.join(__dirname,'../..',p),'utf8');
describe('Mission 25 Part 12H external financial outcomes',()=>{
 const migration=read('migrations/120_canonical_external_financial_outcomes.sql');
 test('pins current financial source, reviewed references and estimate lineage',()=>{for(const value of['source_consent_id','target_digest','source_manifest','reference_matches','source_digest'])expect(migration).toContain(value);});
 test('keeps revenue, collection, realized cost and margin independent',()=>{for(const value of["'revenue'","'collection'","'realizedCost'","'margin'",'revenueRecordCount','costRecordCount'])expect(migration).toContain(value);});
 test('uses explicit posted accounting and collected-amount evidence only',()=>{expect(migration).toContain("amount_claim->>'basis'='revenue'");expect(migration).toContain("record_state<>'posted'");expect(migration).toContain("amount_claim->>'basis'='amount_collected'");expect(migration).toContain("amount_claim->>'basis' IN('direct_cost','overhead_cost','other_cost')");});
 test('does not infer zero, currency conversion or native financial authority',()=>{expect(migration).toContain("revenue_currencies=1");expect(migration).toContain("cost_currencies=1");expect(migration).toContain("revenue_currency=cost_currency");expect(migration).toContain('NorthStar financial records remain unavailable until Mission 27.');const doc=read('docs/operations/M25_PART12_FINANCIAL_OUTCOMES.md');expect(doc).toContain('Missing records or amounts never become zero');expect(doc).toContain('No exchange rate');});
 test('preserves revocation, non-revival, staleness and entry-only runtime authority',()=>{const db=read('src/db.js');for(const value of['sourcePermissionCurrent','hiddenByConsent','fresh_value'])expect(migration).toContain(value);for(const value of['external_financial_outcome_tables_withheld','external_financial_outcome_entry_execute','external_financial_outcome_helpers_withheld',"'120_canonical_external_financial_outcomes.sql'"])expect(db).toContain(value);});
 test('keeps the slice API-only and advisory',()=>{expect(migration).toContain('No customer, job, estimate, schedule, price, financial record, source record or company policy was changed.');expect(migration).not.toMatch(/UPDATE public\.(canonical_estimates|canonical_external_financial_import_records|canonical_external_business_reference_matches)/);const doc=read('docs/operations/M25_PART12_FINANCIAL_OUTCOMES.md');expect(doc).toContain('This API-only slice adds no rendered owner surface.');expect(doc).toContain('Slices I-K remain mandatory');});
});
