'use strict';
const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'../..');const read=value=>fs.readFileSync(path.join(root,value),'utf8');
describe('Mission 25 Part 13D cross-job proposal ratification',()=>{
 const migration=read('migrations/127_canonical_job_outcome_cross_job_proposals.sql');
 test('pins permission and exact summary lineage',()=>{for(const token of['graph_consent_id UUID NOT NULL','proposal_consent_id UUID NOT NULL','cohort_manifest JSONB NOT NULL','cohort_digest CHAR(64) NOT NULL','calculation_version TEXT NOT NULL CHECK(calculation_version=\'m25-cross-job-proposal-generation-v1\'','canonical_job_outcome_cross_job_proposals_immutable'])expect(migration).toContain(token);});
 test('keeps uncertainty, useful ranges and no-mutation boundaries explicit',()=>{for(const token of['percentile_cont(.25)','percentile_cont(.5)','percentile_cont(.75)','median_value BETWEEN .25 AND 4','At least five comparable current job outcomes','They are not a forecast or probability','This proposal does not change an estimate'])expect(migration).toContain(token);});
 test('withholds tables and helpers and exposes only guarded entries',()=>{const db=read('src/db.js');for(const token of['job_outcome_proposal_tables_withheld','job_outcome_proposal_entry_execute','job_outcome_proposal_helpers_withheld',"'127_canonical_job_outcome_cross_job_proposals.sql'"])expect(db).toContain(token);expect(migration).toContain('REVOKE ALL ON TABLE public.canonical_job_outcome_proposal_consents,public.canonical_job_outcome_cross_job_proposals FROM PUBLIC');});
 test('adds API only and preserves later rendered slices',()=>{const routes=read('src/routes/learning.js');expect(routes).toContain("'/job-outcome-proposals/consent'");expect(routes).toContain("'/job-outcome-proposals/:serviceKey'");const changed=['migrations/127_canonical_job_outcome_cross_job_proposals.sql','src/db.js','src/routes/learning.js','src/learning/jobOutcomeProposalContract.js','src/learning/jobOutcomeProposalRepository.js'];expect(changed.some(value=>value.startsWith('public/'))).toBe(false);});
});
