'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'../..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
describe('Mission 25 Part 12 Slice E reviewed reconciliation authority',()=>{
 test('freezes all required reference classes and exact target boundaries',()=>{const sql=read('migrations/117_canonical_external_business_reconciliation.sql');for(const value of['crm_field_service','project_change_order','communication','financial','customer','job','estimate','execution','project','change_order','invoice','payment','collection','accounting_entry'])expect(sql).toContain(`'${value}'`);expect(sql).toContain("reference_kind='customer' AND target_kind='customer'");expect(sql).toContain("reference_kind='execution' AND target_kind='execution'");expect(sql).toContain("target_kind='estimate'");});
 test('pins current consent, complete source manifest and exact target basis',()=>{const sql=read('migrations/117_canonical_external_business_reconciliation.sql');for(const value of['consent_revision','consent_digest','source_manifest','source_digest','target_manifest','target_digest'])expect(sql).toContain(value);expect(sql).toMatch(/DISTINCT ON\(r\.external_record_id\)/);expect(sql).toMatch(/state='active'/);});
 test('keeps runtime entry-only and exposes mounted guarded routes',()=>{const db=read('src/db.js'),routes=read('src/routes/learning.js');expect(db).toContain("REVOKE ALL PRIVILEGES ON TABLE public.canonical_external_business_reference_matches");expect(db).toContain('canonical_external_business_reference_matches_read');expect(db).toContain('canonical_external_business_reference_match_mutate');expect(routes).toContain("/external-business-sources/:sourceClass/:sourceKey/matches");});
 test('preserves the Mission 27 and no-mutation boundaries',()=>{const sql=read('migrations/117_canonical_external_business_reconciliation.sql'),roadmap=read('docs/roadmap/MISSION_25_OUTCOME_LEARNING.md');expect(sql).toMatch(/does not create a NorthStar invoice/i);expect(roadmap).toMatch(/remain unavailable until Mission 27/i);expect(sql).not.toMatch(/UPDATE public\.canonical_(customers|estimates|field_executions)/);});
 test('changed no rendered path in its accepted slice',()=>{const {execFileSync}=require('node:child_process');const changed=execFileSync('git',['diff','--name-only','ffd9b73cc377daa2f1daf1dbc510adf4caa356a5','d8c2492a72b95d667064ef23fe63e04ab084be4e','--','public'],{cwd:root,encoding:'utf8'}).trim();expect(changed).toBe('');});
});
