'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'../..');const read=file=>fs.readFileSync(path.join(root,file),'utf8');
describe('Mission 25 Part 13C ratification',()=>{
 const migration=read('migrations/126_canonical_job_outcome_summary.sql');
 test('pins one exact current graph, evaluation and permission period',()=>{for(const token of['graph_id UUID NOT NULL','evaluation_id UUID NOT NULL','evaluation_source_digest CHAR(64) NOT NULL','consent_id UUID NOT NULL','calculation_version TEXT NOT NULL CHECK(calculation_version=\'m25-job-outcome-summary-v1\'','canonical_job_outcome_summaries_immutable'])expect(migration).toContain(token);});
 test('produces all six fixed job domains without conversions or source choice',()=>{expect(migration).toContain('["equipment","financial","labor","materials","scope","travel"]');expect(migration).toContain("ARRAY['labor','travel','equipment','materials','scope','financial']");expect(migration).toContain("'status',status_value");expect(migration).toContain("'sources',sources");expect(migration).toContain('This summary keeps each source separate.');expect(migration).not.toMatch(/exchange rate|currency conversion|choose the best|preferred source/i);});
 test('masks stale or revoked details and blocks revival',()=>{expect(migration).toContain("'summary',CASE WHEN fresh_value THEN value.summary ELSE NULL END");expect(migration).toContain('replay.consent_id<>consent_value.id');expect(migration).toContain("replay_projection->'fresh' IS DISTINCT FROM 'true'::jsonb");});
 test('withholds tables and helpers while allowing guarded build and read',()=>{expect(migration).toContain('REVOKE ALL ON TABLE public.canonical_job_outcome_summaries FROM PUBLIC');expect(migration).toContain('GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_summary_build');expect(migration).toContain('GRANT EXECUTE ON FUNCTION public.canonical_job_outcome_summary_read');const db=read('src/db.js');for(const condition of['!runtimePrivileges.job_outcome_summary_table_withheld','!runtimePrivileges.job_outcome_summary_entry_execute','!runtimePrivileges.job_outcome_summary_helpers_withheld'])expect(db).toContain(condition);expect(db).toContain("'126_canonical_job_outcome_summary.sql'");});
 test('mounts owner and administrator API routes with no rendered path',()=>{const routes=read('src/routes/learning.js');expect(routes).toContain("'/estimates/:estimateId/job-outcome-summary'");expect(routes).toContain('jobOutcomeSummaryContract.normalizeSummary');expect(read('src/learning/jobOutcomeSummaryRepository.js')).toContain('canonical_job_outcome_summary_build');const changed=['migrations/126_canonical_job_outcome_summary.sql','src/db.js','src/routes/learning.js','src/learning/jobOutcomeSummaryContract.js','src/learning/jobOutcomeSummaryRepository.js'];expect(changed.some(value=>value.startsWith('public/'))).toBe(false);});
});
