 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),c=require('../../src/estimating/capellaScenarios');
const source={kind:'owner_estimate',referenceId:null,digest:null,note:'Estimator assumption, not verified pricing.',effectiveOn:null,endsOn:null};
const b=()=>({enabled:true,digest:'basis',prices:[{id:'reviewed',amount:'1500.00',label:'Reviewed Net Price Before Tax'}],directCosts:'1000.00',overhead:{gross:'150.00',alreadyIncluded:'50.00',incremental:'100.00',overlapResolved:true},policy:null,currency:'USD',references:[],date:'2026-09-13',sourcePins:{estimateId:'test'},selectedRevision:2,simulated:true,historical:false});
const scenario=(kind='adverse',d='100.00',h='0.00',p='0.00')=>({kind,directChange:d,overheadChange:h,priceChange:p,overheadSeparate:true,source});
const run=(basis=b(),v=scenario())=>c.calculate(basis,{basisDigest:'basis',priceBasis:'reviewed',scenarios:[v]});
test('complete costs use incremental overhead once and signed downside',()=>{const r=run();assert.equal(r.base.modeledCosts,'1100.00');assert.equal(r.base.breakEven,'1100.00');assert.equal(r.scenarios[0].result.remaining,'300.00');assert.equal(r.scenarios[0].changeInRemaining,'-100.00');assert.equal(run(b(),scenario('adverse','500.00')).scenarios[0].result.shortfall,'100.00');});
test('unknown is not zero; unresolved overhead remains unknown',()=>{for(const basis of [{...b(),directCosts:null},{...b(),overhead:null}])assert.equal(run(basis).base.remaining,null);assert.equal(run(b(),{...scenario(),overheadSeparate:false}).scenarios[0].result.remaining,null);assert.equal(run(b(),scenario('adverse',null)).scenarios[0].result.modeledCosts,null);});
test('explicit zero and denominator zero do not become invalid ratios',()=>{const basis={...b(),directCosts:'0.00',overhead:{incremental:'0.00',overlapResolved:true},prices:[{id:'reviewed',amount:'0.00'}]};const r=run(basis,scenario('adverse','0.00'));assert.equal(r.base.remaining,'0.00');assert.equal(r.base.margin,null);assert.equal(r.base.markup,null);});
test('favorable/adverse direction and duplicate names validated',()=>{assert.throws(()=>run(b(),scenario('favorable','1.00')),/Favorable/);assert.equal(run(b(),scenario('favorable','-1.00')).scenarios[0].changeInRemaining,'1.00');assert.throws(()=>c.calculate(b(),{basisDigest:'basis',priceBasis:'reviewed',scenarios:[scenario(),scenario()]}),/entries/);});
test('signed values bounds and overflow reject',()=>{for(const x of ['1','1.000','1e2','+1.00','NaN'])assert.throws(()=>run(b(),scenario('adverse',x)));assert.throws(()=>run(b(),scenario('adverse','-1000.01')),/outside/);assert.throws(()=>run(b(),scenario('adverse','999999999999.99')),/outside/);});
test('current source/digest and pause reject without outcomes',()=>{assert.throws(()=>run({...b(),digest:'changed'}),e=>e.status===409);assert.throws(()=>run({...b(),enabled:false}),e=>e.status===503);assert.throws(()=>run(b(),{...scenario(),source:{...source,kind:'published_knowledge',referenceId:'gone',digest:'a'.repeat(64)}}),e=>e.status===409);});
test('source unknown/expired dates remain explicit',()=>{assert.deepEqual(run().scenarios[0].cautions,['Date Not Recorded','Freshness Unknown']);assert.ok(run(b(),{...scenario(),source:{...source,effectiveOn:'2026-01-01',endsOn:'2026-02-01'}}).scenarios[0].cautions.includes('Source Date Has Passed'));});
test('separate contingency and ceiling policy floor share existing math',()=>{const basis=b();basis.policy={inputs:{serviceKey:'fence',method:'target_margin',percent:'20.00',contingency:{method:'percent',amount:null,percent:'10.00',coverage:{status:'declared_separate',explanation:'Separate unspent contingency'}},minimum:{method:'fixed',amount:'1600.00'},source}};const r=run(basis);assert.equal(r.base.modeledCosts,'1100.00');assert.equal(r.base.policy.allowance,'110.00');assert.equal(r.base.policy.policyBudget,'1210.00');assert.equal(r.base.policy.threshold,'1600.00');assert.equal(r.base.policy.comparison.status,'below');assert.equal(r.scenarios[0].result.policy.allowance,'120.00');assert.equal(r.scenarios[0].result.policy.threshold,'1650.00');});
test('negative percentages use signed ties away from zero',()=>{const r=c.result(3n,0n,2n,null,null,'USD');assert.equal(r.margin.value,'-50.0000');assert.equal(r.markup.value,'-33.3333');});

test('malformed shape and reversed source dates reject as input errors',()=>{assert.throws(()=>c.calculate(b(),{}),e=>e.status===400);assert.throws(()=>run(b(),{...scenario(),source:{...source,effectiveOn:'2026-09-14',endsOn:'2026-09-13'}}),e=>e.status===400);});
