'use strict';
const c=require('../../src/estimating/commercialContract'),{fixture}=require('../helpers/m24-commercial-input');
const {sha256}=require('../../src/services/businessProfileAdapter');
function setup(){const f=fixture(['1100.00']);f.value.version=c.VERSION;f.value.jobApplicability={serviceOperation:null,propertyUse:'unknown',workContext:'unknown',customerExemption:'unknown',evidenceRef:{serviceOperation:'',propertyUse:'',workContext:'',customerExemption:''}};const source=f.value.taxGroups[0].source;Object.assign(source,{legalEffectiveOn:source.effectiveOn,legalEndsOn:source.endsOn,reviewedOn:'2026-09-13',reviewValidThrough:'2026-09-13'});delete source.effectiveOn;delete source.endsOn;const pin={id:'pricing',revision:1,digest:'a'.repeat(64)};const sources={digest:'b'.repeat(64),asOfDate:'2026-09-13',sourcePins:{estimate:'original'},currency:'USD',pricingPin:pin,pricing:{result:f.context.pricing},pricingCurrent:true,policyPin:{id:'policy',revision:1,digest:'c'.repeat(64)},policy:{action:'save',expectedDecisionRevision:0,expectedDecisionDigest:'none',result:{threshold:'1200.00'}},policyBasisCurrent:true,profilePin:{id:'profile'},taxProfilePin:{id:'tax'},rulePins:[],sourceDigest:'d'.repeat(64),decisionBasis:{revision:0,digest:'none'},decision:null,serviceKey:'fence',simulated:true,validatedRules:[]};const review={pins:sources.sourcePins,currency:'USD',isCurrent:true,decisions:{writeBasis:sources.decisionBasis}};const body={action:'save',expectedRevision:0,expectedDigest:'none',sourcePins:review.pins,expectedDecisionRevision:0,expectedDecisionDigest:'none',inputs:f.value,currency:'USD',reason:'Review terms',confirmed:true,confirmationVersion:c.VERSION,evidenceDigest:sources.digest};const now=new Date('2026-09-13T12:00:00Z');const terms=c.demoPlan([],review,body,'save',now,sources).receipt;const approve={termsPin:c.pin(terms),evidenceDigest:sources.digest,expectedDecisionRevision:0,expectedDecisionDigest:'none',scopeSummary:'Recorded work',reason:'Reviewed full charges',confirmed:true,confirmationVersion:c.VERSION,exceptions:{policyReason:'Deliberate owner exception',policyUnknownAcknowledged:false,ownerRecordedTaxAcknowledged:true}};return {sources,review,body,now,terms,approve};}
describe('Commercial immutable authority and explicit human binding',()=>{
 test('net 1100 remains below 1200 despite tax raising payable to 1210',()=>{const f=setup();expect(f.terms.result.total).toBe('1210.00');expect(c.comparison(f.terms,f.sources)).toEqual({state:'below',reason:null,threshold:'1200.00',difference:'-100.00'});expect(c.approvalDecision(f.approve,f.terms,f.sources,f.now).decision.priceBeforeTax).toBe('1100.00');f.approve.exceptions.policyReason='';expect(()=>c.approvalDecision(f.approve,f.terms,f.sources,f.now)).toThrow(/below/);});
 test('owner-recorded treatment requires separate acknowledgment',()=>{const f=setup();f.approve.exceptions.ownerRecordedTaxAcknowledged=false;expect(()=>c.approvalDecision(f.approve,f.terms,f.sources,f.now)).toThrow(/owner-recorded/);});
 test('unknown policy needs its own acknowledgment, never a fabricated threshold',()=>{const f=setup();f.sources.policy.result.threshold=null;expect(()=>c.approvalDecision(f.approve,f.terms,f.sources,f.now)).toThrow(/unavailable/);f.approve.exceptions.policyUnknownAcknowledged=true;expect(c.approvalDecision(f.approve,f.terms,f.sources,f.now).policy.threshold).toBeNull();});
 test('exact self-approval exception retains all other pins; later decision invalidates',()=>{const f=setup();const d={id:'decision',revision:1,digest:'e'.repeat(64),action:'approve',priceBeforeTax:'1100.00',sourcePins:f.terms.sourcePins};const binding={termsPin:c.pin(f.terms),authorityPin:f.terms.authorityPin,previousDecisionBasis:f.sources.decisionBasis,decisionPin:c.pin(d),scopeSummary:'Recorded work'};f.sources.decision=d;f.sources.decisionBasis={revision:d.revision,digest:d.digest};expect(c.currentState(f.terms,f.sources,binding)).toEqual({current:true,linkedApproval:true});f.sources.profilePin={id:'new-profile'};expect(c.currentState(f.terms,f.sources,binding).current).toBe(false);f.sources.profilePin={id:'profile'};f.sources.decision={...d,id:'unrelated'};expect(c.currentState(f.terms,f.sources,binding).current).toBe(false);f.sources.decision=d;f.sources.decisionBasis={revision:2,digest:'f'.repeat(64)};expect(c.currentState(f.terms,f.sources,binding).current).toBe(false);});
 test('self-approval cannot rescue a changed policy, terms or selected source',()=>{const f=setup();const d={id:'d',revision:1,digest:'e'.repeat(64),action:'approve',priceBeforeTax:'1100.00',sourcePins:f.terms.sourcePins};const binding={termsPin:c.pin(f.terms),authorityPin:f.terms.authorityPin,previousDecisionBasis:f.sources.decisionBasis,decisionPin:c.pin(d)};f.sources.decision=d;f.sources.decisionBasis={revision:1,digest:d.digest};for(const field of ['policyPin','pricingPin','sourcePins','taxProfilePin','rulePins','sourceDigest']){const prior=f.sources[field];f.sources[field]={changed:true};expect(c.currentState(f.terms,f.sources,binding).current).toBe(false);f.sources[field]=prior;}binding.termsPin.digest='f'.repeat(64);expect(c.currentState(f.terms,f.sources,binding).current).toBe(false);});
 test('full body replay preserves historical success but rejects changed terms',()=>{const f=setup();f.sources.digest='f'.repeat(64);expect(c.demoPlan([f.terms],f.review,f.body,'save',f.now,f.sources).replayed).toBe(true);const changed=structuredClone(f.body);changed.inputs.transactionDate='2026-09-14';expect(()=>c.demoPlan([f.terms],f.review,changed,'save',f.now,f.sources)).toThrow(/different/);expect(f.terms.requestDigest).toBe(sha256(f.body));});
 test('midnight transition invalidates new preview while no historical recalculation occurs',()=>{const f=setup();expect(()=>c.preview(f.body.inputs,'USD',f.sources,new Date('2026-09-14T00:00:00Z'))).toThrow(/date changed/);expect(f.terms.result.total).toBe('1210.00');});
 test('incomplete draft cannot be approved with a generic exception',()=>{const f=setup();f.body.inputs.taxGroups[0].source.location='';f.terms=c.demoPlan([],f.review,f.body,'draft',f.now,f.sources).receipt;f.approve.termsPin=c.pin(f.terms);expect(()=>c.approvalDecision(f.approve,f.terms,f.sources,f.now)).toThrow(/Resolve/);});
 test('customer projection excludes private policy, sources and evidence and requires linked approval',()=>{const f=setup();expect(c.customerSummary(f.terms,null,f.sources)).toBeNull();const d={id:'d',revision:1,digest:'e'.repeat(64),action:'approve',priceBeforeTax:'1100.00',sourcePins:f.terms.sourcePins};const binding={termsPin:c.pin(f.terms),authorityPin:f.terms.authorityPin,previousDecisionBasis:f.sources.decisionBasis,decisionPin:c.pin(d),scopeSummary:'Recorded work'};f.sources.decision=d;f.sources.decisionBasis={revision:1,digest:d.digest};const r=c.customerSummary(f.terms,binding,f.sources);expect(r.total).toBe('1210.00');expect(r).not.toHaveProperty('evidence');expect(r).not.toHaveProperty('policy');expect(JSON.stringify(r)).not.toContain('Fixture source');});
});
