'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const recipe=require('../../src/estimating/proposalRecipe'),proposal=require('../../src/estimating/estimateProposal'),repository=require('../../src/estimating/estimateProposalRepository'),equipment=require('../../src/commandCenter/demoEquipmentPlans');
const now=new Date('2026-09-14T12:00:00Z');
function fixture(){const record={state:{equipmentBasis:equipment.create('proposal-unit',now.toISOString())},expiresAt:'2026-09-15T12:00:00Z'},item={snapshot:{service:{key:'fence',scope:{linearFeet:146,material:'cedar'}}}},review={pins:{original:'fixture'},currency:'USD',selectedRevision:1,isCurrent:true,pricingPlans:{sources:{serviceKey:'fence',asOfDate:'2026-09-14',references:[],digest:'fixture',basis:{directCosts:null,overheadIncluded:[]}}}};return{record,item,review,body:{version:proposal.VERSION,selectedRevision:null,expectedBasisDigest:null,overrides:[],candidateIds:[]}};}
function run(f,body=f.body){return repository.demo(f.record,f.review,f.item,body,now);}
test('pricing rates require currency per measured unit through the full preview',()=>{
 for(const unit of ['USD/ft','ft','CAD/ft','USD/m']){
  const f=fixture(),knowledge=f.record.state.equipmentBasis.knowledgeRows.find(k=>JSON.parse(k.canonical_document).content.estimateProposalRecipe);
  require('../helpers/m24-proposal-rate').transformKnowledge(knowledge,unit);const before=JSON.stringify(f);
  if(unit==='USD/ft'){const output=run(f),pricing=output.components.find(c=>c.kind==='pricing');assert.equal(pricing.inputs.lines[0].rate,'5');assert.equal(pricing.result.result.proposedBeforeTax,'500.00');}
  else assert.throws(()=>run(f),e=>e.status===400);
  assert.equal(JSON.stringify(f),before);
 }
});
test('adjacent typed quantity, unit-price, hourly-cost, amount and productivity bindings retain dimensions',()=>{
 const cases=[['materials','unitPrice','USD/ft','ft'],['labor','hourlyCost','USD/hour','hour'],['labor','hoursPerUnit','worker_hour/ft','ft'],['pricing','amount','USD','ft'],['pricing','quantity','ft','USD/ft']];
 for(const[kind,field,good,bad]of cases){const c={kind,inputs:{lines:[{unit:'ft',[field]:'1'}]},bindings:[{line:0,field,step:'v'}]};assert.doesNotThrow(()=>proposal.inputsFor(c,{values:{v:{unit:good,decimal:'5'}}},'USD'));assert.throws(()=>proposal.inputsFor(c,{values:{v:{unit:bad,decimal:'5'}}},'USD'),e=>e.status===400);}
});
test('declared simulated recipe uses actual calculators without changing source or history',()=>{const f=fixture(),before=JSON.stringify(f),a=run(f),b=run(f);assert.deepEqual(a,b);assert.equal(JSON.stringify(f),before);assert.equal(a.components.find(c=>c.kind==='materials').result.total,'521.95');assert.equal(a.components.find(c=>c.kind==='labor').result.total,'490.56');assert.equal(a.components.find(c=>c.kind==='travel').result.total,'20.00');assert.equal(a.completeCost,null);assert.equal(a.simulated,true);});
test('a changed selected decision invalidates the previous basis',()=>{const f=fixture(),a=run(f);f.review.decisions={writeBasis:{revision:1,digest:'changed'}};assert.throws(()=>run(f,{...f.body,expectedBasisDigest:a.basisDigest}),e=>e.status===409);});
test('typed owner edit recalculates dependent quantities and preserves original record',()=>{const f=fixture(),before=JSON.stringify(f.record),a=run(f);const b=run(f,{...f.body,expectedBasisDigest:a.basisDigest,overrides:[{fieldId:'linearFeet',value:'100',unit:'ft',sourceKind:'owner_assumption',reason:'Owner measured the fence run'}]});assert.equal(b.components.find(c=>c.kind==='materials').result.total,'357.50');assert.equal(b.components.find(c=>c.kind==='labor').result.total,'336.00');assert.equal(JSON.stringify(f.record),before);assert.throws(()=>run(f,{...f.body,overrides:[{fieldId:'linearFeet',value:'100',unit:'ft',sourceKind:'owner_assumption',reason:'Owner measured'}]}));});
test('old sessions and unsupported tree service remain provisional without fake quantities',()=>{const f=fixture();delete f.record.state.equipmentBasis;assert.equal(run(f).readiness,'incomplete');assert.deepEqual(run(f).components,[]);f.item.snapshot.service={key:'tree_removal',scope:{city:'Windsor',state:'CT'}};const a=run(f);assert.equal(a.completeCost,null);assert.deepEqual(a.components,[]);assert.match(a.questions[0].question,/volume/);});
test('wrong unit, stale recipe and expired session are not current calculations',()=>{const f=fixture(),a=run(f);assert.throws(()=>run(f,{...f.body,expectedBasisDigest:a.basisDigest,overrides:[{fieldId:'linearFeet',value:'10',unit:'m',sourceKind:'owner_assumption',reason:'Measured'}]}),e=>e.status===400);f.record.expiresAt='2026-09-14T11:59:59Z';assert.throws(()=>run(f),e=>e.status===410);});
test('recipe arithmetic checks units, dependency order, exact rational division and ceilings',()=>{const f=fixture(),s=equipment.sources(f.record.state,f.item),r=s.knowledge.find(k=>k.content.estimateProposalRecipe).content.estimateProposalRecipe;const base={...r,components:[],equipmentCostLines:[],fields:[],steps:[{id:'quantity',op:'constant',unit:'ft',args:[],fieldId:null,value:'10'},{id:'length',op:'constant',unit:'ft',args:[],fieldId:null,value:'3'},{id:'pieces',op:'ratio',unit:'1',args:['quantity','length'],fieldId:null,value:null},{id:'whole',op:'ceil',unit:'1',args:['pieces'],fieldId:null,value:null}]};const a=recipe.evaluate(base,{},now);assert.equal(a.values.pieces.decimal,null);assert.equal(a.values.whole.decimal,'4');assert.throws(()=>recipe.evaluate({...base,steps:base.steps.map(s=>s.id==='pieces'?{...s,unit:'ft'}:s)}, {},now));assert.throws(()=>recipe.normalize({...base,steps:base.steps.toReversed()}));});
test('known material mismatch outranks a missing length; explicit proposed category is separate from original',()=>{const f=fixture();f.item.snapshot.service.scope.material='chain-link';delete f.item.snapshot.service.scope.linearFeet;const first=run(f);assert.equal(first.readiness,'blocked');const original=JSON.stringify(f.item);const second=run(f,{...f.body,expectedBasisDigest:first.basisDigest,overrides:[{fieldId:'material',value:'cedar',unit:'category',sourceKind:'owner_assumption',reason:'Owner chooses cedar for proposed replacement'}]});assert.equal(second.readiness,'incomplete');assert(second.questions.some(q=>q.id==='linearFeet'));assert.equal(JSON.stringify(f.item),original);});
test('expired review window requires fresh basis and current saved plans are retained',()=>{const f=fixture(),first=run(f);assert.throws(()=>repository.demo(f.record,f.review,f.item,{...f.body,expectedBasisDigest:first.basisDigest},new Date(+now+300001)),e=>e.status===409);f.review.materialPlans={current:{id:'saved',revision:2,digest:'d',action:'save',calculationVersion:'estimate-material-plan-v2',sourceBasisCurrent:true,inputs:{retained:'exact'},result:{total:'12.00'}}};const current=run(f);assert.deepEqual(current.components.find(c=>c.kind==='materials').inputs,{retained:'exact'});assert.equal(current.components.find(c=>c.kind==='materials').state,'retained');});
test('old costs cannot become new draft pricing or approval',()=>{const f=fixture();f.review.pricingPlans.sources.basis={directCosts:'900.00',overheadIncluded:[]};const current=run(f),pricing=current.components.find(c=>c.kind==='pricing').result.result;assert.equal(pricing.directCosts,null);assert.equal(pricing.costWithOverhead,null);assert.equal(current.completeCost,null);assert(current.components.every(c=>c.replacesSaved===false));assert.equal(current.components.find(c=>c.kind==='equipment').costs[0].total,'176.00');});
test('bounded typed recipe rejects another service, extra steps and arbitrary expressions',()=>{const f=fixture(),r=equipment.sources(f.record.state,f.item).knowledge.find(k=>k.content.estimateProposalRecipe).content.estimateProposalRecipe;const other=structuredClone(r);other.components.find(c=>c.kind==='labor').inputs.serviceKey='roofing';assert.throws(()=>recipe.normalize(other));assert.throws(()=>recipe.normalize({...r,steps:Array.from({length:13},(_,n)=>({id:'v'+n,op:'constant',unit:'1',args:[],fieldId:null,value:'1'}))}));assert.throws(()=>recipe.normalize({...r,expression:'process.env'}));assert.throws(()=>proposal.normalize({...f.body,overrides:Array(25).fill({})}));});
test('current shared skill mismatch is blocked without pretending a schedule is known',()=>{const p=require('../../src/estimating/proposalResources'),candidate={exists:true,kind:'profile',members:[{profileId:'example',membershipStatus:'active',userStatus:'active',serviceIds:['roofing'],availability:null}]};const result=p.assess(candidate,{id:'example',kind:'profile',label:'Example Worker'},'fence',true);assert.equal(result.status,'blocked');assert.equal(result.availability,'unknown');});
test('inferred and unresolved scope values require confirmation rather than becoming measured inputs',()=>{const f=fixture();f.item.facts=[{variable:'linearFeet',status:'inferred'},{variable:'material',status:'unresolved'}];const output=run(f);assert.equal(output.readiness,'incomplete');assert.equal(output.components.length,0);assert(output.sourceFacts.every(f=>f.value===null&&f.state==='needs_confirmation'));assert(output.questions.some(q=>q.id==='material'));});
test('review expires no later than a current equipment source',()=>{const f=fixture(),expiry=new Date(+now+30000).toISOString();f.record.state.equipmentBasis.assets[0].research.freshUntil=expiry;assert.equal(run(f).expiresAt,expiry);});
