 'use strict';
const c=require('../../src/polaris/groundedRecommendations'),policy=require('../../src/polaris/groundedRecommendationPolicy');
const {sha256}=require('../../src/services/businessProfileAdapter');
function item(id='selected',scope={jobType:'replace',linearFeet:100,material:'cedar',removal:true}){return{ids:{estimate:id,graph:id,customer:'private-name',operation:id,opportunity:id,polarisSnapshot:id},snapshot:{service:{key:'fence',supported:true,scope},customerFacingPrice:1200},estimate:{currency:'USD'},snapshotDigest:'digest',normalizedInputFingerprint:'fingerprint',businessProfileAuthorityId:'profile',businessProfileInputVersion:1,businessProfileInputHash:'hash',calculationVersion:'original',snapshotCreatedAt:id==='selected'?'2026-09-13T12:00:00Z':'2026-09-12T12:00:00Z'};}
function review(){return{pins:{estimateId:'selected'},selectedRevision:2,isCurrent:true,recordedAt:'2026-09-13T12:00:00Z',currency:'USD',rows:[],missing:[],decisions:{writeBasis:{revision:1,digest:'decision'}},commercialTerms:{approvalState:'commercial_approved'}};}
afterEach(()=>{policy.enabled=true;});
test('explicit quantitative string and numeric fields require units and complete service minimums',()=>{
 const scope=extra=>({jobType:'replace',linearFeet:100,material:'cedar',...extra});
 expect(c.comparisonKey(item())).not.toBeNull();
 for(const s of [{},{material:'cedar'},{jobType:'replace',material:'cedar'},{height:'6'},scope({height:6}),scope({height:'6'}),scope({height:'unknown'}),scope({linearFeet:null}),scope({linearFeet:'unknown'}),scope({linearFeet:Infinity}),scope({linearFeet:-1}),scope({linearFeet:'1e3'}),scope({linearFeetUnit:'m'}),scope({mysteryQuantity:'6'}),scope({height:'6 ft'})])expect(c.comparisonKey(item('selected',s))).toBeNull();
 for(const s of [scope({height:6,heightUnit:'ft'}),scope({height:'6',heightUnit:'ft'}),scope({linearFeet:'100'}),scope({material:'2x4',model:'123'}),scope({height:'0',heightUnit:'ft'})])expect(c.comparisonKey(item('selected',s))).not.toBeNull();
 expect(c.comparisonKey(item('selected',scope({height:6,heightUnit:'ft'})))).not.toEqual(c.comparisonKey(item('selected',scope({height:'6',heightUnit:'ft'}))));
 expect(c.comparisonKey(item('selected',scope({height:'6',heightUnit:'ft'})))).not.toEqual(c.comparisonKey(item('selected',scope({height:'6',heightUnit:'m'}))));
 expect(c.comparisonKey(item('selected',scope({height:'6.0',heightUnit:'ft'})))).not.toEqual(c.comparisonKey(item('selected',scope({height:'6',heightUnit:'ft'}))));
});
test('supported service comparison minimums are explicit; categories alone never imply job size',()=>{for(const [key,scope]of [['roofing',{jobType:'replace',material:'metal',squares:'20'}],['hvac',{jobType:'replace',systemType:'heat pump',tonnage:'3',tonnageUnit:'tons of cooling'}],['concrete',{jobType:'install',squareFeet:'300'}]]){const i=item('selected',scope);i.snapshot.service.key=key;expect(c.comparisonKey(i)).not.toBeNull();}for(const key of ['plumbing','electrical','unrecognized']){const i=item();i.snapshot.service.key=key;expect(c.comparisonKey(i)).toBeNull();}});
test('original examples are bounded exact dated and exclude same graph unsupported currency and source gaps',()=>{const a=item(),b=item('prior');let other=item('eur');other.estimate.currency='EUR';let missing=item('missing');delete missing.snapshotDigest;const r=c.comparisons(a,[a,b,other,missing]);expect(r.examples).toHaveLength(1);expect(r.examples[0].amount).toBe(1200);expect(JSON.stringify(r)).not.toMatch(/private-name/);expect(c.comparisons(a,Array.from({length:55},(_,i)=>item('p'+i))).examples).toHaveLength(3);expect(c.comparisons(a,Array.from({length:55},(_,i)=>item('p'+i))).truncated).toBe(true);b.snapshot.service.supported=false;expect(c.comparisons(a,[b]).examples).toHaveLength(0);});
test('no price confidence or automatic action and original history objects unchanged',()=>{const r=review(),a=item(),before=sha256({r,a});const out=c.build(r,a);expect(out.items).toEqual([]);expect(out.sources[0].kind).toBe('calculated_result');expect(sha256({r,a})).toBe(before);expect(out).not.toHaveProperty('confidence');expect(out).not.toHaveProperty('price');});
test('hard block precedes incomplete cost and full approval recommendation',()=>{const r=review();r.missing=['not covered'];r.equipmentReadiness={current:{action:'save',result:{status:'blocked'}}};r.commercialTerms.approvalState='scope_price_only';const out=c.build(r,item());expect(out.items[0].id).toBe('readiness');expect(out.items.map(x=>x.id)).toEqual(expect.arrayContaining(['costs','approval']));});
test('current and still-included travel resource uncertainty remains explicit',()=>{const r=review();r.travelPlans={current:{action:'save',resourceReview:{needsReview:true}}};r.adoptedTravelPlan={action:'save',resourceReview:{needsReview:true}};expect(c.build(r,item()).items.map(x=>x.id)).toEqual(expect.arrayContaining(['travel_access','included_travel']));});
test('historical review retains cautions but offers no mutation action',()=>{const r=review();r.isCurrent=false;r.pricingPlans={current:{action:'save',sourceUnavailable:true}};const out=c.build(r,item());expect(out.historical).toBe(true);expect(out.items.every(x=>x.action===null)).toBe(true);});
test('revoked private publication title content never replayed from historic result',()=>{const r=review();r.equipmentPlans={current:{action:'save',inputs:{lines:[{knowledgePins:['pub']}]},result:{lines:[{status:'matches_reviewed_requirements',companyReferences:[{publicationId:'pub',label:'SECRET',content:'SECRET'}]}]}},sources:{knowledge:[]}};expect(JSON.stringify(c.build(r,item()))).not.toContain('SECRET');r.equipmentPlans.sources.knowledge=[{publicationId:'pub',label:'Permitted Source',content:{text:'Source statement'},digest:'d'}];const out=c.build(r,item());expect(out.sources.some(x=>x.label==='Permitted Source')).toBe(true);r.equipmentPlans.sources.knowledge=[];expect(c.build(r,item()).basisDigest).not.toEqual(out.basisDigest);});
test('unselected knowledge never appears and missing end date is unknown',()=>{const r=review();r.equipmentPlans={current:{action:'save',inputs:{lines:[]},result:{lines:[{lineId:'a',status:'matches_reviewed_requirements',research:{state:'reviewed',reviewedAt:'2026-09-01'}}]}},sources:{knowledge:[{publicationId:'unselected',label:'Unrelated private content'}]}};const out=c.build(r,item());expect(JSON.stringify(out)).not.toContain('Unrelated');expect(out.sources.find(x=>x.kind==='reviewed_source').freshness).toBe('unknown');});
test('disable preserves populated financial/history source and returns useful unavailable copy',()=>{const r=review();r.revisionHistory=[{revision:2}];const before=sha256(r);policy.enabled=false;expect(c.build(r,item()).state).toBe('unavailable');expect(sha256(r)).toBe(before);policy.enabled=true;expect(c.build(r,item()).state).toBe('ready');});
test('all source and selection changes alter ephemeral basis identity',()=>{const r=review(),a=item(),before=c.build(r,a).basisDigest;r.decisions.writeBasis.revision++;expect(c.build(r,a).basisDigest).not.toBe(before);r.pins.estimateId='second';expect(c.build(r,a).sources[0].pins.estimateId).toBe('second');});

test('material evidence includes still-adopted shortage after current withdrawal',()=>{const r=review();r.materialPlans={current:{action:'withdraw'}};r.adoptedMaterialPlan={action:'save',currentAvailabilityAssessment:{lines:[{currentStatus:'reported_shortage',flags:[]}]},currentSourceAssessment:{lines:[{flags:['expired']}]}};expect(c.build(r,item()).items.map(x=>x.id)).toEqual(expect.arrayContaining(['included_material_shortage','included_material_evidence']));});
test('actual below-policy result is a priority conflict without inventing a new threshold',()=>{const r=review();r.pricingPolicyCheck={state:'compared',result:{threshold:'1500.00',proposed:{status:'below'},reviewed:{status:'at'}}};const out=c.build(r,item());expect(out.items[0].id).toBe('policy_floor');expect(r.pricingPolicyCheck.result.threshold).toBe('1500.00');});
test('partial comparison dates and unknown unsupported service do not produce examples',()=>{const a=item();delete a.snapshotCreatedAt;expect(c.comparisons(a,[item('prior')]).examples).toHaveLength(0);a.snapshot.service.key='unknown';expect(c.comparisonKey(a)).toBeNull();});
