'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const c=require('../../src/estimating/pricingCalculation');
const source=()=>({kind:'owner_estimate',referenceId:null,digest:null,note:'',effectiveOn:null,endsOn:null});
const line=(id,amount='100.00')=>({lineId:id,label:'Service',kind:'fixed',quantity:null,unit:null,rate:null,amount,scope:'',includes:[],period:null,source:source()});
const input=()=>({serviceKey:'fence_installation',lines:[line('a')],payments:{mode:'none',balanceId:null,stages:[]},overhead:{method:'unknown',amount:null,percent:null,period:null,source:source(),coverage:{status:'unknown',explanation:'',included:[]}}});
test('unit charge rounds once at cents; zero and missing remain distinct',()=>{const v=input();Object.assign(v.lines[0],{kind:'unit',amount:null,quantity:'3',rate:'12.3456',unit:'each'});assert.equal(c.calculate(v,'USD').proposedBeforeTax,'37.04');v.lines[0].quantity='0';assert.equal(c.calculate(v,'USD').proposedBeforeTax,'0.00');v.lines[0].quantity=null;assert.equal(c.calculate(v,'USD').proposedBeforeTax,null);});
test('package inclusion conserves charges, rejects duplicate parent and cycle',()=>{const v=input();v.lines.push({...line('package','500.00'),kind:'package',scope:'Complete installation',includes:['a']});assert.equal(c.calculate(v,'USD').proposedBeforeTax,'500.00');v.lines.push({...line('other'),kind:'package',scope:'Other',includes:['a']});assert.throws(()=>c.calculate(v,'USD'),/only one/);v.lines.pop();Object.assign(v.lines[0],{kind:'package',scope:'Scope',includes:['package']});assert.throws(()=>c.calculate(v,'USD'),/cycle/);});
test('finite retainer multiplies explicit whole periods only',()=>{const v=input();Object.assign(v.lines[0],{kind:'retainer',amount:null,quantity:'4',rate:'250.00',unit:'period',period:{label:'Monthly',startsOn:'2026-09-01',endsOn:'2026-12-31'},scope:'Four inspections'});assert.equal(c.calculate(v,'USD').proposedBeforeTax,'1000.00');v.lines[0].quantity='1.5';assert.throws(()=>c.calculate(v,'USD'),/whole number/);});
test('deposit is part of price; shares conserve tiny cents',()=>{const v=input();v.lines[0].amount='1.00';v.payments={mode:'share',balanceId:'c',stages:[{stageId:'a',label:'Deposit',kind:'deposit',value:'33.33'},{stageId:'b',label:'Progress',kind:'milestone',value:'33.33'},{stageId:'c',label:'Final',kind:'balance',value:'33.34'}]};assert.deepEqual(c.calculate(v,'USD').payments.map(p=>p.amount),['0.33','0.33','0.34']);v.payments.stages[2].value='33.33';assert.throws(()=>c.calculate(v,'USD'),/equal/);});
test('explicit allocation uses selected costs and bounded included amount',()=>{const v=input();Object.assign(v.overhead,{method:'percent',percent:'10',coverage:{status:'disjoint',explanation:'Separate office expense',included:[]}});assert.equal(c.calculate(v,'USD',{directCosts:'1000.00'}).costWithOverhead,'1100.00');Object.assign(v.overhead,{method:'fixed',percent:null,amount:'100.00',coverage:{status:'allocated',explanation:'Same declared office pool',included:[{referenceId:'labor:a',amount:'30.00'}]}});const basis={directCosts:'1000.00',overheadIncluded:[{referenceId:'labor:a',amount:'30.00'}]};assert.equal(c.calculate(v,'USD',basis).costWithOverhead,'1070.00');v.overhead.coverage.included[0].amount='30.01';assert.throws(()=>c.calculate(v,'USD',basis),/recorded amount/);});
test('period allocation is exact; missing applicable direct costs prevent complete total',()=>{const v=input();Object.assign(v.overhead,{method:'period',period:{startsOn:'2026-09-01',endsOn:'2026-09-30',pool:'2400.00',jobUnits:'5',totalUnits:'120',unit:'person_hour'},coverage:{status:'disjoint',explanation:'Office only',included:[]}});const r=c.calculate(v,'USD');assert.equal(r.overhead.gross,'100.00');assert.equal(r.costWithOverhead,null);v.overhead.period.jobUnits='121';assert.throws(()=>c.calculate(v,'USD'),/exceed/);});
test('12 whole-plan lines accepted; 13, precision, currency and overflow rejected',()=>{const v=input();v.lines=Array.from({length:12},(_,i)=>line('line'+i));assert.equal(c.calculate(v,'USD').proposedBeforeTax,'1200.00');v.lines.push(line('extra'));assert.throws(()=>c.calculate(v,'USD'));v.lines=[line('a','1.001')];assert.throws(()=>c.calculate(v,'USD'));v.lines=[line('a')];assert.throws(()=>c.calculate(v,'GBP'));v.lines=[line('a','999999999999.99'),line('b','0.01')];assert.throws(()=>c.calculate(v,'USD'),/too large/);});
module.exports={source,line,input};

test('UTC review date cannot silently cross midnight; historical and current cautions stay separate',()=>{const c=require('../../src/estimating/pricingPlanContract'),inputs=require('../helpers/m24-pricing-input').fixture('fence'),sources={serviceKey:'fence',asOfDate:'2026-09-12',basis:{directCosts:'1000.00',overheadIncluded:[]},references:[],digest:'a'.repeat(64)};inputs.lines[0].source.effectiveOn='2026-09-11';inputs.lines[0].source.endsOn='2026-09-12';const p=c.preview(inputs,'USD',sources,new Date('2026-09-12T23:59:59.999Z'));assert.equal(p.assessment.date,'2026-09-12');assert.throws(()=>c.preview(inputs,'USD',sources,new Date('2026-09-13T00:00:00Z')),/date changed/);assert.ok(c.assess(inputs,{...sources,asOfDate:'2026-09-13'}).cautions[0].reasons.includes('expired'));assert.ok(!p.assessment.cautions.some(r=>r.index===0&&r.reasons.includes('expired')));});
