'use strict';
const {buildCanonicalKnowledgeDocument}=require('../knowledge/contract');
const {VERSION}=require('../estimating/proposalRecipe');
function create(id,createdAt,asset){
 const effectiveOn=new Date(createdAt).toISOString().slice(0,10),reviewBy=new Date(Date.parse(createdAt)+30*86400000).toISOString().slice(0,10);
 const evidence={kind:'company_reference',reference:'Simulated Fence Recipe v1',note:'Declared fictional planning inputs, not observed productivity or market rates.',effectiveOn,endsOn:reviewBy,geography:'simulated-workspace'};
 const source={kind:'owner_estimate',referenceId:null,digest:null,note:'Declared simulated company recipe; not a verified market price.',effectiveOn,endsOn:reviewBy};
 const recipe={version:VERSION,id:'simulated_fence_v1',serviceKey:'fence',currency:'USD',geography:'simulated-workspace',effectiveOn,reviewBy,
  applicability:[{fieldId:'material',value:'cedar',question:'Which fence material is required?'}],
  equipmentCostLines:[{lineId:id('proposal-equipment'),access:'owned',method:'economic_recovery',notApplicableReason:null,plannedHours:'8',rental:null,allocation:{period:'year',usableHours:'600',pool:{amount:'12000.00',scope:'equipment_only',split:null},includedCategories:['capital_recovery'],additionalCosts:[]},operating:{mode:'all_in',allIn:{status:'known',rate:{amount:'2.00',scope:'equipment_only',split:null}},fuelEnergy:null,consumables:null,maintenance:null},fees:[],source:{kind:'my_estimate',issuer:'Simulated Company',reference:'Simulated Fence Recipe v1',note:'Declared fictional annual equipment allocation and operating rate; no labor or travel included.',effectiveOn,endsOn:reviewBy,geography:'simulated-workspace'}}],
  fields:[{id:'linearFeet',label:'Fence length',type:'quantity',unit:'ft',allowedValues:null,question:'How many feet of fence are being installed?',why:'Fence length determines the declared material quantity and installation work.'},{id:'material',label:'Proposed fence material',type:'category',unit:'category',allowedValues:['cedar'],question:'Is cedar the material for the proposed work?',why:'This simulated recipe supports cedar only. Choosing it is an explicit owner assumption and does not change the recorded job.'}],
  steps:[{id:'length',op:'input',unit:'ft',args:[],fieldId:'linearFeet',value:null}],
  components:[
   {kind:'materials',version:'estimate-material-plan-v2',inputs:{lines:[{lineId:id('proposal-material'),material:'Simulated cedar fence materials',quantity:'1',unit:'ft',wastePercent:'10',unitPrice:'3.25',sourceType:'entered_price',sourceNote:'Simulated Fence Recipe v1: declared materials per installed foot. No supplier verification.',priceDate:effectiveOn}]},bindings:[{line:0,field:'quantity',step:'length'}]},
   {kind:'labor',version:'estimate-labor-plan-v1',inputs:{serviceKey:'fence',lines:[{lineId:id('proposal-labor'),task:'Simulated onsite fence installation',basis:'quantity_productivity',workerHours:null,people:null,elapsedHours:null,quantity:'1',unit:'ft',hoursPerUnit:'0.08',rateMode:'all_in',hourlyCost:'42.00',burdenPercent:null,quantitySource:evidence,rateSource:evidence}],assessment:null},bindings:[{line:0,field:'quantity',step:'length'}]},
   {kind:'equipment',version:'estimate-equipment-plan-v1',inputs:{serviceKey:'fence',lines:[{lineId:id('proposal-equipment'),task:'Review auger for simulated fence holes',assetId:asset.id,identity:asset.privateConfiguration,accessBasis:'owned',requirements:[{requirementId:id('proposal-requirement'),label:'Declared hole diameter',kind:'numeric',operator:'equals',value:'150',unit:'mm',origin:'owner_entry',scopeKey:null,specificationIndex:0}],knowledgePins:[],ownerReview:'Simulated requirement only. Site conditions and underground services still need review.'}],assessment:null},bindings:[]},
   {kind:'travel',version:'estimate-travel-plan-v1',inputs:{serviceKey:'fence',trips:[],logistics:[{lineId:id('proposal-mobilization'),label:'Simulated job mobilization charge',category:'mobilization',applicable:true,reason:null,basis:'whole_job',tripId:null,quantity:'1',unit:'job',rate:'20.00',source:{kind:'my_estimate',issuer:'Simulated Company',reference:'Simulated Fence Recipe v1',note:'Declared equipment-only mobilization cost. Driving, fuel and driver time remain unrecorded.',effectiveOn,endsOn:reviewBy,geography:'simulated-workspace'}}],access:[],hauls:[],loadBindings:[],stagePlan:null,assessment:null},bindings:[]},
   {kind:'pricing',version:'estimate-pricing-plan-v1',inputs:{serviceKey:'fence',lines:[{lineId:'simulated-installation',label:'Simulated installation price',kind:'package',quantity:null,unit:null,rate:null,amount:'1500.00',scope:'Declared simulated installation charge, subject to owner review',includes:[],period:null,source}],payments:{mode:'none',balanceId:null,stages:[]},overhead:{method:'fixed',amount:'100.00',percent:null,period:null,source,coverage:{status:'unknown',explanation:'The overhead allocation has not been reconciled with this new draft.',included:[]}}},bindings:[]}
  ]};
 const document=buildCanonicalKnowledgeDocument({applicability:{},canonicalKey:'organization.services',content:{estimateProposalRecipe:recipe},entryType:'generated_knowledge',label:'Simulated Fence Planning Recipe',origin:'human',reviewRequirement:'high_risk',sensitivity:'restricted'});
 const knowledge={entry_id:id('proposal-entry'),canonical_key:'organization.services',entry_type:'generated_knowledge',version_id:id('proposal-version'),version_number:1,sensitivity:'restricted',review_requirement:'high_risk',canonical_document:document.canonicalDocument,canonical_digest:document.canonicalDigest,publication_id:id('proposal-publication'),publication_number:1,publication_digest:document.canonicalDigest};
 return{knowledge,basis:{version:'simulated-fence-proposal-basis-v1',geography:'simulated-workspace',publicationId:knowledge.publication_id,digest:knowledge.canonical_digest,simulated:true}};
}
module.exports={create};
