'use strict';
const {stableValue,sha256}=require('../services/businessProfileAdapter'),p=require('../estimating/taxPreparation');
const LEGACY_VERSION='demo-tax-preparation-v1',VERSION='demo-tax-preparation-v2';
function create(profile,createdAt){
 const start=new Date(createdAt).toISOString().slice(0,10),end=new Date(new Date(createdAt).getTime()+365*86400000).toISOString().slice(0,10),location=profile?.headquarters||{};
 const examples=(profile?.services||[]).slice(0,12).map(service=>({id:'practice-'+service.id,country:location.country||'',region:location.state||'',locality:location.city||'',jurisdiction:'Simulated Practice Jurisdiction',serviceKey:service.id,classification:'Practice Service',registration:'registered',registrationReference:'Simulated Registration — Not A Real Registration',collectionBasis:'Authored arithmetic example only',exemptionReference:'',effectiveOn:start,endsOn:end,sourceNote:'Authored demo evidence. The practice rate is not a real jurisdiction rate.',sourceReference:'NorthStar simulated tax example v1',acknowledged:false}));
 const ruleValues=examples.map(c=>{const value={id:'practice-rule-'+c.serviceKey,version:p.VERSION,validation:'validated',simulated:true,active:true,country:c.country,region:c.region,locality:c.locality,jurisdiction:c.jurisdiction,serviceKey:c.serviceKey,classification:c.classification,registration:c.registration,collectionBasis:c.collectionBasis,legalEffectiveOn:start,legalEndsOn:null,reviewedOn:start,reviewValidThrough:end,applicability:{serviceOperations:['practice_service'],propertyUses:['residential','commercial'],workContexts:['maintenance','repair'],customerExemptions:['none']},treatment:'taxable',ratePercent:'10',behavior:'exclusive'};return {...value,digest:sha256(value)};});
 return {version:VERSION,simulated:true,rules:ruleValues,examples};
}
function rules(state){return [LEGACY_VERSION,VERSION].includes(state.taxPreparationBasis?.version)&&state.taxPreparationBasis.simulated===true?state.taxPreparationBasis.rules||[]:[];}
// Seeded profiles explicitly bind their durable service ID to a supported job key.
// Never infer this relationship from a label or manufacture it for legacy profiles.
function serviceIdentity(state,jobKey){const services=state.workspace?.businessProfile?.services||[],supported=require('./demoWorkspaceGenerator').SERVICE_DEFINITIONS.some(s=>s.key===jobKey);if(!supported)return null;const matches=services.filter(s=>s.key===jobKey&&typeof s.id==='string'&&s.id);if(matches.length!==1||services.filter(s=>s.id===matches[0].id).length!==1)return null;return matches[0].id;}
function read(state,now){const history=state.taxProfiles||[],current=history[0]||null,profile=state.workspace?.businessProfile||{},inputs=p.preparationInput(profile,current?.inputs||{version:p.VERSION,contexts:[]});const result=p.evaluate(inputs.inputs,rules(state),now.toISOString().slice(0,10),{simulated:true});return {version:inputs.version,services:(profile.services||[]).map(s=>({id:s.id,label:s.label||s.name||'Unnamed Business Service'})),practiceExamples:[LEGACY_VERSION,VERSION].includes(state.taxPreparationBasis?.version)?state.taxPreparationBasis.examples||[]:[],expectedProfileVersion:'demo-profile:'+sha256(profile),current:current?{id:current.id,revision:current.revision,digest:current.digest,inputs:current.inputs,createdAt:current.createdAt}:null,history:history.map(e=>({id:e.id,revision:e.revision,digest:e.digest,inputs:e.inputs,createdAt:e.createdAt})),inputDigest:inputs.digest,rulesDigest:sha256(rules(state)),resultCurrent:true,result,preparationState:result.state,simulated:true};}
function apply(state,raw,key,now){const b=p.normalizeMutation(raw),history=state.taxProfiles||[],old=history.find(e=>e.requestKey===key),requestDigest=sha256(b);if(old){if(old.requestDigest!==requestDigest)throw Object.assign(new Error('This attempt was already used for different tax setup entries.'),{status:409,code:'COMMERCIAL_CHANGED'});return state;}if(b.confirmationVersion!==p.VERSION)throw Object.assign(new Error('Refresh to review the current tax setup form.'),{status:400,code:'TAX_PROFILE_INVALID'});const current=read(state,now);if(b.expectedRevision!==(current.current?.revision||0)||b.expectedDigest!==(current.current?.digest||'none')||b.expectedProfileVersion!==current.expectedProfileVersion)throw Object.assign(new Error('The tax setup changed. Refresh and review the current entries.'),{status:409,code:'COMMERCIAL_CHANGED'});if(history.length>=20)throw Object.assign(new Error('This demo has reached its tax setup history limit. Saved history remains available. Resetting clears its practice work.'),{status:429,code:'COMMERCIAL_HISTORY_LIMIT'});const receipt={id:require('node:crypto').randomUUID(),revision:(current.current?.revision||0)+1,inputs:b.inputs,body:b,createdAt:now.toISOString(),requestKey:key,requestDigest,digest:sha256({body:b,previous:current.current?.digest||null})};return stableValue({...state,taxProfiles:[receipt,...history],taxPreparationResult:read({...state,taxProfiles:[receipt,...history]},now).result});}
module.exports={VERSION,create,rules,read,apply,serviceIdentity};
