'use strict';
const w=require('../../src/commandCenter/workspace'),{DEFAULT_SELECTION}=require('../../src/commandCenter/scenarioSpace');
const {sha256}=require('../../src/services/businessProfileAdapter'),{calculateCanonicalPolaris,CALCULATION_VERSION}=require('../../src/services/canonicalPolarisCalculation');
const tenantId='11111111-1111-4111-8111-111111111111',createdAt=new Date('2026-09-14T12:00:00Z');
function check(g){expect(g.polaris.calculationVersion).toBe(CALCULATION_VERSION);expect(g.polaris.snapshot).toEqual(calculateCanonicalPolaris(g.polaris.syntheticCalculation.input));expect(g.polaris.snapshotDigest).toBe(sha256(g.polaris.snapshot));expect(g.polaris.syntheticCalculation.note).toMatch(/Illustrative.*not researched|Fictional review amount only|Fictional tree estimate calculated/);expect(g.polaris.snapshot.service.key).toBe(g.lead.serviceType);expect(g.polaris.snapshot.service.scope.jobType).toBe(g.polaris.facts.find(f=>f.variable==='jobType')?.normalizedValue||g.polaris.snapshot.service.scope.jobType);}
test('every initial/reset service and graph uses deterministic canonical fictional costs',()=>{const services=new Set();for(let i=0;i<24;i++){const args={seed:'entry-test-'+i,generation:i+1},s=w.createInitialDemoState(tenantId,createdAt,args);expect(w.createInitialDemoState(tenantId,createdAt,args)).toEqual(s);for(const g of s.graphs){check(g);services.add(g.lead.serviceType);}}expect([...services].sort()).toEqual(Object.keys(w.DEMO_SERVICES).sort());});
test.each(Object.keys(w.DEMO_SERVICES))('%s ordinary simulated lead retains selected facts and deterministic calculation',service=>{const input={tenantId,key:'normal-'+service,createdAt,scenarioSelection:{...DEFAULT_SELECTION,service,intent:'repair_request'}},before=JSON.stringify(input),g=w.buildSimulatedGraph(input);check(g);expect(w.buildSimulatedGraph(input)).toEqual(g);expect(JSON.stringify(input)).toBe(before);expect(g.communication.transcript.some(t=>t.text===(service==='tree'?'I would like the tree trimmed and pruned.':'A repair.'))).toBe(true);expect(g.polaris.snapshot.service.scope.jobType).toBe(service==='tree'?'pruning':'repair');});
test('legacy adoption remains refused before any calculation',()=>{expect(()=>require('../../src/estimating/proposalAdoptionReview').build({item:{calculationVersion:'command-center-demo-v1'}},{version:'estimate-proposal-adoption-v1',draft:{version:'estimate-proposal-preview-v1',selectedRevision:null,expectedBasisDigest:'a'.repeat(64),overrides:[],candidateIds:[]},selection:{materials:'replace',labor:'replace',equipment:'replace',travel:'replace',pricing:'replace'},previousReceipt:null,coverage:{costs:{overlaps:[],equipmentOutside:[],travelOutside:[],confirmed:true,reason:'Explicit local legacy boundary.'},overhead:{status:'disjoint',explanation:'Separate local test costs.',included:[]}},pricingPolicy:null,expectedReviewDigest:null,confirmed:false,reason:'Local legacy preservation check.'})).toThrow(/earlier estimate/);});

test('shared boundary preserves prior identity, business, dialogue, schedule and original first example',()=>{const Module=require('module'),filename=require.resolve('../../src/commandCenter/workspace'),old=new Module(filename,module);old.filename=filename;old.paths=module.paths;old._compile(require('child_process').execFileSync('git',['show','abfe3abcea4f98bdff602edc0ab27ff270d4e27f:src/commandCenter/workspace.js'],{encoding:'utf8'}),filename);const before=old.exports.createInitialDemoState(tenantId,createdAt,{seed:'same-records'}),after=w.createInitialDemoState(tenantId,createdAt,{seed:'same-records'});expect(after.graphs[0]).toEqual(before.graphs[0]);for(let i=0;i<3;i++){const omit=g=>Object.fromEntries(Object.entries(g).filter(([k])=>!['polaris','estimate','projectionDigest'].includes(k)));expect(omit(after.graphs[i])).toEqual(omit(before.graphs[i]));expect(after.graphs[i].polaris.facts).toEqual(before.graphs[i].polaris.facts);expect(after.graphs[i].estimate.customerPrice).toEqual(before.graphs[i].estimate.customerPrice);}expect(after.workspace).toEqual(before.workspace);expect(after.operationsSchedulingBasis).toEqual(before.operationsSchedulingBasis);});
