'use strict';
const {calculate}=require('../../src/estimating/equipmentCostCalculation');
const source={kind:'my_estimate',issuer:'',reference:'',note:'',effectiveOn:null,endsOn:null,geography:''};
const charge=amount=>({amount,scope:'equipment_only',split:null});
const na=()=>({status:'not_applicable',rate:null});
const operating=()=>({mode:'all_in',allIn:na(),fuelEnergy:null,consumables:null,maintenance:null});
function line(){return{lineId:'11111111-1111-4111-8111-111111111111',access:'owned',method:'economic_recovery',notApplicableReason:null,plannedHours:'8',rental:null,allocation:{period:'year',usableHours:'600',pool:charge('12000.00'),includedCategories:['capital_recovery'],additionalCosts:[]},operating:operating(),fees:[],source:{...source}};}
const result=l=>calculate({lines:[l]},'USD');
test('declared economic allocation uses the same period and exact hours',()=>expect(result(line()).total).toBe('160.00'));
test('financing allocation does not also add economic recovery',()=>{const l=line();l.method='financing_cash';l.access='financed';Object.assign(l.allocation,{period:'month',usableHours:'60',pool:charge('1200.00'),includedCategories:['debt_service']});expect(result(l).total).toBe('160.00');l.allocation.additionalCosts.push({category:'capital_recovery',label:'Recovery',charge:charge('100.00')});expect(()=>result(l)).toThrow(/separate period/);});
test('explicit rental quantity meets, or exceeds, its known minimum',()=>{const l=line();l.method='rental';l.access='rented';l.allocation=null;l.rental={unit:'day',quantity:'2',minimumQuantity:'1',charge:charge('150.00')};l.fees=[{category:'setup',label:'Equipment setup fee',amount:'25.00'}];expect(result(l).total).toBe('325.00');l.rental.minimumQuantity='3';expect(()=>result(l)).toThrow(/minimum/);l.rental.minimumQuantity=null;expect(result(l).total).toBe('325.00');});
test('round once per line, then sum rounded line amounts',()=>{const l=line();l.plannedHours='1';l.allocation.pool=charge('1.00');l.allocation.usableHours='3';expect(result(l).total).toBe('0.33');const lines=[1,2,3].map(n=>({...structuredClone(l),lineId:`11111111-1111-4111-8111-11111111111${n}`}));expect(calculate({lines},'USD').total).toBe('0.99');l.operating.allIn={status:'known',rate:charge('0.01')};expect(result(l).total).toBe('0.34');});
test('known zero differs from missing and denominator zero is invalid',()=>{const l=line();l.allocation.pool=charge('0.00');expect(result(l).total).toBe('0.00');l.allocation.pool.amount=null;expect(result(l)).toMatchObject({total:null,knownCostSubtotal:'0.00',complete:false});l.allocation.usableHours='0';expect(()=>result(l)).toThrow(/greater than zero/);});
test('operator share is excluded and unaccounted coverage prevents complete adoption',()=>{const l=line();l.method='rental';l.allocation=null;const coverage={status:'unknown',basis:null,note:''};l.rental={unit:'job',quantity:'1',minimumQuantity:null,charge:{amount:'500.00',scope:'mixed',split:{equipment:'300.00',operator:'200.00',travel:'0.00',overhead:'0.00',operatorCoverage:{...coverage},travelCoverage:{...coverage}}}};expect(result(l)).toMatchObject({knownCostSubtotal:'300.00',total:null,complete:false});l.rental.charge.split.operatorCoverage={status:'covered',basis:{kind:'original'},note:'Operator covered in the reviewed labor basis.'};expect(result(l).total).toBe('300.00');l.rental.charge.split.equipment='301.00';expect(()=>result(l)).toThrow(/equal/);});
test('included maintenance and interest cannot be charged twice',()=>{const l=line();l.allocation.includedCategories.push('maintenance','interest');expect(result(l).total).toBe('160.00');l.operating={mode:'separate',allIn:null,fuelEnergy:na(),consumables:na(),maintenance:{status:'known',rate:charge('1.00')}};expect(()=>result(l)).toThrow(/more than once/);l.operating=operating();l.allocation.additionalCosts=[{category:'interest',label:'Interest',charge:charge('1.00')}];expect(()=>result(l)).toThrow(/more than once/);});
test('incomplete operating costs never become free or a complete total',()=>{const l=line();l.operating.allIn={status:'unknown',rate:null};expect(result(l)).toMatchObject({knownCostSubtotal:'160.00',total:null,complete:false});});
test('overflow, unsupported currency, duplicate identity and fractional per-job billing reject',()=>{const l=line();l.allocation.pool.amount='999999999999.99';l.plannedHours='999999999';l.allocation.usableHours='0.000001';expect(()=>result(l)).toThrow(/too large/);expect(()=>calculate({lines:[line()]},'GBP')).toThrow(/currency/);expect(()=>calculate({lines:[line(),line()]},'USD')).toThrow(/only once/);l.method='rental';l.allocation=null;l.rental={unit:'job',quantity:'0.5',minimumQuantity:null,charge:charge('1.00')};expect(()=>result(l)).toThrow(/one billed job/);});
test('not applicable retains a reason and cannot hide a cost payload',()=>{const l=line();Object.assign(l,{method:'not_applicable',notApplicableReason:'This equipment will not be used.',plannedHours:null,allocation:null,operating:null});expect(result(l).total).toBe('0.00');l.fees.push({category:'setup',label:'Setup',amount:'1.00'});expect(()=>result(l)).toThrow(/no applicable/);});
module.exports={line,charge};
