'use strict';
const {assessLine,validate}=require('../../src/estimating/equipmentReadinessContract');
const id='11111111-1111-4111-8111-111111111111',now='2026-09-12T12:00:00.000Z';
function line(){return {lineId:id,required:true,notRequiredReason:'',quantity:1,start:'2026-09-12T13:00:00Z',end:'2026-09-12T14:00:00Z',timeZone:'America/New_York',location:'Recorded job site',source:{kind:'my_observation',label:'Owner observation',reference:'',observedAt:'2026-09-12T11:00:00Z',validUntil:'2026-09-12T15:00:00Z',quantity:1,start:'2026-09-12T13:00:00Z',end:'2026-09-12T14:00:00Z',condition:'reported_no_problem',restrictions:'',location:'Recorded job site',leadTime:0,leadTimeUnit:'hours'},maintenance:{dueAt:null,meterKey:null,threshold:null,unit:null,reference:''},alternatives:[]};}
function fact(){return {lineId:id,assetId:id,complete:true,sourceCurrent:true,requirementStatus:'matches_reviewed_requirements',state:{downtime:false,checkedOutExecution:null,recordedFault:false,readings:{hours:{reading:'10',unit:'hours'}}}};}
test('complete declared covering evidence is qualified nonconflict, never reserved or safe',()=>expect(assessLine(line(),fact(),now).status).toBe('no_recorded_conflict'));
test.each([['no ledger',null,'operational_history_unknown'],['truncated',{...fact(),complete:false},'operational_history_unknown'],['source changed',{...fact(),sourceCurrent:false},'equipment_source_changed'],['fault followed by maintenance',{...fact(),state:{...fact().state,recordedFault:true}},'recorded_fault']])('%s remains review',(_,f,code)=>expect(assessLine(line(),f,now).review).toContain(code));
test('open downtime stays blocked despite expired optimistic owner evidence',()=>{const l=line();l.source.validUntil=now;expect(assessLine(l,{...fact(),state:{downtime:true}},now).hard).toContain('recorded_downtime');});
test('other execution checkout blocks; matching execution and target does not independently claim availability',()=>{const f=fact();f.state.checkedOutExecution=id;expect(assessLine(line(),f,now).status).toBe('blocked');f.currentJob=true;f.targetMatches=true;expect(assessLine(line(),f,now,{scheduledStart:line().start,scheduledEnd:line().end}).hard).toEqual([]);f.targetMatches=false;expect(assessLine(line(),f,now,{}).hard).toContain('recorded_checkout');});
test.each([null,'2026-09-12T12:00:00Z'])('unknown/expired validity %s cannot establish availability',until=>{const l=line();l.source.validUntil=until;expect(assessLine(l,fact(),now).review).toContain('source_date_unknown_or_expired');});
test('source window boundary covers exact half-open work, shorter does not',()=>{const l=line();expect(assessLine(l,fact(),now).hard).toEqual([]);l.source.end='2026-09-12T13:59:59Z';expect(assessLine(l,fact(),now).hard).toContain('reported_window_shortfall');});
test('missing quantity differs from known zero stock; identified asset cannot supply two',()=>{const l=line();l.source.quantity=null;expect(assessLine(l,fact(),now).review).toContain('quantity_unknown');l.source.quantity=0;expect(assessLine(l,fact(),now).hard).toContain('reported_quantity_shortfall');l.source.quantity=2;l.quantity=2;expect(assessLine(l,fact(),now).hard).toContain('identified_asset_quantity');});
test('due maintenance asks for review and never clears a fault',()=>{const l=line();l.maintenance.dueAt=now;const f=fact();f.state.recordedFault=true;expect(assessLine(l,f,now).review).toEqual(expect.arrayContaining(['recorded_fault','maintenance_due']));});
test('threshold has exact same-unit semantics, reset/unknown does not infer service clearance',()=>{const l=line();l.maintenance={dueAt:null,meterKey:'hours',threshold:'10',unit:'hours',reference:'Declared interval'};expect(assessLine(l,fact(),now).review).toContain('maintenance_due');l.maintenance.unit='mi';expect(assessLine(l,fact(),now).review).toContain('maintenance_meter_unknown');});
test('future owner observation rejects with actionable date category',()=>{const l=line();l.source.observedAt='2026-09-13T00:00:00Z';expect(()=>assessLine(l,fact(),now)).toThrow('future');});
test('a required scope mismatch blocks; unknown requirements only review',()=>{expect(assessLine(line(),{...fact(),requirementStatus:'conflicts_with_requirement'},now).status).toBe('blocked');expect(assessLine(line(),{...fact(),requirementStatus:'needs_information'},now).status).toBe('needs_review');});
test('explicit not-required needs a reason; alternatives bounded across all lines',()=>{const l=line(),v={equipmentBasis:{planId:id,revision:1,digest:'a'.repeat(64)},lines:[l],replacement:null,assessment:null};expect(()=>validate(v)).not.toThrow();l.required=false;expect(()=>validate(v)).toThrow();l.notRequiredReason='This item is not required for this scope';expect(()=>validate(v)).not.toThrow();});

test('unscheduled proposal never borrows the saved equipment window',()=>{expect(assessLine(line(),fact(),now,{scheduledStart:null,scheduledEnd:null}).review).toContain('required_window_unknown');});
test('reported lead time uses its observation instant and does not promise delivery',()=>{const l=line();l.source.leadTime=3;expect(assessLine(l,fact(),now).review).toContain('lead_time_after_work_start');l.source.leadTime=2;expect(assessLine(l,fact(),now).review).not.toContain('lead_time_after_work_start');});
test('different human location wording and restrictions require review without semantic inference',()=>{const l=line();l.source.location='Yard';l.source.restrictions='Requires collection';expect(assessLine(l,fact(),now).review).toEqual(expect.arrayContaining(['location_needs_confirmation','reported_restrictions']));});
test.each(['2026-02-30T12:00:00Z','2026-09-12T24:00:00Z','2026-09-12T12:00:60Z','2026-09-12T12:00:00+14:01','0000-01-01T00:00:00Z'])('invalid calendar instant %s rejects before preview',instant=>{const l=line();l.source.observedAt=instant;expect(()=>validate({equipmentBasis:{planId:id,revision:1,digest:'a'.repeat(64)},lines:[l],replacement:null,assessment:null})).toThrow();});

test('one physical asset cannot satisfy overlapping line needs, but adjacent windows do not overlap',()=>{const a=line(),b=line();b.lineId='22222222-2222-4222-8222-222222222222';const inputs={equipmentBasis:{planId:id,revision:1,digest:'a'.repeat(64)},lines:[a,b],replacement:null,assessment:null},evidence={lines:[fact(),{...fact(),lineId:b.lineId}]},evaluate=require('../../src/estimating/equipmentReadinessContract').evaluate;expect(evaluate(inputs,evidence,now).lines.every(l=>l.hard.includes('identified_asset_overlap'))).toBe(true);b.start=a.end;b.end='2026-09-12T15:00:00Z';expect(evaluate(inputs,evidence,now).lines.every(l=>!l.hard.includes('identified_asset_overlap'))).toBe(true);b.start=null;b.end=null;expect(evaluate(inputs,evidence,now).lines.every(l=>l.review.includes('identified_asset_windows_unknown'))).toBe(true);});

test('meter reset provenance is per meter and compared with the reviewed observation',()=>{const l=line();l.maintenance={dueAt:null,meterKey:'hours',threshold:'100',unit:'hours',reference:'Declared threshold'};const f=fact();f.meterResets={miles:'2026-09-12T11:30:00Z'};expect(assessLine(l,f,now).review).not.toContain('maintenance_meter_unknown');f.meterResets.hours='2026-09-12T11:30:00Z';expect(assessLine(l,f,now).review).toContain('maintenance_meter_unknown');l.source.observedAt='2026-09-12T11:45:00Z';expect(assessLine(l,f,now).review).not.toContain('maintenance_meter_unknown');});


test('a simulated job hold never fabricates an exact execution match',()=>{const f=fact();f.declaredCheckout={currentJob:true,targetMatches:true,executionKnown:false};const proposal={scheduledStart:line().start,scheduledEnd:line().end};expect(assessLine(line(),f,now,proposal).review).toContain('checkout_execution_unknown');expect(f.currentJob).toBeUndefined();f.declaredCheckout.currentJob=false;expect(assessLine(line(),f,now,proposal).hard).toContain('recorded_checkout');f.declaredCheckout.currentJob=true;f.declaredCheckout.targetMatches=false;expect(assessLine(line(),f,now,proposal).hard).toContain('recorded_checkout');});

test('fresh simulated checkout examples reference existing jobs without creating work history',()=>{const demo=require('../../src/commandCenter/demoEquipmentReadiness'),graphs=[{ids:{appointment:id}},{ids:{appointment:'22222222-2222-4222-8222-222222222222'}}],team={members:[{accessRole:'member',id:'33333333-3333-4333-8333-333333333333'}]},basis=demo.create('checkout-source',now,graphs,team),holds=basis.assets.filter(a=>a.checkoutJob);expect(holds).toHaveLength(2);expect(holds.map(a=>a.checkoutJob.appointmentId)).toEqual(graphs.map(g=>g.ids.appointment));expect(holds.every(a=>a.checkoutJob.executionId===null&&a.state.checkedOutExecution===null&&a.events[0].kind==='declared_checkout')).toBe(true);expect(basis.operations).toBeUndefined();expect(demo.create('old-source',now).assets.some(a=>a.checkoutJob)).toBe(false);});
