'use strict';
const source=require('../../src/estimating/materialSourceContract'),plan=require('../../src/estimating/materialPlanContract');
const when=new Date('2026-09-11T23:59:59.900Z');
function line(){return {lineId:'00000000-0000-4000-8000-000000000051',material:'Boards',quantity:'100',unit:'ft',wastePercent:'10',unitPrice:'3.25',sourceType:'my_estimate',sourceNote:'Human record',priceDate:null,evidence:{kind:'my_estimate',issuer:null,reference:null,effectiveOn:null,validThrough:null,countryCode:null,region:null,locality:null,serviceKey:null,materialSpecification:null,statedUnit:'ft',statedCurrency:'USD',statedUnitPrice:'3.25',appliesToReviewedJob:true,exceptionReason:null}};}
function inputs(){return {lines:[line()],sourceAssessment:null};}
function reviewed(v,now=when){v.sourceAssessment=source.assess(v,'USD',{now});return v;}
test('human estimate with missing dates/place needs attestation, no fictitious dates or exception',()=>{const v=reviewed(inputs());expect(source.checkSaved(v,'USD',{now:when}).lines[0].flags).toEqual(['date_missing','end_date_missing','place_unknown']);expect(plan.calculate(v,'USD',plan.V3).total).toBe('357.50');});
test.each(['statedCurrency','statedUnit','statedUnitPrice'])('structural source mismatch %s cannot be overridden',key=>{const v=inputs();v.lines[0].evidence[key]='wrong';v.lines[0].evidence.exceptionReason='I choose this';expect(()=>source.assess(v,'USD',{now:when})).toThrow(/must match/);});
test.each(['company_record','supplier_quote','published_reference'])('%s requires actual human reference',kind=>{const v=inputs();v.lines[0].evidence.kind=kind;expect(()=>reviewed(v)).toThrow(/reference/);Object.assign(v.lines[0].evidence,{issuer:'Supplier',reference:'Q-7'});expect(()=>reviewed(v)).not.toThrow();});
test('inclusive end date, midnight save conflict, historical exact assessment remains intact',()=>{const v=inputs();Object.assign(v.lines[0].evidence,{effectiveOn:'2026-09-01',validThrough:'2026-09-11'});reviewed(v);const saved=JSON.stringify(v);expect(source.checkSaved(v,'USD',{now:when}).lines[0].flags).not.toContain('expired');expect(()=>source.checkSaved(v,'USD',{now:new Date('2026-09-12T00:00:00Z')})).toThrow(/changed/);expect(JSON.stringify(v)).toBe(saved);expect(()=>source.checkSaved(v,'USD',{now:new Date('2026-09-12T00:00:00Z')},true)).toThrow(/changed/);});
test('adoption another day with unchanged status remains valid',()=>{const v=reviewed(inputs());expect(()=>source.checkSaved(v,'USD',{now:new Date('2026-09-12T00:00:00Z')},true)).not.toThrow();});
test.each(['expired','future'])('%s needs explicit exception, flag remains truthful',kind=>{const v=inputs();Object.assign(v.lines[0].evidence,kind==='expired'?{effectiveOn:'2026-09-01',validThrough:'2026-09-10'}:{effectiveOn:'2026-09-12',validThrough:'2026-10-10'});reviewed(v);expect(()=>source.checkSaved(v,'USD',{now:when})).toThrow(/Explain/);v.lines[0].evidence.exceptionReason='Use as an estimate pending recheck';reviewed(v);expect(()=>source.checkSaved(v,'USD',{now:when})).not.toThrow();expect(v.sourceAssessment.lines[0].flags).toContain(kind==='expired'?'expired':'not_effective');});
test('unconfirmed job and wrong service cannot be overridden',()=>{const v=inputs();v.lines[0].evidence.appliesToReviewedJob=false;reviewed(v);expect(()=>source.checkSaved(v,'USD',{now:when})).toThrow(/applicability/);v.lines[0].evidence.appliesToReviewedJob=true;v.lines[0].evidence.serviceKey='roofing';v.sourceAssessment=source.assess(v,'USD',{now:when,serviceKey:'fencing'});expect(()=>source.checkSaved(v,'USD',{now:when,serviceKey:'fencing'})).toThrow(/applicability/);});
test('all contradictory shared references flagged; distinct vendors not auto-selected',()=>{const v=inputs();Object.assign(v.lines[0].evidence,{kind:'supplier_quote',issuer:'A',reference:'Q-7'});v.lines.push({...structuredClone(v.lines[0]),lineId:'00000000-0000-4000-8000-000000000052'},{...structuredClone(v.lines[0]),lineId:'00000000-0000-4000-8000-000000000053'});v.lines[1].unitPrice='3.75';v.lines[1].evidence.statedUnitPrice='3.75';reviewed(v);expect(v.sourceAssessment.lines.every(x=>x.flags.includes('conflict'))).toBe(true);expect(()=>source.checkSaved(v,'USD',{now:when})).toThrow(/conflict/);v.lines[1].evidence.issuer='B';reviewed(v);expect(v.sourceAssessment.lines.every(x=>!x.flags.includes('conflict'))).toBe(true);});
test.each(['2026-02-30','2026-13-01','2026-1-01','not-a-date'])('invalid date %s fails',date=>{const v=inputs();v.lines[0].evidence.effectiveOn=date;expect(()=>reviewed(v)).toThrow(/valid source date/);});
test('recorded assessment object key order is immaterial',()=>{const v=reviewed(inputs());v.sourceAssessment=JSON.parse(JSON.stringify(v.sourceAssessment,Object.keys(v.sourceAssessment).sort()));const original=reviewed(inputs());v.sourceAssessment={digest:original.sourceAssessment.digest,lines:original.sourceAssessment.lines,asOfDate:original.sourceAssessment.asOfDate};expect(()=>source.checkSaved(v,'USD',{now:when})).not.toThrow();});
module.exports={line,inputs,reviewed};
