'use strict';
const {createInitialDemoState,buildDemoWorkspace,demoCanonicalItems}=require('../../src/commandCenter/workspace');
const schedule=require('../../src/commandCenter/demoScheduling');
const time=require('../../public/js/scheduling-time-contract');
const {sha256}=require('../../src/services/businessProfileAdapter');
const tenantId='00000000-0000-4000-8000-000000000001',sessionId='00000000-0000-4000-8000-000000000002',now=new Date('2030-04-03T08:00:00Z');
function fixture(){let state=createInitialDemoState(tenantId,now);let revision=1;return{get state(){return state;},workspace(){return buildDemoWorkspace({tenantId,sessionId,state,revision,simulationCount:0,persisted:true,expiresAt:new Date('2030-04-04T08:00:00Z')});},apply(input,at=now){const result=schedule.apply(this.workspace(),state,input,at);state=result.state;revision++;return result.response;}};}
function proposed(f,key='preview-first-key-1234'){const w=f.workspace(),r=w.schedulingOverview.records.find(r=>r.allowedActions.length),zone=w.configuration.businessProfile.timeZone;return{operation:'schedule_preview',appointmentId:r.appointmentId,idempotencyKey:key,idempotencyHash:sha256(key),scheduleBody:{expectedRevision:r.authority.revision,expectedDigest:r.authority.digest,expectedTimeZone:zone,action:r.allowedActions[0],target:{kind:'unassigned',id:null},scheduledStart:time.formatInstant('2030-04-03T14:00:00Z',zone).rfc3339,scheduledEnd:time.formatInstant('2030-04-03T16:00:00Z',zone).rfc3339,appointmentStatus:r.authority.appointmentStatus,reason:'Review the entered times; assignment is still needed.'}};}
function approved(p,response,key='approval-first-key-1234'){return{operation:'schedule_approve',appointmentId:p.appointmentId,idempotencyKey:key,idempotencyHash:sha256(key),scheduleBody:{previewId:response.id,previewDigest:response.previewDigest,acknowledgedWarningDigests:response.warningDigests,acknowledgedReviewReasonDigests:response.reviewReasonDigests,reason:p.scheduleBody.reason}};}
test('explicit interval preview and approval update one existing appointment, preserving raw graphs and estimate pins',()=>{const f=fixture(),graphs=JSON.stringify(f.state.graphs),before=demoCanonicalItems(f.workspace()),p=proposed(f),response=f.apply(p);expect(response.conflicts.status).toBe('needs_review');expect(response.recommendation.rankingComplete).toBe(false);expect(response.recommendation.recommendedCandidate).toBe(null);expect(f.workspace().schedulingOverview.records.find(r=>r.appointmentId===p.appointmentId).authority.scheduledEnd).toBe(null);const result=f.apply(approved(p,response));expect(result.scheduleAuthority.revision).toBe(2);expect(result.scheduleAuthority.scheduledEnd).toBe('2030-04-03T16:00:00.000Z');expect(JSON.stringify(f.state.graphs)).toBe(graphs);const after=demoCanonicalItems(f.workspace());expect(after.length).toBe(before.length);for(let i=0;i<after.length;i++){expect(after[i].snapshotDigest).toBe(before[i].snapshotDigest);expect(after[i].estimate).toEqual(before[i].estimate);}expect(f.workspace().schedulingOverview.records.find(r=>r.appointmentId===p.appointmentId).allowedActions).toEqual(['reschedule']);});
test('missing end is never inferred and unsupported staff assignment is rejected',()=>{const f=fixture(),p=proposed(f);p.scheduleBody.scheduledEnd=null;expect(()=>f.apply(p)).toThrow();const other=proposed(f);other.scheduleBody.action='assign';expect(()=>f.apply(other)).toThrow();expect(f.state.demoScheduling).toBeUndefined();});
test('preview expires and missing acknowledgement cannot approve',()=>{const f=fixture(),p=proposed(f),r=f.apply(p),a=approved(p,r);a.scheduleBody.acknowledgedReviewReasonDigests=[];expect(()=>f.apply(a)).toThrow(/acknowledge/);expect(()=>f.apply(approved(p,r),new Date(now.getTime()+900000))).toThrow(/expired/);expect(f.state.demoScheduling.history).toHaveLength(0);});
test('an intervening preview invalidates earlier consent and completed replay keeps exact saved response',()=>{const f=fixture(),p=proposed(f),r=f.apply(p),p2=proposed(f,'preview-second-key-1234');f.apply(p2);expect(()=>f.apply(approved(p,r))).toThrow(/changed/);const p3=proposed(f,'preview-third-key-1234'),r3=f.apply(p3),a=approved(p3,r3),done=f.apply(a);expect(schedule.replay(f.state,a,now)).toEqual(done);expect(f.state.demoScheduling.history).toHaveLength(1);});
test('tampered saved receipt fails read validation rather than silently replacing history',()=>{const f=fixture();f.apply(proposed(f));f.state.demoScheduling.previews[0].response.expiresAt='2040-01-01T00:00:00Z';expect(()=>f.workspace()).toThrow(/could not be read/);});
