'use strict';
const c=require('../../src/estimating/laborPlanContract'),{line,inputs}=require('../helpers/m24-labor-input');
test('people and elapsed time are converted to worker-hours with explicit burden',()=>{const r=c.calculate(inputs(),'USD');expect(r.workerHours).toBe('16');expect(r.total).toBe('960.00');expect(r.elapsedHours).toBeNull();expect(r.lines[0].elapsedHours).toBe('8');});
test('direct hours with all-in cost preserve unknown duration',()=>{const r=c.calculate(inputs([line({basis:'worker_hours',workerHours:'16',people:null,elapsedHours:null,rateMode:'all_in',hourlyCost:'60.00',burdenPercent:null})]),'USD');expect(r.total).toBe('960.00');expect(r.lines[0].elapsedHours).toBeNull();});
test('task quantity productivity uses exact worker-hours not invented crew duration',()=>{const r=c.calculate(inputs([line({basis:'quantity_productivity',people:null,elapsedHours:null,quantity:'100',unit:'ft2',hoursPerUnit:'0.125',hourlyCost:'40.00',burdenPercent:'25'})]),'USD');expect(r.total).toBe('625.00');expect(r.workerHours).toBe('12.5');});
test('round cents at each task and preserve rational hours',()=>{const l=line({basis:'worker_hours',workerHours:'0.005',people:null,elapsedHours:null,rateMode:'all_in',hourlyCost:'1.00',burdenPercent:null});const r=c.calculate(inputs([l,{...l,lineId:require('crypto').randomUUID()}]),'USD');expect(r.total).toBe('0.02');expect(r.lines[0].exactWorkerHours).toEqual({numerator:'1',denominator:'200'});});
test('unknown cost is not zero; zero hours with missing rate still incomplete',()=>{const r=c.calculate(inputs([line(),line({elapsedHours:'0',hourlyCost:null})]),'USD');expect(r.complete).toBe(false);expect(r.total).toBeNull();expect(r.knownCostSubtotal).toBe('960.00');});
test('explicit zero remains supported',()=>expect(c.calculate(inputs([line({elapsedHours:'0'})]),'USD').total).toBe('0.00'));
test.each([{rateMode:'all_in'}, {burdenPercent:'101'},{hourlyCost:'1'},{elapsedHours:'-1'},{elapsedHours:'1e2'},{people:1.2},{people:101},{elapsedHours:'0.0000001'},{workerHours:'2'},{hourlyCost:'999999999999.99'}])('reject contradictory precision, scope or overflow %j',change=>expect(()=>c.calculate(inputs([line(change)]),'USD')).toThrow());
test('sources have no implicit end date; unknowns need reason but estimates need no fake reference',()=>{const i=inputs();const a=c.assess(i,new Date('2026-09-12T00:00:00Z'));expect(a.cautions).toHaveLength(2);i.assessment={...a,acknowledged:true,explanation:'Owner assumptions for this task; dates not verified.'};expect(()=>c.checkEvidence(i,'fence',new Date('2026-09-12T23:59:59Z'))).not.toThrow();expect(()=>c.checkEvidence(i,'fence',new Date('2026-09-13T00:00:00Z'))).toThrow();});
test('raw references retained and dates strictly validated',()=>{const i=inputs();i.lines[0].rateSource.reference='  Payroll Note A  ';c.calculate(i,'USD');expect(i.lines[0].rateSource.reference).toBe('  Payroll Note A  ');i.lines[0].rateSource.effectiveOn='2026-02-30';expect(()=>c.calculate(i,'USD')).toThrow();});

test('ordinary shared card source has no replacement or mojibake marker',()=>{const s=require('fs').readFileSync(require('path').join(__dirname,'../../public/js/customer-detail.js'),'utf8');expect(s).not.toMatch(/[\u00c2\ufffd]/);});
