const {buildMaterialReview}=require('../../src/estimating/materialReview');
const version='m19-part3-canonical-v2';
const review={pins:{estimateId:'one',calculationVersion:version},currency:'USD',recordedAt:'2026-09-10T00:00:00Z',simulated:false};
const snapshot={calculationVersion:version,knownDirectMaterialCost:500,service:{scope:{material:'cedar',quantity:100,unit:'ft',waste:10,stock:999}}};
test('preserves amount and exact pins without inferring arbitrary quantity/stock or mutating input',()=>{const before=JSON.stringify(snapshot),result=buildMaterialReview(review,snapshot);expect(result.amount).toBe('500.00');expect(result.material).toBe('cedar');expect(result.sourcePins).toEqual(review.pins);expect(result.quantity).toBe('not_recorded');expect(result.availability).toBe('not_verified');expect(JSON.stringify(snapshot)).toBe(before);});
test.each([[0,'0.00','recorded'],[null,null,'unavailable'],[-1,null,'invalid'],[NaN,null,'invalid'],[Infinity,null,'invalid'],[0.001,null,'invalid'],['12',null,'invalid'],[1000000000000,null,'invalid']])('money %p retains bounded state',(value,amount,state)=>{const x=buildMaterialReview(review,{...snapshot,knownDirectMaterialCost:value});expect(x.amount).toBe(amount);expect(x.amountState).toBe(state);});
test('absent is distinct from null',()=>{expect(buildMaterialReview(review,{...snapshot,knownDirectMaterialCost:undefined}).amountState).toBe('invalid');const x={...snapshot};delete x.knownDirectMaterialCost;expect(buildMaterialReview(review,x).amountState).toBe('missing');});
test.each([{},'a'.repeat(161),'bad\ntext',null,''])('unsafe or absent material is not serialized %p',material=>{expect(buildMaterialReview(review,{...snapshot,service:{scope:{material}}}).material).toBe(null);});
test('unsupported version/currency do not fabricate a basis or money conversion',()=>{expect(buildMaterialReview({...review,pins:{...review.pins,calculationVersion:'future'}},snapshot).basis).toBe('unavailable');expect(buildMaterialReview({...review,currency:'ZZZ'},snapshot).amount).toBe(null);});
test('same isolated projector carries explicit synthetic status',()=>expect(buildMaterialReview({...review,simulated:true},snapshot).simulated).toBe(true));

test('actual stored legacy demo remains missing without fabricated configured basis',()=>{const {buildDemoWorkspace,demoCanonicalItems}=require('../../src/commandCenter/workspace'),{buildEstimateReview}=require('../../src/services/estimateReview');const fixture=require('../fixtures/m24-demo-pre-slice4.json'),state=structuredClone(fixture.state),before=JSON.stringify(state);const workspace=buildDemoWorkspace({tenantId:'00000000-0000-4000-8000-000000000101',state,revision:1,sessionId:'00000000-0000-4000-8000-000000000102',expiresAt:'2026-09-11T00:00:00Z',persisted:true,simulationCount:0}),item=demoCanonicalItems(workspace)[0];const review=buildEstimateReview(item,{simulated:true}),result=buildMaterialReview(review,item.snapshot);expect(result.amount).toBeNull();expect(result.basis).toBe('unavailable');expect(review.pins).toEqual(fixture.reviewPins);expect(JSON.stringify(state)).toBe(before);});
