'use strict';
const crypto=require('crypto'),material=require('../../src/estimating/materialPlanContract'),adoption=require('../../src/estimating/materialAdoptionContract');
const line=delta=>({lineId:crypto.randomUUID(),material:'Cedar boards',quantity:'100',unit:'ft',wastePercent:'10',unitPrice:'3.25',sourceType:'my_estimate',sourceNote:'Entered cost for synthetic work',priceDate:null,...delta});
const calc=lines=>material.calculate({lines},'USD',material.V2);
test('whole plan sums exact individually rounded lines with mixed units',()=>{const r=calc([line(),line({material:'Fasteners',quantity:'3',unit:'ea',unitPrice:'2.50'}),line({material:'Sealant',quantity:'1.5',unit:'gal',wastePercent:'0',unitPrice:'12.00'})]);expect(r.total).toBe('385.50');expect(r.lines.map(x=>x.total)).toEqual(['357.50','10.00','18.00']);expect(r.lines[2].unitLabel).toBe('US liquid gallons');});
test('each half cent rounds before aggregate; zero retained',()=>{const r=calc([line({quantity:'0.5',unit:'m',wastePercent:'0',unitPrice:'0.01'}),line({quantity:'0.5',unit:'m',wastePercent:'0',unitPrice:'0.01'}),line({unitPrice:'0.00'})]);expect(r.total).toBe('0.02');expect(r.lines[2].total).toBe('0.00');});
test('identical named materials remain distinct intentional lines',()=>expect(calc([line(),line()]).total).toBe('715.00'));
test('line IDs remain ordered; duplicate identity rejected',()=>{const a=line(),b=line();expect(calc([b,a]).lines.map(x=>x.lineId)).toEqual([b.lineId,a.lineId]);expect(()=>calc([a,a])).toThrow();expect(()=>calc([a,{...a,lineId:a.lineId.toUpperCase()}])).toThrow();});
test.each([[],Array.from({length:21},()=>line()),[line({quantity:''})],[line({quantity:'1.5',unit:'ea'})],[line({unitPrice:null})],[line({wastePercent:'101'})],[line({unit:'gallon'})],[line({priceDate:'2026-02-31'})],[line({extra:'bad'})]].map(lines=>[lines]))('invalid lines rejected %p',lines=>expect(()=>calc(lines)).toThrow());
test('aggregate overflow rejected although each line valid',()=>expect(()=>calc([line({quantity:'1',wastePercent:'0',unitPrice:'999999999999.99'}),line({quantity:'1',wastePercent:'0',unitPrice:'0.01'})])).toThrow(/combined/));
test('retained v1 is exact, v2 requires explicit version',()=>{const {lineId,...v1}=line();expect(material.calculate(v1,'USD').total).toBe('357.50');expect(()=>material.calculate({lines:[line()]},'USD')).toThrow();expect(()=>material.calculate(v1,'USD','future')).toThrow();});
test.each(Object.keys(material.UNITS))('supported unit %s remains explicit',unit=>expect(calc([line({unit,quantity:'1'})]).lines[0].unitLabel).toBe(material.UNITS[unit]));
test('whole-plan replaces material cost, preserves missingness and avoids old approval',()=>{const plan={calculationVersion:material.V2,action:'save',currency:'USD',inputs:{lines:[line(),line({quantity:'3',unit:'ea',unitPrice:'2.50'}),line({quantity:'1.5',unit:'gal',wastePercent:'0',unitPrice:'12.00'})]}};const item={calculationVersion:adoption.BASE_VERSION,estimate:{currency:'USD'},snapshot:{service:{supported:true},laborCharge:200,equipmentCharge:100,knownInternalLaborCost:100,knownEquipmentCost:50,knownDirectMaterialCost:500,knownDirectCosts:650,travel:{distanceMiles:null,knownInternalCost:null}}};expect(adoption.calculate(item,plan,adoption.V2).knownDirectCosts).toBe('535.50');expect(()=>adoption.calculate(item,plan)).toThrow();item.snapshot.knownInternalLaborCost=null;expect(adoption.calculate(item,plan,adoption.V2).knownDirectCosts).toBe(null);});
