'use strict';
const {createInitialDemoState,buildDemoWorkspace,demoCanonicalItems}=require('../../src/commandCenter/workspace');
const schedule=require('../../src/commandCenter/demoScheduling'),workforce=require('../../src/commandCenter/demoWorkforce');
const {sha256}=require('../../src/services/businessProfileAdapter');
const time=require('../../public/js/scheduling-time-contract');
const tenantId='00000000-0000-4000-8000-000000000001',sessionId='00000000-0000-4000-8000-000000000002',now=new Date('2030-04-03T08:00:00Z');
function fixture(legacy=false){let state=createInitialDemoState(tenantId,now),revision=1,n=0;if(legacy)delete state.schedulingWorkforce;return{get state(){return state;},workspace(){return buildDemoWorkspace({tenantId,sessionId,state,revision,simulationCount:0,persisted:true,expiresAt:'2030-04-04T08:00:00Z'});},preview(action,target,id,interval){const w=this.workspace(),r=w.schedulingOverview.records.find(r=>id?r.appointmentId===id:r.allowedActions.length),a=r.authority,key='assignment-preview-key-'+(++n);const input={operation:'schedule_preview',appointmentId:r.appointmentId,idempotencyKey:key,idempotencyHash:sha256(key),scheduleBody:{expectedRevision:a.revision,expectedDigest:a.digest,expectedTimeZone:w.configuration.businessProfile.timeZone,action,target:target||{kind:'unassigned',id:null},scheduledStart:interval?time.formatInstant(interval[0],w.configuration.businessProfile.timeZone).rfc3339:(a.scheduledStart?time.formatInstant(a.scheduledStart,w.configuration.businessProfile.timeZone).rfc3339:null),scheduledEnd:interval?time.formatInstant(interval[1],w.configuration.businessProfile.timeZone).rfc3339:(a.scheduledEnd?time.formatInstant(a.scheduledEnd,w.configuration.businessProfile.timeZone).rfc3339:null),appointmentStatus:a.appointmentStatus,reason:'Review this simulated team change.'}};const result=schedule.apply(w,state,input,now);state=result.state;revision++;return{input,response:result.response};},approve(p){const key='assignment-approval-key-'+(++n),input={operation:'schedule_approve',appointmentId:p.input.appointmentId,idempotencyKey:key,idempotencyHash:sha256(key),scheduleBody:{previewId:p.response.id,previewDigest:p.response.previewDigest,acknowledgedWarningDigests:p.response.warningDigests,acknowledgedReviewReasonDigests:p.response.reviewReasonDigests,reason:p.input.scheduleBody.reason}};const result=schedule.apply(this.workspace(),state,input,now);state=result.state;revision++;return { ...result.response, replayInput:input };}};}
function target(f,n=0){const t=f.workspace().schedulingOperator.targets[n];return {kind:t.kind,id:t.id};}

function scheduled(f){const v=f.state.schedulingWorkforce,zone=v.timeZone,id=f.workspace().schedulingOverview.records.find(r=>r.allowedActions.length).appointmentId,t=target(f);const start=time.resolveWallTime('2030-04-03','10:00',zone).candidates[0].rfc3339,end=time.resolveWallTime('2030-04-03','11:00',zone).candidates[0].rfc3339;f.approve(f.preview('schedule',null,id,[start,end]));f.approve(f.preview('assign',t,id));return{id,t,start,end};}
test.each(['reassign','unassign','reschedule'])('dispatch then %s revokes; exact replay cannot restore revoked state',action=>{const f=fixture(),{id,t,start,end}=scheduled(f),old=JSON.stringify(f.state.demoScheduling.history),raw=JSON.stringify(f.state.graphs);const dispatched=f.approve(f.preview('dispatch',t,id));expect(dispatched.scheduleAuthority.dispatchState).toBe('dispatched');expect(f.workspace().schedulingOverview.records.find(r=>r.appointmentId===id).allowedActions).not.toContain('dispatch');expect(()=>f.preview('dispatch',t,id)).toThrow(/Dispatch requires/);expect(()=>f.preview('reschedule',t,id,[start,end])).toThrow(/different/);const interval=action==='reschedule'?[new Date(Date.parse(start)+3600000).toISOString(),new Date(Date.parse(end)+3600000).toISOString()]:undefined,newTarget=action==='unassign'?null:action==='reassign'?target(f,1):t;const changed=f.approve(f.preview(action,newTarget,id,interval));expect(changed.scheduleAuthority.dispatchState).toBe('revoked');const replay=schedule.replay(f.state,dispatched.replayInput,now);expect(replay.scheduleAuthority).toEqual(dispatched.scheduleAuthority);expect(f.workspace().schedulingOverview.records.find(r=>r.appointmentId===id).authority.dispatchState).toBe('revoked');expect(JSON.stringify(f.state.demoScheduling.history.slice(2))).toBe(old);expect(JSON.stringify(f.state.graphs)).toBe(raw);if(action!=='unassign'){const a=f.approve(f.preview('dispatch',newTarget,id));expect(a.scheduleAuthority.dispatchState).toBe('dispatched');expect(a.scheduleAuthority.scheduledStart).toBe(changed.scheduleAuthority.scheduledStart);}else expect(f.workspace().schedulingOverview.records.find(r=>r.appointmentId===id).allowedActions).not.toContain('dispatch');});
test('dispatch cannot guess a missing team or schedule and never edits current target or times',()=>{const f=fixture();expect(()=>f.preview('dispatch',target(f))).toThrow(/Dispatch requires/);const{id,t,start,end}=scheduled(f);expect(()=>f.preview('dispatch',target(f,1),id)).toThrow(/Dispatch requires/);expect(()=>f.preview('dispatch',t,id,[start,new Date(Date.parse(end)+1000).toISOString()])).toThrow(/Dispatch requires/);expect(f.workspace().schedulingOverview.records.find(r=>r.appointmentId===id).authority.dispatchState).toBe('not_dispatched');});
test('fresh dispatch consent binds current state, exact warnings and expiry',()=>{const f=fixture(),{id,t}=scheduled(f),p=f.preview('dispatch',t,id);f.preview('dispatch',t,id);expect(()=>f.approve(p)).toThrow(/changed/);const g=fixture(),s=scheduled(g),v=g.preview('dispatch',s.t,s.id);v.response.reviewReasonDigests=[];expect(()=>g.approve(v)).toThrow(/acknowledge/);});
test('dispatch uses actual unavailable and overlap evidence instead of a canned ready response',()=>{const f=fixture(),{id,t,start,end}=scheduled(f),v=f.state.schedulingWorkforce,member=v.members.find(m=>m.profileId===t.id);member.availability.intervals.push({kind:'unavailable',start,end});delete v.digest;v.digest=sha256(v);const p=f.preview('dispatch',t,id);expect(p.response.conflicts.hardConflicts.some(c=>c.code==='declared_unavailable')).toBe(true);expect(()=>f.approve(p)).toThrow(/changed/);});
test('forged dispatch/revocation transition is rejected even if its hashes are recomputed',()=>{const f=fixture();f.approve(f.preview('assign',target(f)));const h=f.state.demoScheduling.history[0];h.response.scheduleAuthority.dispatchState='revoked';delete h.response.scheduleAuthority.digest;h.response.scheduleAuthority.digest=sha256(h.response.scheduleAuthority);delete h.digest;h.digest=sha256(h);expect(()=>f.workspace()).toThrow(/dispatch history/);});
