const {calculate,normalize,VERSION}=require('../../src/estimating/materialPlanContract');
const input={material:'Cedar board',quantity:'100',unit:'ft',wastePercent:'10',unitPrice:'3.25',sourceType:'my_estimate',sourceNote:'Human entered cost estimate',priceDate:null};
test.each([[{},'110','357.50'],[{quantity:'3',unit:'ea',unitPrice:'2.50'},'4','10.00'],[{quantity:'1',wastePercent:'0',unitPrice:'0.00'},'1','0.00'],[{quantity:'0.333333',unit:'m',wastePercent:'0',unitPrice:'0.01'},'0.333333','0.00'],[{quantity:'0.000001',unit:'m',wastePercent:'0.01',unitPrice:'0.01'},'0.000002','0.00']])('exact authoritative arithmetic %p',(delta,q,total)=>{const v=calculate({...input,...delta},'USD');expect(v.plannedQuantity).toBe(q);expect(v.total).toBe(total);});
test.each([{quantity:''},{quantity:'0'},{quantity:'1.5',unit:'ea'},{wastePercent:'101'},{wastePercent:'-1'},{unitPrice:'3.255'},{unitPrice:null},{unit:'gallon'},{priceDate:'2026-02-31'},{sourceNote:''},{quantity:'999999999',unitPrice:'999999999999.99'}])('invalid or overflowing inputs rejected %p',delta=>expect(()=>calculate({...input,...delta},'USD')).toThrow());
test('US gallon explicitly named and currency unsupported',()=>{expect(calculate({...input,unit:'gal'},'USD').unitLabel).toBe('US liquid gallons');expect(()=>calculate(input,'ZZZ')).toThrow();});
test('exact normalization requires explicit confirmation',()=>{const b={action:'save',expectedRevision:0,expectedDigest:'none',sourcePins:{},expectedDecisionRevision:0,expectedDecisionDigest:'none',inputs:input,currency:'USD',reason:'Test source',confirmed:false,confirmationVersion:VERSION};expect(()=>normalize(b)).toThrow();expect(normalize({...b,confirmed:true}).inputs).toEqual(input);});

test.each([[{quantity:'0.5',wastePercent:'0',unitPrice:'0.01'},'0.5','0.01'],[{quantity:'2',wastePercent:'100',unitPrice:'1.00'},'4','4.00'],[{quantity:'1',wastePercent:'0',unitPrice:'999999999999.99'},'1','999999999999.99']])('money half-up and supported boundaries %p',(delta,q,total)=>{const v=calculate({...input,...delta},'USD');expect(v.plannedQuantity).toBe(q);expect(v.total).toBe(total);});
test.each([{quantity:null},{wastePercent:null},{priceDate:''},{priceDate:'0000-01-01'},{material:'\u0085'},{sourceNote:'\u00a0'},{sourceNote:'\twrong'}])('missing or invalid source values remain unavailable %p',delta=>expect(()=>calculate({...input,...delta},'USD')).toThrow());
