'use strict';
const contract=require('../../src/estimating/equipmentPlanContract');
const demo=require('../../src/commandCenter/demoEquipmentPlans');
const {line,inputs}=require('../helpers/m24-equipment-input');
const crypto=require('node:crypto');
function fixture(){const now=new Date('2026-09-12T12:00:00Z'),state={equipmentBasis:demo.create('equipment-unit',now)},item={snapshot:{service:{key:'fence',scope:{holeDiameter:'150'}}}},sources=demo.sources(state,item),asset=sources.assets[0];const q={requirementId:crypto.randomUUID(),label:'Hole Diameter',kind:'numeric',operator:'at_least',value:'150',unit:'mm',origin:'owner_entry',scopeKey:null,specificationIndex:0};return {now,state,item,sources,inputs:inputs([line({assetId:asset.id,identity:JSON.parse(JSON.stringify(asset.privateConfiguration)),requirements:[q]})])};}
test('explicit same-unit reviewed comparison preserves zero and exact six-place numbers',()=>{const f=fixture(),q=f.inputs.lines[0].requirements[0];expect(contract.evaluate(f.inputs,f.sources,f.now).lines[0].status).toBe('matches_reviewed_requirements');q.value='150.000001';expect(contract.evaluate(f.inputs,f.sources,f.now).lines[0].status).toBe('conflicts_with_requirement');q.value='0';expect(contract.evaluate(f.inputs,f.sources,f.now).lines[0].status).toBe('matches_reviewed_requirements');q.value=null;expect(contract.evaluate(f.inputs,f.sources,f.now).lines[0].status).toBe('needs_information');});
test('no unit conversion, prose parsing, or implied certainty from unknown configuration',()=>{const f=fixture(),q=f.inputs.lines[0].requirements[0];q.unit='cm';expect(contract.evaluate(f.inputs,f.sources,f.now).lines[0].status).toBe('needs_information');q.unit='mm';f.sources.assets[0].research.specifications[0].value='up to 150';expect(contract.evaluate(f.inputs,f.sources,f.now).lines[0].status).toBe('needs_information');f.inputs.lines[0].identity.engine=null;expect(contract.evaluate(f.inputs,f.sources,f.now).lines[0].flags).toContain('configuration_changed');});
test('freshness and withdrawn private references invalidate the acknowledgment',()=>{const f=fixture();f.inputs.lines[0].knowledgePins=[f.sources.knowledge[0].publicationId];const result=contract.evaluate(f.inputs,f.sources,f.now);f.inputs.assessment={...contract.assessment(result),acknowledged:true};expect(()=>contract.requireReview(f.inputs,f.sources,f.now)).not.toThrow();expect(()=>contract.requireReview(f.inputs,f.sources,new Date('2026-11-01'))).toThrow(/Preview/);f.sources.knowledge=[];expect(()=>contract.requireReview(f.inputs,f.sources,f.now)).toThrow(/Preview/);});
test('recorded job facts must bind exactly; caller and owner declarations do not become verified job facts',()=>{const f=fixture(),q=f.inputs.lines[0].requirements[0];q.origin='recorded_job';q.scopeKey='holeDiameter';expect(()=>contract.evaluate(f.inputs,f.sources,f.now)).not.toThrow();q.value='151';expect(()=>contract.evaluate(f.inputs,f.sources,f.now)).toThrow(/recorded job fact changed/);q.origin='caller_assertion';q.scopeKey=null;expect(contract.evaluate(f.inputs,f.sources,f.now).lines[0].requirements[0].origin).toBe('caller_assertion');});
test('old demo state remains without equipment sources and initialization leaves old state untouched',()=>{const f=fixture(),old={graphs:[]},before=JSON.stringify(old);expect(demo.sources(old,f.item).assets).toEqual([]);expect(demo.sources(old,f.item).knowledge).toEqual([]);expect(JSON.stringify(old)).toBe(before);expect(f.state.equipmentBasis.assets[0].availability).toBe('unknown');});
