'use strict';
const {createInitialDemoState,buildDemoWorkspace,demoCanonicalItems}=require('../../src/commandCenter/workspace');
const schedule=require('../../src/commandCenter/demoScheduling'),workforce=require('../../src/commandCenter/demoWorkforce');
const {sha256}=require('../../src/services/businessProfileAdapter');
const time=require('../../public/js/scheduling-time-contract');
const tenantId='00000000-0000-4000-8000-000000000001',sessionId='00000000-0000-4000-8000-000000000002',now=new Date('2030-04-03T08:00:00Z');
function fixture(legacy=false){let state=createInitialDemoState(tenantId,now),revision=1,n=0;if(legacy)delete state.schedulingWorkforce;return{get state(){return state;},workspace(){return buildDemoWorkspace({tenantId,sessionId,state,revision,simulationCount:0,persisted:true,expiresAt:'2030-04-04T08:00:00Z'});},preview(action,target,id,interval){const w=this.workspace(),r=w.schedulingOverview.records.find(r=>id?r.appointmentId===id:r.allowedActions.length),a=r.authority,key='assignment-preview-key-'+(++n);const input={operation:'schedule_preview',appointmentId:r.appointmentId,idempotencyKey:key,idempotencyHash:sha256(key),scheduleBody:{expectedRevision:a.revision,expectedDigest:a.digest,expectedTimeZone:w.configuration.businessProfile.timeZone,action,target:target||{kind:'unassigned',id:null},scheduledStart:interval?time.formatInstant(interval[0],w.configuration.businessProfile.timeZone).rfc3339:(a.scheduledStart?time.formatInstant(a.scheduledStart,w.configuration.businessProfile.timeZone).rfc3339:null),scheduledEnd:interval?time.formatInstant(interval[1],w.configuration.businessProfile.timeZone).rfc3339:(a.scheduledEnd?time.formatInstant(a.scheduledEnd,w.configuration.businessProfile.timeZone).rfc3339:null),appointmentStatus:a.appointmentStatus,reason:'Review this simulated team change.'}};const result=schedule.apply(w,state,input,now);state=result.state;revision++;return{input,response:result.response};},approve(p){const key='assignment-approval-key-'+(++n),input={operation:'schedule_approve',appointmentId:p.input.appointmentId,idempotencyKey:key,idempotencyHash:sha256(key),scheduleBody:{previewId:p.response.id,previewDigest:p.response.previewDigest,acknowledgedWarningDigests:p.response.warningDigests,acknowledgedReviewReasonDigests:p.response.reviewReasonDigests,reason:p.input.scheduleBody.reason}};const result=schedule.apply(this.workspace(),state,input,now);state=result.state;revision++;return result.response;}};}
function target(f,n=0){const t=f.workspace().schedulingOperator.targets[n];return {kind:t.kind,id:t.id};}
test('unscheduled assign/reassign/unassign preserve null times, raw graph and financial identity',()=>{const f=fixture(),raw=JSON.stringify(f.state.graphs),items=demoCanonicalItems(f.workspace());let a=f.approve(f.preview('assign',target(f)));expect(a.scheduleAuthority.scheduleState).toBe('unscheduled');expect(a.scheduleAuthority.scheduledStart).toBeNull();expect(a.scheduleAuthority.targetState).toBe('assigned');a=f.approve(f.preview('reassign',target(f,1)));expect(a.scheduleAuthority.revision).toBe(3);a=f.approve(f.preview('unassign'));expect(a.scheduleAuthority.revision).toBe(4);expect(a.scheduleAuthority.workforceProfileId).toBeNull();expect(JSON.stringify(f.state.graphs)).toBe(raw);expect(demoCanonicalItems(f.workspace()).map(i=>i.estimate)).toEqual(items.map(i=>i.estimate));});
test('actual shared overlap blocks crew after member assignment while times and source stay unchanged',()=>{const f=fixture(),v=f.state.schedulingWorkforce,zone=v.timeZone,start=time.resolveWallTime('2030-04-03','10:00',zone).candidates[0].rfc3339,end=time.resolveWallTime('2030-04-03','12:00',zone).candidates[0].rfc3339;const first=f.workspace().schedulingOverview.records.filter(r=>r.allowedActions.length)[0];f.approve(f.preview('schedule',null,first.appointmentId,[start,end]));f.approve(f.preview('assign',target(f),first.appointmentId));const second=f.workspace().schedulingOverview.records.filter(r=>r.allowedActions.length)[1];f.approve(f.preview('schedule',null,second.appointmentId,[start,end]));const crew=f.workspace().schedulingOperator.targets.find(t=>t.kind==='crew'&&t.members.some(m=>m.profileId===target(f).id));const p=f.preview('assign',{kind:'crew',id:crew.id},second.appointmentId);expect(p.response.conflicts.hardConflicts.some(c=>c.code==='approved_schedule_overlap')).toBe(true);expect(()=>f.approve(p)).toThrow(/changed/);expect(f.workspace().schedulingOverview.records.find(r=>r.appointmentId===second.appointmentId).authority.targetState).toBe('unassigned');});
test('assigned time changes preserve target; assignment cannot covertly change interval',()=>{const f=fixture(),t=target(f);f.approve(f.preview('assign',t));const a=f.approve(f.preview('schedule',t,null,['2030-04-03T14:00:00Z','2030-04-03T15:00:00Z']));expect(a.scheduleAuthority.workforceProfileId).toBe(t.id);expect(()=>f.preview('reassign',target(f,1),null,['2030-04-03T16:00:00Z','2030-04-03T17:00:00Z'])).toThrow(/existing times/);});
test('legacy retains time-only history and replay without manufactured workforce',()=>{const f=fixture(true);expect(f.workspace().schedulingOperator.targets).toEqual([]);const p=f.preview('schedule',null,null,['2030-04-03T14:00:00Z','2030-04-03T15:00:00Z']);f.approve(p);expect(f.state.demoScheduling.history).toHaveLength(1);expect(()=>f.preview('assign',{kind:'profile',id:sessionId})).toThrow(/older demo/);expect(f.workspace().schedulingOperator.workforceAvailable).toBe(false);});
test('directory has same Team identities, scope-bound search and explicit finite coverage',()=>{const f=fixture(),w=f.workspace(),v=workforce.read(f.state);const p=workforce.page(v,w.tenant.id,{query:'Crew'});expect(p.targets.every(t=>t.kind==='crew')).toBe(true);expect(w.configuration.workforceProjection.crews.map(c=>c.id).sort()).toEqual(p.targets.map(t=>t.id).sort());expect(new Date(v.coverageEnd)>new Date(v.coverageStart)).toBe(true);expect(()=>workforce.page(v,w.tenant.id,{query:'x',cursor:'invalid'})).toThrow();});
test('expiry/stale acknowledgments and evidence corruption cannot commit',()=>{const f=fixture(),p=f.preview('assign',target(f));f.preview('assign',target(f,1));expect(()=>f.approve(p)).toThrow(/changed/);f.state.schedulingWorkforce.members[0].name='Changed';expect(()=>f.workspace()).toThrow(/could not be read/);});

test('same evaluator distinguishes explicit unavailable, wrong skill and stale availability',()=>{for(const kind of ['unavailable','skill','stale']){const f=fixture(),v=f.state.schedulingWorkforce,t=target(f),member=v.members.find(m=>m.profileId===t.id),zone=v.timeZone,start=time.resolveWallTime('2030-04-03','10:00',zone).candidates[0].rfc3339,end=time.resolveWallTime('2030-04-03','11:00',zone).candidates[0].rfc3339;if(kind==='unavailable')member.availability.intervals.push({kind:'unavailable',start,end});if(kind==='skill')member.serviceIds=['unsupported-specialty'];if(kind==='stale')member.availability.coverageEnd='2030-04-02T00:00:00Z';delete v.digest;v.digest=sha256(v);f.approve(f.preview('schedule',null,null,[start,end]));const p=f.preview('assign',t);if(kind==='stale')expect(p.response.conflicts.reviewReasons.some(c=>c.code==='availability_authority_stale')).toBe(true);else{expect(p.response.conflicts.hardConflicts.some(c=>c.code===(kind==='skill'?'required_skill_mismatch':'declared_unavailable'))).toBe(true);expect(()=>f.approve(p)).toThrow();}}});
test('directory pagination binds its exact dataset and tenant and never silently drops pages',()=>{const f=fixture(),v=f.state.schedulingWorkforce,member=v.members.find(m=>m.accessRole==='member');v.members=Array.from({length:60},(_,i)=>({...member,id:'11111111-1111-4111-8111-'+String(i).padStart(12,'0'),profileId:'11111111-1111-4111-8111-'+String(i).padStart(12,'0'),name:'Simulated Worker '+i}));v.crews=[];delete v.digest;v.digest=sha256(v);const tenant=f.workspace().tenant.id,p=workforce.page(v,tenant,{}),p2=workforce.page(v,tenant,{cursor:p.page.nextCursor});expect(p.targets).toHaveLength(25);expect(p2.targets).toHaveLength(25);expect(new Set([...p.targets,...p2.targets].map(t=>t.id)).size).toBe(50);expect(()=>workforce.page(v,sessionId,{cursor:p.page.nextCursor})).toThrow();v.digest='a'.repeat(64);expect(()=>workforce.page(v,tenant,{cursor:p.page.nextCursor})).toThrow(/changed/);});
