const {project,amount}=require('../../public/js/saved-material-review');
const fixture=()=>({contract:'NorthStarEstimateReview/v1',pins:{estimateId:'selected'},currency:'USD',selectedRevision:2,currentRevision:2,isCurrent:true,recordedAt:'2026-09-11T00:00:00Z',rows:[],adoptedMaterialPlan:{id:'included',inputs:{lines:[{},{}]},currentSourceAssessment:{lines:[{flags:['date_missing']}]},currentAvailabilityAssessment:{lines:[{flags:['unknown']}]}},financialCosts:{knownDirectMaterialCost:'33.00'},materialPlans:{current:{id:'later',action:'save',currency:'USD',result:{total:'99.00'}}},riskReview:{state:'compared',priceBeforeTax:'700.00',recordedDirectCosts:'183.00',remainingAfterDirectCosts:'517.00'}});
test('included and later plan remain distinct; renewed human comparison is presented unchanged',()=>{const r=fixture(),before=JSON.stringify(r),p=project(r);expect(p.facts).toContainEqual(['Included Material Cost','USD 33.00']);expect(p.facts).toContainEqual(['Latest Saved Plan','USD 99.00']);expect(p.facts).toContainEqual(['Remaining After Direct Costs','USD 517.00']);expect(p.notes.join(' ')).toMatch(/separate/);expect(JSON.stringify(r)).toBe(before);});
test.each(['USD','CAD','EUR'])('exact %s zero, missing and precision',c=>{expect(amount('0.00',c)).toBe(c+' 0.00');expect(amount(null,c)).toBe('Unavailable');expect(amount('0.001',c)).toBe('Unavailable');expect(amount(0,c)).toBe(c+' 0.00');});
test('original missingness and historical selection do not imply latest plan included',()=>{const r=fixture();r.adoptedMaterialPlan=null;r.rows=[{label:'Recorded material cost',sourceState:'missing',amount:null}];r.isCurrent=false;r.selectedRevision=1;r.riskReview={state:'review_required'};const p=project(r);expect(p.facts).toContainEqual(['Included Material Cost','Unavailable']);expect(p.facts[0][1]).toMatch(/Earlier/);expect(p.notes.join(' ')).toMatch(/matching scope/);});

const material=require('../../src/estimating/materialPlanContract');
test.each([['Fence','10','ft','10','2.00','22.00'],['Roofing','100','ft2','5','1.25','131.25'],['Concrete','2','m3','2.5','100.00','205.00'],['Whole Items','1','ea','1','0.01','0.02']])('human-entered %s arithmetic independently preserves units and waste', (name,quantity,unit,wastePercent,unitPrice,total)=>{
 for(const currency of ['USD','CAD','EUR']){const inputs={lines:[{lineId:'11111111-1111-4111-8111-111111111111',material:name,quantity,unit,wastePercent,unitPrice,sourceType:'my_estimate',sourceNote:'Illustrative human input, not a verified market price',priceDate:null}]};
 const result=material.calculate(inputs,currency,material.V2);expect(result.total).toBe(total);expect(result.currency).toBe(currency);expect(result.lines[0].unit).toBe(unit);}
});

test('twenty reported shortages remain one concise summary, with details owned by the material plan',()=>{const r=fixture();r.adoptedMaterialPlan.currentAvailabilityAssessment.lines=Array.from({length:20},()=>({flags:[],currentStatus:'reported_shortage'}));const p=project(r);expect(p.notes.filter(n=>n.startsWith('Reported shortages'))).toEqual(['Reported shortages affect 20 materials. Review the quantities and units in the material plan before arranging supplies.']);expect(p.notes.length).toBeLessThanOrEqual(7);});
