'use strict';
const contract = require('../../src/learning/importedAssetOutcomeContract');
const repository = require('../../src/learning/importedAssetOutcomeRepository');
const digest = 'a'.repeat(64), estimate = '11111111-1111-4111-8111-111111111111';
const consent = () => ({ action:'grant',expectedRevision:0,expectedDigest:'none',reason:'Use reviewed job asset evidence.',confirmed:true,confirmationVersion:'m25-imported-asset-utilization-cost-consent-v1' });
const observation = () => ({ externalJobReference:'job-19',expectedConsentRevision:1,expectedConsentDigest:digest,reason:'Compare current evidence with adopted plans.',confirmed:true,confirmationVersion:'m25-imported-asset-utilization-cost-observation-v1' });
describe('Mission 25 imported vehicle and equipment outcome contract',()=>{
 test('accepts exact separately consented observation inputs',()=>{expect(contract.normalizeConsent('fleet.primary',consent()).sourceKey).toBe('fleet.primary');expect(contract.normalizeObservation('fleet.primary',estimate,observation()).estimateId).toBe(estimate);});
 test('rejects missing pins, extra fields and changed confirmation contracts',()=>{for(const change of [v=>{v.expectedConsentDigest=null;},v=>{v.extra=true;},v=>{v.confirmed=false;},v=>{v.confirmationVersion='wrong';}]){const value=observation();change(value);expect(()=>contract.normalizeObservation('fleet.primary',estimate,value)).toThrow('Imported vehicle and equipment outcome details are invalid.');}});
 test('maps stale evidence and missing reviewed matches to plain review messages',async()=>{const pool=error=>({connect:async()=>({query:async sql=>{if(sql.startsWith('SELECT public.'))throw error;return{rows:[]};},release(){}})});await expect(repository.observe(pool({code:'40001'}),{organizationId:'1',actorUserId:'2',actorAccessRole:'owner',authSessionId:'3',csrfToken:'x',idempotencyKey:'1234567890123456',sourceKey:'fleet.primary',estimateId:estimate,...observation()})).rejects.toMatchObject({status:409,code:'M25_IMPORTED_ASSET_OUTCOME_CHANGED'});await expect(repository.observe(pool({code:'P0002',constraint:'imported_asset_asset_match_unavailable'}),{organizationId:'1',actorUserId:'2',actorAccessRole:'owner',authSessionId:'3',csrfToken:'x',idempotencyKey:'1234567890123456',sourceKey:'fleet.primary',estimateId:estimate,...observation()})).rejects.toMatchObject({status:409,message:'Current reviewed job, vehicle, and equipment matches are required.'});});
});
