'use strict';
const contract=require('../../src/learning/externalProjectOutcomeContract'),repository=require('../../src/learning/externalProjectOutcomeRepository'),crypto=require('node:crypto');
const digest='a'.repeat(64),estimateId=crypto.randomUUID();
const consent=()=>({action:'grant',expectedRevision:0,expectedDigest:'none',reason:'Use reviewed project outcome evidence.',confirmed:true,confirmationVersion:'m25-external-project-outcome-consent-v1'});
const observation=()=>({estimateId,projectReference:'project-ext-1',expectedConsentRevision:1,expectedConsentDigest:digest,reason:'Record reviewed project outcomes.',confirmed:true,confirmationVersion:'m25-external-project-outcome-observation-v1'});
describe('Mission 25 external project outcome contract',()=>{
 test('accepts exact source consent, observation and read pins',()=>{expect(contract.normalizeSource('projects.primary').sourceKey).toBe('projects.primary');expect(contract.normalizeConsent('projects.primary',consent()).sourceKey).toBe('projects.primary');expect(contract.normalizeObservation('projects.primary',observation()).estimateId).toBe(estimateId);expect(contract.normalizeRead('projects.primary',estimateId,'project-ext-1').projectReference).toBe('project-ext-1');});
 test('rejects missing pins, extras and changed confirmation versions',()=>{for(const change of[v=>{v.expectedConsentDigest=null;},v=>{v.projectReference='space is not opaque';},v=>{v.extra=true;},v=>{v.confirmed=false;},v=>{v.confirmationVersion='wrong';}]){const value=observation();change(value);expect(()=>contract.normalizeObservation('projects.primary',value)).toThrow('Project outcome details are invalid.');}});
 test('maps stale, missing-lineage and key-conflict errors to plain review messages',async()=>{const pool=error=>({connect:async()=>({query:async sql=>{if(sql.startsWith('SELECT public.'))throw error;return{rows:[]};},release(){}})});const input={organizationId:'1',actorUserId:'2',actorAccessRole:'owner',authSessionId:'3',csrfToken:'x',idempotencyKey:'1234567890123456',sourceKey:'projects.primary',...observation()};await expect(repository.observe(pool({code:'40001'}),input)).rejects.toMatchObject({status:409,code:'M25_EXTERNAL_PROJECT_OUTCOME_CHANGED'});await expect(repository.observe(pool({code:'P0002',constraint:'project_outcome_lineage_unavailable'}),input)).rejects.toMatchObject({status:409,message:'Current reviewed project and change-order links are required.'});await expect(repository.observe(pool({code:'23505'}),input)).rejects.toMatchObject({status:409,code:'M25_EXTERNAL_PROJECT_OUTCOME_KEY_CONFLICT'});});
});
