'use strict';
const contract=require('../../src/learning/externalFinancialOutcomeContract'),repository=require('../../src/learning/externalFinancialOutcomeRepository'),crypto=require('node:crypto');
const digest='a'.repeat(64),estimateId=crypto.randomUUID();
const consent=()=>({action:'grant',expectedRevision:0,expectedDigest:'none',reason:'Use reviewed external financial evidence.',confirmed:true,confirmationVersion:'m25-external-financial-outcome-consent-v1'});
const observation=()=>({estimateId,expectedConsentRevision:1,expectedConsentDigest:digest,reason:'Record reviewed external financial outcomes.',confirmed:true,confirmationVersion:'m25-external-financial-outcome-observation-v1'});
describe('Mission 25 external financial outcome contract',()=>{
 test('accepts exact source consent, observation and read pins',()=>{expect(contract.normalizeSource('finance.primary').sourceKey).toBe('finance.primary');expect(contract.normalizeConsent('finance.primary',consent()).sourceKey).toBe('finance.primary');expect(contract.normalizeObservation('finance.primary',observation()).estimateId).toBe(estimateId);expect(contract.normalizeRead('finance.primary',estimateId).estimateId).toBe(estimateId);});
 test('rejects missing pins, extras and changed confirmation versions',()=>{for(const change of[v=>{v.expectedConsentDigest=null;},v=>{v.estimateId='not-an-estimate';},v=>{v.extra=true;},v=>{v.confirmed=false;},v=>{v.confirmationVersion='wrong';}]){const value=observation();change(value);expect(()=>contract.normalizeObservation('finance.primary',value)).toThrow('Financial outcome details are invalid.');}});
 test('maps stale, missing-lineage and key-conflict errors to plain review messages',async()=>{const pool=error=>({connect:async()=>({query:async sql=>{if(sql.startsWith('SELECT public.'))throw error;return{rows:[]};},release(){}})});const input={organizationId:'1',actorUserId:'2',actorAccessRole:'owner',authSessionId:'3',csrfToken:'x',idempotencyKey:'1234567890123456',sourceKey:'finance.primary',...observation()};await expect(repository.observe(pool({code:'40001'}),input)).rejects.toMatchObject({status:409,code:'M25_EXTERNAL_FINANCIAL_OUTCOME_CHANGED'});await expect(repository.observe(pool({code:'P0002',constraint:'financial_outcome_lineage_unavailable'}),input)).rejects.toMatchObject({status:409,message:'Current reviewed financial links and evidence are required.'});await expect(repository.observe(pool({code:'23505'}),input)).rejects.toMatchObject({status:409,code:'M25_EXTERNAL_FINANCIAL_OUTCOME_KEY_CONFLICT'});});
});
