'use strict';
const contract = require('../../src/learning/externalCustomerOutcomeContract');
const repository = require('../../src/learning/externalCustomerOutcomeRepository');
const crypto = require('node:crypto');
const digest='a'.repeat(64),estimateId=crypto.randomUUID(),token='ref_'+digest;
const consent=()=>({action:'grant',expectedRevision:0,expectedDigest:'none',reason:'Use reviewed customer outcome evidence.',confirmed:true,confirmationVersion:'m25-external-customer-outcome-consent-v1'});
const observation=()=>({estimateId,crmEstimateReference:'estimate-ext-1',communicationEstimateReference:token,expectedConsentRevision:1,expectedConsentDigest:digest,reason:'Record the current reviewed customer outcomes.',confirmed:true,confirmationVersion:'m25-external-customer-outcome-observation-v1'});
describe('Mission 25 external customer outcome contract',()=>{
 test('accepts exact source-pair consent and observation pins',()=>{expect(contract.normalizeConsent('crm.primary','communications.primary',consent()).crmSourceKey).toBe('crm.primary');expect(contract.normalizeObservation('crm.primary','communications.primary',observation()).estimateId).toBe(estimateId);expect(contract.normalizeRead('crm.primary','communications.primary',estimateId,'estimate-ext-1',token).communicationEstimateReference).toBe(token);});
 test('rejects missing pins, content-bearing communication references, extras and changed confirmation versions',()=>{for(const change of [v=>{v.expectedConsentDigest=null;},v=>{v.communicationEstimateReference='customer@example.test';},v=>{v.extra=true;},v=>{v.confirmed=false;},v=>{v.confirmationVersion='wrong';}]){const value=observation();change(value);expect(()=>contract.normalizeObservation('crm.primary','communications.primary',value)).toThrow('Customer outcome details are invalid.');}});
 test('maps stale, missing-lineage and key-conflict errors to plain review messages',async()=>{const pool=error=>({connect:async()=>({query:async sql=>{if(sql.startsWith('SELECT public.'))throw error;return{rows:[]};},release(){}})});const input={organizationId:'1',actorUserId:'2',actorAccessRole:'owner',authSessionId:'3',csrfToken:'x',idempotencyKey:'1234567890123456',crmSourceKey:'crm.primary',communicationSourceKey:'communications.primary',...observation()};await expect(repository.observe(pool({code:'40001'}),input)).rejects.toMatchObject({status:409,code:'M25_EXTERNAL_CUSTOMER_OUTCOME_CHANGED'});await expect(repository.observe(pool({code:'P0002',constraint:'customer_outcome_lineage_unavailable'}),input)).rejects.toMatchObject({status:409,message:'Current reviewed estimate links and imported evidence are required.'});await expect(repository.observe(pool({code:'23505'}),input)).rejects.toMatchObject({status:409,code:'M25_EXTERNAL_CUSTOMER_OUTCOME_KEY_CONFLICT'});});
});
