'use strict';
const contract = require('../../src/learning/externalTravelImportContract');
const digest = 'a'.repeat(64);
const record = () => ({ externalRecordId: 'route-1', externalVersion: 1, state: 'active', jobReference: 'job-1', vehicleReference: 'truck-2', routeStartedAt: '2026-09-15T12:00:00.000Z', routeEndedAt: '2026-09-15T12:48:00.000Z', timeZone: 'America/New_York', distance: { value: '23.4', unit: 'mi', basis: 'gps' }, fuel: { quantity: '2.8', unit: 'us_gal', costAmount: '10.92', currency: 'USD', basis: 'fuel_card' }, evidenceClass: 'provider_recorded', sourceUpdatedAt: '2026-09-15T13:00:00.000Z' });
const batch = () => ({ schemaVersion: 'm25-external-travel-actual-v1', mode: 'historical_backfill', expectedConsentRevision: 1, expectedConsentDigest: digest, cursorBefore: null, cursorAfter: null, complete: true, records: [record()], reason: 'Owner confirmed this source and normalized route page.', confirmed: true, confirmationVersion: 'm25-external-travel-import-batch-v1' });
describe('Mission 25 external travel evidence contract', () => {
  test('accepts explicit measured route, distance, fuel, unit, currency and timezone evidence', () => expect(contract.normalizeBatch('fleet.example', batch()).records[0].distance.value).toBe('23.4'));
  test('accepts the canonical UTC zone without weakening database timezone validation', () => { const value = batch(); value.records[0].timeZone = 'UTC'; expect(contract.normalizeBatch('fleet.example', value).records[0].timeZone).toBe('UTC'); });
  test('keeps unavailable dimensions explicit without fabricating them', () => { const value = batch(); value.records[0].fuel = null; expect(contract.normalizeBatch('fleet.example', value).records[0].fuel).toBeNull(); value.records[0].distance = null; expect(() => contract.normalizeBatch('fleet.example', value)).toThrow(/include measured distance or fuel/); });
  test('rejects estimates, future routes and silent unit/currency gaps as actual evidence', () => { for (const change of [r => { r.distance.basis = 'estimated'; }, r => { r.distance.unit = null; }, r => { r.fuel.costAmount = '10.92'; r.fuel.currency = null; }, r => { r.fuel.currency = 'ZZZ'; }, r => { r.timeZone = null; }, r => { r.routeEndedAt = '2099-09-15T12:48:00.000Z'; }]) { const value = batch(); change(value.records[0]); expect(() => contract.normalizeBatch('fleet.example', value)).toThrow(); } });
  test('requires detail-free tombstones and exact record fields', () => { const value = batch(); Object.assign(value.records[0], { state: 'tombstone', jobReference: null, vehicleReference: null, routeStartedAt: null, routeEndedAt: null, timeZone: null, distance: null, fuel: null, evidenceClass: null }); expect(contract.normalizeBatch('fleet.example', value).records[0].state).toBe('tombstone'); value.records[0].distance = { value: '1', unit: 'mi', basis: 'gps' }; expect(() => contract.normalizeBatch('fleet.example', value)).toThrow(/cannot retain/); });
  test('requires current consent pins and bounded resumable pages', () => { const value = batch(); value.records = Array.from({ length: 101 }, (_, index) => ({ ...record(), externalRecordId: `r-${index}` })); expect(() => contract.normalizeBatch('fleet.example', value)).toThrow(); const continuous = batch(); continuous.mode = 'continuous_update'; continuous.complete = false; continuous.cursorAfter = 'cursor-1'; expect(contract.normalizeBatch('fleet.example', continuous).cursorAfter).toBe('cursor-1'); });
});
