'use strict';
const a=require('../../src/estimating/materialAvailabilityContract');
const id='00000000-0000-4000-8000-000000000001';
function line(overrides={}){return {lineId:id,unit:'ft',evidence:{materialSpecification:'Board'},replacement:null,availability:{kind:'company_record',issuer:null,reference:'Stock1',observedOn:'2026-09-11',validThrough:'2026-09-12',location:'Job store',availableQuantity:'8',statedUnit:'ft',leadTimeDays:null,appliesToReviewedJob:true,exceptionReason:null,...overrides}};}
const results={lines:[{plannedQuantity:'11'}]};
function assess(l){return a.assess({lines:[l]},results,{now:new Date('2026-09-11T12:00:00Z')});}
test('exact shortage and surplus distinguish zero and unknown',()=>{expect(assess(line()).lines[0]).toMatchObject({shortage:'3',surplus:'0',currentStatus:'reported_shortage'});expect(assess(line({availableQuantity:'11'})).lines[0].currentStatus).toBe('reported_sufficient');expect(assess(line({availableQuantity:'0'})).lines[0].shortage).toBe('11');expect(assess(line({availableQuantity:null,statedUnit:null})).lines[0]).toMatchObject({shortage:null,currentStatus:'unknown'});});
test('unknown end or checked date never claims current freshness',()=>{for(const field of ['observedOn','validThrough'])expect(assess(line({[field]:null})).lines[0].currentStatus).toBe('unknown');});
test('expired keeps comparison but requires reason',()=>{const l=line({observedOn:'2026-09-01',validThrough:'2026-09-10'}),assessment=assess(l);expect(assessment.lines[0]).toMatchObject({shortage:'3',currentStatus:'unknown'});expect(()=>a.requireUsable({lines:[l]},assessment)).toThrow(/expired/);l.availability.exceptionReason='Recheck before buying';expect(()=>a.requireUsable({lines:[l]},assessment)).not.toThrow();});
test('end date inclusive; future observation invalid',()=>{expect(assess(line({validThrough:'2026-09-11'})).lines[0].currentStatus).toBe('reported_shortage');expect(()=>assess(line({observedOn:'2026-09-12'}))).toThrow(/future/);});
test('units and whole item quantities cannot be waived',()=>{expect(()=>assess(line({statedUnit:'m',exceptionReason:'Trust me'}))).toThrow(/same units/);const l=line({availableQuantity:'1.5',statedUnit:'ea'});l.unit='ea';expect(()=>assess(l)).toThrow();});
test('same supply cannot cover separate lines twice',()=>{const x=line(),y=line({reference:' Stock1\u00a0'});y.lineId='00000000-0000-4000-8000-000000000002';expect(()=>a.assess({lines:[x,y]},{lines:[{plannedQuantity:'11'},{plannedQuantity:'2'}]})).toThrow(/same available supply/);});
test('retained replacement history allows ordinary price edit, forbids removing lineage',()=>{const old=line();old.replacement={previousPlanId:id,previousPlanRevision:1,previousPlanDigest:'a'.repeat(64),previousLineId:id,reason:'Owner selected',suitabilityConfirmed:true};const next={...old,unitPrice:'5.00'};expect(()=>a.checkLineage({lines:[next]},{action:'save',inputs:{lines:[old]}})).not.toThrow();expect(()=>a.checkLineage({lines:[{...next,replacement:null}]},{action:'save',inputs:{lines:[old]}})).toThrow(/history/);});
test('default unknown needs no invented reference or quantity',()=>{const l=line();l.availability=a.unknown();const result=assess(l);expect(result.lines[0].currentStatus).toBe('unknown');expect(()=>a.requireUsable({lines:[l]},result)).not.toThrow();});
