'use strict';
const {EventEmitter}=require('node:events'),{createHash}=require('node:crypto');
const {matchReviewedPdf,validateReviewedExtraction}=require('../../src/estimating/taxReviewedPdf');
const {createTaxSourceTransport}=require('../../src/estimating/taxSourceTransport');
const {createTaxSourceAcquisition}=require('../../src/estimating/taxSourceAcquisition');
const hash=b=>createHash('sha256').update(b).digest('hex');
// Deliberately NOT a real parsed PDF or legal source. Proves opaque identity matching.
const pdf=Buffer.from('%PDF-synthetic opaque fixture; no parsing'),text='Synthetic reviewed text. No tax rule or rate.';
const artifact={version:'reviewed-pinned-text-v1',rawBytes:pdf.length,rawDocumentDigest:hash(pdf),text,textDigest:hash(text),pages:1,reviewedBy:'synthetic-review-only',reviewedOn:'2026-09-13',sourceExtractionVersion:'synthetic fixture v1'};
const context={country:'US',region:'CT',locality:'Windsor',jurisdiction:'Connecticut',serviceKey:'local-tree-001',classification:'research_only'};
function transport(body=pdf,{reviewed=true,type='application/pdf',timeoutMs=8000}={}){
 let destroyed=0;
 const request=(url,options,callback)=>{const req=new EventEmitter();req.destroy=e=>{if(req.destroyed)return;req.destroyed=true;destroyed++;if(e)req.emit('error',e);queueMicrotask(()=>req.emit('close'));};req.end=()=>queueMicrotask(()=>{const res=new EventEmitter();res.statusCode=200;res.headers={'content-type':type};res.resume=()=>{};res.destroy=()=>{res.destroyed=true;};callback(res);queueMicrotask(()=>{res.emit('data',body);res.emit('end');});});return req;};
 return {counts:()=>destroyed,reader:createTaxSourceTransport({documents:()=>[{url:'https://portal.ct.gov/fixture.pdf',...(reviewed?{documentType:'pdf',reviewedExtraction:artifact}:{}),effectiveOn:'1999-04-07',endsOn:null}],allowedOrigins:new Set(['https://portal.ct.gov']),request,lookup:async()=>[{address:'8.8.8.8',family:4}],timeoutMs})};
}

test('exact pinned opaque bytes return only the reviewed text without parsing',()=>{expect(matchReviewedPdf(pdf,artifact,{signal:AbortSignal.timeout(8000)})).toEqual({text,pages:1,extractionVersion:'reviewed-pinned-text-v1'});});
test.each([Buffer.from('%PDF-changed opaque fixture; no parsing'),Buffer.concat([pdf,Buffer.from(' ')]),Buffer.alloc(262145),Buffer.from('not PDF')])('different raw identity fails closed',bytes=>{expect(()=>matchReviewedPdf(bytes,artifact,{signal:AbortSignal.timeout(8000)})).toThrow(/changed/);});
test.each([{text:'altered'},{textDigest:'a'.repeat(64)},{pages:9},{rawBytes:262145},{reviewedBy:''},{sourceExtractionVersion:''},{reviewedOn:'2026-02-30'},{extra:true}])('malformed artifact rejects %j',delta=>{expect(()=>validateReviewedExtraction({...artifact,...delta})).toThrow(/reviewed document/);});
test('unreviewed PDF has no fallback parser',()=>{expect(()=>matchReviewedPdf(pdf,null,{signal:AbortSignal.timeout(8000)})).toThrow(/reviewed/);});
test('aborted acquisition cannot return a pinned candidate',()=>{const c=new AbortController();c.abort();expect(()=>matchReviewedPdf(pdf,artifact,{signal:c.signal})).toThrow(/interrupted/);});
test('transport emits exact candidate provenance without validated coverage or private context',async()=>{const t=transport();const result=await createTaxSourceAcquisition({transport:t.reader,allowedOrigins:new Set(['https://portal.ct.gov']),clock:()=>new Date('2026-09-13T12:00:00Z')})({...context,taxId:'private',street:'private'});const s=result.candidates[0];expect(s.document.rawDocumentDigest).toBe(hash(pdf));expect(s.document.extractedTextDigest).toBe(hash(text));expect(s.document.extractionVersion).toBe('reviewed-pinned-text-v1');expect(s.reviewRequired).toBe(true);expect(s.endsOn).toBeNull();expect(s).not.toHaveProperty('validation');expect(s).not.toHaveProperty('rate');expect(JSON.stringify(result)).not.toContain('private');expect(t.counts()).toBe(1);});
test('changed download is closed and never reused as old text',async()=>{const t=transport(Buffer.concat([pdf,Buffer.from('changed')]));await expect(t.reader.acquire(context)).rejects.toThrow(/changed/);expect(t.counts()).toBe(1);});
test('PDF requires explicit type and reviewed artifact',async()=>{await expect(transport(pdf,{reviewed:false}).reader.acquire(context)).rejects.toThrow(/unsupported/);});
test('reviewed PDF does not accept HTML',async()=>{await expect(transport(Buffer.from('HTML'),{type:'text/html'}).reader.acquire(context)).rejects.toThrow(/unsupported/);});
test('raw download overflow destroys request',async()=>{const t=transport(Buffer.alloc(262145));await expect(t.reader.acquire(context)).rejects.toThrow(/review limit/);expect(t.counts()).toBe(1);});
test('legacy text candidate remains exact v1 shape',async()=>{const t=transport(Buffer.from('Recorded fixture'),{reviewed:false,type:'text/plain'});const r=await createTaxSourceAcquisition({transport:t.reader,allowedOrigins:new Set(['https://portal.ct.gov']),clock:()=>new Date('2026-09-13T12:00:00Z')})(context);expect(r.candidates[0]).not.toHaveProperty('document');expect(r.candidates[0].contentDigest).toBe(hash('Recorded fixture'));expect(r.version).toBe('tax-source-candidate-v1');});
test('tampered extracted provenance cannot enter candidates',async()=>{const sources=await transport().reader.acquire(context);sources[0].document.extractedTextDigest='a'.repeat(64);await expect(createTaxSourceAcquisition({transport:{acquire:async()=>sources},allowedOrigins:new Set(['https://portal.ct.gov'])})(context)).rejects.toThrow(/evidence/);});
test('registry requires pinned artifact and stays disabled/empty in production',()=>{const {validateRegistry,createProductionTaxAcquisition}=require('../../src/estimating/taxSourceBinding');const r={version:'tax-source-registry-v1',entries:[{context,documents:[{url:'https://portal.ct.gov/fixture',allowedOrigins:['https://portal.ct.gov'],effectiveOn:null,endsOn:null,coverage:'fixture',exclusions:'all real coverage',documentType:'pdf',reviewedExtraction:artifact}],review:{reviewedBy:'synthetic-test-only',accessBasis:'fixture',reviewedOn:'2026-09-13',expiresOn:'2026-09-13'}}]};expect(validateRegistry(r)).toBe(r);expect(createProductionTaxAcquisition({}, {getRegistry:()=>r})).toBeNull();expect(require('../../src/estimating/taxSourceRegistry').entries).toEqual([]);delete r.entries[0].documents[0].reviewedExtraction;expect(()=>validateRegistry(r)).toThrow();});
