'use strict';
const fs=require('node:fs'),path=require('node:path'),{EventEmitter}=require('node:events');
const {createHash}=require('node:crypto');
const {extractPdf}=require('../../src/estimating/taxPdfExtraction');
const {createTaxSourceTransport}=require('../../src/estimating/taxSourceTransport');
const {createTaxSourceAcquisition}=require('../../src/estimating/taxSourceAcquisition');
const hash=b=>createHash('sha256').update(b).digest('hex');
const pdf=fs.readFileSync(path.join(__dirname,'../fixtures/tax-documents/ct-landscaping.pdf'));
const context={country:'US',region:'CT',locality:'Windsor',jurisdiction:'Connecticut',serviceKey:'local-tree-001',classification:'research_only'};
jest.setTimeout(15000);
function simplePdf(pages=1,text=''){
 const objects=['<< /Type /Catalog /Pages 2 0 R >>',`<< /Type /Pages /Count ${pages} /Kids [${Array.from({length:pages},(_,i)=>`${3+i*2} 0 R`).join(' ')}] >>`];
 for(let i=0;i<pages;i++){objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >> /Contents ${4+i*2} 0 R >>`);const stream=(text.match(/.{1,80}/g)||['']).map(part=>`BT /F1 12 Tf 10 700 Td (${part}) Tj ET`).join('\n');objects.push(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);}
 let data='%PDF-1.7\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(data));data+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=Buffer.byteLength(data);data+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(n=>`${String(n).padStart(10,'0')} 00000 n \n`).join('')+`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(data);
}
function transport(body=pdf,{reviewed=true,type='application/pdf',timeoutMs=8000}={}){
 let destroyed=0;
 const request=(url,options,callback)=>{const req=new EventEmitter();req.destroy=e=>{destroyed++;req.emit('error',e);};req.end=()=>queueMicrotask(()=>{const res=new EventEmitter();res.statusCode=200;res.headers={'content-type':type};res.resume=()=>{};callback(res);queueMicrotask(()=>{res.emit('data',body);res.emit('end');});});return req;};
 return {counts:()=>destroyed,reader:createTaxSourceTransport({documents:()=>[{url:'https://portal.ct.gov/fixture.pdf',...(reviewed?{documentType:'pdf'}:{}),effectiveOn:'1999-04-07',endsOn:null}],allowedOrigins:new Set(['https://portal.ct.gov']),request,lookup:async()=>[{address:'8.8.8.8',family:4}],timeoutMs})};
}
test('actual recorded official PDF fits bounds and extracts dated regulation text',async()=>{const r=await extractPdf(pdf,{signal:AbortSignal.timeout(8000)});expect(pdf.length).toBe(19395);expect(r.pages).toBe(4);expect(r.text).toContain('tree removal');expect(r.text).toContain('April 7, 1999');expect(Buffer.byteLength(r.text)).toBeLessThanOrEqual(32768);expect(r.extractionVersion).toBe('pdfjs-dist@6.3.289/text-v1');});
test.each([['malformed',Buffer.from('%PDF-invalid')],['image-only/no-text',simplePdf()],['nine pages',simplePdf(9,'fixture')],['extracted overflow',simplePdf(1,'x'.repeat(33000))],['raw overflow',Buffer.concat([Buffer.from('%PDF-'),Buffer.alloc(262144)])]])('rejects %s without truncation',async(_name,data)=>{await expect(extractPdf(data,{signal:AbortSignal.timeout(8000)})).rejects.toThrow();});
test('encrypted marker does not become a candidate',async()=>{const b=Buffer.from(simplePdf(1,'fixture').toString().replace('/Root 1 0 R','/Root 1 0 R /Encrypt << /Filter /Standard /V 1 /R 2 /O (x) /U (x) /P -4 >>'));await expect(extractPdf(b,{signal:AbortSignal.timeout(8000)})).rejects.toThrow();});
test('reviewed PDF transport carries exact raw and extracted identities, candidate stays unvalidated',async()=>{const t=transport();const candidate=await createTaxSourceAcquisition({transport:t.reader,allowedOrigins:new Set(['https://portal.ct.gov']),clock:()=>new Date('2026-09-13T12:00:00Z')})({...context,taxId:'private',street:'private'});expect(candidate.version).toBe('tax-source-candidate-v1');const s=candidate.candidates[0];expect(s.document.rawDocumentDigest).toBe(hash(pdf));expect(s.document.extractedTextDigest).toBe(hash(s.excerpt));expect(s.document.finalUrl).toBe(s.url);expect(s.endsOn).toBeNull();expect(s.reviewRequired).toBe(true);expect(JSON.stringify(candidate)).not.toContain('private');expect(s).not.toHaveProperty('validation');expect(s).not.toHaveProperty('rate');});
test('PDF requires explicit reviewed document type',async()=>{await expect(transport(pdf,{reviewed:false}).reader.acquire(context)).rejects.toThrow(/unsupported/);});
test('reviewed PDF does not accept HTML',async()=>{await expect(transport(Buffer.from('HTML'),{type:'text/html'}).reader.acquire(context)).rejects.toThrow(/unsupported/);});
test('raw download overflow destroys request',async()=>{const t=transport(Buffer.alloc(262145));await expect(t.reader.acquire(context)).rejects.toThrow(/review limit/);expect(t.counts()).toBe(1);});
test('whole operation deadline covers extraction startup and awaits termination',async()=>{await expect(transport(pdf,{timeoutMs:100}).reader.acquire(context)).rejects.toThrow(/interrupted/);});
test('legacy text candidate remains exact v1 shape',async()=>{const t=transport(Buffer.from('Recorded fixture'),{reviewed:false,type:'text/plain'});const r=await createTaxSourceAcquisition({transport:t.reader,allowedOrigins:new Set(['https://portal.ct.gov']),clock:()=>new Date('2026-09-13T12:00:00Z')})(context);expect(r.candidates[0]).not.toHaveProperty('document');expect(r.candidates[0].contentDigest).toBe(hash('Recorded fixture'));expect(r.version).toBe('tax-source-candidate-v1');});
test('combined evidence limit is preserved for multiple extracted documents',async()=>{const source={url:'https://portal.ct.gov/fixture',content:'a'.repeat(31000),effectiveOn:null,endsOn:null,coverage:'fixture',exclusions:'all real coverage'};await expect(createTaxSourceAcquisition({transport:{acquire:async()=>[source,source]},allowedOrigins:new Set(['https://portal.ct.gov'])})(context)).rejects.toThrow(/combined/);});
test('tampered extracted provenance cannot enter candidates',async()=>{const sources=await transport().reader.acquire(context);sources[0].document.extractedTextDigest='a'.repeat(64);await expect(createTaxSourceAcquisition({transport:{acquire:async()=>sources},allowedOrigins:new Set(['https://portal.ct.gov'])})(context)).rejects.toThrow(/evidence/);});
test('registry admits only explicit PDF type and preserves disabled gate',()=>{const {validateRegistry,createProductionTaxAcquisition}=require('../../src/estimating/taxSourceBinding');const r={version:'tax-source-registry-v1',entries:[{context,documents:[{url:'https://portal.ct.gov/fixture',allowedOrigins:['https://portal.ct.gov'],effectiveOn:null,endsOn:null,coverage:'fixture',exclusions:'all real coverage',documentType:'pdf'}],review:{reviewedBy:'synthetic-test-only',accessBasis:'fixture',reviewedOn:'2026-09-13',expiresOn:'2026-09-13'}}]};expect(validateRegistry(r)).toBe(r);expect(createProductionTaxAcquisition({}, {getRegistry:()=>r})).toBeNull();r.entries[0].documents[0].documentType='arbitrary';expect(()=>validateRegistry(r)).toThrow();});
test('actual hung extraction worker is terminated before rejection',async()=>{
 const RealWorker=require('node:worker_threads').Worker;let worker,termination;
 jest.resetModules();jest.doMock('node:worker_threads',()=>({Worker:function(_file,options){worker=new RealWorker('while(true){}',{...options,eval:true});const real=worker.terminate.bind(worker);worker.terminate=()=>{termination=real();return termination;};return worker;}}));
 try{const isolated=require('../../src/estimating/taxPdfExtraction');await expect(isolated.extractPdf(pdf,{signal:AbortSignal.timeout(100)})).rejects.toThrow(/interrupted/);expect(termination).toBeDefined();await termination;expect(worker.threadId).toBe(-1);}finally{jest.dontMock('node:worker_threads');jest.resetModules();}
});
